/**
 * Fallback Data Utilities
 *
 * Provides fallback data when API calls fail.
 * Industry best practice: Always have fallback/mock data for better UX.
 * All data matches real Firebase schema for type safety.
 */

import { logger } from "./logger";

/**
 * Global flag to enable/disable fallback data
 * Set to false to disable fallback and see actual errors
 */
export const ENABLE_FALLBACK =
  process.env.NEXT_PUBLIC_ENABLE_FALLBACK !== "false";

export const FALLBACK_PRODUCTS = [
  {
    id: "fallback-prod-1",
    name: "Premium Wireless Headphones",
    slug: "premium-wireless-headphones",
    price: 2999,
    comparePrice: 4999,
    images: ["/placeholder-product.svg"],
    rating: 4.5,
    reviewCount: 128,
    stock: 15,
    sku: "WBH-2026-001",
    status: "active" as const,
    featured: true,
    condition: "new",
    shopName: "TechStore India",
    shopSlug: "techstore-india",
    categorySlug: "electronics",
    category: "Electronics",
    description: "High-quality wireless headphones with noise cancellation",
    viewCount: 1247,
    createdAt: new Date("2026-01-15T10:00:00Z"),
    updatedAt: new Date("2026-01-20T14:30:00Z"),
  },
  {
    id: "fallback-prod-2",
    name: "Smart Fitness Watch",
    slug: "smart-fitness-watch",
    price: 3499,
    comparePrice: 5999,
    images: ["/placeholder-product.svg"],
    rating: 4.3,
    reviewCount: 89,
    stock: 25,
    sku: "SFW-2026-002",
    status: "active" as const,
    featured: true,
    condition: "new",
    shopName: "FitGear Store",
    shopSlug: "fitgear-store",
    categorySlug: "electronics",
    category: "Electronics",
    description: "Track your fitness goals with this smart watch",
    viewCount: 892,
    createdAt: new Date("2026-01-18T09:15:00Z"),
    updatedAt: new Date("2026-01-21T11:20:00Z"),
  },
  {
    id: "fallback-prod-3",
    name: "Designer Cotton T-Shirt",
    slug: "designer-cotton-tshirt",
    price: 599,
    comparePrice: 999,
    images: ["/placeholder-product.svg"],
    rating: 4.7,
    reviewCount: 234,
    stock: 50,
    sku: "DCT-2026-003",
    status: "active" as const,
    featured: false,
    condition: "new",
    shopName: "Fashion Hub",
    shopSlug: "fashion-hub",
    categorySlug: "fashion",
    category: "Fashion",
    description: "Premium quality cotton t-shirt with modern design",
    viewCount: 543,
    createdAt: new Date("2026-01-10T08:00:00Z"),
    updatedAt: new Date("2026-01-19T16:45:00Z"),
  },
  {
    id: "fallback-prod-4",
    name: "Leather Laptop Bag",
    slug: "leather-laptop-bag",
    price: 1999,
    comparePrice: 2999,
    images: ["/placeholder-product.svg"],
    rating: 4.6,
    reviewCount: 156,
    stock: 12,
    sku: "LLB-2026-004",
    status: "active" as const,
    featured: true,
    condition: "new",
    shopName: "Leather Works",
    shopSlug: "leather-works",
    categorySlug: "accessories",
    category: "Accessories",
    description: "Genuine leather laptop bag with multiple compartments",
    viewCount: 678,
    createdAt: new Date("2026-01-12T13:30:00Z"),
    updatedAt: new Date("2026-01-20T10:15:00Z"),
  },
  {
    id: "fallback-prod-5",
    name: "Organic Green Tea (500g)",
    slug: "organic-green-tea-500g",
    price: 499,
    images: ["/placeholder-product.svg"],
    rating: 4.8,
    reviewCount: 432,
    stock: 0,
    sku: "OGT-2026-005",
    status: "inactive" as const,
    featured: false,
    condition: "new",
    shopName: "Tea House",
    shopSlug: "tea-house",
    categorySlug: "food-beverage",
    category: "Food & Beverage",
    description: "Pure organic green tea imported from Darjeeling",
    viewCount: 1892,
    createdAt: new Date("2026-01-05T07:00:00Z"),
    updatedAt: new Date("2026-01-21T09:00:00Z"),
  },
];

export const FALLBACK_AUCTIONS = [
  {
    id: "fallback-auction-1",
    title: "Vintage Camera Collection",
    slug: "vintage-camera-collection",
    currentBid: 15000,
    startingBid: 10000,
    bidCount: 12,
    images: ["/placeholder-auction.svg"],
    startTime: new Date(Date.now() - 86400000 * 2), // Started 2 days ago
    endTime: new Date(Date.now() + 86400000 * 2), // Ends in 2 days
    status: "active" as const,
    featured: true,
    seller: "Vintage Collectibles",
    sellerSlug: "vintage-collectibles",
    shopSlug: "vintage-collectibles",
    categorySlug: "collectibles",
    category: "Collectibles",
    condition: "used",
    description: "Rare vintage camera collection from the 1970s",
    viewCount: 456,
    createdAt: new Date("2026-01-16T12:00:00Z"),
    updatedAt: new Date("2026-01-21T15:30:00Z"),
  },
  {
    id: "fallback-auction-2",
    title: "Antique Wooden Furniture",
    slug: "antique-wooden-furniture",
    currentBid: 25000,
    startingBid: 20000,
    bidCount: 8,
    images: ["/placeholder-auction.svg"],
    startTime: new Date(Date.now() - 86400000), // Started 1 day ago
    endTime: new Date(Date.now() + 86400000 * 5), // Ends in 5 days
    status: "active" as const,
    featured: true,
    seller: "Heritage Antiques",
    sellerSlug: "heritage-antiques",
    shopSlug: "heritage-antiques",
    categorySlug: "furniture",
    category: "Furniture",
    condition: "used",
    description: "Beautiful antique wooden furniture set",
    viewCount: 289,
    createdAt: new Date("2026-01-17T10:30:00Z"),
    updatedAt: new Date("2026-01-21T14:00:00Z"),
  },
  {
    id: "fallback-auction-3",
    title: "Limited Edition Sneakers",
    slug: "limited-edition-sneakers",
    currentBid: 8000,
    startingBid: 5000,
    bidCount: 24,
    images: ["/placeholder-auction.svg"],
    startTime: new Date(Date.now() + 86400000), // Starts in 1 day
    endTime: new Date(Date.now() + 86400000 * 8), // Ends in 8 days
    status: "scheduled" as const,
    featured: false,
    seller: "Sneaker Haven",
    sellerSlug: "sneaker-haven",
    shopSlug: "sneaker-haven",
    categorySlug: "fashion",
    category: "Fashion",
    condition: "new",
    description: "Rare limited edition sneakers, brand new in box",
    viewCount: 1234,
    createdAt: new Date("2026-01-19T09:00:00Z"),
    updatedAt: new Date("2026-01-21T11:15:00Z"),
  },
  {
    id: "fallback-auction-4",
    title: "Signed Cricket Bat - Legends Edition",
    slug: "signed-cricket-bat-legends",
    currentBid: 45000,
    startingBid: 30000,
    bidCount: 67,
    images: ["/placeholder-auction.svg"],
    startTime: new Date(Date.now() - 86400000 * 10), // Started 10 days ago
    endTime: new Date(Date.now() - 86400000 * 1), // Ended 1 day ago
    status: "ended" as const,
    featured: true,
    seller: "Sports Memorabilia",
    sellerSlug: "sports-memorabilia",
    shopSlug: "sports-memorabilia",
    categorySlug: "sports",
    category: "Sports",
    condition: "used",
    description: "Cricket bat signed by Indian cricket legends",
    viewCount: 3421,
    createdAt: new Date("2026-01-08T14:00:00Z"),
    updatedAt: new Date("2026-01-20T18:30:00Z"),
  },
];

export const FALLBACK_SHOPS = [
  {
    id: "fallback-shop-1",
    name: "TechStore India",
    slug: "techstore-india",
    nameLower: "techstore india",
    logo: "/placeholder-shop.jpg",
    banner: "/placeholder-banner.jpg",
    description: "Your trusted electronics store",
    rating: 4.6,
    reviewCount: 456,
    totalProducts: 1234,
    productCount: 1234,
    ownerId: "owner-tech-1",
    ownerName: "Ramesh Sharma",
    ownerEmail: "ramesh@techstore.in",
    verified: true,
    featured: true,
    categories: ["Electronics", "Gadgets"],
    categorySlug: "electronics",
    address: "MG Road, Bangalore, Karnataka",
    phone: "+91 98765 43210",
    email: "support@techstore.in",
    website: "https://techstore.in",
    status: "active" as const,
    createdAt: new Date("2025-06-15T08:00:00Z"),
    updatedAt: new Date("2026-01-21T12:00:00Z"),
  },
  {
    id: "fallback-shop-2",
    name: "Fashion Hub",
    slug: "fashion-hub",
    nameLower: "fashion hub",
    logo: "/placeholder-shop.jpg",
    banner: "/placeholder-banner.jpg",
    description: "Latest fashion trends and styles",
    rating: 4.8,
    reviewCount: 892,
    totalProducts: 2567,
    productCount: 2567,
    ownerId: "owner-fashion-1",
    ownerName: "Priya Patel",
    ownerEmail: "priya@fashionhub.in",
    verified: true,
    featured: true,
    categories: ["Fashion", "Apparel"],
    categorySlug: "fashion",
    address: "Commercial Street, Mumbai, Maharashtra",
    phone: "+91 98765 54321",
    email: "contact@fashionhub.in",
    website: "https://fashionhub.in",
    status: "active" as const,
    createdAt: new Date("2025-08-10T10:30:00Z"),
    updatedAt: new Date("2026-01-20T16:45:00Z"),
  },
  {
    id: "fallback-shop-3",
    name: "Vintage Collectibles",
    slug: "vintage-collectibles",
    nameLower: "vintage collectibles",
    logo: "/placeholder-shop.jpg",
    banner: "/placeholder-banner.jpg",
    description: "Rare and vintage items from around the world",
    rating: 4.5,
    reviewCount: 234,
    totalProducts: 456,
    productCount: 456,
    ownerId: "owner-vintage-1",
    ownerName: "Suresh Reddy",
    ownerEmail: "suresh@vintagecollectibles.in",
    verified: false,
    featured: false,
    categories: ["Collectibles", "Antiques"],
    categorySlug: "collectibles",
    address: "Old City, Hyderabad, Telangana",
    phone: "+91 98765 67890",
    email: "info@vintagecollectibles.in",
    status: "active" as const,
    createdAt: new Date("2025-11-20T14:00:00Z"),
    updatedAt: new Date("2026-01-19T09:30:00Z"),
  },
];

export const FALLBACK_CATEGORIES = [
  {
    id: "fallback-cat-1",
    name: "Electronics",
    slug: "electronics",
    nameLower: "electronics",
    image: "/placeholder-category.jpg",
    icon: "📱",
    description: "Latest electronic devices and gadgets",
    productCount: 5432,
    featured: true,
    order: 1,
    parentId: null,
    parentSlug: null,
    subcategories: ["Mobile Phones", "Laptops", "Cameras", "Audio"],
    subcategoryCount: 4,
    status: "active" as const,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-21T10:00:00Z"),
  },
  {
    id: "fallback-cat-2",
    name: "Fashion",
    slug: "fashion",
    nameLower: "fashion",
    image: "/placeholder-category.jpg",
    icon: "👗",
    description: "Trendy clothing and accessories",
    productCount: 8765,
    featured: true,
    order: 2,
    parentId: null,
    parentSlug: null,
    subcategories: ["Men's Wear", "Women's Wear", "Kids", "Accessories"],
    subcategoryCount: 4,
    status: "active" as const,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-20T15:30:00Z"),
  },
  {
    id: "fallback-cat-3",
    name: "Home & Garden",
    slug: "home-garden",
    nameLower: "home & garden",
    image: "/placeholder-category.jpg",
    icon: "🏠",
    description: "Everything for your home and garden",
    productCount: 3421,
    featured: true,
    order: 3,
    parentId: null,
    parentSlug: null,
    subcategories: ["Furniture", "Decor", "Kitchen", "Garden"],
    subcategoryCount: 4,
    status: "active" as const,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-19T12:15:00Z"),
  },
  {
    id: "fallback-cat-4",
    name: "Mobile Phones",
    slug: "mobile-phones",
    nameLower: "mobile phones",
    image: "/placeholder-category.jpg",
    icon: "📱",
    description: "Latest smartphones and accessories",
    productCount: 1234,
    featured: false,
    order: 1,
    parentId: "fallback-cat-1",
    parentSlug: "electronics",
    subcategories: [],
    subcategoryCount: 0,
    status: "active" as const,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-21T09:00:00Z"),
  },
  {
    id: "fallback-cat-5",
    name: "Laptops",
    slug: "laptops",
    nameLower: "laptops",
    image: "/placeholder-category.jpg",
    icon: "💻",
    description: "Laptops and notebooks for work and gaming",
    productCount: 892,
    featured: false,
    order: 2,
    parentId: "fallback-cat-1",
    parentSlug: "electronics",
    subcategories: [],
    subcategoryCount: 0,
    status: "active" as const,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-20T14:45:00Z"),
  },
];

export const FALLBACK_CART_ITEMS = [
  {
    id: "fallback-cart-1",
    userId: "user-guest-1",
    productId: "fallback-prod-1",
    productSlug: "premium-wireless-headphones",
    name: "Premium Wireless Headphones",
    price: 2999,
    quantity: 1,
    image: "/placeholder-product.svg",
    shopName: "TechStore India",
    shopSlug: "techstore-india",
    inStock: true,
    stock: 15,
    status: "active",
    addedAt: new Date("2026-01-20T14:30:00Z"),
    updatedAt: new Date("2026-01-21T10:15:00Z"),
  },
  {
    id: "fallback-cart-2",
    userId: "user-guest-1",
    productId: "fallback-prod-3",
    productSlug: "designer-cotton-tshirt",
    name: "Designer Cotton T-Shirt",
    price: 599,
    quantity: 2,
    image: "/placeholder-product.svg",
    shopName: "Fashion Hub",
    shopSlug: "fashion-hub",
    inStock: true,
    stock: 50,
    status: "active",
    addedAt: new Date("2026-01-21T09:00:00Z"),
    updatedAt: new Date("2026-01-21T09:00:00Z"),
  },
];

export const FALLBACK_WISHLIST_ITEMS = [
  {
    id: "fallback-wish-1",
    userId: "user-guest-1",
    productId: "fallback-prod-2",
    productSlug: "smart-fitness-watch",
    name: "Smart Fitness Watch",
    price: 3499,
    originalPrice: 5999,
    comparePrice: 5999,
    image: "/placeholder-product.svg",
    shopName: "FitGear Store",
    shopSlug: "fitgear-store",
    inStock: true,
    stock: 25,
    status: "active",
    addedAt: new Date("2026-01-18T11:20:00Z"),
  },
  {
    id: "fallback-wish-2",
    userId: "user-guest-1",
    productId: "fallback-prod-4",
    productSlug: "leather-laptop-bag",
    name: "Leather Laptop Bag",
    price: 1999,
    originalPrice: 2999,
    comparePrice: 2999,
    image: "/placeholder-product.svg",
    shopName: "Leather Works",
    shopSlug: "leather-works",
    inStock: true,
    stock: 12,
    status: "active",
    addedAt: new Date("2026-01-19T15:45:00Z"),
  },
];

export const FALLBACK_ORDERS = [
  {
    id: "fallback-order-1",
    orderNumber: "ORD-2026-001",
    userId: "user-guest-1",
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh.kumar@example.com",
    customerPhone: "+91 98765 43210",
    status: "delivered" as const,
    paymentStatus: "paid" as const,
    paymentMethod: "UPI",
    total: 2999,
    subtotal: 2999,
    tax: 0,
    shippingFee: 0,
    discount: 0,
    items: 1,
    itemCount: 1,
    shippingAddress: {
      fullName: "Rajesh Kumar",
      phone: "+91 98765 43210",
      addressLine1: "123 MG Road",
      addressLine2: "Near Metro Station",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560001",
      country: "India",
    },
    date: new Date(Date.now() - 86400000 * 5),
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(Date.now() - 86400000 * 2),
    estimatedDelivery: new Date(Date.now() - 86400000 * 2),
    deliveredAt: new Date(Date.now() - 86400000 * 2),
    trackingNumber: "TRACK-2026-001",
  },
  {
    id: "fallback-order-2",
    orderNumber: "ORD-2026-002",
    userId: "user-guest-1",
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh.kumar@example.com",
    customerPhone: "+91 98765 43210",
    status: "processing" as const,
    paymentStatus: "paid" as const,
    paymentMethod: "Credit Card",
    total: 5499,
    subtotal: 4698,
    tax: 801,
    shippingFee: 0,
    discount: 0,
    items: 2,
    itemCount: 3,
    shippingAddress: {
      fullName: "Rajesh Kumar",
      phone: "+91 98765 43210",
      addressLine1: "123 MG Road",
      addressLine2: "Near Metro Station",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560001",
      country: "India",
    },
    date: new Date(Date.now() - 86400000 * 2),
    createdAt: new Date(Date.now() - 86400000 * 2),
    updatedAt: new Date(Date.now() - 86400000 * 1),
    estimatedDelivery: new Date(Date.now() + 86400000 * 3),
    trackingNumber: "TRACK-2026-002",
  },
  {
    id: "fallback-order-3",
    orderNumber: "ORD-2026-003",
    userId: "user-guest-1",
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh.kumar@example.com",
    customerPhone: "+91 98765 43210",
    status: "pending" as const,
    paymentStatus: "pending" as const,
    paymentMethod: "COD",
    total: 1999,
    subtotal: 1999,
    tax: 0,
    shippingFee: 0,
    discount: 0,
    items: 1,
    itemCount: 1,
    shippingAddress: {
      fullName: "Rajesh Kumar",
      phone: "+91 98765 43210",
      addressLine1: "123 MG Road",
      addressLine2: "Near Metro Station",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560001",
      country: "India",
    },
    date: new Date(Date.now() - 86400000),
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 86400000),
    estimatedDelivery: new Date(Date.now() + 86400000 * 5),
    trackingNumber: null,
  },
];

export const FALLBACK_ADDRESSES = [
  {
    id: "fallback-addr-1",
    userId: "user-guest-1",
    type: "both" as const,
    name: "Home",
    label: "Home",
    fullName: "John Doe",
    phone: "+91 98765 43210",
    addressLine1: "123 MG Road",
    addressLine2: "Near Metro Station",
    address: "123 MG Road, Near Metro Station",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560001",
    pincode: "560001",
    country: "India",
    isDefault: true,
    createdAt: new Date("2025-12-15T10:00:00Z"),
    updatedAt: new Date("2026-01-10T14:30:00Z"),
  },
  {
    id: "fallback-addr-2",
    userId: "user-guest-1",
    type: "shipping" as const,
    name: "Office",
    label: "Office",
    fullName: "John Doe",
    phone: "+91 98765 43210",
    addressLine1: "456 Whitefield Tech Park",
    addressLine2: "Floor 5, Building B",
    address: "456 Whitefield Tech Park, Floor 5, Building B",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560066",
    pincode: "560066",
    country: "India",
    isDefault: false,
    createdAt: new Date("2026-01-05T09:15:00Z"),
    updatedAt: new Date("2026-01-15T16:20:00Z"),
  },
];

export const FALLBACK_COUPONS = [
  {
    id: "fallback-coupon-1",
    code: "WELCOME10",
    description: "Get 10% off on your first order",
    type: "percentage" as const,
    value: 10,
    discount: 10,
    minOrder: 500,
    minOrderValue: 500,
    maxDiscount: 500,
    startDate: new Date("2026-01-01T00:00:00Z"),
    endDate: new Date(Date.now() + 86400000 * 30),
    expiresAt: new Date(Date.now() + 86400000 * 30),
    usageLimit: 1000,
    usagePerUser: 1,
    usedCount: 234,
    applicableProducts: "all" as const,
    firstOrderOnly: true,
    status: "active" as const,
    createdAt: new Date("2026-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-21T10:00:00Z"),
  },
  {
    id: "fallback-coupon-2",
    code: "SAVE100",
    description: "Flat ₹100 off on orders above ₹1000",
    type: "fixed" as const,
    value: 100,
    discount: 100,
    minOrder: 1000,
    minOrderValue: 1000,
    maxDiscount: 100,
    startDate: new Date("2026-01-15T00:00:00Z"),
    endDate: new Date(Date.now() + 86400000 * 15),
    expiresAt: new Date(Date.now() + 86400000 * 15),
    usageLimit: 500,
    usagePerUser: 1,
    usedCount: 89,
    applicableProducts: "all" as const,
    firstOrderOnly: false,
    status: "active" as const,
    createdAt: new Date("2026-01-15T00:00:00Z"),
    updatedAt: new Date("2026-01-20T14:30:00Z"),
  },
  {
    id: "fallback-coupon-3",
    code: "FASHION20",
    description: "20% off on all fashion products",
    type: "percentage" as const,
    value: 20,
    discount: 20,
    minOrder: 799,
    minOrderValue: 799,
    maxDiscount: 1000,
    startDate: new Date("2026-01-10T00:00:00Z"),
    endDate: new Date(Date.now() + 86400000 * 20),
    expiresAt: new Date(Date.now() + 86400000 * 20),
    usageLimit: 300,
    usagePerUser: 2,
    usedCount: 156,
    applicableProducts: "specific" as const,
    productIds: ["fallback-prod-3"],
    firstOrderOnly: false,
    status: "active" as const,
    createdAt: new Date("2026-01-10T00:00:00Z"),
    updatedAt: new Date("2026-01-19T11:45:00Z"),
  },
];

export const FALLBACK_REVIEWS = [
  {
    id: "fallback-review-1",
    productId: "fallback-prod-1",
    productSlug: "premium-wireless-headphones",
    userId: "user-1",
    userName: "Rajesh Kumar",
    userAvatar: "/placeholder-avatar.jpg",
    rating: 5,
    title: "Excellent product!",
    comment:
      "Excellent product! Highly recommended. The sound quality is amazing and battery life is great.",
    date: new Date(Date.now() - 86400000 * 10),
    createdAt: new Date(Date.now() - 86400000 * 10),
    updatedAt: new Date(Date.now() - 86400000 * 10),
    verified: true,
    verifiedPurchase: true,
    helpful: 12,
    helpfulCount: 12,
    notHelpful: 1,
    images: [],
    status: "approved" as const,
  },
  {
    id: "fallback-review-2",
    productId: "fallback-prod-1",
    productSlug: "premium-wireless-headphones",
    userId: "user-2",
    userName: "Priya Sharma",
    userAvatar: "/placeholder-avatar.jpg",
    rating: 4,
    title: "Good quality",
    comment:
      "Good quality, but delivery was a bit delayed. Overall satisfied with the purchase.",
    date: new Date(Date.now() - 86400000 * 5),
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(Date.now() - 86400000 * 5),
    verified: true,
    verifiedPurchase: true,
    helpful: 8,
    helpfulCount: 8,
    notHelpful: 2,
    images: [],
    status: "approved" as const,
  },
  {
    id: "fallback-review-3",
    productId: "fallback-prod-2",
    productSlug: "smart-fitness-watch",
    userId: "user-3",
    userName: "Amit Patel",
    userAvatar: "/placeholder-avatar.jpg",
    rating: 5,
    title: "Perfect for fitness tracking",
    comment:
      "Perfect for tracking workouts. Battery lasts for days. Highly recommend for fitness enthusiasts.",
    date: new Date(Date.now() - 86400000 * 3),
    createdAt: new Date(Date.now() - 86400000 * 3),
    updatedAt: new Date(Date.now() - 86400000 * 3),
    verified: true,
    verifiedPurchase: true,
    helpful: 15,
    helpfulCount: 15,
    notHelpful: 0,
    images: ["/placeholder-review-1.jpg", "/placeholder-review-2.jpg"],
    status: "approved" as const,
  },
];

export const FALLBACK_BLOGS = [
  {
    id: "fallback-blog-1",
    title: "Top 10 Shopping Tips for 2026",
    slug: "top-10-shopping-tips-2026",
    excerpt:
      "Learn how to save more and shop smarter in 2026 with our expert tips and tricks.",
    content: "Full blog content here...",
    image: "/placeholder-blog.jpg",
    author: "LetItRip Team",
    authorId: "admin-1",
    authorAvatar: "/placeholder-avatar.jpg",
    date: new Date(Date.now() - 86400000 * 3),
    publishedAt: new Date(Date.now() - 86400000 * 3),
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(Date.now() - 86400000 * 3),
    readTime: 5,
    readTimeMinutes: 5,
    category: "Shopping Tips",
    categorySlug: "shopping-tips",
    tags: ["shopping", "tips", "savings", "2026"],
    views: 1234,
    viewCount: 1234,
    likes: 89,
    comments: 23,
    featured: true,
    status: "published" as const,
    seoTitle: "Top 10 Shopping Tips for 2026 - LetItRip",
    seoDescription: "Discover the best shopping tips to save money in 2026",
  },
  {
    id: "fallback-blog-2",
    title: "How to Spot Fake Products Online",
    slug: "how-to-spot-fake-products",
    excerpt:
      "Protect yourself from counterfeit products with these essential tips and warning signs.",
    content: "Full blog content here...",
    image: "/placeholder-blog.jpg",
    author: "LetItRip Team",
    authorId: "admin-1",
    authorAvatar: "/placeholder-avatar.jpg",
    date: new Date(Date.now() - 86400000 * 7),
    publishedAt: new Date(Date.now() - 86400000 * 7),
    createdAt: new Date(Date.now() - 86400000 * 10),
    updatedAt: new Date(Date.now() - 86400000 * 7),
    readTime: 8,
    readTimeMinutes: 8,
    category: "Safety",
    categorySlug: "safety",
    tags: ["safety", "fake products", "counterfeit", "protection"],
    views: 2567,
    viewCount: 2567,
    likes: 156,
    comments: 45,
    featured: true,
    status: "published" as const,
    seoTitle: "How to Spot Fake Products Online - Safety Guide",
    seoDescription:
      "Learn to identify counterfeit products and shop safely online",
  },
  {
    id: "fallback-blog-3",
    title: "Best Auction Strategies for Beginners",
    slug: "best-auction-strategies-beginners",
    excerpt:
      "Master the art of online auctions with our beginner-friendly strategies.",
    content: "Full blog content here...",
    image: "/placeholder-blog.jpg",
    author: "Vikram Singh",
    authorId: "author-1",
    authorAvatar: "/placeholder-avatar.jpg",
    date: new Date(Date.now() - 86400000 * 2),
    publishedAt: new Date(Date.now() - 86400000 * 2),
    createdAt: new Date(Date.now() - 86400000 * 4),
    updatedAt: new Date(Date.now() - 86400000 * 2),
    readTime: 6,
    readTimeMinutes: 6,
    category: "Auctions",
    categorySlug: "auctions",
    tags: ["auctions", "bidding", "strategies", "beginners"],
    views: 892,
    viewCount: 892,
    likes: 67,
    comments: 12,
    featured: false,
    status: "published" as const,
    seoTitle: "Best Auction Strategies for Beginners - Win More Bids",
    seoDescription:
      "Learn proven auction strategies to win more bids as a beginner",
  },
];

export const FALLBACK_USERS = [
  {
    id: "user-guest-1",
    uid: "user-guest-1",
    email: "rajesh.kumar@example.com",
    displayName: "Rajesh Kumar",
    photoURL: "/placeholder-avatar.jpg",
    phoneNumber: "+91 98765 43210",
    role: "customer" as const,
    emailVerified: true,
    accountStatus: "active" as const,
    preferences: {
      theme: "light",
      language: "en",
      notifications: {
        email: true,
        push: true,
        sms: false,
      },
    },
    addresses: ["fallback-addr-1", "fallback-addr-2"],
    wishlistCount: 2,
    cartCount: 2,
    orderCount: 3,
    createdAt: new Date("2025-11-01T08:00:00Z"),
    updatedAt: new Date("2026-01-21T10:30:00Z"),
    lastLogin: new Date("2026-01-21T10:30:00Z"),
  },
  {
    id: "owner-tech-1",
    uid: "owner-tech-1",
    email: "ramesh@techstore.in",
    displayName: "Ramesh Sharma",
    photoURL: "/placeholder-avatar.jpg",
    phoneNumber: "+91 98765 43210",
    role: "seller" as const,
    emailVerified: true,
    accountStatus: "active" as const,
    preferences: {
      theme: "light",
      language: "en",
      notifications: {
        email: true,
        push: true,
        sms: true,
      },
    },
    shopId: "fallback-shop-1",
    shopSlug: "techstore-india",
    totalSales: 156789,
    totalOrders: 432,
    rating: 4.6,
    reviewCount: 456,
    createdAt: new Date("2025-06-15T08:00:00Z"),
    updatedAt: new Date("2026-01-21T14:00:00Z"),
    lastLogin: new Date("2026-01-21T14:00:00Z"),
  },
];

export const FALLBACK_NOTIFICATIONS = [
  {
    id: "fallback-notif-1",
    userId: "user-guest-1",
    type: "order" as const,
    title: "Order Delivered",
    message: "Your order ORD-2026-001 has been delivered successfully",
    read: false,
    actionUrl: "/user/orders/fallback-order-1",
    icon: "📦",
    createdAt: new Date(Date.now() - 86400000 * 2),
  },
  {
    id: "fallback-notif-2",
    userId: "user-guest-1",
    type: "promotion" as const,
    title: "Flash Sale Alert!",
    message: "50% off on electronics. Limited time offer!",
    read: false,
    actionUrl: "/products?category=electronics",
    icon: "🎉",
    createdAt: new Date(Date.now() - 3600000 * 5),
  },
  {
    id: "fallback-notif-3",
    userId: "user-guest-1",
    type: "auction" as const,
    title: "Auction Ending Soon",
    message: "Vintage Camera Collection auction ends in 2 hours",
    read: true,
    actionUrl: "/auctions/fallback-auction-1",
    icon: "⏰",
    createdAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    id: "fallback-notif-4",
    userId: "user-guest-1",
    type: "wishlist" as const,
    title: "Price Drop!",
    message: "Smart Fitness Watch is now ₹3,499 (was ₹5,999)",
    read: true,
    actionUrl: "/products/smart-fitness-watch",
    icon: "💰",
    createdAt: new Date(Date.now() - 86400000 * 7),
  },
];

export const FALLBACK_BIDS = [
  {
    id: "fallback-bid-1",
    auctionId: "fallback-auction-1",
    auctionSlug: "vintage-camera-collection",
    userId: "user-guest-1",
    userName: "Rajesh Kumar",
    amount: 15000,
    status: "active" as const,
    isWinning: true,
    createdAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: "fallback-bid-2",
    auctionId: "fallback-auction-1",
    auctionSlug: "vintage-camera-collection",
    userId: "user-2",
    userName: "Amit Verma",
    amount: 14500,
    status: "outbid" as const,
    isWinning: false,
    createdAt: new Date(Date.now() - 3600000 * 5),
  },
  {
    id: "fallback-bid-3",
    auctionId: "fallback-auction-4",
    auctionSlug: "signed-cricket-bat-legends",
    userId: "user-guest-1",
    userName: "Rajesh Kumar",
    amount: 42000,
    status: "lost" as const,
    isWinning: false,
    winningBid: 45000,
    winningBidder: "Sachin Fan",
    createdAt: new Date(Date.now() - 86400000 * 8),
  },
];

/**
 * Fallback CMS Pages
 */
export const FALLBACK_CMS_PAGES = [
  {
    id: "fallback-cms-1",
    slug: "about-us",
    title: "About Us",
    content: `
      <h1>Welcome to Let It Rip</h1>
      <p>India's premier auction and marketplace platform. We connect buyers and sellers across the country, offering a secure and transparent platform for auctions and direct sales.</p>
      <h2>Our Mission</h2>
      <p>To revolutionize online commerce in India by providing a trusted platform for auctions and sales.</p>
    `,
    metaTitle: "About Us - Let It Rip",
    metaDescription: "Learn about Let It Rip, India's premier auction platform",
    status: "published" as const,
    featured: false,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-15T10:00:00Z"),
  },
  {
    id: "fallback-cms-2",
    slug: "privacy-policy",
    title: "Privacy Policy",
    content: `
      <h1>Privacy Policy</h1>
      <p>Last updated: January 2026</p>
      <h2>Information We Collect</h2>
      <p>We collect information you provide directly to us when you create an account, make purchases, or contact us.</p>
      <h2>How We Use Your Information</h2>
      <p>We use the information we collect to provide, maintain, and improve our services.</p>
    `,
    metaTitle: "Privacy Policy - Let It Rip",
    metaDescription: "Our privacy policy and data protection practices",
    status: "published" as const,
    featured: false,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-10T14:30:00Z"),
  },
  {
    id: "fallback-cms-3",
    slug: "terms-of-service",
    title: "Terms of Service",
    content: `
      <h1>Terms of Service</h1>
      <p>Last updated: January 2026</p>
      <h2>Acceptance of Terms</h2>
      <p>By accessing and using Let It Rip, you accept and agree to be bound by these terms.</p>
      <h2>User Responsibilities</h2>
      <p>Users must provide accurate information and comply with all applicable laws.</p>
    `,
    metaTitle: "Terms of Service - Let It Rip",
    metaDescription: "Terms and conditions for using our platform",
    status: "published" as const,
    featured: false,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-10T14:35:00Z"),
  },
  {
    id: "fallback-cms-4",
    slug: "how-to-bid",
    title: "How to Bid",
    content: `
      <h1>How to Bid on Auctions</h1>
      <p>Learn how to participate in our auctions and win amazing items.</p>
      <h2>Step 1: Create an Account</h2>
      <p>Sign up for a free account to start bidding.</p>
      <h2>Step 2: Browse Auctions</h2>
      <p>Find auctions that interest you and place your bids.</p>
      <h2>Step 3: Win and Pay</h2>
      <p>If you win, complete payment within 24 hours.</p>
    `,
    metaTitle: "How to Bid - Let It Rip",
    metaDescription: "Learn how to participate in auctions on our platform",
    status: "published" as const,
    featured: true,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-12T09:00:00Z"),
  },
  {
    id: "fallback-cms-5",
    slug: "seller-guide",
    title: "Seller Guide",
    content: `
      <h1>Selling on Let It Rip</h1>
      <p>Start selling your products and reaching millions of buyers across India.</p>
      <h2>Getting Started</h2>
      <p>Register as a seller and complete your profile verification.</p>
      <h2>List Your Products</h2>
      <p>Create compelling listings with high-quality photos.</p>
      <h2>Manage Orders</h2>
      <p>Process orders quickly and maintain excellent customer service.</p>
    `,
    metaTitle: "Seller Guide - Let It Rip",
    metaDescription: "Learn how to sell on our platform and grow your business",
    status: "published" as const,
    featured: true,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-12T09:15:00Z"),
  },
];

/**
 * Fallback CMS Banners
 */
export const FALLBACK_CMS_BANNERS = [
  {
    id: "fallback-banner-1",
    title: "Welcome to Let It Rip",
    subtitle: "India's Premier Auction Platform",
    image: "/images/banner-1.jpg",
    link: "/auctions",
    buttonText: "Browse Auctions",
    position: "home-hero" as const,
    order: 1,
    active: true,
    createdAt: new Date("2026-01-01T00:00:00Z"),
  },
  {
    id: "fallback-banner-2",
    title: "Flash Sale",
    subtitle: "Up to 50% Off on Electronics",
    image: "/images/banner-2.jpg",
    link: "/products?category=electronics",
    buttonText: "Shop Now",
    position: "home-secondary" as const,
    order: 2,
    active: true,
    createdAt: new Date("2026-01-15T00:00:00Z"),
  },
];

/**
 * Utility function to get data with fallback
 */
export async function fetchWithFallback<T>(
  fetchFn: () => Promise<T>,
  fallbackData: T,
  errorMessage?: string,
): Promise<T> {
  try {
    const data = await fetchFn();
    // Check if data is empty/null and use fallback
    if (!data || (Array.isArray(data) && data.length === 0)) {
      if (ENABLE_FALLBACK) {
        console.warn(
          errorMessage || "No data received, using fallback data",
          data,
        );
        return fallbackData;
      } else {
        throw new Error(
          errorMessage || "No data received and fallback is disabled",
        );
      }
    }
    return data;
  } catch (error) {
    logger.error(error as Error, {
      context: "fetchWithFallback",
      errorMessage: errorMessage || "Error fetching data",
    });

    if (ENABLE_FALLBACK) {
      console.error(
        errorMessage || "Error fetching data, using fallback:",
        error,
      );
      return fallbackData;
    } else {
      // Re-throw error if fallback is disabled
      throw error;
    }
  }
}

/**
 * Get paginated fallback data
 */
export function getPaginatedFallback<T>(
  data: T[],
  page: number = 1,
  limit: number = 12,
): { data: T[]; hasMore: boolean; nextCursor: string | null } {
  const start = (page - 1) * limit;
  const end = start + limit;
  const paginatedData = data.slice(start, end);

  return {
    data: paginatedData,
    hasMore: end < data.length,
    nextCursor: end < data.length ? `page-${page + 1}` : null,
  };
}
