export {
  type DiscountConfig,
  type BXGYConfig,
  type TieredDiscount,
  type UsageConfig,
  type ValidityConfig,
  type RestrictionsConfig,
  type CouponStats,
  type CouponType,
  type CouponDocument,
  type CouponUsageDocument,
  type CouponCreateInput,
  type CouponUpdateInput,
  type CouponValidationResult,
  COUPONS_COLLECTION,
  COUPON_USAGE_SUBCOLLECTION,
  COUPONS_INDEXED_FIELDS,
  COUPON_TYPE_LABELS,
  DEFAULT_COUPON_DATA,
  COUPONS_PUBLIC_FIELDS,
  COUPONS_UPDATABLE_FIELDS,
  couponQueryHelpers,
  createCouponId,
  isValidCouponCode,
  sellerCouponCodePrefix,
  buildSellerCouponCode,
  isCouponValid,
  canUserUseCoupon,
  calculateDiscount,
  getTieredDiscount,
} from "@mohasinac/appkit/features/promotions";

