/**
 * Newsletter Subscribers Collection Schema
 *
 * Firestore schema definition for newsletter subscriber management.
 * Tracks email subscribers, their opt-in status, and subscription source.
 *
 * Document ID: auto-generated by Firestore
 */

// ============================================
// NEWSLETTER SUBSCRIBER TYPES
// ============================================

export type NewsletterSubscriberStatus = "active" | "unsubscribed";

export type NewsletterSubscriberSource =
  | "footer"
  | "homepage"
  | "checkout"
  | "popup"
  | "admin"
  | "import";

// ============================================
// 1. COLLECTION INTERFACE & NAME
// ============================================

export interface NewsletterSubscriberDocument {
  id: string;
  email: string;
  status: NewsletterSubscriberStatus;
  source?: NewsletterSubscriberSource; // Where the subscriber signed up
  ipAddress?: string; // Anonymised for GDPR — last octet zeroed
  subscribedAt: Date;
  unsubscribedAt?: Date;
  resubscribedAt?: Date;
  adminNote?: string; // Internal notes (admin only)
  createdAt: Date;
  updatedAt: Date;
}

export const NEWSLETTER_SUBSCRIBERS_COLLECTION =
  "newsletterSubscribers" as const;

// ============================================
// 2. INDEXED FIELDS
// ============================================
/**
 * Fields indexed in Firestore for query performance.
 *
 * Composite indexes defined in firestore.indexes.json:
 *   - status + createdAt DESC → admin subscriber listing & counts
 */
export const NEWSLETTER_SUBSCRIBER_INDEXED_FIELDS = [
  "status",
  "email",
  "createdAt",
  "subscribedAt",
] as const;

// ============================================
// 3. RELATIONSHIPS
// ============================================
/**
 * newsletterSubscribers — standalone collection, no FK to users.
 * A user may subscribe without an account (email-only).
 */

// ============================================
// 4. HELPER CONSTANTS
// ============================================

export const NEWSLETTER_SUBSCRIBER_FIELDS = {
  ID: "id",
  EMAIL: "email",
  STATUS: "status",
  SOURCE: "source",
  IP_ADDRESS: "ipAddress",
  SUBSCRIBED_AT: "subscribedAt",
  UNSUBSCRIBED_AT: "unsubscribedAt",
  RESUBSCRIBED_AT: "resubscribedAt",
  ADMIN_NOTE: "adminNote",
  CREATED_AT: "createdAt",
  UPDATED_AT: "updatedAt",

  STATUS_VALUES: {
    ACTIVE: "active" as NewsletterSubscriberStatus,
    UNSUBSCRIBED: "unsubscribed" as NewsletterSubscriberStatus,
  },

  SOURCE_VALUES: {
    FOOTER: "footer" as NewsletterSubscriberSource,
    HOMEPAGE: "homepage" as NewsletterSubscriberSource,
    CHECKOUT: "checkout" as NewsletterSubscriberSource,
    POPUP: "popup" as NewsletterSubscriberSource,
    ADMIN: "admin" as NewsletterSubscriberSource,
    IMPORT: "import" as NewsletterSubscriberSource,
  },
} as const;

export const NEWSLETTER_SUBSCRIBER_PUBLIC_FIELDS: (keyof NewsletterSubscriberDocument)[] =
  ["id", "email", "status", "source", "subscribedAt", "createdAt"];

export const DEFAULT_NEWSLETTER_SUBSCRIBER: Omit<
  NewsletterSubscriberDocument,
  "id" | "email" | "subscribedAt" | "createdAt" | "updatedAt"
> = {
  status: "active",
};

// ============================================
// 5. TYPE UTILITIES
// ============================================

export type NewsletterSubscriberCreateInput = Pick<
  NewsletterSubscriberDocument,
  "email" | "source" | "ipAddress"
>;

export type NewsletterSubscriberUpdateInput = Partial<
  Pick<
    NewsletterSubscriberDocument,
    "status" | "adminNote" | "unsubscribedAt" | "resubscribedAt"
  >
>;

// ============================================
// 6. QUERY HELPERS
// ============================================

export const newsletterSubscriberQueryHelpers = {
  /** Filter for active subscribers only */
  activeFilter: () => ({
    field: NEWSLETTER_SUBSCRIBER_FIELDS.STATUS,
    op: "==" as const,
    value: NEWSLETTER_SUBSCRIBER_FIELDS.STATUS_VALUES.ACTIVE,
  }),

  /** Filter by status */
  byStatus: (status: NewsletterSubscriberStatus) => ({
    field: NEWSLETTER_SUBSCRIBER_FIELDS.STATUS,
    op: "==" as const,
    value: status,
  }),

  /** Look up by email (exact match) */
  byEmail: (email: string) => ({
    field: NEWSLETTER_SUBSCRIBER_FIELDS.EMAIL,
    op: "==" as const,
    value: email.toLowerCase().trim(),
  }),
};
