/**
 * Bids Seed Data
 * Auction bids for testing - related to vintage camera auction
 */

import type { BidDocument } from "@/db/schema";

// ─── Dynamic date helpers ───────────────────────────────────────────────────
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const bidsSeedData: Partial<BidDocument>[] = [
  // Bid 1 - Initial bid by John
  {
    id: "bid-vintage-canon-ae-1-film-camera-john-20260120-p3q7r2",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 15000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(48),
    createdAt: daysAgo(48),
    updatedAt: daysAgo(47), // Updated when outbid
  },
  // Bid 2 - Jane outbids John
  {
    id: "bid-vintage-canon-ae-1-film-camera-jane-20260121-k8m2n5",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 16500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(47),
    createdAt: daysAgo(47),
    updatedAt: daysAgo(46),
  },
  // Bid 3 - Mike enters the bidding
  {
    id: "bid-vintage-canon-ae-1-film-camera-mike-20260122-w4x9y1",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 17500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(46),
    createdAt: daysAgo(46),
    updatedAt: daysAgo(45),
  },
  // Bid 4 - John raises his bid
  {
    id: "bid-vintage-canon-ae-1-film-camera-john-20260123-b7c1d4",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 18500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 15000,
    bidDate: daysAgo(45),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(43),
  },
  // Bid 5 - Jane counters
  {
    id: "bid-vintage-canon-ae-1-film-camera-jane-20260125-e2f6g3",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 19500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 16500,
    bidDate: daysAgo(43),
    createdAt: daysAgo(43),
    updatedAt: daysAgo(40),
  },
  // Bid 6 - Mike raises the stakes
  {
    id: "bid-vintage-canon-ae-1-film-camera-mike-20260128-h5j9k2",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 20500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 17500,
    bidDate: daysAgo(40),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(34),
  },
  // Bid 7 - John makes a strong bid
  {
    id: "bid-vintage-canon-ae-1-film-camera-john-20260203-l8m3n6",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 21500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 18500,
    bidDate: daysAgo(34),
    createdAt: daysAgo(34),
    updatedAt: daysAgo(29),
  },
  // Bid 8 - Jane wins with final bid (current highest)
  {
    id: "bid-vintage-canon-ae-1-film-camera-jane-20260208-p4q8r7",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Evangelion Unit-01 Original Production Cel — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 22000,
    currency: "INR",
    status: "active", // Auction still ongoing, so current bid is active
    isWinning: true, // Current highest bid
    previousBidAmount: 19500,
    autoMaxBid: 25000, // Willing to go up to ₹25,000
    bidDate: daysAgo(29),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },

  // ─── MacBook Pro M3 Auction Bids ──────────────────────────────────────────
  // productId: product-macbook-pro-m3-auction-electronics-techhub-1
  // Starting: 100000, Current: 115000, Bids: 7
  {
    id: "bid-macbook-m3-john-1-20260211-a1b2c3",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 100000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(26),
    createdAt: daysAgo(26),
    updatedAt: daysAgo(25),
  },
  {
    id: "bid-macbook-m3-mike-1-20260211-d4e5f6",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 103000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(26),
    createdAt: daysAgo(26),
    updatedAt: daysAgo(24),
  },
  {
    id: "bid-macbook-m3-raj-1-20260212-g7h8i9",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 107000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(25),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(23),
  },
  {
    id: "bid-macbook-m3-john-2-20260213-j1k2l3",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 110000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 100000,
    bidDate: daysAgo(24),
    createdAt: daysAgo(24),
    updatedAt: daysAgo(23),
  },
  {
    id: "bid-macbook-m3-priya-1-20260214-m4n5o6",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    bidAmount: 112500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(23),
    createdAt: daysAgo(23),
    updatedAt: daysAgo(21),
  },
  {
    id: "bid-macbook-m3-mike-2-20260115-p7q8r9",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 113500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 103000,
    bidDate: daysAgo(21),
    createdAt: daysAgo(21),
    updatedAt: daysAgo(18),
  },
  {
    id: "bid-macbook-m3-raj-2-20260219-s1t2u3",
    productId: "product-macbook-pro-m3-auction-electronics-techhub-1",
    productTitle: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 115000,
    currency: "INR",
    status: "active",
    isWinning: true,
    previousBidAmount: 107000,
    autoMaxBid: 130000,
    bidDate: daysAgo(18),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },

  // ─── NGE Evangelion Signed Poster Auction Bids ────────────────────────────
  // productId: product-vintage-leica-camera-auction-artisan-1
  // Starting: 85000, Current: 97500, Bids: 5
  {
    id: "bid-leica-m6-meera-1-20260206-v4w5x6",
    productId: "product-vintage-leica-camera-auction-artisan-1",
    productTitle:
      "Neon Genesis Evangelion 1995 First-Run Signed Poster — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 85000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(31),
    createdAt: daysAgo(31),
    updatedAt: daysAgo(29),
  },
  {
    id: "bid-leica-m6-john-1-20260208-y7z8a9",
    productId: "product-vintage-leica-camera-auction-artisan-1",
    productTitle:
      "Neon Genesis Evangelion 1995 First-Run Signed Poster — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 89000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(29),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(26),
  },
  {
    id: "bid-leica-m6-meera-2-20260211-b1c2d3",
    productId: "product-vintage-leica-camera-auction-artisan-1",
    productTitle:
      "Neon Genesis Evangelion 1995 First-Run Signed Poster — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 92000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 85000,
    bidDate: daysAgo(26),
    createdAt: daysAgo(26),
    updatedAt: daysAgo(22),
  },
  {
    id: "bid-leica-m6-jane-1-20260215-e4f5g6",
    productId: "product-vintage-leica-camera-auction-artisan-1",
    productTitle:
      "Neon Genesis Evangelion 1995 First-Run Signed Poster — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 95000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(22),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(19),
  },
  {
    id: "bid-leica-m6-meera-3-20260218-h7i8j9",
    productId: "product-vintage-leica-camera-auction-artisan-1",
    productTitle:
      "Neon Genesis Evangelion 1995 First-Run Signed Poster — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 97500,
    currency: "INR",
    status: "active",
    isWinning: true,
    previousBidAmount: 92000,
    autoMaxBid: 110000,
    bidDate: daysAgo(19),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },

  // ─── Air Jordan Auction Bids ──────────────────────────────────────────────
  // productId: product-limited-air-jordan-sneakers-auction-artisan-1
  // Starting: 25000, Current: 38000, Bids: 11
  {
    id: "bid-jordan-chicago-priya-1-20260208-k1l2m3",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    bidAmount: 25000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(28),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(27),
  },
  {
    id: "bid-jordan-chicago-raj-1-20260210-n4o5p6",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 27500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(27),
    createdAt: daysAgo(27),
    updatedAt: daysAgo(26),
  },
  {
    id: "bid-jordan-chicago-priya-2-20260211-q7r8s9",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    bidAmount: 29000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 25000,
    bidDate: daysAgo(26),
    createdAt: daysAgo(26),
    updatedAt: daysAgo(24),
  },
  {
    id: "bid-jordan-chicago-mike-1-20260213-t1u2v3",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 31000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(24),
    createdAt: daysAgo(24),
    updatedAt: daysAgo(22),
  },
  {
    id: "bid-jordan-chicago-raj-2-20260215-w4x5y6",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 33000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 27500,
    bidDate: daysAgo(22),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(20),
  },
  {
    id: "bid-jordan-chicago-priya-3-20260217-z7a8b9",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    bidAmount: 35000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 29000,
    bidDate: daysAgo(20),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(19),
  },
  {
    id: "bid-jordan-chicago-raj-3-20260218-a1b2c3",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 36000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 33000,
    bidDate: daysAgo(19),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  {
    id: "bid-jordan-chicago-priya-4-20260218-d4e5f6",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    bidAmount: 36500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 35000,
    bidDate: daysAgo(19),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(18),
  },
  {
    id: "bid-jordan-chicago-mike-2-20260219-g7h8i9",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 37000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 31000,
    bidDate: daysAgo(18),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
  {
    id: "bid-jordan-chicago-raj-4-20260219-j1k2l3",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 37500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    previousBidAmount: 36000,
    bidDate: daysAgo(18),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
  {
    id: "bid-jordan-chicago-meera-1-20260219-c1d2e3",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 38000,
    currency: "INR",
    status: "active",
    isWinning: true,
    autoMaxBid: 45000,
    bidDate: daysAgo(18),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },

  // ── CANCELLED bid — user withdrew before auction ended ───────────────────
  // Tests: cancel bid API, bid list filtered by status, refund-on-cancel flow
  {
    id: "bid-jordan-chicago-raj-cancelled-20260215-x9z1a4",
    productId: "product-limited-air-jordan-sneakers-auction-artisan-1",
    productTitle: "One Piece Zoro Limited Edition Signed Art Print — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 26000,
    currency: "INR",
    status: "cancelled", // ← user cancelled this bid before being outbid
    isWinning: false,
    bidDate: daysAgo(25),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25), // cancellation time
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BIDS FOR NEW AUCTION PRODUCTS (16 new auctions)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── PS5 Slim (closing March 7) — 9 bids ──────────────────────────────────
  {
    id: "bid-ps5-slim-john-1-20260223",
    productId: "auction-ps5-slim-gaming-console-techhub-1",
    productTitle: "PlayStation 5 Slim Disc Edition — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 45000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(14),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(13),
  },
  {
    id: "bid-ps5-slim-ananya-1-20260224",
    productId: "auction-ps5-slim-gaming-console-techhub-1",
    productTitle: "PlayStation 5 Slim Disc Edition — AUCTION",
    userId: "user-ananya-bose-ananya",
    userName: "Ananya Bose",
    userEmail: "ananya@letitrip.in",
    bidAmount: 46500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(13),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(11),
  },
  {
    id: "bid-ps5-slim-mike-1-20260226",
    productId: "auction-ps5-slim-gaming-console-techhub-1",
    productTitle: "PlayStation 5 Slim Disc Edition — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 48000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(11),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(9),
  },
  {
    id: "bid-ps5-slim-ravi-1-20260228",
    productId: "auction-ps5-slim-gaming-console-techhub-1",
    productTitle: "PlayStation 5 Slim Disc Edition — AUCTION",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userEmail: "ravi@letitrip.in",
    bidAmount: 52000,
    currency: "INR",
    status: "active",
    isWinning: true,
    autoMaxBid: 60000,
    bidDate: daysAgo(9),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },

  // ── AirPods Pro 2 (closing March 8) — 6 bids ─────────────────────────────
  {
    id: "bid-airpods-pro2-sneha-1-20260225",
    productId: "auction-airpods-pro2-audio-techhub-1",
    productTitle: "Apple AirPods Pro 2nd Gen (USB-C) — AUCTION",
    userId: "user-sneha-gupta-sneha",
    userName: "Sneha Gupta",
    userEmail: "sneha@letitrip.in",
    bidAmount: 18000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },
  {
    id: "bid-airpods-pro2-jane-1-20260227",
    productId: "auction-airpods-pro2-audio-techhub-1",
    productTitle: "Apple AirPods Pro 2nd Gen (USB-C) — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 19500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(7),
  },
  {
    id: "bid-airpods-pro2-sneha-2-20260302",
    productId: "auction-airpods-pro2-audio-techhub-1",
    productTitle: "Apple AirPods Pro 2nd Gen (USB-C) — AUCTION",
    userId: "user-sneha-gupta-sneha",
    userName: "Sneha Gupta",
    userEmail: "sneha@letitrip.in",
    bidAmount: 21500,
    currency: "INR",
    status: "active",
    isWinning: true,
    autoMaxBid: 27000,
    bidDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },

  // ── Swiss TAG Heuer Watch (closing March 8) — 4 bids ─────────────────────
  {
    id: "bid-tagheuer-john-1-20260220",
    productId: "auction-swiss-titanium-watch-fashion-1",
    productTitle: "TAG Heuer Carrera Chronograph Titanium — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 150000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(17),
    createdAt: daysAgo(17),
    updatedAt: daysAgo(14),
  },
  {
    id: "bid-tagheuer-mike-1-20260223",
    productId: "auction-swiss-titanium-watch-fashion-1",
    productTitle: "TAG Heuer Carrera Chronograph Titanium — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 160000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(14),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(8),
  },
  {
    id: "bid-tagheuer-ananya-1-20260301",
    productId: "auction-swiss-titanium-watch-fashion-1",
    productTitle: "TAG Heuer Carrera Chronograph Titanium — AUCTION",
    userId: "user-ananya-bose-ananya",
    userName: "Ananya Bose",
    userEmail: "ananya@letitrip.in",
    bidAmount: 175000,
    currency: "INR",
    status: "active",
    isWinning: true,
    autoMaxBid: 220000,
    bidDate: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },

  // ── Pioneer Hi-Fi System (closing March 9) — 5 bids ──────────────────────
  {
    id: "bid-pioneer-hifi-vikram-1-20260226",
    productId: "auction-pioneer-hifi-system-homeessentials-1",
    productTitle:
      "Pioneer A-40AE Stereo Amplifier + Q Acoustics Speakers — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 35000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(11),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(9),
  },
  {
    id: "bid-pioneer-hifi-john-1-20260228",
    productId: "auction-pioneer-hifi-system-homeessentials-1",
    productTitle:
      "Pioneer A-40AE Stereo Amplifier + Q Acoustics Speakers — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 38000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(9),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(6),
  },
  {
    id: "bid-pioneer-hifi-raj-1-20260303",
    productId: "auction-pioneer-hifi-system-homeessentials-1",
    productTitle:
      "Pioneer A-40AE Stereo Amplifier + Q Acoustics Speakers — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 41000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(6),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },

  // ── Vintage Denim Jacket (closing March 9) — 7 bids ──────────────────────
  {
    id: "bid-denim-jacket-ananya-1-20260225",
    productId: "auction-vintage-denim-jacket-fashion-1",
    productTitle: "Vintage Levi's 70505 Type III Denim Jacket (1978) — AUCTION",
    userId: "user-ananya-bose-ananya",
    userName: "Ananya Bose",
    userEmail: "ananya@letitrip.in",
    bidAmount: 8000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
  },
  {
    id: "bid-denim-jacket-jane-1-20260226",
    productId: "auction-vintage-denim-jacket-fashion-1",
    productTitle: "Vintage Levi's 70505 Type III Denim Jacket (1978) — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 9000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(11),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(8),
  },
  {
    id: "bid-denim-jacket-pooja-1-20260301",
    productId: "auction-vintage-denim-jacket-fashion-1",
    productTitle: "Vintage Levi's 70505 Type III Denim Jacket (1978) — AUCTION",
    userId: "user-pooja-mehta-pooja",
    userName: "Pooja Mehta",
    userEmail: "pooja@letitrip.in",
    bidAmount: 11000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },

  // ── Bose 700 Headphones (closing March 8) — 5 bids ───────────────────────
  {
    id: "bid-bose700-priya-1-20260224",
    productId: "auction-bose700-headphones-homeessentials-1",
    productTitle: "Bose 700 Wireless Noise-Cancelling Headphones — AUCTION",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    bidAmount: 25000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(13),
    createdAt: daysAgo(13),
    updatedAt: daysAgo(11),
  },
  {
    id: "bid-bose700-mike-1-20260226",
    productId: "auction-bose700-headphones-homeessentials-1",
    productTitle: "Bose 700 Wireless Noise-Cancelling Headphones — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 26500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(11),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(7),
  },
  {
    id: "bid-bose700-vikram-1-20260302",
    productId: "auction-bose700-headphones-homeessentials-1",
    productTitle: "Bose 700 Wireless Noise-Cancelling Headphones — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 28000,
    currency: "INR",
    status: "active",
    isWinning: true,
    autoMaxBid: 35000,
    bidDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },

  // ── Supreme Box Logo Tee (March 11) — 5 bids ─────────────────────────────
  {
    id: "bid-supreme-tee-ravi-1-20260228",
    productId: "auction-supreme-box-logo-tee-fashion-1",
    productTitle: "Supreme Box Logo Tee FW23 — AUCTION",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userEmail: "ravi@letitrip.in",
    bidAmount: 20000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(9),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(7),
  },
  // ── Makima 1/7 Kotobukiya (AnimeCraft Apparel) — 3 bids ──────────────────
  {
    id: "bid-supreme-tee-john-1-20260302",
    productId: "auction-chainsaw-man-makima-figure-fashion-1",
    productTitle:
      "Chainsaw Man Makima 1/7 Scale Figure — Kotobukiya ARTFX J — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 13000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },
  {
    id: "bid-supreme-tee-ananya-1-20260304",
    productId: "auction-chainsaw-man-makima-figure-fashion-1",
    productTitle:
      "Chainsaw Man Makima 1/7 Scale Figure — Kotobukiya ARTFX J — AUCTION",
    userId: "user-ananya-bose-ananya",
    userName: "Ananya Bose",
    userEmail: "ananya@letitrip.in",
    bidAmount: 15500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "bid-makima-figure-ravi-1-20260305",
    productId: "auction-chainsaw-man-makima-figure-fashion-1",
    productTitle:
      "Chainsaw Man Makima 1/7 Scale Figure — Kotobukiya ARTFX J — AUCTION",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userEmail: "ravi@letitrip.in",
    bidAmount: 18500,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },

  // ── Sukuna 1/6 MegaHouse (OtakuShelf) — 3 bids ──────────────────────────
  {
    id: "bid-trek-bike-ravi-1-20260221",
    productId: "auction-jjk-sukuna-figure-homeessentials-1",
    productTitle:
      "Jujutsu Kaisen Ryomen Sukuna King of Curses 1/6 Scale — AUCTION",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userEmail: "ravi@letitrip.in",
    bidAmount: 16000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(16),
    createdAt: daysAgo(16),
    updatedAt: daysAgo(12),
  },
  {
    id: "bid-trek-bike-mike-1-20260225",
    productId: "auction-jjk-sukuna-figure-homeessentials-1",
    productTitle:
      "Jujutsu Kaisen Ryomen Sukuna King of Curses 1/6 Scale — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 19000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(7),
  },
  {
    id: "bid-trek-bike-raj-1-20260302",
    productId: "auction-jjk-sukuna-figure-homeessentials-1",
    productTitle:
      "Jujutsu Kaisen Ryomen Sukuna King of Curses 1/6 Scale — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 22000,
    currency: "INR",
    status: "active",
    isWinning: true,
    autoMaxBid: 28000,
    bidDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },

  // ── Saber Alter Wedding 1/7 (FigureVault JP) — 2 bids ───────────────────
  {
    id: "bid-hermes-scarf-jane-1-20260302",
    productId: "auction-fate-saber-alter-figure-techhub-1",
    productTitle:
      "Fate/Stay Night Saber Alter Wedding Dress 1/7 Scale — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 20000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },
  {
    id: "bid-hermes-scarf-pooja-1-20260304",
    productId: "auction-fate-saber-alter-figure-techhub-1",
    productTitle:
      "Fate/Stay Night Saber Alter Wedding Dress 1/7 Scale — AUCTION",
    userId: "user-pooja-mehta-pooja",
    userName: "Pooja Mehta",
    userEmail: "pooja@letitrip.in",
    bidAmount: 28000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },

  // ── Spirited Away Production Cel (OtakuShelf) — 3 bids ──────────────────
  {
    id: "bid-babolat-ravi-1-20260301",
    productId: "auction-spirited-away-cel-homeessentials-1",
    productTitle:
      "Spirited Away 2001 Original Production Cel — Studio Ghibli — AUCTION",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userEmail: "ravi@letitrip.in",
    bidAmount: 32000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
  {
    id: "bid-babolat-mike-1-20260303",
    productId: "auction-spirited-away-cel-homeessentials-1",
    productTitle:
      "Spirited Away 2001 Original Production Cel — Studio Ghibli — AUCTION",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    bidAmount: 39000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(6),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: "bid-babolat-raj-1-20260304",
    productId: "auction-spirited-away-cel-homeessentials-1",
    productTitle:
      "Spirited Away 2001 Original Production Cel — Studio Ghibli — AUCTION",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    bidAmount: 45000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },

  // ── Charizard 1st Edition PSA 9 (AnimeCraft) — 2 bids ───────────────────
  {
    id: "bid-sony-a7iv-john-1-20260226",
    productId: "auction-pokemon-charizard-1st-ed-fashion-1",
    productTitle:
      "Pokémon 1st Edition Base Set Charizard Holo — PSA Graded 9 — AUCTION",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    bidAmount: 30000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(11),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(8),
  },
  {
    id: "bid-sony-a7iv-vikram-1-20260301",
    productId: "auction-pokemon-charizard-1st-ed-fashion-1",
    productTitle:
      "Pokémon 1st Edition Base Set Charizard Holo — PSA Graded 9 — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 52000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },

  // ── PG Wing Zero Built (FigureVault JP) — 2 bids ────────────────────────
  {
    id: "bid-dyson-v15-pooja-1-20260302",
    productId: "auction-gunpla-pg-wing-zero-techhub-1",
    productTitle:
      "Gundam Wing Perfect Grade Wing Zero Custom — Full Build & Paint — AUCTION",
    userId: "user-pooja-mehta-pooja",
    userName: "Pooja Mehta",
    userEmail: "pooja@letitrip.in",
    bidAmount: 9000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },
  {
    id: "bid-dyson-v15-jane-1-20260304",
    productId: "auction-gunpla-pg-wing-zero-techhub-1",
    productTitle:
      "Gundam Wing Perfect Grade Wing Zero Custom — Full Build & Paint — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 14500,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },

  // ── Rem Wedding 1/7 GSC (FigureVault JP) — 2 bids ───────────────────────
  {
    id: "bid-nikon-z30-sneha-1-20260303",
    productId: "auction-rezero-rem-wedding-figure-techhub-1",
    productTitle:
      "Re:Zero Rem Wedding Dress 1/7 Scale — Good Smile Company — AUCTION",
    userId: "user-sneha-gupta-sneha",
    userName: "Sneha Gupta",
    userEmail: "sneha@letitrip.in",
    bidAmount: 22000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(6),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
  },
  {
    id: "bid-nikon-z30-vikram-1-20260305",
    productId: "auction-rezero-rem-wedding-figure-techhub-1",
    productTitle:
      "Re:Zero Rem Wedding Dress 1/7 Scale — Good Smile Company — AUCTION",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    bidAmount: 32000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },

  // ── Oda Signed Artbook (FigureVault JP) — 2 bids ────────────────────────
  {
    id: "bid-iphone15-bundle-ravi-1-20260304",
    productId: "auction-one-piece-signed-artbook-techhub-1",
    productTitle:
      "One Piece 25th Anniversary Artbook Signed by Eiichiro Oda — AUCTION",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userEmail: "ravi@letitrip.in",
    bidAmount: 11000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "bid-iphone15-bundle-sneha-1-20260305",
    productId: "auction-one-piece-signed-artbook-techhub-1",
    productTitle:
      "One Piece 25th Anniversary Artbook Signed by Eiichiro Oda — AUCTION",
    userId: "user-sneha-gupta-sneha",
    userName: "Sneha Gupta",
    userEmail: "sneha@letitrip.in",
    bidAmount: 16000,
    currency: "INR",
    status: "active",
    isWinning: true,
    bidDate: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },

  // ── Makima figure 2nd wave (AnimeCraft) — 2 more bids ────────────────────
  {
    id: "bid-kanjeevaram-ananya-1-20260304",
    productId: "auction-chainsaw-man-makima-figure-fashion-1",
    productTitle:
      "Chainsaw Man Makima 1/7 Scale Figure — Kotobukiya ARTFX J — AUCTION",
    userId: "user-ananya-bose-ananya",
    userName: "Ananya Bose",
    userEmail: "ananya@letitrip.in",
    bidAmount: 19000,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "bid-kanjeevaram-jane-1-20260305",
    productId: "auction-chainsaw-man-makima-figure-fashion-1",
    productTitle:
      "Chainsaw Man Makima 1/7 Scale Figure — Kotobukiya ARTFX J — AUCTION",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    bidAmount: 20500,
    currency: "INR",
    status: "outbid",
    isWinning: false,
    bidDate: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },

  // No bids on pre-orders — tests "no bids yet" state in auction detail page
];

