/**
 * Categories Seed Data
 * Hierarchical category structure for products
 */

import type { CategoryDocument } from "@/db/schema";

// Dynamic date helpers
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);
const hoursAgo = (h: number) => new Date(NOW.getTime() - h * 3_600_000);

export const categoriesSeedData: Partial<CategoryDocument>[] = [
  // ROOT: Scale Figures
  {
    id: "category-electronics",
    name: "Scale Figures",
    slug: "electronics",
    description: "Premium anime scale figures and collectibles",
    rootId: "category-electronics",
    parentIds: [],
    childrenIds: [
      "category-mobiles-accessories-electronics",
      "category-laptops-computers-electronics",
      "category-audio-electronics",
      "category-cameras-photography-electronics",
    ],
    tier: 0,
    path: "electronics",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 1,
      auctionIds: ["auction-ps5-slim-gaming-console-techhub-1"],
      totalProductCount: 10,
      totalAuctionCount: 10,
      totalItemCount: 20,
      lastUpdated: daysAgo(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 1,
    seo: {
      title: "Scale Figures — Anime Collectibles | LetItRip",
      description:
        "Shop premium anime scale figures including Dragon Ball Z, One Piece, Demon Slayer, and more",
      keywords: [
        "anime figures",
        "scale figures",
        "collectibles",
        "dragon ball",
        "one piece",
      ],
      ogImage:
        "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "ðŸŽŒ",
      coverImage:
        "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
      color: "#3b82f6",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },
  // Scale Figures > Nendoroids & Chibis
  {
    id: "category-mobiles-accessories-electronics",
    name: "Nendoroids & Chibis",
    slug: "mobiles-accessories",
    description: "Nendoroids, chibi figurines, and small-scale collectibles",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [
      "category-smartphones-mobiles-accessories",
      "category-mobile-accessories-mobiles-accessories",
    ],
    tier: 1,
    path: "electronics/mobiles-accessories",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 1,
      productIds: ["product-samsung-galaxy-watch6-electronics-new-techhub-1"],
      auctionCount: 1,
      auctionIds: ["auction-gunpla-pg-wing-zero-techhub-1"],
      totalProductCount: 5,
      totalAuctionCount: 1,
      totalItemCount: 6,
      lastUpdated: daysAhead(4),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Nendoroids & Chibis | LetItRip",
      description:
        "Browse Nendoroids, chibi figurines, and small-scale anime collectibles",
      keywords: [
        "nendoroid",
        "chibi",
        "good smile company",
        "mini figurine",
        "anime",
      ],
    },
    display: {
      icon: "ðŸ«§",
      coverImage:
        "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [{ id: "category-electronics", name: "Scale Figures", tier: 0 }],
  },
  // Scale Figures > Nendoroids > Dragon Ball Figures
  {
    id: "category-smartphones-mobiles-accessories",
    name: "Dragon Ball Figures",
    slug: "smartphones",
    description: "Dragon Ball Z and Dragon Ball Super scale figures",
    rootId: "category-electronics",
    parentIds: [
      "category-electronics",
      "category-mobiles-accessories-electronics",
    ],
    childrenIds: [],
    tier: 2,
    path: "electronics/mobiles-accessories/smartphones",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 3,
      productIds: [
        "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
        "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
        "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 3,
      totalAuctionCount: 0,
      totalItemCount: 3,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 2,
    seo: {
      title: "Dragon Ball Figures — Goku, Vegeta & More | LetItRip",
      description:
        "Shop Dragon Ball Z and Super scale figures by Bandai Spirits, MegaHouse, and Banpresto",
      keywords: ["dragon ball", "goku", "vegeta", "bandai", "scale figure"],
    },
    display: {
      icon: "ðŸ”¥",
      coverImage:
        "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [
      { id: "category-electronics", name: "Scale Figures", tier: 0 },
      {
        id: "category-mobiles-accessories-electronics",
        name: "Nendoroids & Chibis",
        tier: 1,
      },
    ],
  },
  // Scale Figures > Nendoroids > Chibi Figurines
  {
    id: "category-mobile-accessories-mobiles-accessories",
    name: "Chibi Figurines",
    slug: "mobile-accessories",
    description: "Mini figurines, gashapon, and chibi collectibles",
    rootId: "category-electronics",
    parentIds: [
      "category-electronics",
      "category-mobiles-accessories-electronics",
    ],
    childrenIds: [],
    tier: 2,
    path: "electronics/mobiles-accessories/mobile-accessories",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: ["product-anker-usbc-charger-electronics-new-techhub-1"],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: daysAhead(4),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Chibi Figurines & Mini Collectibles | LetItRip",
      description:
        "Shop Nendoroids, gashapon, mini figurines, and chibi anime collectibles",
      keywords: [
        "chibi",
        "mini figurine",
        "gashapon",
        "spirited away",
        "studio ghibli",
      ],
    },
    display: {
      icon: "ðŸ˜Š",
      coverImage:
        "https://images.unsplash.com/photo-1560762484-813fc97650a0?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [
      { id: "category-electronics", name: "Scale Figures", tier: 0 },
      {
        id: "category-mobiles-accessories-electronics",
        name: "Nendoroids & Chibis",
        tier: 1,
      },
    ],
  },
  // Scale Figures > Premium Statues
  {
    id: "category-laptops-computers-electronics",
    name: "Premium Statues",
    slug: "laptops-computers",
    description: "Large-scale One Piece, Bleach, and premium anime statues",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/laptops-computers",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 3,
      productIds: [
        "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
        "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
        "product-apple-ipad-pro-electronics-new-techhub-1",
      ],
      auctionCount: 1,
      auctionIds: ["product-macbook-pro-m3-auction-electronics-techhub-1"],
      totalProductCount: 3,
      totalAuctionCount: 1,
      totalItemCount: 4,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 3,
    seo: {
      title: "Premium Anime Statues — One Piece, Bleach | LetItRip",
      description:
        "Browse large-scale One Piece, Bleach, and premium anime statues by Bandai Spirits and MegaHouse",
      keywords: [
        "one piece",
        "bleach",
        "premium statue",
        "large scale",
        "megahouse",
      ],
    },
    display: {
      icon: "ðŸ†",
      coverImage:
        "https://images.unsplash.com/photo-1599409636295-e3cf3538f212?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [{ id: "category-electronics", name: "Scale Figures", tier: 0 }],
  },
  // Scale Figures > Limited Edition
  {
    id: "category-audio-electronics",
    name: "Limited Edition Figures",
    slug: "audio",
    description: "Limited and sold-out exclusive anime figures",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/audio",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 2,
      productIds: [
        "preorder-chainsaw-man-makima-gsc-techhub-1",
        "preorder-frieren-1-7-alter-techhub-1",
      ],
      auctionCount: 4,
      auctionIds: [
        "auction-chainsaw-man-makima-figure-fashion-1",
        "auction-jjk-sukuna-figure-homeessentials-1",
        "auction-fate-saber-alter-figure-techhub-1",
        "auction-rezero-rem-wedding-figure-techhub-1",
      ],
      totalProductCount: 2,
      totalAuctionCount: 4,
      totalItemCount: 6,
      lastUpdated: daysAhead(4),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Limited Edition Anime Figures | LetItRip",
      description:
        "Shop exclusive, limited-run anime figures — Alter Co., Union Creative, limited releases",
      keywords: [
        "limited edition",
        "exclusive figure",
        "alter co",
        "sold out",
        "rare anime",
      ],
    },
    display: {
      icon: "â­",
      coverImage:
        "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [{ id: "category-electronics", name: "Scale Figures", tier: 0 }],
  },
  // Scale Figures > Signed Art & Collectibles
  {
    id: "category-cameras-photography-electronics",
    name: "Signed Art & Collectibles",
    slug: "cameras-photography",
    description:
      "Signed production art, original cels, and rare anime collectibles",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/cameras-photography",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 5,
      auctionIds: [
        "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
        "product-vintage-leica-camera-auction-artisan-1",
        "auction-pokemon-charizard-1st-ed-fashion-1",
        "auction-spirited-away-cel-homeessentials-1",
        "auction-one-piece-signed-artbook-techhub-1",
      ],
      totalProductCount: 0,
      totalAuctionCount: 5,
      totalItemCount: 5,
      lastUpdated: daysAhead(4),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Signed Anime Art & Rare Collectibles | LetItRip",
      description:
        "Shop original production cels, signed posters, and rare anime collectibles from Gainax, Toei, and more",
      keywords: [
        "production cel",
        "signed poster",
        "evangelion",
        "gainax",
        "anime auction",
      ],
    },
    display: {
      icon: "ðŸ–¼ï¸",
      coverImage:
        "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [{ id: "category-electronics", name: "Scale Figures", tier: 0 }],
  },

  // ROOT: Cosplay & Apparel
  {
    id: "category-fashion",
    name: "Cosplay & Apparel",
    slug: "fashion",
    description: "Anime cosplay, apparel, and accessories",
    rootId: "category-fashion",
    parentIds: [],
    childrenIds: [
      "category-mens-fashion-fashion",
      "category-womens-fashion-fashion",
    ],
    tier: 0,
    path: "fashion",
    order: 2,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 8,
      totalAuctionCount: 0,
      totalItemCount: 8,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 4,
    seo: {
      title: "Cosplay & Anime Apparel | LetItRip",
      description:
        "Shop anime cosplay outfits, graphic tees, hoodies, and official licensed apparel",
      keywords: [
        "cosplay",
        "anime apparel",
        "cosplay outfit",
        "anime tee",
        "hoodie",
      ],
    },
    display: {
      icon: "ðŸŽ­",
      coverImage:
        "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=800&h=800&fit=crop",
      color: "#ec4899",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },
  // Cosplay > Men's Cosplay
  {
    id: "category-mens-fashion-fashion",
    name: "Men's Cosplay",
    slug: "mens-fashion",
    description: "Cosplay sets, jackets, hoodies, and apparel for men",
    rootId: "category-fashion",
    parentIds: ["category-fashion"],
    childrenIds: [],
    tier: 1,
    path: "fashion/mens-fashion",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 4,
      productIds: [
        "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
        "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
        "product-mens-slim-chinos-fashion-new-fashionboutique-1",
        "product-mens-leather-derby-shoes-fashion-new-fashionboutique-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 4,
      totalAuctionCount: 0,
      totalItemCount: 4,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 5,
    seo: {
      title: "Men's Cosplay & Anime Apparel | LetItRip",
      description:
        "Shop men's anime cosplay sets, Scout Regiment jackets, Akatsuki cloaks, and graphic hoodies",
      keywords: [
        "mens cosplay",
        "anime jacket",
        "attack on titan",
        "naruto",
        "akatsuki cloak",
      ],
    },
    display: {
      icon: "ðŸ‘˜",
      coverImage:
        "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [{ id: "category-fashion", name: "Cosplay & Apparel", tier: 0 }],
  },
  // Cosplay > Women's Cosplay
  {
    id: "category-womens-fashion-fashion",
    name: "Women's Cosplay",
    slug: "womens-fashion",
    description: "Cosplay dresses, kimono sets, and anime apparel for women",
    rootId: "category-fashion",
    parentIds: ["category-fashion"],
    childrenIds: [],
    tier: 1,
    path: "fashion/womens-fashion",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 4,
      productIds: [
        "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
        "product-womens-anarkali-kurta-fashion-new-fashionboutique-1",
        "product-womens-casual-midi-dress-fashion-new-fashionboutique-1",
        "product-womens-structured-tote-bag-fashion-new-fashionboutique-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 4,
      totalAuctionCount: 0,
      totalItemCount: 4,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 6,
    seo: {
      title: "Women's Cosplay & Anime Apparel | LetItRip",
      description:
        "Shop women's cosplay dresses, Sailor Moon sets, Genshin Impact cosplay, and anime bags",
      keywords: [
        "womens cosplay",
        "sailor moon",
        "genshin impact",
        "nezuko",
        "cosplay dress",
      ],
    },
    display: {
      icon: "ðŸ‘—",
      coverImage:
        "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&h=800&fit=crop",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [{ id: "category-fashion", name: "Cosplay & Apparel", tier: 0 }],
  },

  // ROOT: Collectibles & Display
  {
    id: "category-home-kitchen",
    name: "Collectibles & Display",
    slug: "home-kitchen",
    description:
      "Nendoroids, garage kits, art replicas, and display collectibles",
    rootId: "category-home-kitchen",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "home-kitchen",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 5,
      productIds: [
        "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
        "product-prestige-pressure-cooker-home-new-homeessentials-1",
        "product-nonstick-cookware-set-home-new-homeessentials-1",
        "product-smart-air-purifier-home-new-homeessentials-1",
        "product-solid-wood-coffee-table-home-new-homeessentials-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 5,
      totalAuctionCount: 0,
      totalItemCount: 5,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 7,
    seo: {
      title: "Anime Collectibles & Display Sets | LetItRip",
      description:
        "Shop Nendoroids, studio display sets, garage kits, 3D Maneuver Gear replicas and more",
      keywords: [
        "nendoroid",
        "garage kit",
        "collectible",
        "display set",
        "ghibli",
      ],
    },
    display: {
      icon: "ðŸŽŽ",
      coverImage:
        "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
      color: "#10b981",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Model Kits & Gunpla
  {
    id: "category-sports-outdoors",
    name: "Model Kits & Gunpla",
    slug: "sports-outdoors",
    description: "Gundam model kits, Gunpla, ship models, and poseable figures",
    rootId: "category-sports-outdoors",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "sports-outdoors",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 5,
      productIds: [
        "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
        "product-premium-yoga-mat-sports-new-sportszone-1",
        "product-adjustable-dumbbell-set-sports-new-sportszone-1",
        "product-cricket-bat-mrf-sports-new-sportszone-1",
        "product-running-shoes-adidas-sports-new-sportszone-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 5,
      totalAuctionCount: 0,
      totalItemCount: 5,
      lastUpdated: daysAhead(4),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 8,
    seo: {
      title: "Gunpla & Model Kits | LetItRip",
      description:
        "Shop Gundam Perfect Grade, Master Grade model kits, ship models, and Naruto Figures",
      keywords: [
        "gunpla",
        "gundam",
        "model kit",
        "perfect grade",
        "master grade",
      ],
    },
    display: {
      icon: "ðŸ¤–",
      coverImage:
        "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
      color: "#f97316",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Beauty & Health
  {
    id: "category-beauty-health",
    name: "Beauty & Health",
    slug: "beauty-health",
    description: "Skincare, cosmetics, and wellness products",
    rootId: "category-beauty-health",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "beauty-health",
    order: 5,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(29),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 9,
    seo: {
      title: "Beauty & Health | LetItRip",
      description: "Shop skincare, cosmetics, and wellness products",
      keywords: ["beauty", "skincare", "cosmetics", "health", "wellness"],
    },
    display: {
      icon: "ðŸ’„",
      coverImage:
        "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop",
      color: "#ec4899",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Books & Stationery
  {
    id: "category-books-stationery",
    name: "Books & Stationery",
    slug: "books-stationery",
    description: "Books, notebooks, and office supplies",
    rootId: "category-books-stationery",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "books-stationery",
    order: 6,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(29),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 10,
    seo: {
      title: "Books & Stationery | LetItRip",
      description: "Shop books, notebooks, and office supplies",
      keywords: ["books", "stationery", "notebooks", "office supplies"],
    },
    display: {
      icon: "ðŸ“š",
      coverImage:
        "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=800&fit=crop",
      color: "#f59e0b",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Automotive
  {
    id: "category-automotive",
    name: "Automotive",
    slug: "automotive",
    description: "Car accessories, tools, and parts",
    rootId: "category-automotive",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "automotive",
    order: 7,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(29),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 11,
    seo: {
      title: "Automotive | LetItRip",
      description: "Shop car accessories, tools, and parts",
      keywords: ["automotive", "car accessories", "vehicle parts", "tools"],
    },
    display: {
      icon: "ðŸš—",
      coverImage:
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=800&fit=crop",
      color: "#6b7280",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Jewelry & Accessories
  {
    id: "category-jewelry-accessories",
    name: "Jewelry & Accessories",
    slug: "jewelry-accessories",
    description: "Fine jewelry, watches, and fashion accessories",
    rootId: "category-jewelry-accessories",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "jewelry-accessories",
    order: 8,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(29),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 12,
    seo: {
      title: "Jewelry & Accessories | LetItRip",
      description: "Shop fine jewelry, watches, and fashion accessories",
      keywords: ["jewelry", "watches", "accessories", "rings", "necklaces"],
    },
    display: {
      icon: "ðŸ’",
      coverImage:
        "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&h=800&fit=crop",
      color: "#d97706",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Toys & Baby
  {
    id: "category-toys-baby",
    name: "Toys & Baby",
    slug: "toys-baby",
    description: "Toys, games, and baby essentials",
    rootId: "category-toys-baby",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "toys-baby",
    order: 9,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(29),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 13,
    seo: {
      title: "Toys & Baby | LetItRip",
      description: "Shop toys, games, and baby essentials",
      keywords: ["toys", "baby", "kids", "games", "educational toys"],
    },
    display: {
      icon: "ðŸ§¸",
      coverImage:
        "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=800&fit=crop",
      color: "#8b5cf6",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // ROOT: Food & Groceries
  {
    id: "category-food-groceries",
    name: "Food & Groceries",
    slug: "food-groceries",
    description: "Fresh produce, packaged foods, and beverages",
    rootId: "category-food-groceries",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "food-groceries",
    order: 10,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(29),
    },
    isFeatured: true,
    isBrand: false,
    featuredPriority: 14,
    seo: {
      title: "Food & Groceries | LetItRip",
      description: "Shop fresh produce, packaged foods, and beverages",
      keywords: ["food", "groceries", "beverages", "fresh produce", "snacks"],
    },
    display: {
      icon: "ðŸ›’",
      coverImage:
        "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&h=800&fit=crop",
      color: "#059669",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(29),
    ancestors: [],
  },

  // BRAND: Apple
  {
    id: "category-brand-apple",
    name: "Apple",
    slug: "apple",
    description:
      "Official Apple products including iPhone, Mac, iPad, and accessories",
    rootId: "category-brand-apple",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand/apple",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 3,
      productIds: [
        "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
        "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
        "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
      ],
      auctionCount: 2,
      auctionIds: [
        "auction-iphone15-sealed-bundle-techhub-1",
        "product-macbook-pro-m3-auction-electronics-techhub-1",
      ],
      totalProductCount: 3,
      totalAuctionCount: 2,
      totalItemCount: 5,
      lastUpdated: daysAgo(3),
    },
    isFeatured: false,
    isBrand: true,
    seo: {
      title: "Apple Products | LetItRip",
      description:
        "Shop genuine Apple products — iPhone, MacBook, iPad, and accessories",
      keywords: ["apple", "iphone", "macbook", "ipad", "airpods"],
      ogImage:
        "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "ðŸŽ",
      coverImage:
        "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&h=800&fit=crop",
      color: "#555555",
      showInMenu: false,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(3),
    ancestors: [],
  },
  // BRAND: Samsung
  {
    id: "category-brand-samsung",
    name: "Samsung",
    slug: "samsung",
    description:
      "Samsung electronics including smartphones, TVs, and home appliances",
    rootId: "category-brand-samsung",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand/samsung",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 2,
      productIds: [
        "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
        "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 2,
      totalAuctionCount: 0,
      totalItemCount: 2,
      lastUpdated: daysAgo(3),
    },
    isFeatured: false,
    isBrand: true,
    seo: {
      title: "Samsung Products | LetItRip",
      description: "Shop Samsung smartphones, TVs, and home appliances",
      keywords: ["samsung", "galaxy", "samsung tv", "samsung phone"],
      ogImage:
        "https://images.unsplash.com/photo-1610945264803-c22b62831028?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "ðŸ“º",
      coverImage:
        "https://images.unsplash.com/photo-1610945264803-c22b62831028?w=800&h=800&fit=crop",
      color: "#1428a0",
      showInMenu: false,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(3),
    ancestors: [],
  },
  // BRAND: Sony
  {
    id: "category-brand-sony",
    name: "Sony",
    slug: "sony",
    description:
      "Sony electronics including headphones, cameras, and gaming consoles",
    rootId: "category-brand-sony",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand/sony",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
      ],
      auctionCount: 2,
      auctionIds: [
        "auction-ps5-slim-gaming-console-techhub-1",
        "auction-sony-alpha-7iv-camera-techhub-1",
      ],
      totalProductCount: 1,
      totalAuctionCount: 2,
      totalItemCount: 3,
      lastUpdated: daysAgo(3),
    },
    isFeatured: false,
    isBrand: true,
    seo: {
      title: "Sony Products | LetItRip",
      description:
        "Shop Sony headphones, cameras, and PlayStation gaming consoles",
      keywords: ["sony", "playstation", "sony headphones", "sony camera"],
      ogImage:
        "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "ðŸŽ®",
      coverImage:
        "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop",
      color: "#000000",
      showInMenu: false,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(3),
    ancestors: [],
  },
  // BRAND: Nike
  {
    id: "category-brand-nike",
    name: "Nike",
    slug: "nike",
    description: "Nike sportswear, footwear, and athletic equipment",
    rootId: "category-brand-nike",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand/nike",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
      ],
      auctionCount: 1,
      auctionIds: ["product-limited-air-jordan-sneakers-auction-artisan-1"],
      totalProductCount: 1,
      totalAuctionCount: 1,
      totalItemCount: 2,
      lastUpdated: daysAgo(3),
    },
    isFeatured: false,
    isBrand: true,
    seo: {
      title: "Nike Products | LetItRip",
      description: "Shop Nike sportswear, running shoes, and athletic gear",
      keywords: ["nike", "nike shoes", "sportswear", "running", "athletic"],
      ogImage:
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "ðŸ‘Ÿ",
      coverImage:
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
      color: "#111111",
      showInMenu: false,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(3),
    ancestors: [],
  },
  // BRAND: Adidas
  {
    id: "category-brand-adidas",
    name: "Adidas",
    slug: "adidas",
    description: "Adidas sportswear, footwear, and accessories",
    rootId: "category-brand-adidas",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand/adidas",
    order: 5,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: daysAgo(3),
    },
    isFeatured: false,
    isBrand: true,
    seo: {
      title: "Adidas Products | LetItRip",
      description: "Shop Adidas sportswear, shoes, and accessories",
      keywords: ["adidas", "adidas shoes", "sportswear", "running"],
      ogImage:
        "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "ðŸ‘•",
      coverImage:
        "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&h=800&fit=crop",
      color: "#000000",
      showInMenu: false,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-user-admin",
    createdAt: daysAgo(799),
    updatedAt: daysAgo(3),
    ancestors: [],
  },
];
