/**
 * Orders Seed Data — Anime/Otaku Marketplace
 * Sample orders across all statuses, linked to anime products and users
 */

import type { OrderDocument } from "@/db/schema";

// Dynamic date helpers
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const ordersSeedData: Partial<OrderDocument>[] = [
  // ── DELIVERED ─────────────────────────────────────────────────────────────
  {
    id: "order-1-20260115-xk7m9p",
    productId:
      "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    productTitle: "Dragon Ball Super Saiyan Blue Goku 1/4 Scale Figure",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    quantity: 1,
    unitPrice: 12490,
    totalPrice: 12490,
    currency: "INR",
    status: "delivered",
    paymentStatus: "paid",
    paymentId: "pay_001",
    paymentMethod: "credit_card",
    shippingAddress: "123 Marine Drive, Mumbai 400001",
    trackingNumber: "TRACK123456789",
    notes: "Deliver 10 AM - 6 PM",
    orderDate: daysAgo(53),
    shippingDate: daysAgo(52),
    deliveryDate: daysAgo(50),
    createdAt: daysAgo(53),
    updatedAt: daysAgo(50),
  },
  {
    id: "order-1-20260120-b4n8q3",
    productId:
      "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    productTitle: "Super Saiyan Vegeta Final Flash 1/4 Scale Statue",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    quantity: 1,
    unitPrice: 9990,
    totalPrice: 9990,
    currency: "INR",
    status: "delivered",
    paymentStatus: "paid",
    paymentId: "pay_002",
    paymentMethod: "upi",
    shippingAddress: "45, Connaught Place, New Delhi, Delhi - 110001",
    trackingNumber: "TRACK987654321",
    orderDate: daysAgo(48),
    shippingDate: daysAgo(47),
    deliveryDate: daysAgo(45),
    createdAt: daysAgo(48),
    updatedAt: daysAgo(45),
  },
  {
    id: "order-2-20260125-r5t9w1",
    productId:
      "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    productTitle: "Demon Slayer Tanjiro Kamado Graphic T-Shirt",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    quantity: 2,
    unitPrice: 1499,
    totalPrice: 2998,
    currency: "INR",
    status: "delivered",
    paymentStatus: "paid",
    paymentId: "pay_003",
    paymentMethod: "debit_card",
    shippingAddress: "78, MG Road, Bangalore, Karnataka - 560001",
    trackingNumber: "TRACK456789123",
    orderDate: daysAgo(43),
    shippingDate: daysAgo(42),
    deliveryDate: daysAgo(40),
    createdAt: daysAgo(43),
    updatedAt: daysAgo(40),
  },

  // Shipped orders
  {
    id: "order-1-20260205-h2k6m4",
    productId:
      "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    productTitle: "Monkey D. Luffy Gear 5 Sun God 1/4 Scale Scene Figure",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    quantity: 1,
    unitPrice: 24990,
    totalPrice: 24990,
    currency: "INR",
    status: "shipped",
    paymentStatus: "paid",
    paymentId: "pay_004",
    paymentMethod: "credit_card",
    shippingAddress:
      "123, Marine Drive, Apartment 45, Mumbai, Maharashtra - 400001",
    trackingNumber: "TRACK789123456",
    orderDate: daysAgo(32),
    shippingDate: daysAgo(30),
    createdAt: daysAgo(32),
    updatedAt: daysAgo(30),
  },
  {
    id: "order-3-20260206-m3n7p5",
    productId:
      "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    productTitle: "Nezuko Kamado Pink Kimono Hoodie Dress",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    quantity: 3,
    unitPrice: 1999,
    totalPrice: 5997,
    currency: "INR",
    status: "shipped",
    paymentStatus: "paid",
    paymentId: "pay_005",
    paymentMethod: "netbanking",
    shippingAddress: "45, Connaught Place, New Delhi, Delhi - 110001",
    trackingNumber: "TRACK123789456",
    orderDate: daysAgo(31),
    shippingDate: daysAgo(29),
    createdAt: daysAgo(31),
    updatedAt: daysAgo(29),
  },

  // Confirmed orders (awaiting shipment)
  {
    id: "order-1-20260208-k2l4n8",
    productId:
      "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    productTitle: "My Neighbour Totoro Nendoroid No.1234 Deluxe Set",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    quantity: 1,
    unitPrice: 3499,
    totalPrice: 3499,
    currency: "INR",
    status: "confirmed",
    paymentStatus: "paid",
    paymentId: "pay_006",
    paymentMethod: "cod",
    shippingAddress: "78, MG Road, Bangalore, Karnataka - 560001",
    orderDate: daysAgo(29),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: "order-3-20260208-v1w7x2",
    productId:
      "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    productTitle: "Gundam RX-78-2 Perfect Grade 1/60 Model Kit",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    quantity: 2,
    unitPrice: 1299,
    totalPrice: 2598,
    currency: "INR",
    status: "confirmed",
    paymentStatus: "paid",
    paymentId: "pay_007",
    paymentMethod: "upi",
    shippingAddress:
      "123, Marine Drive, Apartment 45, Mumbai, Maharashtra - 400001",
    orderDate: daysAgo(29),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },

  // Pending orders
  {
    id: "order-1-20260209-d6f2h1",
    productId:
      "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    productTitle: "Ultra Instinct Goku Premium 1/6 Scale Figure",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    quantity: 1,
    unitPrice: 6990,
    totalPrice: 6990,
    currency: "INR",
    status: "pending",
    paymentStatus: "pending",
    paymentMethod: "credit_card",
    shippingAddress: "45, Connaught Place, New Delhi, Delhi - 110001",
    orderDate: daysAgo(28),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
  },

  // Cancelled order
  {
    id: "order-1-20260128-t9u3v7",
    productId:
      "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    productTitle: "Roronoa Zoro Enma Slash Diorama 1/7 Scale",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    quantity: 1,
    unitPrice: 18990,
    totalPrice: 18990,
    currency: "INR",
    status: "cancelled",
    paymentStatus: "refunded",
    paymentId: "pay_009",
    paymentMethod: "debit_card",
    shippingAddress: "78, MG Road, Bangalore, Karnataka - 560001",
    cancellationDate: daysAgo(38),
    cancellationReason: "Customer cancelled - found better price",
    refundAmount: 18990,
    refundStatus: "completed",
    orderDate: daysAgo(40),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(38),
  },

  // Returned order
  {
    id: "order-1-20260128-s4t7u1",
    productId:
      "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    productTitle: "Demon Slayer Tanjiro Kamado Graphic T-Shirt",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    quantity: 1,
    unitPrice: 1499,
    totalPrice: 1499,
    currency: "INR",
    status: "returned",
    paymentStatus: "refunded",
    paymentId: "pay_010",
    paymentMethod: "upi",
    shippingAddress:
      "123, Marine Drive, Apartment 45, Mumbai, Maharashtra - 400001",
    trackingNumber: "TRACK321654987",
    cancellationReason: "Size issue - exchanged",
    refundAmount: 1499,
    refundStatus: "completed",
    orderDate: daysAgo(58),
    shippingDate: daysAgo(57),
    deliveryDate: daysAgo(55),
    cancellationDate: daysAgo(50),
    createdAt: daysAgo(58),
    updatedAt: daysAgo(48),
  },

  // Payment failed order
  {
    id: "order-1-20260208-z1x5c9",
    productId:
      "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    productTitle: "Super Saiyan Vegeta Final Flash 1/4 Scale Statue",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    quantity: 1,
    unitPrice: 9990,
    totalPrice: 9990,
    currency: "INR",
    status: "pending",
    paymentStatus: "failed",
    paymentId: "pay_011_failed",
    paymentMethod: "credit_card",
    shippingAddress: "78, MG Road, Bangalore, Karnataka - 560001",
    notes: "Payment timeout",
    orderDate: daysAgo(29),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },

  // Multiple items order
  {
    id: "order-5-20260201-w8y2a6",
    productId:
      "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    productTitle: "Gundam RX-78-2 Perfect Grade 1/60 Model Kit",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    quantity: 5,
    unitPrice: 4999,
    totalPrice: 24995,
    currency: "INR",
    status: "delivered",
    paymentStatus: "paid",
    paymentId: "pay_012",
    paymentMethod: "netbanking",
    shippingAddress: "45, Connaught Place, New Delhi, Delhi - 110001",
    trackingNumber: "TRACK654987321",
    notes: "Bulk order for Gunpla club",
    orderDate: daysAgo(36),
    shippingDate: daysAgo(35),
    deliveryDate: daysAgo(32),
    createdAt: daysAgo(36),
    updatedAt: daysAgo(32),
  },

  // ─── Pending Orders ────────────────────────────────────────────────────────
  {
    id: "order-pending-1-20260219-np3k7x",
    productId: "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
    productTitle: "Attack on Titan Scout Regiment Cosplay Jacket",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    quantity: 2,
    unitPrice: 1299,
    totalPrice: 2598,
    currency: "INR",
    status: "pending",
    paymentStatus: "pending",
    shippingAddress: "12 MG Road, Ahmedabad, Gujarat - 380009",
    orderDate: daysAgo(18),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
  {
    id: "order-pending-2-20260218-bm9q2y",
    productId: "product-premium-yoga-mat-sports-new-sportszone-1",
    productTitle: "Naruto Sage Mode Toad Sage 1/7 Scale PVC Figure",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    quantity: 1,
    unitPrice: 3999,
    totalPrice: 3999,
    currency: "INR",
    status: "pending",
    paymentStatus: "paid",
    paymentId: "pay_013",
    paymentMethod: "upi",
    shippingAddress: "88/4 MG Road, Kochi, Kerala - 682001",
    notes: "Please include invoice",
    orderDate: daysAgo(19),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },

  // ─── Confirmed Orders ──────────────────────────────────────────────────────
  {
    id: "order-confirmed-1-20260217-ck4t8w",
    productId: "product-prestige-pressure-cooker-home-new-homeessentials-1",
    productTitle: "Rem & Ram Re:Zero Nendoroid Duo Set",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    quantity: 1,
    unitPrice: 2499,
    totalPrice: 2499,
    currency: "INR",
    status: "confirmed",
    paymentStatus: "paid",
    paymentId: "pay_014",
    paymentMethod: "credit_card",
    shippingAddress: "34 Banjara Hills, Hyderabad, Telangana - 500034",
    orderDate: daysAgo(20),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: "order-confirmed-2-20260216-fp7r1v",
    productId: "product-samsung-galaxy-watch6-electronics-new-techhub-1",
    productTitle: "Dragon Ball Z Scouter Replica & Capsule Corp Gift Set",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    quantity: 1,
    unitPrice: 4999,
    totalPrice: 4999,
    currency: "INR",
    status: "confirmed",
    paymentStatus: "paid",
    paymentId: "pay_015",
    paymentMethod: "debit_card",
    shippingAddress: "123 Marine Drive, Mumbai, Maharashtra - 400001",
    orderDate: daysAgo(21),
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: "order-confirmed-3-20260215-gx2s5u",
    productId: "product-womens-anarkali-kurta-fashion-new-fashionboutique-1",
    productTitle: "Sailor Moon Neo Queen Serenity Cosplay Dress Set",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    quantity: 1,
    unitPrice: 2899,
    totalPrice: 2899,
    currency: "INR",
    status: "confirmed",
    paymentStatus: "paid",
    paymentId: "pay_016",
    paymentMethod: "upi",
    shippingAddress: "88/4 MG Road, Kochi, Kerala - 682001",
    notes: "For Holi celebration, please ensure timely delivery",
    orderDate: daysAgo(22),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(22),
  },

  // ─── Shipped Orders ────────────────────────────────────────────────────────
  {
    id: "order-shipped-1-20260214-hn5u9z",
    productId: "product-cricket-bat-mrf-sports-new-sportszone-1",
    productTitle: "One Piece Going Merry Ship 1/144 Scale Resin Model",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    quantity: 1,
    unitPrice: 6999,
    totalPrice: 6999,
    currency: "INR",
    status: "shipped",
    paymentStatus: "paid",
    paymentId: "pay_017",
    paymentMethod: "netbanking",
    shippingAddress: "12 MG Road, Ahmedabad, Gujarat - 380009",
    trackingNumber: "BLRDT202602140892",
    orderDate: daysAgo(23),
    shippingDate: daysAgo(22),
    createdAt: daysAgo(23),
    updatedAt: daysAgo(22),
  },
  {
    id: "order-shipped-2-20260213-jq8v4a",
    productId: "product-anker-usbc-charger-electronics-new-techhub-1",
    productTitle: "Spirited Away No-Face Resin Miniature Figurine",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    quantity: 2,
    unitPrice: 1290,
    totalPrice: 2580,
    currency: "INR",
    status: "shipped",
    paymentStatus: "paid",
    paymentId: "pay_018",
    paymentMethod: "credit_card",
    shippingAddress: "34 Banjara Hills, Hyderabad, Telangana - 500034",
    trackingNumber: "BOMDT202602130441",
    orderDate: daysAgo(24),
    shippingDate: daysAgo(23),
    createdAt: daysAgo(24),
    updatedAt: daysAgo(23),
  },
  {
    id: "order-shipped-3-20260212-kt1w6b",
    productId: "product-nonstick-cookware-set-home-new-homeessentials-1",
    productTitle: "Attack on Titan 3D Maneuver Gear Wallhanger Replica",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userEmail: "jane@letitrip.in",
    quantity: 1,
    unitPrice: 3799,
    totalPrice: 3799,
    currency: "INR",
    status: "shipped",
    paymentStatus: "paid",
    paymentId: "pay_019",
    paymentMethod: "upi",
    shippingAddress: "45, Connaught Place, New Delhi, Delhi - 110001",
    trackingNumber: "DELDT202602120213",
    orderDate: daysAgo(25),
    shippingDate: daysAgo(24),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(24),
  },

  // ─── Cancelled Orders ──────────────────────────────────────────────────────
  {
    id: "order-cancelled-1-20260210-lv4x7c",
    productId: "product-apple-ipad-pro-electronics-new-techhub-1",
    productTitle: "Bleach Ichigo Bankai Tensa Zangetsu 1/6 Scale Figure",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userEmail: "mike@letitrip.in",
    quantity: 1,
    unitPrice: 8990,
    totalPrice: 8990,
    currency: "INR",
    status: "cancelled",
    paymentStatus: "refunded",
    paymentId: "pay_020",
    paymentMethod: "credit_card",
    shippingAddress: "56 Anna Nagar, Chennai, Tamil Nadu - 600040",
    cancellationDate: daysAgo(26),
    cancellationReason: "Found a better deal elsewhere",
    refundAmount: 8990,
    refundStatus: "completed",
    orderDate: daysAgo(27),
    createdAt: daysAgo(27),
    updatedAt: daysAgo(26),
  },
  {
    id: "order-cancelled-2-20260205-mx8y2d",
    productId: "product-adjustable-dumbbell-set-sports-new-sportszone-1",
    productTitle: "Gundam Wing Zero Custom 1/100 Master Grade Model Kit",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userEmail: "john@letitrip.in",
    quantity: 1,
    unitPrice: 14999,
    totalPrice: 14999,
    currency: "INR",
    status: "cancelled",
    paymentStatus: "refunded",
    paymentId: "pay_021",
    paymentMethod: "debit_card",
    shippingAddress: "123 Marine Drive, Mumbai, Maharashtra - 400001",
    cancellationDate: daysAgo(32),
    cancellationReason: "Ordered by mistake — wrong size",
    refundAmount: 14999,
    refundStatus: "completed",
    orderDate: daysAgo(32),
    createdAt: daysAgo(32),
    updatedAt: daysAgo(31),
  },
  {
    id: "order-cancelled-3-20260130-ny2z5e",
    productId: "product-solid-wood-coffee-table-home-new-homeessentials-1",
    productTitle: "Studio Ghibli Collector's Display Shelf Set (8 Figures)",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userEmail: "priya@letitrip.in",
    quantity: 1,
    unitPrice: 8499,
    totalPrice: 8499,
    currency: "INR",
    status: "cancelled",
    paymentStatus: "pending",
    shippingAddress: "34 Banjara Hills, Hyderabad, Telangana - 500034",
    cancellationDate: daysAgo(38),
    cancellationReason: "Payment failed — order auto-cancelled after 24 hours",
    orderDate: daysAgo(39),
    createdAt: daysAgo(39),
    updatedAt: daysAgo(38),
  },

  // ─── Returned Orders ───────────────────────────────────────────────────────
  {
    id: "order-returned-1-20260120-pz6a8f",
    productId: "product-womens-casual-midi-dress-fashion-new-fashionboutique-1",
    productTitle: "Genshin Impact Ganyu Qixing Cosplay Dress",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userEmail: "vikram@letitrip.in",
    quantity: 1,
    unitPrice: 1649,
    totalPrice: 1649,
    currency: "INR",
    status: "returned",
    paymentStatus: "refunded",
    paymentId: "pay_022",
    paymentMethod: "upi",
    shippingAddress: "88/4 MG Road, Kochi, Kerala - 682001",
    trackingNumber: "KOCDT202601200098",
    cancellationReason: "Size mismatch — product smaller than described",
    refundAmount: 1649,
    refundStatus: "completed",
    orderDate: daysAgo(48),
    shippingDate: daysAgo(47),
    deliveryDate: daysAgo(45),
    cancellationDate: daysAgo(43),
    createdAt: daysAgo(48),
    updatedAt: daysAgo(40),
  },
  {
    id: "order-returned-2-20260112-qb9c1g",
    productId: "product-running-shoes-adidas-sports-new-sportszone-1",
    productTitle: "Jujutsu Kaisen Gojo Satoru Infinity Domain 1/7 Scale",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userEmail: "raj@letitrip.in",
    quantity: 1,
    unitPrice: 15999,
    totalPrice: 15999,
    currency: "INR",
    status: "returned",
    paymentStatus: "refunded",
    paymentId: "pay_023",
    paymentMethod: "credit_card",
    shippingAddress: "12 MG Road, Ahmedabad, Gujarat - 380009",
    trackingNumber: "AHDDT202601120512",
    cancellationReason: "Received wrong colour — ordered black, received white",
    refundAmount: 15999,
    refundStatus: "processing",
    orderDate: daysAgo(56),
    shippingDate: daysAgo(55),
    deliveryDate: daysAgo(53),
    cancellationDate: daysAgo(52),
    createdAt: daysAgo(56),
    updatedAt: daysAgo(48),
  },
];
