/**
 * Products Seed Data — 101 anime figures, collectibles, cosplay & merch
 * All dates computed dynamically at module-load time (never stale).
 */
import type { ProductDocument } from "@/db/schema";

// ─── Dynamic date helpers ───────────────────────────────────────────────────
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

// ─── Seller shortcuts ───────────────────────────────────────────────────────
const FV = {
  sellerId: "user-techhub-electronics-electron",
  storeId: "store-figurevault-jp-by-figurevault",
  sellerName: "FigureVault JP",
  sellerEmail: "techhub@letitrip.in",
} as const;
const AC = {
  sellerId: "user-fashion-boutique-fashionb",
  storeId: "store-animecraft-apparel-by-animecraft",
  sellerName: "AnimeCraft Apparel",
  sellerEmail: "fashion@letitrip.in",
} as const;
const OS = {
  sellerId: "user-home-essentials-homeesse",
  storeId: "store-otakushelf-co-by-otakushelf",
  sellerName: "OtakuShelf Co",
  sellerEmail: "home@letitrip.in",
} as const;

// ─── Regular stockable products (24 — all referenced by orders/reviews/cart) ─
const regularProducts: Partial<ProductDocument>[] = [
  {
    id: "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    title: "Dragon Ball Super Saiyan Blue Goku 1/4 Scale Figure",
    description:
      "Bandai Spirits 1/4 scale SSB Goku with swappable hands, Ki energy aura effect and detachable display stand.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "Bandai Spirits",
    price: 12490,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 25,
    mainImage: "https://picsum.photos/seed/goku-blue/800/800",
    images: ["https://picsum.photos/seed/goku-blue/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      thumbnailUrl: "https://picsum.photos/seed/goku-blue-vid/800/450",
      duration: 15,
    },
    status: "published",
    ...FV,
    featured: true,
    tags: ["dragon-ball", "goku", "scale-figure", "bandai"],
    specifications: [
      { name: "Scale", value: "1/4" },
      { name: "Height", value: "36 cm" },
    ],
    features: ["Ki energy aura", "Swappable hands", "Display stand"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 999,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    avgRating: 4.7,
    reviewCount: 3,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
  {
    id: "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    title: "Super Saiyan Vegeta Final Flash 1/4 Scale Statue",
    description:
      "MegaHouse Vegeta Final Flash statue with energy beam effect, battle damage base.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "MegaHouse",
    price: 9990,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage: "https://picsum.photos/seed/vegeta-flash/800/800",
    images: ["https://picsum.photos/seed/vegeta-flash/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["dragon-ball", "vegeta", "megahouse"],
    specifications: [
      { name: "Scale", value: "1/4" },
      { name: "Height", value: "32 cm" },
    ],
    features: ["Energy beam effect", "Battle base diorama"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 5,
    reviewCount: 1,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(8),
  },
  {
    id: "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    title: "Ultra Instinct Goku Premium 1/6 Scale Figure",
    description:
      "Banpresto Ultra Instinct Goku with silver aura effect and floating display stand.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "Banpresto",
    price: 6990,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 40,
    mainImage: "https://picsum.photos/seed/ui-goku/800/800",
    images: ["https://picsum.photos/seed/ui-goku/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["dragon-ball", "goku", "ultra-instinct"],
    specifications: [
      { name: "Scale", value: "1/6" },
      { name: "Height", value: "27 cm" },
    ],
    features: ["Silver aura effect", "Mirror-finish base"],
    shippingInfo: "Free shipping in 3-5 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 4,
    reviewCount: 1,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(10),
  },
  {
    id: "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    title: "Monkey D. Luffy Gear 5 Sun God 1/4 Scale Scene Figure",
    description:
      "Bandai Spirits Gear 5 Luffy Sun God Nika — 42 cm with cloud effect base.",
    category: "category-laptops-computers-electronics",
    subcategory: "One Piece Figures",
    brand: "Bandai Spirits",
    price: 24990,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    mainImage: "https://picsum.photos/seed/luffy-gear5/800/800",
    images: ["https://picsum.photos/seed/luffy-gear5/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      thumbnailUrl: "https://picsum.photos/seed/luffy-gear5-vid/800/450",
      duration: 15,
    },
    status: "published",
    ...FV,
    featured: true,
    tags: ["one-piece", "luffy", "gear-5", "sun-god-nika"],
    specifications: [
      { name: "Scale", value: "1/4" },
      { name: "Height", value: "42 cm" },
    ],
    features: ["Cloud effect base", "Balloon effect parts"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(21),
    avgRating: 5,
    reviewCount: 2,
    createdAt: daysAgo(130),
    updatedAt: daysAgo(6),
  },
  {
    id: "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    title: "Roronoa Zoro Enma Slash Diorama 1/7 Scale",
    description:
      "MegaHouse Zoro three-sword '360-pound phoenix' pose with black marble base.",
    category: "category-laptops-computers-electronics",
    subcategory: "One Piece Figures",
    brand: "MegaHouse",
    price: 18990,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 15,
    mainImage: "https://picsum.photos/seed/zoro-enma/800/800",
    images: ["https://picsum.photos/seed/zoro-enma/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["one-piece", "zoro", "diorama"],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "35 cm" },
    ],
    features: ["Three-sword form", "Marble-style base"],
    shippingInfo: "Free shipping in 4-6 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(145),
    updatedAt: daysAgo(9),
  },
  {
    id: "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    title: "Demon Slayer Tanjiro Kamado Graphic T-Shirt",
    description:
      "Official Kimetsu no Yaiba oversize tee with Tanjiro flame-water art. 100% heavyweight cotton.",
    category: "category-mens-fashion-fashion",
    subcategory: "Anime Tees",
    brand: "AnimeCraft Apparel",
    price: 1299,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 100,
    mainImage: "https://picsum.photos/seed/tanjiro-tee/800/800",
    images: ["https://picsum.photos/seed/tanjiro-tee/1200/800"],
    status: "published",
    ...AC,
    featured: false,
    tags: ["demon-slayer", "tanjiro", "tee"],
    specifications: [{ name: "Material", value: "100% Cotton (280 GSM)" }],
    features: ["DTG printed art", "Pre-shrunk fabric"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 4,
    reviewCount: 1,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(15),
  },
  {
    id: "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    title: "Nezuko Kamado Pink Kimono Hoodie Dress",
    description:
      "Nezuko-inspired pink kimono hemp leaf pattern hoodie dress with bamboo embroidery.",
    category: "category-womens-fashion-fashion",
    subcategory: "Cosplay Dresses",
    brand: "AnimeCraft Apparel",
    price: 1999,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 80,
    mainImage: "https://picsum.photos/seed/nezuko-dress/800/800",
    images: ["https://picsum.photos/seed/nezuko-dress/1200/800"],
    status: "published",
    ...AC,
    featured: true,
    tags: ["demon-slayer", "nezuko", "kimono", "cosplay"],
    specifications: [{ name: "Material", value: "Soft Fleece Blend" }],
    features: ["Hemp leaf pattern", "Embroidered cuffs"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 5,
    reviewCount: 2,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(20),
  },
  {
    id: "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    title: "My Neighbour Totoro Nendoroid Deluxe Set",
    description:
      "Good Smile Totoro Nendoroid with Satsuki & Mei chibis, bus stop diorama base.",
    category: "category-home-kitchen",
    subcategory: "Nendoroids",
    brand: "Good Smile Company",
    price: 3499,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: "https://picsum.photos/seed/totoro-nendo/800/800",
    images: ["https://picsum.photos/seed/totoro-nendo/1200/800"],
    status: "published",
    ...OS,
    featured: false,
    tags: ["ghibli", "totoro", "nendoroid"],
    specifications: [
      { name: "Height", value: "10 cm" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: ["Bus stop diorama", "Multiple face plates"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 4,
    reviewCount: 2,
    createdAt: daysAgo(240),
    updatedAt: daysAgo(25),
  },
  {
    id: "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    title: "Gundam RX-78-2 Perfect Grade 1/60 Model Kit",
    description:
      "Bandai PG 1/60 RX-78-2 with LED unit, 550+ snap-fit parts, internal skeleton frame.",
    category: "category-sports-outdoors",
    subcategory: "Perfect Grade Gunpla",
    brand: "Bandai",
    price: 4999,
    currency: "INR",
    stockQuantity: 75,
    availableQuantity: 75,
    mainImage: "https://picsum.photos/seed/rx78-gundam/800/800",
    images: ["https://picsum.photos/seed/rx78-gundam/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      thumbnailUrl: "https://picsum.photos/seed/rx78-gundam-vid/800/450",
      duration: 30,
      trimStart: 0,
      trimEnd: 25,
    },
    status: "published",
    ...OS,
    featured: false,
    tags: ["gundam", "rx-78-2", "perfect-grade"],
    specifications: [
      { name: "Scale", value: "1/60" },
      { name: "Parts", value: "550+" },
    ],
    features: ["Internal skeleton frame", "LED unit included"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 5,
    reviewCount: 1,
    createdAt: daysAgo(265),
    updatedAt: daysAgo(30),
  },
  {
    id: "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
    title: "Attack on Titan Scout Regiment Cosplay Jacket",
    description:
      "Licensed Survey Corps jacket with embroidered Wings of Freedom on chest and back.",
    category: "category-mens-fashion-fashion",
    subcategory: "Cosplay Jackets",
    brand: "AnimeCraft Apparel",
    price: 1499,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 75,
    mainImage: "https://picsum.photos/seed/aot-jacket/800/800",
    images: ["https://picsum.photos/seed/aot-jacket/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      thumbnailUrl: "https://picsum.photos/seed/aot-jacket-vid/800/450",
      duration: 60,
    },
    status: "published",
    ...AC,
    featured: true,
    tags: ["attack-on-titan", "scout-regiment", "cosplay"],
    specifications: [{ name: "Material", value: "Heavy Canvas + Cotton" }],
    features: ["Machine washable", "Screen-accurate emblem"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
  {
    id: "product-womens-anarkali-kurta-fashion-new-fashionboutique-1",
    title: "Sailor Moon Neo Queen Serenity Cosplay Dress Set",
    description:
      "3-piece Sailor Moon dress with tiara, moon rod and gloves. Screen-accurate detailing.",
    category: "category-womens-fashion-fashion",
    subcategory: "Cosplay Sets",
    brand: "AnimeCraft Apparel",
    price: 2899,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 38,
    mainImage: "https://picsum.photos/seed/sailor-moon/800/800",
    images: ["https://picsum.photos/seed/sailor-moon/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
      thumbnailUrl: "https://picsum.photos/seed/sailor-moon-vid/800/450",
      duration: 15,
    },
    status: "published",
    ...AC,
    featured: true,
    tags: ["sailor-moon", "serenity", "cosplay"],
    specifications: [{ name: "Material", value: "Satin + Organza" }],
    features: ["Tiara prop included", "Convention-ready set"],
    shippingInfo: "Ships in 2-4 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(28),
    avgRating: 5,
    reviewCount: 1,
    createdAt: daysAgo(140),
    updatedAt: daysAgo(4),
  },
  {
    id: "product-womens-casual-midi-dress-fashion-new-fashionboutique-1",
    title: "Genshin Impact Ganyu Qixing Cosplay Dress",
    description:
      "Ganyu cosplay with detachable cryo horns, pastel-blue tail, silk-style pleated dress.",
    category: "category-womens-fashion-fashion",
    subcategory: "Cosplay Dresses",
    brand: "AnimeCraft Apparel",
    price: 1649,
    currency: "INR",
    stockQuantity: 55,
    availableQuantity: 50,
    mainImage: "https://picsum.photos/seed/ganyu-cosplay/800/800",
    images: ["https://picsum.photos/seed/ganyu-cosplay/1200/800"],
    status: "published",
    ...AC,
    featured: false,
    tags: ["genshin-impact", "ganyu", "cosplay"],
    specifications: [{ name: "Material", value: "Chiffon Silk Blend" }],
    features: ["Detachable horns + tail", "Inclusive sizing XS-3XL"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(25),
  },
  {
    id: "product-womens-structured-tote-bag-fashion-new-fashionboutique-1",
    title: "Totoro Forest Spirit Embroidered Canvas Tote Bag",
    description:
      "Premium canvas tote with Totoro embroidery, magnetic snap, inner zipper pocket.",
    category: "category-womens-fashion-fashion",
    subcategory: "Anime Bags",
    brand: "AnimeCraft Apparel",
    price: 1999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage: "https://picsum.photos/seed/totoro-tote/800/800",
    images: ["https://picsum.photos/seed/totoro-tote/1200/800"],
    status: "published",
    ...AC,
    featured: false,
    tags: ["ghibli", "totoro", "tote"],
    specifications: [{ name: "Material", value: "12oz Canvas" }],
    features: ["Embroidered art", "Magnetic snap closure"],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(15),
  },
  {
    id: "product-prestige-pressure-cooker-home-new-homeessentials-1",
    title: "Rem & Ram Re:Zero Nendoroid Duo Set",
    description:
      "Good Smile twin Nendoroids Rem (#1002) + Ram (#1003) with ice flower and maid accessories.",
    category: "category-home-kitchen",
    subcategory: "Nendoroids",
    brand: "Good Smile Company",
    price: 2499,
    currency: "INR",
    stockQuantity: 45,
    availableQuantity: 42,
    mainImage: "https://picsum.photos/seed/rem-ram-nendo/800/800",
    images: ["https://picsum.photos/seed/rem-ram-nendo/1200/800"],
    status: "published",
    ...OS,
    featured: true,
    tags: ["rezero", "rem", "ram", "nendoroid"],
    specifications: [{ name: "Height", value: "10 cm each" }],
    features: ["Interchangeable faces", "Window box packaging"],
    shippingInfo: "Free shipping over ₹999.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(10),
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(175),
    updatedAt: daysAgo(3),
  },
  {
    id: "product-nonstick-cookware-set-home-new-homeessentials-1",
    title: "Attack on Titan 3D Maneuver Gear Wall Replica",
    description:
      "Resin replica of ODM Gear with gas tanks, blade holsters, and wall-mount bracket.",
    category: "category-home-kitchen",
    subcategory: "Cosplay Props & Replicas",
    brand: "OtakuShelf Co",
    price: 3799,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 23,
    mainImage: "https://picsum.photos/seed/odm-gear/800/800",
    images: ["https://picsum.photos/seed/odm-gear/1200/800"],
    status: "published",
    ...OS,
    featured: false,
    tags: ["attack-on-titan", "odm-gear", "replica"],
    specifications: [
      { name: "Material", value: "Resin + Metal" },
      { name: "Size", value: "45 × 30 cm" },
    ],
    features: ["Wall-mount bracket", "Weathered finish"],
    shippingInfo: "Free shipping in 3-4 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(160),
    updatedAt: daysAgo(30),
  },
  {
    id: "product-smart-air-purifier-home-new-homeessentials-1",
    title: "Evangelion Unit-01 Berserker Mode Garage Kit 1/35",
    description:
      "Unpainted resin garage kit of EVA Unit-01 in berserker mode with AT-Field effect base.",
    category: "category-home-kitchen",
    subcategory: "Garage Kits",
    brand: "OtakuShelf Co",
    price: 12999,
    currency: "INR",
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage: "https://picsum.photos/seed/eva-unit01/800/800",
    images: ["https://picsum.photos/seed/eva-unit01/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
      thumbnailUrl: "https://picsum.photos/seed/eva-unit01-vid/800/450",
      duration: 52,
      trimStart: 5,
      trimEnd: 45,
    },
    status: "published",
    ...OS,
    featured: true,
    tags: ["evangelion", "unit-01", "garage-kit"],
    specifications: [
      { name: "Scale", value: "1/35" },
      { name: "Material", value: "Cast Resin" },
    ],
    features: ["AT-Field base", "Requires assembly + painting"],
    shippingInfo: "Free shipping in 2-4 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(8),
  },
  {
    id: "product-solid-wood-coffee-table-home-new-homeessentials-1",
    title: "Studio Ghibli Collector's Display Shelf Set (8 Figures)",
    description:
      "8-figure display set: Totoro, Kiki, Howl, Calcifer, Nausicaä, No-Face, Chihiro, Haku with acrylic case.",
    category: "category-home-kitchen",
    subcategory: "Collector Sets",
    brand: "OtakuShelf Co",
    price: 8499,
    currency: "INR",
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: "https://picsum.photos/seed/ghibli-display/800/800",
    images: ["https://picsum.photos/seed/ghibli-display/1200/800"],
    status: "published",
    ...OS,
    featured: false,
    tags: ["ghibli", "collector-set", "totoro", "spirited-away"],
    specifications: [{ name: "Figures", value: "8 (hand-painted PVC)" }],
    features: ["Dust-proof acrylic case", "Artist signature card"],
    shippingInfo: "Ships in 7-10 days (curated set).",
    returnPolicy: "No returns on opened sets.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(250),
    updatedAt: daysAgo(60),
  },
  {
    id: "product-premium-yoga-mat-sports-new-sportszone-1",
    title: "Naruto Sage Mode Toad Sage 1/7 Scale Figure",
    description:
      "Megahouse Naruto Sage Mode with Fukasaku and Shima frogs, stone gate diorama base.",
    category: "category-sports-outdoors",
    subcategory: "Naruto Figures",
    brand: "Megahouse",
    price: 3999,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 47,
    mainImage: "https://picsum.photos/seed/naruto-sage/800/800",
    images: ["https://picsum.photos/seed/naruto-sage/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
      thumbnailUrl: "https://picsum.photos/seed/naruto-sage-vid/800/450",
      duration: 22,
    },
    status: "published",
    ...OS,
    featured: true,
    tags: ["naruto", "sage-mode", "megahouse"],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "22 cm" },
    ],
    features: ["Frog sages included", "Stone gate base"],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(7),
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(220),
    updatedAt: daysAgo(2),
  },
  {
    id: "product-adjustable-dumbbell-set-sports-new-sportszone-1",
    title: "Gundam Wing Zero Custom 1/100 Master Grade Kit",
    description:
      "Bandai MG 1/100 Wing Zero Custom with DRAGOON wing binders and full inner frame.",
    category: "category-sports-outdoors",
    subcategory: "Master Grade Gunpla",
    brand: "Bandai",
    price: 14999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage: "https://picsum.photos/seed/wing-zero/800/800",
    images: ["https://picsum.photos/seed/wing-zero/1200/800"],
    status: "published",
    ...OS,
    featured: true,
    tags: ["gundam", "wing-zero", "master-grade"],
    specifications: [
      { name: "Scale", value: "1/100" },
      { name: "Parts", value: "200+" },
    ],
    features: ["Full inner frame", "Foil sticker sheet"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(15),
  },
  {
    id: "product-cricket-bat-mrf-sports-new-sportszone-1",
    title: "One Piece Going Merry Ship 1/144 Resin Model",
    description:
      "Hand-cast polystone Going Merry replica, limited artisan run of 200 numbered pieces.",
    category: "category-sports-outdoors",
    subcategory: "Ship Models",
    brand: "OtakuShelf Co",
    price: 6999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage: "https://picsum.photos/seed/going-merry/800/800",
    images: ["https://picsum.photos/seed/going-merry/1200/800"],
    status: "published",
    ...OS,
    featured: false,
    tags: ["one-piece", "going-merry", "ship-model", "artisan"],
    specifications: [
      { name: "Scale", value: "1/144" },
      { name: "Material", value: "Polystone Resin" },
    ],
    features: ["Numbered limited edition", "Straw Hat flag"],
    shippingInfo: "Ships in 2-4 business days.",
    returnPolicy: "7-day returns (unopened).",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(145),
    updatedAt: daysAgo(25),
  },
  {
    id: "product-running-shoes-adidas-sports-new-sportszone-1",
    title: "Jujutsu Kaisen Gojo Satoru Infinity Domain 1/7 Scale",
    description:
      "Union Creative Gojo with Infinity barrier effect, LED-compatible base, two head sculpts.",
    category: "category-sports-outdoors",
    subcategory: "JJK Figures",
    brand: "Union Creative",
    price: 15999,
    currency: "INR",
    stockQuantity: 22,
    availableQuantity: 19,
    mainImage: "https://picsum.photos/seed/gojo-infinity/800/800",
    images: ["https://picsum.photos/seed/gojo-infinity/1200/800"],
    status: "published",
    ...OS,
    featured: true,
    tags: ["jujutsu-kaisen", "gojo", "infinity"],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "28 cm" },
    ],
    features: ["Two head sculpts", "LED-compatible base"],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(130),
    updatedAt: daysAgo(5),
  },
  {
    id: "product-apple-ipad-pro-electronics-new-techhub-1",
    title: "Bleach Ichigo Bankai Tensa Zangetsu 1/6 Scale",
    description:
      "Bandai S.H.Figuarts Ichigo Final Bankai with Zangetsu sword and energy effect parts.",
    category: "category-laptops-computers-electronics",
    subcategory: "Bleach Figures",
    brand: "Bandai S.H.Figuarts",
    price: 8990,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage: "https://picsum.photos/seed/ichigo-bankai/800/800",
    images: ["https://picsum.photos/seed/ichigo-bankai/1200/800"],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
      thumbnailUrl: "https://picsum.photos/seed/ichigo-bankai-vid/800/450",
      duration: 15,
    },
    status: "published",
    ...FV,
    featured: true,
    tags: ["bleach", "ichigo", "bankai", "shfiguarts"],
    specifications: [
      { name: "Scale", value: "1/6" },
      { name: "Articulation", value: "25+ points" },
    ],
    features: ["Zangetsu sword", "Energy effect parts"],
    shippingInfo: "Free delivery in 1-2 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(12),
    avgRating: 5,
    reviewCount: 1,
    createdAt: daysAgo(85),
    updatedAt: daysAgo(2),
  },
  {
    id: "product-samsung-galaxy-watch6-electronics-new-techhub-1",
    title: "Dragon Ball Z Scouter Replica & Capsule Corp Gift Set",
    description:
      "ABS scouter with working green LED. Includes 10 Capsule Corp resin capsules in wooden case.",
    category: "category-mobiles-accessories-electronics",
    subcategory: "Cosplay Props",
    brand: "FigureVault JP",
    price: 4999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage: "https://picsum.photos/seed/dbz-scouter/800/800",
    images: ["https://picsum.photos/seed/dbz-scouter/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["dragon-ball", "scouter", "capsule-corp", "gift-set"],
    specifications: [
      { name: "Material", value: "ABS + PETG lens" },
      { name: "LED", value: "Green working" },
    ],
    features: ["Working LED scouter", "Wooden display case"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 5,
    reviewCount: 1,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: "product-anker-usbc-charger-electronics-new-techhub-1",
    title: "Spirited Away No-Face Resin Miniature Twin Pack",
    description:
      "Hand-painted No-Face mini figurines (9 cm) — standard and gold mask variants.",
    category: "category-mobile-accessories-mobiles-accessories",
    subcategory: "Mini Figurines",
    brand: "FigureVault JP",
    price: 1290,
    currency: "INR",
    stockQuantity: 70,
    availableQuantity: 68,
    mainImage: "https://picsum.photos/seed/no-face-mini/800/800",
    images: ["https://picsum.photos/seed/no-face-mini/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["ghibli", "no-face", "spirited-away", "mini"],
    specifications: [
      { name: "Height", value: "9 cm" },
      { name: "Material", value: "Hand-painted Resin" },
    ],
    features: ["Hand-painted finish", "Twin pack"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    avgRating: 5,
    reviewCount: 1,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(2),
  },
];

// ─── Out-of-stock products (5) ──────────────────────────────────────────────
const outOfStockProducts: Partial<ProductDocument>[] = [
  {
    id: "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
    title: "Tanjiro Hinokami Kagura 1/7 Scale — SOLD OUT",
    description:
      "Alter Co. Dance of the Fire God Tanjiro with translucent flame resin.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Alter Co.",
    price: 29990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/tanjiro-hinokami/800/800",
    images: ["https://picsum.photos/seed/tanjiro-hinokami/1200/800"],
    status: "out_of_stock",
    ...FV,
    featured: false,
    tags: ["demon-slayer", "tanjiro", "limited", "out-of-stock"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(15),
  },
  {
    id: "product-gojo-hollow-purple-oos-1",
    title: "Gojo Satoru Hollow Purple 1/4 Scale — SOLD OUT",
    description:
      "MegaHouse Gojo Hollow Purple technique. 38 cm with gravity-defying purple orb.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "MegaHouse",
    price: 39990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/gojo-hollow/800/800",
    images: ["https://picsum.photos/seed/gojo-hollow/1200/800"],
    status: "out_of_stock",
    ...FV,
    featured: true,
    tags: ["jujutsu-kaisen", "gojo", "out-of-stock"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(10),
  },
  {
    id: "product-aot-colossal-titan-oos-1",
    title: "AoT Colossal Titan 1/6 Scale — SOLD OUT",
    description:
      "Prime 1 Studio Colossal Titan with steam effect and wall breach diorama.",
    category: "category-home-kitchen",
    subcategory: "Premium Statues",
    brand: "Prime 1 Studio",
    price: 54990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/colossal-titan/800/800",
    images: ["https://picsum.photos/seed/colossal-titan/1200/800"],
    status: "out_of_stock",
    ...OS,
    featured: true,
    tags: ["attack-on-titan", "colossal-titan", "out-of-stock"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(250),
    updatedAt: daysAgo(20),
  },
  {
    id: "product-sukuna-finger-set-oos-1",
    title: "Sukuna Finger Box Set (20 pcs) — SOLD OUT",
    description:
      "Complete Ryomen Sukuna finger replica set in cursed wooden box.",
    category: "category-home-kitchen",
    subcategory: "Cosplay Props",
    brand: "OtakuShelf Co",
    price: 11999,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/sukuna-fingers/800/800",
    images: ["https://picsum.photos/seed/sukuna-fingers/1200/800"],
    status: "out_of_stock",
    ...OS,
    featured: false,
    tags: ["jujutsu-kaisen", "sukuna", "out-of-stock"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(30),
  },
  {
    id: "product-bakugo-explosion-oos-1",
    title: "MHA Bakugo Explosion 1/4 Scale — SOLD OUT",
    description:
      "Tsume Art Bakugo full explosion with LED effects. Sold out within hours.",
    category: "category-laptops-computers-electronics",
    subcategory: "Premium Statues",
    brand: "Tsume Art",
    price: 44990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/bakugo-boom/800/800",
    images: ["https://picsum.photos/seed/bakugo-boom/1200/800"],
    status: "out_of_stock",
    ...FV,
    featured: false,
    tags: ["my-hero-academia", "bakugo", "out-of-stock"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(45),
  },
];

// ─── Live auctions (13 — ending in the future) ─────────────────────────────
const liveAuctions: Partial<ProductDocument>[] = [
  {
    id: "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    title: "Evangelion Unit-01 Original Production Cel — AUCTION",
    description:
      "Authenticated 1995 NGE production cel (ep. 19) with certificate of authenticity.",
    category: "category-cameras-photography-electronics",
    subcategory: "Production Art",
    brand: "Gainax (Auth.)",
    price: 15000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/eva-cel/800/800",
    images: ["https://picsum.photos/seed/eva-cel/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["evangelion", "production-art", "auction"],
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(3),
    startingBid: 15000,
    currentBid: 22000,
    bidCount: 8,
    reservePrice: 25000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: daysAhead(3),
    avgRating: 4,
    reviewCount: 1,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(1),
  },
  {
    id: "product-macbook-pro-m3-auction-electronics-techhub-1",
    title: "Dragon Ball Z Complete Son Family 7-Piece Set — AUCTION",
    description:
      "Ultra-rare first-run Son family set: Goku, Gohan ×2, Goten, Bardock, Raditz, Broly.",
    category: "category-laptops-computers-electronics",
    subcategory: "Collector Sets",
    brand: "Bandai / MegaHouse",
    price: 169900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/son-family/800/800",
    images: ["https://picsum.photos/seed/son-family/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["dragon-ball", "son-family", "rare", "auction"],
    condition: "new",
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(5),
    startingBid: 100000,
    currentBid: 115000,
    bidCount: 7,
    buyNowPrice: 180000,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: daysAhead(5),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: "product-vintage-leica-camera-auction-artisan-1",
    title: "Neon Genesis Evangelion 1995 Signed Poster — AUCTION",
    description:
      "Original Japanese limited-run theatrical poster signed by Hideaki Anno.",
    category: "category-cameras-photography-electronics",
    subcategory: "Production Art",
    brand: "Gainax (Verified)",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/eva-poster/800/800",
    images: ["https://picsum.photos/seed/eva-poster/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["evangelion", "hideaki-anno", "signed", "auction"],
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(28),
    startingBid: 75000,
    currentBid: 97500,
    bidCount: 5,
    reservePrice: 120000,
    minBidIncrement: 2500,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: daysAhead(28),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-chainsaw-man-makima-figure-fashion-1",
    title: "Chainsaw Man Makima 1/7 Kotobukiya ARTFX J — AUCTION",
    description:
      "Kotobukiya ARTFX J Makima with chain and bloodmoon backdrop. Limited run.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Kotobukiya",
    price: 12000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/makima-auction/800/800",
    images: ["https://picsum.photos/seed/makima-auction/1200/800"],
    status: "published",
    ...AC,
    featured: true,
    tags: ["chainsaw-man", "makima", "auction"],
    condition: "new",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(9),
    startingBid: 12000,
    currentBid: 18500,
    bidCount: 6,
    buyNowPrice: 28000,
    reservePrice: 15000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: daysAhead(9),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-jjk-sukuna-figure-homeessentials-1",
    title: "JJK Ryomen Sukuna King of Curses 1/6 Scale — AUCTION",
    description:
      "Megahouse Sukuna 1/6 with cursed energy aura, tattooed skin, multiple arms.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "MegaHouse",
    price: 15000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/sukuna-auction/800/800",
    images: ["https://picsum.photos/seed/sukuna-auction/1200/800"],
    status: "published",
    ...OS,
    featured: true,
    tags: ["jujutsu-kaisen", "sukuna", "auction"],
    condition: "new",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(11),
    startingBid: 15000,
    currentBid: 22000,
    bidCount: 5,
    buyNowPrice: 35000,
    reservePrice: 18000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-fate-saber-alter-figure-techhub-1",
    title: "Fate/Stay Night Saber Alter Wedding 1/7 — AUCTION",
    description:
      "Alter Co. exclusive Saber Alter in white wedding dress. 2019 limited production, sealed.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Alter Co.",
    price: 18000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/saber-alter/800/800",
    images: ["https://picsum.photos/seed/saber-alter/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["fate", "saber-alter", "wedding", "auction"],
    condition: "new",
    insurance: true,
    insuranceCost: 800,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(7),
    startingBid: 18000,
    currentBid: 28000,
    bidCount: 7,
    buyNowPrice: 45000,
    reservePrice: 22000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: daysAhead(7),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-pokemon-charizard-1st-ed-fashion-1",
    title: "Pokémon 1st Edition Charizard Holo PSA 9 — AUCTION",
    description:
      "1999 Wizards of the Coast 1st Edition Base Set Charizard, PSA 9 NM-Mint slab.",
    category: "category-cameras-photography-electronics",
    subcategory: "Trading Cards",
    brand: "Wizards of the Coast",
    price: 25000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/charizard-psa9/800/800",
    images: ["https://picsum.photos/seed/charizard-psa9/1200/800"],
    status: "published",
    ...AC,
    featured: true,
    tags: ["pokemon", "charizard", "psa-9", "auction"],
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(14),
    startingBid: 25000,
    currentBid: 52000,
    bidCount: 9,
    reservePrice: 30000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-spirited-away-cel-homeessentials-1",
    title: "Spirited Away 2001 Production Cel — Studio Ghibli",
    description:
      "Hand-painted original production cel of Chihiro & Haku river scene. Ghibli Museum cert.",
    category: "category-cameras-photography-electronics",
    subcategory: "Production Art",
    brand: "Studio Ghibli",
    price: 30000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/spirited-cel/800/800",
    images: ["https://picsum.photos/seed/spirited-cel/1200/800"],
    status: "published",
    ...OS,
    featured: true,
    tags: ["spirited-away", "ghibli", "production-cel", "auction"],
    condition: "used",
    insurance: true,
    insuranceCost: 1000,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(17),
    startingBid: 30000,
    currentBid: 45000,
    bidCount: 7,
    reservePrice: 35000,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-gunpla-pg-wing-zero-techhub-1",
    title: "PG Wing Zero Custom Full Build with LED — AUCTION",
    description:
      "Hand-built, panel-lined and painted 1/60 PG Wing Zero with Wing of Light LED unit.",
    category: "category-mobiles-accessories-electronics",
    subcategory: "Built Models",
    brand: "Bandai",
    price: 8000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/pg-wing-built/800/800",
    images: ["https://picsum.photos/seed/pg-wing-built/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["gunpla", "wing-zero", "hand-built", "auction"],
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(4),
    startingBid: 8000,
    currentBid: 14500,
    bidCount: 8,
    reservePrice: 10000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-rezero-rem-wedding-figure-techhub-1",
    title: "Re:Zero Rem Wedding Dress 1/7 GSC — AUCTION",
    description:
      "Good Smile Rem Wedding 1/7 with lace veil and flower bouquet. 2021 JP release.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Good Smile Company",
    price: 20000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/rem-wedding/800/800",
    images: ["https://picsum.photos/seed/rem-wedding/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["rezero", "rem", "wedding", "auction"],
    condition: "new",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(19),
    startingBid: 20000,
    currentBid: 32000,
    bidCount: 6,
    buyNowPrice: 55000,
    reservePrice: 25000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: daysAhead(19),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-ps5-slim-gaming-console-techhub-1",
    title: "Dragon Ball Z Battle of Gods Blu-ray Signed Box — AUCTION",
    description:
      "Sealed Blu-ray box signed by Masako Nozawa (Goku VA). Includes acrylic display stand.",
    category: "category-cameras-photography-electronics",
    subcategory: "Signed Merch",
    brand: "Toei Animation",
    price: 8000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/dbz-bluray/800/800",
    images: ["https://picsum.photos/seed/dbz-bluray/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["dragon-ball", "signed", "blu-ray", "auction"],
    condition: "new",
    insurance: true,
    insuranceCost: 300,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(6),
    startingBid: 8000,
    currentBid: 12500,
    bidCount: 5,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-airpods-pro2-audio-techhub-1",
    title: "Demon Slayer Rengoku Flame Art Print (Signed by VA) — AUCTION",
    description:
      "Limited art print of Rengoku signed by voice actor Satoshi Hino.",
    category: "category-audio-electronics",
    subcategory: "Signed Art",
    brand: "Aniplex",
    price: 5000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/rengoku-art/800/800",
    images: ["https://picsum.photos/seed/rengoku-art/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["demon-slayer", "rengoku", "signed", "auction"],
    condition: "new",
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(10),
    startingBid: 5000,
    currentBid: 8500,
    bidCount: 4,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  {
    id: "auction-swiss-titanium-watch-fashion-1",
    title: "One Piece 25th Anniversary Premium Card Collection — AUCTION",
    description:
      "Complete premium promo card set from OP 25th anniversary, holographic box.",
    category: "category-cameras-photography-electronics",
    subcategory: "Trading Cards",
    brand: "Bandai TCG",
    price: 10000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/op-cards/800/800",
    images: ["https://picsum.photos/seed/op-cards/1200/800"],
    status: "published",
    ...AC,
    featured: false,
    tags: ["one-piece", "cards", "25th-anniversary", "auction"],
    condition: "new",
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: daysAhead(8),
    startingBid: 10000,
    currentBid: 16000,
    bidCount: 6,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
];

// ─── Ended auctions (6 — ended in the past, status: "sold") ────────────────
const endedAuctions: Partial<ProductDocument>[] = [
  {
    id: "auction-one-piece-signed-artbook-techhub-1",
    title: "One Piece 25th Anniversary Artbook Signed by Oda — ENDED",
    description:
      "Color Walk collection signed by Eiichiro Oda with Den Den Mushi ink sketch.",
    category: "category-cameras-photography-electronics",
    subcategory: "Signed Art",
    brand: "Shueisha",
    price: 10000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/oda-artbook/800/800",
    images: ["https://picsum.photos/seed/oda-artbook/1200/800"],
    status: "sold",
    ...FV,
    featured: false,
    tags: ["one-piece", "oda", "signed", "auction", "ended"],
    condition: "used",
    isAuction: true,
    auctionEndDate: daysAgo(3),
    startingBid: 10000,
    currentBid: 24000,
    bidCount: 12,
    reservePrice: 12000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(3),
  },
  {
    id: "product-limited-air-jordan-sneakers-auction-artisan-1",
    title: "Naruto Complete Bijuu (9 Tailed Beasts) Set — ENDED",
    description:
      "Full set of all 9 Tailed Beasts by MegaHouse. Factory sealed, gold serial numbers.",
    category: "category-laptops-computers-electronics",
    subcategory: "Collector Sets",
    brand: "MegaHouse",
    price: 89990,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/bijuu-set/800/800",
    images: ["https://picsum.photos/seed/bijuu-set/1200/800"],
    status: "sold",
    ...FV,
    featured: false,
    tags: ["naruto", "bijuu", "rare", "auction", "ended"],
    condition: "new",
    isAuction: true,
    auctionEndDate: daysAgo(7),
    startingBid: 50000,
    currentBid: 78000,
    bidCount: 15,
    reservePrice: 60000,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(7),
  },
  {
    id: "auction-supreme-box-logo-tee-fashion-1",
    title: "Dragon Ball Z Shenron LED Lamp Sculpture — ENDED",
    description:
      "Custom Shenron LED lamp with 7 dragon ball base, 90 cm wingspan.",
    category: "category-home-kitchen",
    subcategory: "Anime Decor",
    brand: "OtakuShelf Co",
    price: 15000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/shenron-lamp/800/800",
    images: ["https://picsum.photos/seed/shenron-lamp/1200/800"],
    status: "sold",
    ...OS,
    featured: false,
    tags: ["dragon-ball", "shenron", "led-lamp", "auction", "ended"],
    condition: "new",
    isAuction: true,
    auctionEndDate: daysAgo(14),
    startingBid: 15000,
    currentBid: 28500,
    bidCount: 10,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(14),
  },
  {
    id: "auction-pioneer-hifi-system-homeessentials-1",
    title: "Studio Ghibli Limited Cel — Princess Mononoke — ENDED",
    description:
      "Production cel from Princess Mononoke featuring San & Moro. Auction ended.",
    category: "category-cameras-photography-electronics",
    subcategory: "Production Art",
    brand: "Studio Ghibli",
    price: 20000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/mononoke-cel/800/800",
    images: ["https://picsum.photos/seed/mononoke-cel/1200/800"],
    status: "sold",
    ...OS,
    featured: false,
    tags: ["ghibli", "mononoke", "cel", "auction", "ended"],
    condition: "used",
    isAuction: true,
    auctionEndDate: daysAgo(10),
    startingBid: 20000,
    currentBid: 35000,
    bidCount: 8,
    minBidIncrement: 1500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(10),
  },
  {
    id: "auction-vintage-denim-jacket-fashion-1",
    title: "My Hero Academia Original Signed Manuscript Page — ENDED",
    description:
      "Original manuscript page from MHA ch. 1 with Horikoshi autograph.",
    category: "category-cameras-photography-electronics",
    subcategory: "Signed Art",
    brand: "Shueisha",
    price: 30000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/mha-manuscript/800/800",
    images: ["https://picsum.photos/seed/mha-manuscript/1200/800"],
    status: "sold",
    ...AC,
    featured: false,
    tags: ["my-hero-academia", "horikoshi", "manuscript", "auction", "ended"],
    condition: "used",
    isAuction: true,
    auctionEndDate: daysAgo(5),
    startingBid: 30000,
    currentBid: 48000,
    bidCount: 11,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(5),
  },
  {
    id: "auction-bose700-headphones-homeessentials-1",
    title: "Jujutsu Kaisen Gojo Unsigned Limited Print #50/100 — ENDED",
    description: "Limited print run (50 of 100) JJK Gojo art. Sold at auction.",
    category: "category-audio-electronics",
    subcategory: "Art Prints",
    brand: "MAPPA",
    price: 6000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/gojo-print/800/800",
    images: ["https://picsum.photos/seed/gojo-print/1200/800"],
    status: "sold",
    ...OS,
    featured: false,
    tags: ["jujutsu-kaisen", "gojo", "art-print", "auction", "ended"],
    condition: "new",
    isAuction: true,
    auctionEndDate: daysAgo(2),
    startingBid: 6000,
    currentBid: 11000,
    bidCount: 6,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
];

// ─── Pre-orders: 5 open (delivery future) + 2 closed (delivery past) ────────
const preOrders: Partial<ProductDocument>[] = [
  {
    id: "preorder-chainsaw-man-makima-gsc-1",
    title: "Chainsaw Man Makima 1/7 GSC (Pre-Order)",
    description:
      "Good Smile Makima 1/7 with acrylic stand base. Pay deposit now, balance on release.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Good Smile Company",
    price: 14900,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: "https://picsum.photos/seed/makima-po/800/800",
    images: ["https://picsum.photos/seed/makima-po/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["chainsaw-man", "makima", "pre-order"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(90),
    preOrderDepositPercent: 20,
    preOrderDepositAmount: 2980,
    preOrderMaxQuantity: 50,
    preOrderCurrentCount: 23,
    preOrderProductionStatus: "in_production",
    preOrderCancellable: true,
    isPromoted: true,
    promotionEndDate: daysAhead(45),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  {
    id: "preorder-frieren-alter-1",
    title: "Frieren: Beyond Journey's End 1/7 Alter Co. (Pre-Order)",
    description:
      "Alter Frieren with 3 face plates and floating spell effect parts.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Alter Co.",
    price: 17200,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage: "https://picsum.photos/seed/frieren-po/800/800",
    images: ["https://picsum.photos/seed/frieren-po/1200/800"],
    status: "published",
    ...FV,
    featured: true,
    tags: ["frieren", "alter", "pre-order"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(120),
    preOrderDepositPercent: 25,
    preOrderDepositAmount: 4300,
    preOrderMaxQuantity: 30,
    preOrderCurrentCount: 12,
    preOrderProductionStatus: "upcoming",
    preOrderCancellable: true,
    isPromoted: true,
    promotionEndDate: daysAhead(60),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    id: "preorder-solo-leveling-jinwoo-1",
    title: "Solo Leveling Sung Jinwoo Shadow Monarch 1/7 (Pre-Order)",
    description:
      "GSC Sung Jinwoo in Shadow Monarch form with shadow soldier army base.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "Good Smile Company",
    price: 18500,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 40,
    mainImage: "https://picsum.photos/seed/jinwoo-po/800/800",
    images: ["https://picsum.photos/seed/jinwoo-po/1200/800"],
    status: "published",
    ...OS,
    featured: false,
    tags: ["solo-leveling", "sung-jinwoo", "pre-order"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(150),
    preOrderDepositPercent: 20,
    preOrderDepositAmount: 3700,
    preOrderMaxQuantity: 40,
    preOrderCurrentCount: 8,
    preOrderProductionStatus: "upcoming",
    preOrderCancellable: true,
    isPromoted: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: "preorder-gear5-nika-mega-1",
    title: "One Piece Gear 5 Nika MEGA 1/4 Scale (Pre-Order)",
    description:
      "MegaHouse MEGA-size Luffy Gear 5 at 50 cm with flame-cloud base.",
    category: "category-laptops-computers-electronics",
    subcategory: "One Piece Figures",
    brand: "MegaHouse",
    price: 34990,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 20,
    mainImage: "https://picsum.photos/seed/gear5-mega/800/800",
    images: ["https://picsum.photos/seed/gear5-mega/1200/800"],
    status: "published",
    ...OS,
    featured: true,
    tags: ["one-piece", "gear-5", "mega-size", "pre-order"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(180),
    preOrderDepositPercent: 25,
    preOrderDepositAmount: 8748,
    preOrderMaxQuantity: 20,
    preOrderCurrentCount: 5,
    preOrderProductionStatus: "upcoming",
    preOrderCancellable: true,
    isPromoted: true,
    promotionEndDate: daysAhead(90),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "preorder-daima-mini-goku-1",
    title: "Dragon Ball Daima Mini Goku 1/6 (Pre-Order)",
    description:
      "Bandai Spirits Daima chibi Goku with Nimbus cloud base and power pole.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "Bandai Spirits",
    price: 8490,
    currency: "INR",
    stockQuantity: 60,
    availableQuantity: 60,
    mainImage: "https://picsum.photos/seed/daima-goku/800/800",
    images: ["https://picsum.photos/seed/daima-goku/1200/800"],
    status: "published",
    ...FV,
    featured: false,
    tags: ["dragon-ball", "daima", "chibi", "pre-order"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(60),
    preOrderDepositPercent: 20,
    preOrderDepositAmount: 1698,
    preOrderMaxQuantity: 60,
    preOrderCurrentCount: 31,
    preOrderProductionStatus: "in_production",
    preOrderCancellable: true,
    isPromoted: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  // Closed pre-orders (delivery date passed)
  {
    id: "preorder-closed-gojo-domain-1",
    title: "JJK Gojo Domain Expansion 1/6 — CLOSED (Shipped)",
    description:
      "MegaHouse Gojo Infinite Void domain figure. All pre-orders fulfilled.",
    category: "category-audio-electronics",
    subcategory: "Limited Figures",
    brand: "MegaHouse",
    price: 22990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/gojo-domain/800/800",
    images: ["https://picsum.photos/seed/gojo-domain/1200/800"],
    status: "out_of_stock",
    ...FV,
    featured: false,
    tags: ["jujutsu-kaisen", "gojo", "pre-order", "closed"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAgo(15),
    preOrderDepositPercent: 25,
    preOrderDepositAmount: 5748,
    preOrderMaxQuantity: 25,
    preOrderCurrentCount: 25,
    preOrderProductionStatus: "ready_to_ship",
    preOrderCancellable: false,
    isPromoted: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(15),
  },
  {
    id: "preorder-closed-infinity-castle-1",
    title: "Demon Slayer Infinity Castle Diorama — CLOSED (Shipped)",
    description:
      "OtakuShelf modular Infinity Castle diorama with Muzan and Upper Moons. Fulfilled.",
    category: "category-home-kitchen",
    subcategory: "Dioramas",
    brand: "OtakuShelf Co",
    price: 29990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/infinity-castle/800/800",
    images: ["https://picsum.photos/seed/infinity-castle/1200/800"],
    status: "out_of_stock",
    ...OS,
    featured: false,
    tags: ["demon-slayer", "infinity-castle", "pre-order", "closed"],
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAgo(30),
    preOrderDepositPercent: 30,
    preOrderDepositAmount: 8997,
    preOrderMaxQuantity: 15,
    preOrderCurrentCount: 15,
    preOrderProductionStatus: "ready_to_ship",
    preOrderCancellable: false,
    isPromoted: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(30),
  },
];

// ─── Draft products (3) ─────────────────────────────────────────────────────
const draftProducts: Partial<ProductDocument>[] = [
  {
    id: "product-draft-bleach-toshiro-1",
    title: "Bleach Toshiro Hitsugaya Bankai 1/7 [DRAFT]",
    description:
      "Kotobukiya Toshiro Daiguren Hyorinmaru. Awaiting final photos.",
    category: "category-laptops-computers-electronics",
    subcategory: "Bleach Figures",
    brand: "Kotobukiya",
    price: 9490,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 20,
    mainImage: "https://picsum.photos/seed/toshiro-draft/800/800",
    images: [],
    status: "draft",
    ...FV,
    featured: false,
    tags: ["bleach", "toshiro", "draft"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "product-draft-fire-force-shinra-1",
    title: "Fire Force Shinra Devil's Footprints 1/8 [DRAFT]",
    description:
      "AnimeCraft exclusive Shinra with flaming footprints base. Pending approval.",
    category: "category-mens-fashion-fashion",
    subcategory: "Action Figures",
    brand: "AnimeCraft Apparel",
    price: 4990,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage: "https://picsum.photos/seed/shinra-draft/800/800",
    images: [],
    status: "draft",
    ...AC,
    featured: false,
    tags: ["fire-force", "shinra", "draft"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "product-draft-spy-family-bond-plush-1",
    title: "Spy × Family Bond Forger Plush (35 cm) [DRAFT]",
    description: "Bond plush in prophetic vision pose. Pending pricing review.",
    category: "category-home-kitchen",
    subcategory: "Anime Plush",
    brand: "OtakuShelf Co",
    price: 0,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 100,
    mainImage: "https://picsum.photos/seed/bond-draft/800/800",
    images: [],
    status: "draft",
    ...OS,
    featured: false,
    tags: ["spy-family", "bond", "plush", "draft"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
];

// ─── Discontinued (2) + Sold regular (2) ────────────────────────────────────
const discontinuedAndSold: Partial<ProductDocument>[] = [
  {
    id: "product-disc-naruto-original-sage-1",
    title: "Naruto Original Run Sage 1/8 — DISCONTINUED",
    description:
      "Banpresto first-generation Sage figure (2020). Production line discontinued.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Naruto Figures",
    brand: "Banpresto",
    price: 3490,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/naruto-disc/800/800",
    images: ["https://picsum.photos/seed/naruto-disc/1200/800"],
    status: "discontinued",
    ...FV,
    featured: false,
    tags: ["naruto", "discontinued"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(60),
  },
  {
    id: "product-disc-eren-founding-titan-1",
    title: "AoT Eren Founding Titan Statue — DISCONTINUED",
    description: "Prime 1 Studio Eren Founding Titan. Production discontinued.",
    category: "category-home-kitchen",
    subcategory: "Premium Statues",
    brand: "Prime 1 Studio",
    price: 79990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/eren-founding/800/800",
    images: ["https://picsum.photos/seed/eren-founding/1200/800"],
    status: "discontinued",
    ...OS,
    featured: false,
    tags: ["attack-on-titan", "eren", "discontinued"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(90),
  },
  {
    id: "product-sold-cell-perfect-form-1",
    title: "DBZ Cell Perfect Form 1/4 — SOLD",
    description:
      "One-of-one custom Cell Perfect Form statue. Sold to private collector.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "FigureVault JP",
    price: 49990,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/cell-perfect/800/800",
    images: ["https://picsum.photos/seed/cell-perfect/1200/800"],
    status: "sold",
    ...FV,
    featured: false,
    tags: ["dragon-ball", "cell", "sold"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(45),
  },
  {
    id: "product-sold-ace-memorial-1",
    title: "One Piece Ace Memorial Statue — SOLD",
    description:
      "OtakuShelf Ace memorial with flame fist. Limited 50 pieces — all sold.",
    category: "category-sports-outdoors",
    subcategory: "One Piece Figures",
    brand: "OtakuShelf Co",
    price: 24990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/ace-memorial/800/800",
    images: ["https://picsum.photos/seed/ace-memorial/1200/800"],
    status: "sold",
    ...OS,
    featured: false,
    tags: ["one-piece", "ace", "sold"],
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(60),
  },
];

// ─── Generated extra products (30) to hit 102 total ────────────────────────
interface QuickItem {
  id: string;
  title: string;
  cat: string;
  sub: string;
  brand: string;
  price: number;
  stock: number;
  seller: typeof FV | typeof AC | typeof OS;
  tags: string[];
  feat: boolean;
  days: number;
}
const quickItems: QuickItem[] = [
  {
    id: "product-gen-76-frieza-figure",
    title: "Dragon Ball Z Frieza Final Form 1/8 Scale",
    cat: "category-smartphones-mobiles-accessories",
    sub: "DBZ Figures",
    brand: "Bandai Spirits",
    price: 5490,
    stock: 25,
    seller: FV,
    tags: ["dragon-ball", "frieza"],
    feat: false,
    days: 22,
  },
  {
    id: "product-gen-77-nami-figure",
    title: "One Piece Nami Cat Burglar 1/7 Scale",
    cat: "category-laptops-computers-electronics",
    sub: "OP Figures",
    brand: "MegaHouse",
    price: 6990,
    stock: 20,
    seller: FV,
    tags: ["one-piece", "nami"],
    feat: false,
    days: 21,
  },
  {
    id: "product-gen-78-kakashi-nendo",
    title: "Naruto Kakashi Hatake Nendoroid #724",
    cat: "category-mobiles-accessories-electronics",
    sub: "Nendoroids",
    brand: "Good Smile Company",
    price: 1799,
    stock: 50,
    seller: OS,
    tags: ["naruto", "kakashi"],
    feat: false,
    days: 19,
  },
  {
    id: "product-gen-79-nobara-figure",
    title: "JJK Nobara Kugisaki Straw Doll 1/7",
    cat: "category-home-kitchen",
    sub: "JJK Figures",
    brand: "Kotobukiya",
    price: 7790,
    stock: 16,
    seller: OS,
    tags: ["jujutsu-kaisen", "nobara"],
    feat: false,
    days: 18,
  },
  {
    id: "product-gen-80-inosuke-figure",
    title: "Demon Slayer Inosuke Beast Breathing 1/8",
    cat: "category-audio-electronics",
    sub: "DS Figures",
    brand: "Bandai Spirits",
    price: 5990,
    stock: 22,
    seller: FV,
    tags: ["demon-slayer", "inosuke"],
    feat: false,
    days: 17,
  },
  {
    id: "product-gen-81-mikasa-figure",
    title: "AoT Mikasa Ackerman 1/7 Scale",
    cat: "category-womens-fashion-fashion",
    sub: "AoT Figures",
    brand: "Good Smile Company",
    price: 8490,
    stock: 14,
    seller: FV,
    tags: ["attack-on-titan", "mikasa"],
    feat: false,
    days: 16,
  },
  {
    id: "product-gen-82-todoroki-figure",
    title: "MHA Todoroki Half-Cold Half-Hot 1/8",
    cat: "category-laptops-computers-electronics",
    sub: "MHA Figures",
    brand: "Kotobukiya",
    price: 6990,
    stock: 18,
    seller: FV,
    tags: ["my-hero-academia", "todoroki"],
    feat: false,
    days: 15,
  },
  {
    id: "product-gen-83-yor-figure",
    title: "Spy × Family Yor Thorn Princess 1/7",
    cat: "category-audio-electronics",
    sub: "SPY Figures",
    brand: "Alter Co.",
    price: 11990,
    stock: 12,
    seller: FV,
    tags: ["spy-family", "yor"],
    feat: false,
    days: 14,
  },
  {
    id: "product-gen-84-kiki-figurine",
    title: "Kiki's Delivery Service Kiki & Jiji Wind-up",
    cat: "category-home-kitchen",
    sub: "Ghibli Minis",
    brand: "OtakuShelf Co",
    price: 1490,
    stock: 45,
    seller: OS,
    tags: ["ghibli", "kiki"],
    feat: false,
    days: 13,
  },
  {
    id: "product-gen-85-barbatos-kit",
    title: "Gundam Barbatos Lupus Rex 1/100 Kit",
    cat: "category-sports-outdoors",
    sub: "MG Gunpla",
    brand: "Bandai",
    price: 3499,
    stock: 30,
    seller: OS,
    tags: ["gundam", "barbatos"],
    feat: false,
    days: 12,
  },
  {
    id: "product-gen-86-byakuya-figure",
    title: "Bleach Byakuya Senbonzakura 1/7",
    cat: "category-laptops-computers-electronics",
    sub: "Bleach Figures",
    brand: "Bandai S.H.Figuarts",
    price: 7990,
    stock: 16,
    seller: FV,
    tags: ["bleach", "byakuya"],
    feat: false,
    days: 11,
  },
  {
    id: "product-gen-87-power-figure",
    title: "Chainsaw Man Power Blood Fiend 1/7",
    cat: "category-audio-electronics",
    sub: "CSM Figures",
    brand: "Good Smile Company",
    price: 10490,
    stock: 10,
    seller: FV,
    tags: ["chainsaw-man", "power"],
    feat: false,
    days: 10,
  },
  {
    id: "product-gen-88-sanji-figure",
    title: "One Piece Sanji Diable Jambe 1/8",
    cat: "category-sports-outdoors",
    sub: "OP Figures",
    brand: "Banpresto",
    price: 4990,
    stock: 20,
    seller: OS,
    tags: ["one-piece", "sanji"],
    feat: false,
    days: 9,
  },
  {
    id: "product-gen-89-levi-figure",
    title: "AoT Levi Ackerman Captain 1/7",
    cat: "category-home-kitchen",
    sub: "AoT Figures",
    brand: "Kotobukiya",
    price: 9990,
    stock: 15,
    seller: OS,
    tags: ["attack-on-titan", "levi"],
    feat: false,
    days: 8,
  },
  {
    id: "product-gen-90-yuji-figure",
    title: "JJK Yuji Itadori Black Flash 1/7",
    cat: "category-audio-electronics",
    sub: "JJK Figures",
    brand: "MegaHouse",
    price: 8490,
    stock: 18,
    seller: OS,
    tags: ["jujutsu-kaisen", "yuji"],
    feat: false,
    days: 7,
  },
  {
    id: "product-gen-91-rengoku-figure",
    title: "Demon Slayer Rengoku Flame Hashira 1/7",
    cat: "category-audio-electronics",
    sub: "DS Figures",
    brand: "Kotobukiya",
    price: 9490,
    stock: 12,
    seller: FV,
    tags: ["demon-slayer", "rengoku"],
    feat: true,
    days: 6,
  },
  {
    id: "product-gen-92-minato-figure",
    title: "Naruto Minato Yellow Flash 1/8",
    cat: "category-smartphones-mobiles-accessories",
    sub: "Naruto Figures",
    brand: "Banpresto",
    price: 4490,
    stock: 28,
    seller: FV,
    tags: ["naruto", "minato"],
    feat: false,
    days: 5,
  },
  {
    id: "product-gen-93-emilia-figure",
    title: "Re:Zero Emilia Crystal Dress 1/7",
    cat: "category-audio-electronics",
    sub: "Limited Figures",
    brand: "Good Smile Company",
    price: 12990,
    stock: 10,
    seller: OS,
    tags: ["rezero", "emilia"],
    feat: false,
    days: 4,
  },
  {
    id: "product-gen-94-gohan-beast-figure",
    title: "Dragon Ball Super Gohan Beast 1/6",
    cat: "category-smartphones-mobiles-accessories",
    sub: "DBZ Figures",
    brand: "Bandai Spirits",
    price: 13990,
    stock: 15,
    seller: FV,
    tags: ["dragon-ball", "gohan"],
    feat: false,
    days: 3,
  },
  {
    id: "product-gen-95-muichiro-figure",
    title: "Demon Slayer Muichiro Mist Hashira 1/8",
    cat: "category-audio-electronics",
    sub: "DS Figures",
    brand: "Kotobukiya",
    price: 6490,
    stock: 20,
    seller: FV,
    tags: ["demon-slayer", "muichiro"],
    feat: false,
    days: 2,
  },
  {
    id: "product-gen-96-robin-figure",
    title: "One Piece Nico Robin Demon Child 1/7",
    cat: "category-laptops-computers-electronics",
    sub: "OP Figures",
    brand: "MegaHouse",
    price: 7490,
    stock: 14,
    seller: FV,
    tags: ["one-piece", "robin"],
    feat: false,
    days: 18,
  },
  {
    id: "product-gen-97-asta-figure",
    title: "Black Clover Asta Devil Union 1/7",
    cat: "category-audio-electronics",
    sub: "Action Figures",
    brand: "MegaHouse",
    price: 8990,
    stock: 12,
    seller: OS,
    tags: ["black-clover", "asta"],
    feat: false,
    days: 16,
  },
  {
    id: "product-gen-98-shigaraki-figure",
    title: "MHA Shigaraki Tomura Decay 1/8",
    cat: "category-laptops-computers-electronics",
    sub: "MHA Figures",
    brand: "Kotobukiya",
    price: 7990,
    stock: 10,
    seller: FV,
    tags: ["my-hero-academia", "shigaraki"],
    feat: false,
    days: 14,
  },
  {
    id: "product-gen-99-tamayo-nendo",
    title: "Demon Slayer Tamayo & Yushiro Nendoroid Pair",
    cat: "category-mobiles-accessories-electronics",
    sub: "Nendoroids",
    brand: "Good Smile Company",
    price: 3490,
    stock: 25,
    seller: OS,
    tags: ["demon-slayer", "tamayo"],
    feat: false,
    days: 12,
  },
  {
    id: "product-gen-100-loid-figure",
    title: "Spy × Family Loid Forger Twilight 1/7",
    cat: "category-audio-electronics",
    sub: "SPY Figures",
    brand: "Alter Co.",
    price: 10990,
    stock: 14,
    seller: FV,
    tags: ["spy-family", "loid"],
    feat: false,
    days: 10,
  },
  {
    id: "product-gen-101-vegito-figure",
    title: "Dragon Ball Super Vegito Blue Kamehameha 1/6",
    cat: "category-smartphones-mobiles-accessories",
    sub: "DBZ Figures",
    brand: "Bandai Spirits",
    price: 14990,
    stock: 10,
    seller: FV,
    tags: ["dragon-ball", "vegito"],
    feat: false,
    days: 8,
  },
  {
    id: "product-gen-102-fern-figure",
    title: "Frieren: Beyond Journey's End Fern 1/7",
    cat: "category-audio-electronics",
    sub: "Isekai Figures",
    brand: "Alter Co.",
    price: 11490,
    stock: 16,
    seller: OS,
    tags: ["frieren", "fern"],
    feat: false,
    days: 6,
  },
  {
    id: "product-gen-103-mob-figure",
    title: "Mob Psycho 100 Shigeo ???% Form 1/7",
    cat: "category-audio-electronics",
    sub: "Action Figures",
    brand: "Good Smile Company",
    price: 8990,
    stock: 15,
    seller: FV,
    tags: ["mob-psycho-100", "mob"],
    feat: false,
    days: 33,
  },
  {
    id: "product-gen-104-pochita-plush",
    title: "Chainsaw Man Pochita Premium Plush (40 cm)",
    cat: "category-home-kitchen",
    sub: "Anime Plush",
    brand: "Good Smile Company",
    price: 2299,
    stock: 90,
    seller: OS,
    tags: ["chainsaw-man", "pochita"],
    feat: false,
    days: 30,
  },
  {
    id: "product-gen-105-anya-nendo",
    title: "Spy × Family Anya Forger Nendoroid #1902",
    cat: "category-mobiles-accessories-electronics",
    sub: "Nendoroids",
    brand: "Good Smile Company",
    price: 1899,
    stock: 200,
    seller: OS,
    tags: ["spy-family", "anya"],
    feat: true,
    days: 45,
  },
  {
    id: "product-mens-slim-chinos-fashion-new-fashionboutique-1",
    title: "Naruto Shippuden Jogger Pants (Akatsuki Red Cloud)",
    cat: "category-mens-fashion-fashion",
    sub: "Anime Pants",
    brand: "AnimeCraft Apparel",
    price: 1799,
    stock: 60,
    seller: AC,
    tags: ["naruto", "akatsuki", "joggers"],
    feat: false,
    days: 40,
  },
  {
    id: "product-mens-leather-derby-shoes-fashion-new-fashionboutique-1",
    title: "Dragon Ball Z Capsule Corp Sneakers",
    cat: "category-mens-fashion-fashion",
    sub: "Anime Shoes",
    brand: "AnimeCraft Apparel",
    price: 2499,
    stock: 35,
    seller: AC,
    tags: ["dragon-ball", "capsule-corp", "sneakers"],
    feat: false,
    days: 38,
  },
  {
    id: "product-gen-106-zenitsu-figure",
    title: "Demon Slayer Zenitsu Thunderclap Flash 1/7",
    cat: "category-audio-electronics",
    sub: "DS Figures",
    brand: "Kotobukiya",
    price: 7990,
    stock: 18,
    seller: FV,
    tags: ["demon-slayer", "zenitsu"],
    feat: false,
    days: 35,
  },
  {
    id: "product-gen-107-deku-figure",
    title: "MHA Deku Full Cowling 100% 1/7",
    cat: "category-laptops-computers-electronics",
    sub: "MHA Figures",
    brand: "Kotobukiya",
    price: 8990,
    stock: 12,
    seller: FV,
    tags: ["my-hero-academia", "deku"],
    feat: false,
    days: 32,
  },
  {
    id: "product-gen-108-law-figure",
    title: "One Piece Trafalgar Law Room 1/7",
    cat: "category-sports-outdoors",
    sub: "OP Figures",
    brand: "MegaHouse",
    price: 9490,
    stock: 14,
    seller: OS,
    tags: ["one-piece", "law"],
    feat: false,
    days: 28,
  },
  {
    id: "product-gen-109-megumin-figure",
    title: "KonoSuba Megumin Explosion 1/7",
    cat: "category-audio-electronics",
    sub: "Isekai Figures",
    brand: "Good Smile Company",
    price: 9990,
    stock: 16,
    seller: FV,
    tags: ["konosuba", "megumin"],
    feat: false,
    days: 24,
  },
  {
    id: "product-gen-110-erza-figure",
    title: "Fairy Tail Erza Scarlet Requip 1/7",
    cat: "category-womens-fashion-fashion",
    sub: "FT Figures",
    brand: "MegaHouse",
    price: 7490,
    stock: 18,
    seller: FV,
    tags: ["fairy-tail", "erza"],
    feat: false,
    days: 20,
  },
  {
    id: "product-gen-111-senku-figure",
    title: "Dr. Stone Senku Ishigami 1/8",
    cat: "category-home-kitchen",
    sub: "Sci-Fi Figures",
    brand: "Kotobukiya",
    price: 6490,
    stock: 20,
    seller: OS,
    tags: ["dr-stone", "senku"],
    feat: false,
    days: 17,
  },
  {
    id: "product-gen-112-jotaro-figure",
    title: "JoJo Part 3 Jotaro Kujo Star Platinum 1/6",
    cat: "category-audio-electronics",
    sub: "JoJo Figures",
    brand: "MegaHouse",
    price: 13990,
    stock: 10,
    seller: FV,
    tags: ["jojo", "jotaro", "star-platinum"],
    feat: true,
    days: 14,
  },
];

const generatedProducts: Partial<ProductDocument>[] = quickItems.map(
  (item) => ({
    id: item.id,
    title: item.title,
    description: `${item.title}. Premium collectible from ${item.brand}.`,
    category: item.cat,
    subcategory: item.sub,
    brand: item.brand,
    price: item.price,
    currency: "INR",
    stockQuantity: item.stock,
    availableQuantity: Math.max(item.stock - 2, 0),
    mainImage: `https://picsum.photos/seed/${item.id}/800/800`,
    images: [`https://picsum.photos/seed/${item.id}/1200/800`],
    status: "published" as const,
    ...item.seller,
    featured: item.feat,
    tags: item.tags,
    specifications: [{ name: "Material", value: "PVC + ABS" }],
    features: ["Detailed sculpt", "Display base included"],
    shippingInfo: "Ships in 2-4 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: daysAgo(item.days),
    updatedAt: daysAgo(1),
  }),
);

// ─── Final export (101 products) ────────────────────────────────────────────
export const productsSeedData: Partial<ProductDocument>[] = [
  ...regularProducts,
  ...outOfStockProducts,
  ...liveAuctions,
  ...endedAuctions,
  ...preOrders,
  ...draftProducts,
  ...discontinuedAndSold,
  ...generatedProducts,
];
