/**
 * Products Seed Data
 * Anime figures, collectibles, cosplay & model kits across all categories
 */

import type { ProductDocument } from "@/db/schema";

export const productsSeedData: Partial<ProductDocument>[] = [
  // Scale Figures > Dragon Ball Figures (smartphones slot)
  {
    id: "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    title: "Dragon Ball Super Saiyan Blue Goku 1/4 Scale Figure",
    description:
      "Premium 1/4 scale Goku in Super Saiyan Blue form by Bandai Spirits. Hand-painted PVC with intricate Ki energy effects, swappable hands, and detachable aura display stand.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "Bandai Spirits",
    price: 12490,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 25,
    mainImage: "https://picsum.photos/seed/goku-blue-figure/800/800",
    images: [
      "https://picsum.photos/seed/goku-blue-figure/1200/800",
      "https://picsum.photos/seed/dragon-ball-figure/1200/800",
      "https://picsum.photos/seed/saiyan-blue-stand/1200/800",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "dragon-ball",
      "goku",
      "scale-figure",
      "bandai",
      "super-saiyan-blue",
    ],
    specifications: [
      { name: "Scale", value: "1/4" },
      { name: "Height", value: "36", unit: "cm" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: [
      "Ki energy aura effect",
      "Swappable hands",
      "Display stand included",
    ],
    shippingInfo: "Free shipping in 2-3 days. Box ships in outer box.",
    returnPolicy: "7-day returns accepted.",
    condition: "new",
    insurance: true,
    insuranceCost: 999,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-12-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },
  {
    id: "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    title: "Super Saiyan Vegeta Final Flash 1/4 Scale Statue",
    description:
      "MegaHouse Dragon Ball Z Vegeta Final Flash statue in firing pose. Includes energy beam effect part, interchangeable hands, and dynamic battle damage base.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "MegaHouse",
    price: 9990,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage: "https://picsum.photos/seed/vegeta-final-flash/800/800",
    images: [
      "https://picsum.photos/seed/vegeta-final-flash/1200/800",
      "https://picsum.photos/seed/vegeta-figure-back/1200/800",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["dragon-ball", "vegeta", "scale-figure", "megahouse", "final-flash"],
    specifications: [
      { name: "Scale", value: "1/4" },
      { name: "Height", value: "32", unit: "cm" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: [
      "Energy beam effect part",
      "Battle base diorama",
      "Swappable hands",
    ],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-01T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },
  {
    id: "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    title: "Ultra Instinct Goku Premium 1/6 Scale Figure",
    description:
      "Banpresto Dragon Ball Super Ultra Instinct Goku with silver aura effect stand. Captures the serene yet devastating power of Mastered Ultra Instinct.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Dragon Ball Z Figures",
    brand: "Banpresto",
    price: 6990,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 40,
    mainImage: "https://picsum.photos/seed/ultra-instinct-goku/800/800",
    images: [
      "https://picsum.photos/seed/ultra-instinct-goku/1200/800",
      "https://picsum.photos/seed/goku-silver-aura/1200/800",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: [
      "dragon-ball",
      "goku",
      "ultra-instinct",
      "banpresto",
      "scale-figure",
    ],
    specifications: [
      { name: "Scale", value: "1/6" },
      { name: "Height", value: "27", unit: "cm" },
      { name: "Material", value: "PVC" },
    ],
    features: [
      "Silver aura effect",
      "Floating display stand",
      "Mirror-finish base",
    ],
    shippingInfo: "Free shipping in 3-5 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-20T00:00:00Z"),
    updatedAt: new Date("2026-02-04T00:00:00Z"),
  },

  // Scale Figures > Premium Statues (laptops slot)
  {
    id: "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    title: "Monkey D. Luffy Gear 5 Sun God 1/4 Scale Scene Figure",
    description:
      "Bandai Spirits One Piece Gear 5 Luffy scene figure — the iconic Sun God Nika form with bouncy balloon effects. Massive 42 cm display piece with cloud effect base.",
    category: "category-laptops-computers-electronics",
    subcategory: "One Piece Figures",
    brand: "Bandai Spirits",
    price: 24990,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    mainImage: "https://picsum.photos/seed/luffy-gear5-figure/800/800",
    images: [
      "https://picsum.photos/seed/luffy-gear5-figure/1200/800",
      "https://picsum.photos/seed/one-piece-scene/1200/800",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "one-piece",
      "luffy",
      "gear-5",
      "bandai",
      "scale-figure",
      "sun-god-nika",
    ],
    specifications: [
      { name: "Scale", value: "1/4" },
      { name: "Height", value: "42", unit: "cm" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: [
      "Clouds effect base",
      "Balloon effect parts",
      "Dynamic scene pose",
    ],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-15T23:59:59Z"),
    createdAt: new Date("2025-11-01T00:00:00Z"),
    updatedAt: new Date("2026-02-07T00:00:00Z"),
  },
  {
    id: "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    title: "Roronoa Zoro Enma Slash Diorama 1/7 Scale",
    description:
      "MegaHouse One Piece Zoro with three swords drawn in the iconic '360-pound phoenix' blade wind pose. Includes black marble-style base.",
    category: "category-laptops-computers-electronics",
    subcategory: "One Piece Figures",
    brand: "MegaHouse",
    price: 18990,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 15,
    mainImage: "https://picsum.photos/seed/zoro-three-swords/800/800",
    images: ["https://picsum.photos/seed/zoro-three-swords/1200/800"],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["one-piece", "zoro", "diorama", "megahouse", "scale-figure"],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "35", unit: "cm" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: [
      "Three-sword form",
      "Marble-style display base",
      "Blade wind effect",
    ],
    shippingInfo: "Free shipping in 4-6 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-15T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },

  // Cosplay & Apparel > Men's Cosplay
  {
    id: "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    title: "Demon Slayer Tanjiro Kamado Graphic T-Shirt",
    description:
      "Official Kimetsu no Yaiba oversize tee with Tanjiro flame-water art print. 100% heavyweight cotton with anime-accurate colour gradients.",
    category: "category-mens-fashion-fashion",
    subcategory: "Anime Tees",
    brand: "AnimeCraft Apparel",
    price: 1299,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 100,
    mainImage: "https://picsum.photos/seed/tanjiro-tee/800/800",
    images: ["https://picsum.photos/seed/tanjiro-tee/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["demon-slayer", "tanjiro", "tee", "anime-apparel", "cosplay"],
    specifications: [
      { name: "Material", value: "100% Cotton (280 GSM)" },
      { name: "Fit", value: "Oversize" },
    ],
    features: [
      "DTG printed art",
      "Pre-shrunk fabric",
      "Anime-accurate colours",
    ],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-09-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // Cosplay & Apparel > Women's Cosplay
  {
    id: "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    title: "Nezuko Kamado Pink Kimono Hoodie Dress",
    description:
      "Inspired by Nezuko's iconic pink kimono with hemp leaf pattern. Soft fleece hoodie dress with bamboo bamboo embroidery on pocket and cuff.",
    category: "category-womens-fashion-fashion",
    subcategory: "Cosplay Dresses",
    brand: "AnimeCraft Apparel",
    price: 1999,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 80,
    mainImage: "https://picsum.photos/seed/nezuko-kimono-dress/800/800",
    images: ["https://picsum.photos/seed/nezuko-kimono-dress/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["demon-slayer", "nezuko", "kimono", "cosplay", "hoodie-dress"],
    specifications: [
      { name: "Material", value: "Soft Fleece Blend" },
      { name: "Length", value: "Knee Length" },
    ],
    features: [
      "Hemp leaf pattern print",
      "Embroidered cuffs",
      "Kangaroo pocket",
    ],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-08-20T00:00:00Z"),
    updatedAt: new Date("2026-01-28T00:00:00Z"),
  },

  // Collectibles & Display > Nendoroids
  {
    id: "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    title: "My Neighbour Totoro Nendoroid No.1234 Deluxe Set",
    description:
      "Good Smile Company Totoro Nendoroid with Satsuki and Mei chibi add-ons. Includes enchanted forest bus stop diorama base and all accessories.",
    category: "category-home-kitchen",
    subcategory: "Nendoroids",
    brand: "Good Smile Company",
    price: 3499,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: "https://picsum.photos/seed/totoro-nendoroid/800/800",
    images: ["https://picsum.photos/seed/totoro-nendoroid/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["ghibli", "totoro", "nendoroid", "good-smile", "chibi"],
    specifications: [
      { name: "Height", value: "10", unit: "cm" },
      { name: "Pieces included", value: "3 (Totoro + Satsuki + Mei chibi)" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: [
      "Bus stop diorama base",
      "Multiple face plates",
      "Swappable accessories",
    ],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-07-10T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },

  // Model Kits & Gunpla
  {
    id: "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    title: "Gundam RX-78-2 Perfect Grade 1/60 Model Kit",
    description:
      "Bandai Gundam PG 1/60 RX-78-2 with LED light unit. Over 550 individually snap-fitted parts with internal skeleton frame and moveable cockpit.",
    category: "category-sports-outdoors",
    subcategory: "Perfect Grade Gunpla",
    brand: "Bandai",
    price: 4999,
    currency: "INR",
    stockQuantity: 75,
    availableQuantity: 75,
    mainImage: "https://picsum.photos/seed/rx78-gundam-kit/800/800",
    images: ["https://picsum.photos/seed/rx78-gundam-kit/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["gundam", "rx-78-2", "perfect-grade", "model-kit", "bandai"],
    specifications: [
      { name: "Scale", value: "1/60" },
      { name: "Parts", value: "550+" },
      { name: "Includes LED", value: "Yes" },
    ],
    features: ["Internal skeleton frame", "LED unit", "Moveable cockpit hatch"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-06-15T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"),
  },

  // Auction — Signed Art & Collectibles
  {
    id: "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    title: "Gainax Evangelion Unit-01 Original Production Art — AUCTION",
    description:
      "Authenticated production cel artwork from Neon Genesis Evangelion (1995 series, episode 19). Framed original hand-drawn cel with print background. Certificate of authenticity included.",
    category: "category-cameras-photography-electronics",
    subcategory: "Signed Art & Production Cels",
    brand: "Gainax (Auth.)",
    price: 15000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/evangelion-art-cel/800/800",
    images: [
      "https://picsum.photos/seed/evangelion-art-cel/1200/800",
      "https://picsum.photos/seed/anime-production-art/1200/800",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "evangelion",
      "production-art",
      "cel",
      "gainax",
      "collector",
      "auction",
    ],
    specifications: [
      { name: "Type", value: "Original Production Cel" },
      { name: "Episode", value: "19 — 'A Human Work'" },
      { name: "Year", value: "1995" },
    ],
    features: [
      "Certificate of authenticity",
      "Original frame",
      "UV-protective glass",
    ],
    shippingInfo: "Insured shipping in 3-5 days.",
    returnPolicy: "No returns on auctions.",
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-14T23:59:59Z"),
    startingBid: 15000,
    currentBid: 22000,
    bidCount: 8,
    reservePrice: 25000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-14T23:59:59Z"),
    createdAt: new Date("2026-01-20T00:00:00Z"),
    updatedAt: new Date("2026-02-08T18:30:00Z"),
  },

  // Limited & Rare — Out of stock
  {
    id: "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
    title: "Tanjiro Hinokami Kagura 1/7 Scale PVC Figure — SOLD OUT",
    description:
      "Alter Co. Tanjiro Kamado 'Dance of the Fire God' in stunning full-colour finish. Hinokami Kagura flames rendered in translucent red resin. Currently sold out.",
    category: "category-audio-electronics",
    subcategory: "Limited Edition Figures",
    brand: "Alter Co.",
    price: 29990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://picsum.photos/seed/tanjiro-hinokami/800/800",
    images: ["https://picsum.photos/seed/tanjiro-hinokami/1200/800"],
    status: "out_of_stock",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: [
      "demon-slayer",
      "tanjiro",
      "hinokami",
      "alter",
      "limited",
      "out-of-stock",
    ],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "30", unit: "cm" },
    ],
    features: [
      "Translucent flame effect",
      "Detailed kimono sculpt",
      "Acrylic display base",
    ],
    shippingInfo: "Currently unavailable.",
    returnPolicy: "7-day returns when available.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-05-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // ─── Men's Cosplay ─────────────────────────────────────────────────────────
  {
    id: "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
    title: "Attack on Titan Scout Regiment Cosplay Jacket",
    description:
      "Officially licensed Survey Corps jacket with Wings of Freedom emblem embroidered on chest and back. Heavy-canvas construction for accurate screen look. Machine washable.",
    category: "category-mens-fashion-fashion",
    subcategory: "Cosplay Jackets",
    brand: "AnimeCraft Apparel",
    price: 1499,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 75,
    mainImage: "https://picsum.photos/seed/aot-jacket/800/800",
    images: [
      "https://picsum.photos/seed/aot-jacket/1200/800",
      "https://picsum.photos/seed/wings-of-freedom/1200/800",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: [
      "attack-on-titan",
      "scout-regiment",
      "cosplay",
      "jacket",
      "survey-corps",
    ],
    specifications: [
      { name: "Material", value: "Heavy Canvas + Cotton" },
      { name: "Emblem", value: "Embroidered Wings of Freedom" },
    ],
    features: [
      "Machine washable",
      "Screen-accurate emblem",
      "Dual chest pockets",
    ],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day easy returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-15T23:59:59Z"),
    createdAt: new Date("2025-11-10T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
  },
  {
    id: "product-mens-slim-chinos-fashion-new-fashionboutique-1",
    title: "My Hero Academia All Might Symbol of Peace Hoodie",
    description:
      "Premium 380 GSM heavyweight hoodie with All Might in Muscle Form art. Available in 'Plus Ultra' blue and 'Smash' black editions. Ribbed cuffs and drawstring hood.",
    category: "category-mens-fashion-fashion",
    subcategory: "Anime Hoodies",
    brand: "AnimeCraft Apparel",
    price: 1799,
    currency: "INR",
    stockQuantity: 60,
    availableQuantity: 55,
    mainImage: "https://picsum.photos/seed/all-might-hoodie/800/800",
    images: ["https://picsum.photos/seed/all-might-hoodie/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["my-hero-academia", "all-might", "hoodie", "cosplay", "plus-ultra"],
    specifications: [
      { name: "Material", value: "380 GSM Cotton Blend" },
      { name: "Fit", value: "Regular" },
    ],
    features: ["DTG printed art", "Ribbed cuffs and hem", "Kangaroo pocket"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day easy returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-15T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },
  {
    id: "product-mens-leather-derby-shoes-fashion-new-fashionboutique-1",
    title: "Naruto Shippuden Akatsuki Cloak Full Cosplay Set",
    description:
      "Full Akatsuki cosplay set: premium woven fabric black cloak with all-over red cloud pattern. Includes metal ring prop, forehead protector, and drawstring carry bag.",
    category: "category-mens-fashion-fashion",
    subcategory: "Cosplay Sets",
    brand: "AnimeCraft Apparel",
    price: 3499,
    currency: "INR",
    stockQuantity: 35,
    availableQuantity: 30,
    mainImage: "https://picsum.photos/seed/akatsuki-cloak/800/800",
    images: ["https://picsum.photos/seed/akatsuki-cloak/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["naruto", "akatsuki", "cloak", "cosplay-set", "forehead-protector"],
    specifications: [
      { name: "Material", value: "Woven Polyester" },
      { name: "Includes", value: "Cloak, Ring, Forehead Protector, Bag" },
    ],
    features: [
      "Metal ring prop",
      "Screen-accurate cloud print",
      "One size with belt tie",
    ],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "7-day returns (unused condition).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-12-01T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },

  // ─── Women's Cosplay ───────────────────────────────────────────────────────
  {
    id: "product-womens-anarkali-kurta-fashion-new-fashionboutique-1",
    title: "Sailor Moon Neo Queen Serenity Cosplay Dress Set",
    description:
      "Deluxe 3-piece Sailor Moon transformation dress with tiara prop, moon rod, and gloves. Japanese sizing available. Screen-accurate detailing on bodice and cape.",
    category: "category-womens-fashion-fashion",
    subcategory: "Cosplay Sets",
    brand: "AnimeCraft Apparel",
    price: 2899,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 38,
    mainImage: "https://picsum.photos/seed/sailor-moon-dress/800/800",
    images: ["https://picsum.photos/seed/sailor-moon-dress/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["sailor-moon", "serenity", "cosplay", "dress", "magical-girl"],
    specifications: [
      { name: "Material", value: "Satin + Organza" },
      { name: "Set includes", value: "Dress, Tiara, Rod, Gloves" },
    ],
    features: [
      "Dry clean recommended",
      "Convention-ready set",
      "Tiara prop included",
    ],
    shippingInfo: "Ships in 2-4 business days.",
    returnPolicy: "7-day returns for unworn items.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-31T23:59:59Z"),
    createdAt: new Date("2025-10-20T00:00:00Z"),
    updatedAt: new Date("2026-02-14T00:00:00Z"),
  },
  {
    id: "product-womens-casual-midi-dress-fashion-new-fashionboutique-1",
    title: "Genshin Impact Ganyu Qixing Cosplay Dress",
    description:
      "High-fidelity Ganyu cosplay outfit with detachable cryo horns, pastel-blue tail, and patterned silk-style pleated dress. Includes hair accessories.",
    category: "category-womens-fashion-fashion",
    subcategory: "Cosplay Dresses",
    brand: "AnimeCraft Apparel",
    price: 1649,
    currency: "INR",
    stockQuantity: 55,
    availableQuantity: 50,
    mainImage: "https://picsum.photos/seed/ganyu-cosplay/800/800",
    images: ["https://picsum.photos/seed/ganyu-cosplay/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["genshin-impact", "ganyu", "cosplay", "dress", "cryo"],
    specifications: [
      { name: "Material", value: "Chiffon Silk Blend" },
      { name: "Length", value: "Midi (below knee)" },
      { name: "Includes", value: "Dress, Horns, Tail, Hair pins" },
    ],
    features: [
      "Detachable horns + tail",
      "All-season wear",
      "Inclusive sizing XS-3XL",
    ],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day easy returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-12-10T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },
  {
    id: "product-womens-structured-tote-bag-fashion-new-fashionboutique-1",
    title: "Totoro Forest Spirit Embroidered Canvas Tote Bag",
    description:
      "Premium canvas tote with large-format Totoro embroidery from Studio Ghibli's licensed collection. Magnetic snap closure and inner zipper pocket.",
    category: "category-womens-fashion-fashion",
    subcategory: "Anime Bags",
    brand: "AnimeCraft Apparel",
    price: 1999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage: "https://picsum.photos/seed/totoro-tote/800/800",
    images: ["https://picsum.photos/seed/totoro-tote/1200/800"],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "AnimeCraft Apparel",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["ghibli", "totoro", "tote", "canvas-bag", "studio-ghibli"],
    specifications: [
      { name: "Material", value: "12oz Canvas" },
      { name: "Dimensions", value: "38 × 30 × 14 cm" },
    ],
    features: [
      "Embroidered Totoro art",
      "Inner zip pocket",
      "Magnetic snap closure",
    ],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-05T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // ─── Collectibles & Display ────────────────────────────────────────────────
  {
    id: "product-prestige-pressure-cooker-home-new-homeessentials-1",
    title: "Rem & Ram Re:Zero Nendoroid Duo Set",
    description:
      "Good Smile Company twin Nendoroids — Rem (No.1002) + Ram (No.1003). Includes ice flower, broom, and maid-headband accessories. Collectible window box packaging.",
    category: "category-home-kitchen",
    subcategory: "Nendoroids",
    brand: "Good Smile Company",
    price: 2499,
    currency: "INR",
    stockQuantity: 45,
    availableQuantity: 42,
    mainImage: "https://picsum.photos/seed/rem-ram-nendoroid/800/800",
    images: ["https://picsum.photos/seed/rem-ram-nendoroid/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["rezero", "rem", "ram", "nendoroid", "good-smile", "maid"],
    specifications: [
      { name: "Height", value: "10", unit: "cm each" },
      { name: "Pieces included", value: "2 Nendoroids" },
      { name: "Material", value: "PVC + ABS" },
    ],
    features: [
      "Interchangeable faces",
      "Accessory stands",
      "Window box packaging",
    ],
    shippingInfo: "Free shipping over ₹999. Ships in 2-3 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-09-15T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
  },
  {
    id: "product-nonstick-cookware-set-home-new-homeessentials-1",
    title: "Attack on Titan 3D Maneuver Gear Wallhanger Replica",
    description:
      "High-quality resin replica of Survey Corps 3D Maneuver Gear (ODM). Includes gas tanks, blade holsters, and display wall-mount bracket. Perfect shelf centrepiece.",
    category: "category-home-kitchen",
    subcategory: "Cosplay Props & Replicas",
    brand: "OtakuShelf Co",
    price: 3799,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 23,
    mainImage: "https://picsum.photos/seed/odm-gear-replica/800/800",
    images: ["https://picsum.photos/seed/odm-gear-replica/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: [
      "attack-on-titan",
      "odm-gear",
      "replica",
      "wall-decor",
      "survey-corps",
    ],
    specifications: [
      { name: "Material", value: "Resin + Metal accents" },
      { name: "Size", value: "45 × 30 cm" },
      { name: "Finish", value: "Metallic gunmetal" },
    ],
    features: [
      "Wall-mount bracket included",
      "Weathered battle finish",
      "Detachable blades",
    ],
    shippingInfo: "Free shipping. Ships in 3-4 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-01T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"),
  },
  {
    id: "product-smart-air-purifier-home-new-homeessentials-1",
    title: "Evangelion Unit-01 Berserker Mode Garage Kit 1/35 Scale",
    description:
      "Unpainted resin garage kit of EVA Unit-01 in berserker Awakening mode. For experienced modellers. Includes display diorama base with AT-Field effect.",
    category: "category-home-kitchen",
    subcategory: "Garage Kits",
    brand: "OtakuShelf Co",
    price: 12999,
    currency: "INR",
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage: "https://picsum.photos/seed/eva-unit01-garage/800/800",
    images: ["https://picsum.photos/seed/eva-unit01-garage/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["evangelion", "eva-unit01", "garage-kit", "resin", "berserker"],
    specifications: [
      { name: "Scale", value: "1/35" },
      { name: "Material", value: "Cast Resin (unpainted)" },
      { name: "Height assembled", value: "28", unit: "cm" },
    ],
    features: [
      "AT-Field diorama base",
      "Requires assembly + painting",
      "Detailed panel lines",
    ],
    shippingInfo: "Free shipping. Ships in 2-4 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-20T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },
  {
    id: "product-solid-wood-coffee-table-home-new-homeessentials-1",
    title: "Studio Ghibli Collector's Display Shelf Set (8 Figures)",
    description:
      "Curated 8-figure display set from Studio Ghibli: Totoro, Kiki, Howl, Calcifer, Nausicaä, No-Face, Chihiro, and Haku dragon. Dust-proof acrylic display case included.",
    category: "category-home-kitchen",
    subcategory: "Collector Sets",
    brand: "OtakuShelf Co",
    price: 8499,
    currency: "INR",
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: "https://picsum.photos/seed/ghibli-display-set/800/800",
    images: ["https://picsum.photos/seed/ghibli-display-set/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: [
      "ghibli",
      "collector-set",
      "display",
      "totoro",
      "spirited-away",
      "kiki",
    ],
    specifications: [
      { name: "Figures", value: "8 (hand-painted PVC)" },
      { name: "Case", value: "Acrylic dust-proof box" },
      {
        name: "Films covered",
        value: "Totoro, Kiki, Howl, Nausicaä, Spirited Away",
      },
    ],
    features: [
      "Dust-proof display case",
      "Hand-painted detail",
      "Signed artist card",
    ],
    shippingInfo: "Ships in 7-10 days (curated set).",
    returnPolicy: "No returns on opened collector sets.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-07-01T00:00:00Z"),
    updatedAt: new Date("2025-12-15T00:00:00Z"),
  },

  // ─── Model Kits & Gunpla ───────────────────────────────────────────────────
  {
    id: "product-premium-yoga-mat-sports-new-sportszone-1",
    title: "Naruto Sage Mode Toad Sage 1/7 Scale PVC Figure",
    description:
      "Megahouse statue of Naruto in full Sage Mode with Fukasaku and Shima frog sages on his shoulders. Multi-piece diorama base with stone frog gate.",
    category: "category-sports-outdoors",
    subcategory: "Naruto Figures",
    brand: "Megahouse",
    price: 3999,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 47,
    mainImage: "https://picsum.photos/seed/naruto-sage-figure/800/800",
    images: ["https://picsum.photos/seed/naruto-sage-figure/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["naruto", "sage-mode", "toad-sage", "megahouse", "scale-figure"],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "22", unit: "cm" },
      { name: "Material", value: "PVC" },
    ],
    features: [
      "Fukasaku & Shima frog sages included",
      "Stone gate base diorama",
      "Ryuumyaku energy detail",
    ],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-01T23:59:59Z"),
    createdAt: new Date("2025-08-01T00:00:00Z"),
    updatedAt: new Date("2026-02-12T00:00:00Z"),
  },
  {
    id: "product-adjustable-dumbbell-set-sports-new-sportszone-1",
    title: "Gundam Wing Zero Custom 1/100 Master Grade Model Kit",
    description:
      "Bandai MG 1/100 Wing Zero Custom (XXXG-00W0) Advanced DRAGOON wing binders with full inner frame. Over 200 parts with foil sticker sheet.",
    category: "category-sports-outdoors",
    subcategory: "Master Grade Gunpla",
    brand: "Bandai",
    price: 14999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage: "https://picsum.photos/seed/wing-zero-gundam/800/800",
    images: ["https://picsum.photos/seed/wing-zero-gundam/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["gundam", "wing-zero", "master-grade", "bandai", "model-kit"],
    specifications: [
      { name: "Scale", value: "1/100" },
      { name: "Parts", value: "200+" },
      { name: "Grade", value: "Master Grade" },
    ],
    features: [
      "Full inner frame",
      "DRAGOON wing binders",
      "Foil sticker sheet",
    ],
    shippingInfo: "Free shipping. Ships in 5-7 days.",
    returnPolicy: "7-day returns (original packaging).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-09-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },
  {
    id: "product-cricket-bat-mrf-sports-new-sportszone-1",
    title: "One Piece Going Merry Ship 1/144 Scale Resin Model",
    description:
      "Hand-cast polystone Going Merry ship replica with original Straw Hat crew flag. Limited artisan run of 200 pieces — each numbered with artist signature card.",
    category: "category-sports-outdoors",
    subcategory: "Ship & Vehicle Models",
    brand: "OtakuShelf Co",
    price: 6999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage: "https://picsum.photos/seed/going-merry-model/800/800",
    images: ["https://picsum.photos/seed/going-merry-model/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: [
      "one-piece",
      "going-merry",
      "ship-model",
      "resin",
      "artisan",
      "limited",
    ],
    specifications: [
      { name: "Scale", value: "1/144" },
      { name: "Material", value: "Polystone Resin" },
      { name: "Edition", value: "Numbered (1-200)" },
    ],
    features: [
      "Numbered limited edition",
      "Artist signature card",
      "Straw Hat flag",
    ],
    shippingInfo: "Ships in 2-4 business days.",
    returnPolicy: "7-day returns (unopened).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-15T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },
  {
    id: "product-running-shoes-adidas-sports-new-sportszone-1",
    title: "Jujutsu Kaisen Gojo Satoru Infinity Domain 1/7 Scale",
    description:
      "Union Creative Gojo Satoru with Infinity barrier effect stand — 28 cm tall with LED-compatible base. Blind-fold variant and open-eyes head sculpt both included.",
    category: "category-sports-outdoors",
    subcategory: "Jujutsu Kaisen Figures",
    brand: "Union Creative",
    price: 15999,
    currency: "INR",
    stockQuantity: 22,
    availableQuantity: 19,
    mainImage: "https://picsum.photos/seed/gojo-satoru-figure/800/800",
    images: ["https://picsum.photos/seed/gojo-satoru-figure/1200/800"],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "OtakuShelf Co",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: [
      "jujutsu-kaisen",
      "gojo",
      "infinity",
      "union-creative",
      "scale-figure",
    ],
    specifications: [
      { name: "Scale", value: "1/7" },
      { name: "Height", value: "28", unit: "cm" },
      { name: "LED base", value: "Compatible (battery not included)" },
    ],
    features: [
      "Two head sculpts (blind-fold + open eyes)",
      "LED-compatible infinity base",
      "Translucent barrier effect",
    ],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "15-day returns (unopened).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },

  // ─── More Scale Figures ────────────────────────────────────────────────────
  {
    id: "product-apple-ipad-pro-electronics-new-techhub-1",
    title: "Bleach Ichigo Bankai Tensa Zangetsu 1/6 Scale Figure",
    description:
      "Bandai S.H.Figuarts Ichigo Kurosaki in Final Bankai form. Highly articulated with swappable wrists, Zangetsu sword in sheath, and energy-release effect parts.",
    category: "category-laptops-computers-electronics",
    subcategory: "Bleach Figures",
    brand: "Bandai S.H.Figuarts",
    price: 8990,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage: "https://picsum.photos/seed/ichigo-bankai-figure/800/800",
    images: ["https://picsum.photos/seed/ichigo-bankai-figure/1200/800"],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "bleach",
      "ichigo",
      "bankai",
      "bandai",
      "shfiguarts",
      "scale-figure",
    ],
    specifications: [
      { name: "Scale", value: "1/6" },
      { name: "Height", value: "26", unit: "cm" },
      { name: "Articulation", value: "25+ points" },
    ],
    features: [
      "Zangetsu sword with sheath",
      "Bankai energy effect parts",
      "25+ articulation points",
    ],
    shippingInfo: "Free delivery in 1-2 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-12-15T00:00:00Z"),
    updatedAt: new Date("2026-02-16T00:00:00Z"),
  },
  {
    id: "product-samsung-galaxy-watch6-electronics-new-techhub-1",
    title: "Dragon Ball Z Scouter Replica & Capsule Corp Gift Set",
    description:
      "Premium-grade ABS Saber Tooth scouter replica with working green LED eye-light. Includes 10 authentic Capsule Corp resin capsules in wooden display case.",
    category: "category-mobiles-accessories-electronics",
    subcategory: "Cosplay Props",
    brand: "FigureVault JP",
    price: 4999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage: "https://picsum.photos/seed/dbz-scouter-capsule/800/800",
    images: ["https://picsum.photos/seed/dbz-scouter-capsule/1200/800"],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "dragon-ball",
      "scouter",
      "capsule-corp",
      "cosplay-prop",
      "gift-set",
    ],
    specifications: [
      { name: "Scouter material", value: "ABS + PETG lens" },
      { name: "LED", value: "Green working LED eye-light" },
      { name: "Capsules", value: "10 resin capsules" },
    ],
    features: [
      "Working LED scouter",
      "Wooden display case",
      "10 Capsule Corp capsules",
    ],
    shippingInfo: "Free shipping. Ships in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-10T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
  },
  {
    id: "product-anker-usbc-charger-electronics-new-techhub-1",
    title: "Spirited Away No-Face Resin Miniature Figurine",
    description:
      "Detailed hand-painted resin No-Face mini figurine (9 cm) from Studio Ghibli's licensed collection. Gold mask variant and standard variant included in twin pack.",
    category: "category-mobile-accessories-mobiles-accessories",
    subcategory: "Mini Figurines",
    brand: "FigureVault JP",
    price: 1290,
    currency: "INR",
    stockQuantity: 70,
    availableQuantity: 68,
    mainImage: "https://picsum.photos/seed/no-face-figurine/800/800",
    images: ["https://picsum.photos/seed/no-face-figurine/1200/800"],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: [
      "ghibli",
      "no-face",
      "spirited-away",
      "mini-figurine",
      "hand-painted",
    ],
    specifications: [
      { name: "Height", value: "9", unit: "cm" },
      { name: "Material", value: "Hand-painted Resin" },
      { name: "Variants", value: "2 (standard + gold mask)" },
    ],
    features: ["Hand-painted finish", "Twin pack", "Ghibli licensed"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-20T00:00:00Z"),
    updatedAt: new Date("2026-02-15T00:00:00Z"),
  },

  // ─── Auction Items ─────────────────────────────────────────────────────────
  {
    id: "product-macbook-pro-m3-auction-electronics-techhub-1",
    title: "Dragon Ball Z Complete Son Family Collector Set — AUCTION",
    description:
      "Ultra-rare 7-piece first-run Son family collector set by Bandai/MegaHouse: Goku, Gohan (Teen & Adult), Goten, Bardock, Raditz, and Broly. Factory sealed. Starting bid 60% of retail.",
    category: "category-laptops-computers-electronics",
    subcategory: "Collector Sets",
    brand: "Bandai / MegaHouse",
    price: 169900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/son-family-set/800/800",
    images: ["https://picsum.photos/seed/son-family-set/1200/800"],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "dragon-ball",
      "son-family",
      "collector-set",
      "bandai",
      "rare",
      "auction",
    ],
    specifications: [
      { name: "Figures", value: "7 (all PVC, hand-painted)" },
      { name: "Tallest figure", value: "Broly at 40 cm" },
      { name: "Production run", value: "First edition (numbered)" },
    ],
    features: [
      "Factory sealed, first run",
      "Numbered certificate",
      "Collector's outer box",
    ],
    shippingInfo: "Ships within 24 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-16T23:59:59Z"),
    startingBid: 100000,
    currentBid: 115000,
    bidCount: 7,
    buyNowPrice: 180000,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-16T23:59:59Z"),
    createdAt: new Date("2026-02-10T00:00:00Z"),
    updatedAt: new Date("2026-02-19T00:00:00Z"),
  },
  {
    id: "product-vintage-leica-camera-auction-artisan-1",
    title: "Neon Genesis Evangelion 1995 Limited-Run Signed Poster — AUCTION",
    description:
      "Original 1995 Japanese limited-run theatrical promotional poster signed by Hideaki Anno. First theatrical release. Includes Gainax certificate of authenticity and archival tube.",
    category: "category-cameras-photography-electronics",
    subcategory: "Signed Art & Production Cels",
    brand: "Gainax (Verified)",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://picsum.photos/seed/evangelion-poster/800/800",
    images: ["https://picsum.photos/seed/evangelion-poster/1200/800"],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "FigureVault JP",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: [
      "evangelion",
      "hideaki-anno",
      "signed",
      "poster",
      "vintage",
      "auction",
      "collector",
    ],
    specifications: [
      { name: "Year", value: "1995" },
      { name: "Condition", value: "9/10 — Excellent" },
      { name: "Signed by", value: "Hideaki Anno (director)" },
    ],
    features: [
      "Director signature",
      "Gainax certificate of authenticity",
      "Archival shipping tube",
    ],
    shippingInfo: "Insured shipping within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-04-10T23:59:59Z"),
    startingBid: 75000,
    currentBid: 97500,
    bidCount: 5,
    reservePrice: 120000,
    minBidIncrement: 2500,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: new Date("2026-04-10T23:59:59Z"),
    createdAt: new Date("2026-01-15T00:00:00Z"),
    updatedAt: new Date("2026-02-19T00:00:00Z"),
  },
];
