/**
 * Reviews Seed Data
 * Sample product reviews with various ratings and statuses
 */

import type { ReviewDocument } from "@/db/schema";

export const reviewsSeedData: Partial<ReviewDocument>[] = [
  // Approved reviews
  {
    id: "review-iphone-15-pro-max-john-20260120",
    productId:
      "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    productTitle: "Dragon Ball Super Saiyan Blue Goku 1/4 Scale Figure",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-doe",
    rating: 5,
    title: "Absolutely Amazing!",
    comment:
      "Exceeded expectations. Camera and battery are outstanding. Worth it!",
    images: [
      "https://picsum.photos/seed/iphone15/800/800",
      "https://picsum.photos/seed/apple-phone/800/800",
    ],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      thumbnailUrl: "https://picsum.photos/seed/iphone15/800/450",
      duration: 15,
    },
    status: "approved",
    helpfulCount: 24,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: new Date("2026-01-20T10:30:00Z"),
    updatedAt: new Date("2026-01-20T10:30:00Z"),
    approvedAt: new Date("2026-01-20T12:00:00Z"),
  },
  {
    id: "review-samsung-galaxy-s24-ultra-jane-20260125",
    productId:
      "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    productTitle: "Super Saiyan Vegeta Final Flash 1/4 Scale Statue",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 5,
    title: "Best Android Phone Yet",
    comment:
      "S Pen is useful, camera is stunning, AI features are helpful. Great for power users.",
    images: [],
    status: "approved",
    helpfulCount: 18,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: new Date("2026-01-25T14:15:00Z"),
    updatedAt: new Date("2026-01-25T14:15:00Z"),
    approvedAt: new Date("2026-01-25T16:00:00Z"),
  },
  {
    id: "review-google-pixel-8-pro-mike-20260131",
    productId:
      "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    productTitle: "Ultra Instinct Goku Premium 1/6 Scale Figure",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-johnson",
    rating: 4,
    title: "Great Camera, Pure Android",
    comment:
      "Love the camera and clean Android. Magic Eraser is fun. Battery could be better.",
    images: [],
    status: "approved",
    helpfulCount: 12,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-01T09:30:00Z"),
    updatedAt: new Date("2026-02-01T09:30:00Z"),
    approvedAt: new Date("2026-02-01T11:00:00Z"),
  },
  {
    id: "review-macbook-pro-16-m3-max-john-20260126",
    productId:
      "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    productTitle: "Monkey D. Luffy Gear 5 Sun God 1/4 Scale Scene Figure",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-doe",
    rating: 5,
    title: "Perfect for Professionals",
    comment:
      "Handles 4K editing smoothly. Display is gorgeous, battery life incredible. Best laptop ever.",
    images: [
      "https://picsum.photos/seed/macbook-laptop/800/800",
      "https://picsum.photos/seed/laptop-apple/800/800",
    ],
    status: "approved",
    helpfulCount: 31,
    reportCount: 0,
    verified: false,
    featured: true,
    createdAt: new Date("2026-02-07T11:00:00Z"),
    updatedAt: new Date("2026-02-07T11:00:00Z"),
    approvedAt: new Date("2026-02-07T13:00:00Z"),
  },
  {
    id: "review-dell-xps-15-jane-20260201",
    productId:
      "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    productTitle: "Roronoa Zoro Enma Slash Diorama 1/7 Scale",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 4,
    title: "Powerful Windows Laptop",
    comment:
      "Excellent build and performance. RTX 4060 handles design work perfectly. Webcam could be better.",
    images: [],
    status: "approved",
    helpfulCount: 15,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-03T13:45:00Z"),
    updatedAt: new Date("2026-02-03T13:45:00Z"),
    approvedAt: new Date("2026-02-03T15:00:00Z"),
  },
  {
    id: "review-mens-cotton-casual-shirt-mike-20260205",
    productId:
      "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    productTitle: "Demon Slayer Tanjiro Kamado Graphic T-Shirt",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-johnson",
    rating: 4,
    title: "Good Quality, Comfortable Fit",
    comment: "Nice cotton shirt, breathable and true to size. Good value.",
    images: [],
    status: "approved",
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-30T15:20:00Z"),
    updatedAt: new Date("2026-01-30T15:20:00Z"),
    approvedAt: new Date("2026-01-30T16:30:00Z"),
  },
  {
    id: "review-womens-ethnic-kurti-jane-20260207",
    productId:
      "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    productTitle: "Nezuko Kamado Pink Kimono Hoodie Dress",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 5,
    title: "Beautiful Design and Quality",
    comment:
      "Love this kurti! Beautiful print, excellent quality, perfect fit. Will buy more.",
    images: ["https://picsum.photos/seed/ethnic-kurti/800/800"],
    status: "approved",
    helpfulCount: 14,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-08T16:30:00Z"),
    updatedAt: new Date("2026-02-08T16:30:00Z"),
    approvedAt: new Date("2026-02-08T18:00:00Z"),
  },
  {
    id: "review-non-stick-cookware-set-john-20260208",
    productId:
      "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    productTitle: "My Neighbour Totoro Nendoroid No.1234 Deluxe Set",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-doe",
    rating: 4,
    title: "Good Value Cookware Set",
    comment:
      "Good set for the price. Non-stick works well, heats evenly. Handles could be better.",
    images: [],
    status: "approved",
    helpfulCount: 9,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-05T10:15:00Z"),
    updatedAt: new Date("2026-02-05T10:15:00Z"),
    approvedAt: new Date("2026-02-05T12:00:00Z"),
  },
  {
    id: "review-yoga-mat-with-carrying-bag-jane-20260209",
    productId:
      "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    productTitle: "Gundam RX-78-2 Perfect Grade 1/60 Model Kit",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 5,
    title: "Perfect for Daily Practice",
    comment:
      "Great mat with excellent grip and cushioning. No slip during intense sessions. Carrying bag is convenient.",
    images: [],
    status: "approved",
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-06T09:00:00Z"),
    updatedAt: new Date("2026-02-06T09:00:00Z"),
    approvedAt: new Date("2026-02-06T10:30:00Z"),
  },

  // Medium rating reviews
  {
    id: "review-vintage-canon-ae-1-film-camera-mike-20260203",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Gainax Evangelion Unit-01 Original Production Art",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-johnson",
    rating: 4,
    title: "Classic Beauty",
    comment:
      "Authentic vintage camera in excellent condition. Film photography at its finest.",
    images: ["https://picsum.photos/seed/film-camera/800/800"],
    status: "approved",
    helpfulCount: 7,
    reportCount: 0,
    verified: false,
    featured: true,
    createdAt: new Date("2026-02-02T14:20:00Z"),
    updatedAt: new Date("2026-02-02T14:20:00Z"),
    approvedAt: new Date("2026-02-02T16:00:00Z"),
  },
  {
    id: "review-iphone-15-pro-max-jane-20260204",
    productId:
      "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    productTitle: "Dragon Ball Super Saiyan Blue Goku 1/4 Scale Figure",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 4,
    title: "Impressive Performance",
    comment:
      "Camera quality is outstanding. Battery life is solid. Slightly heavy but worth it.",
    images: [],
    status: "approved",
    helpfulCount: 5,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-22T11:45:00Z"),
    updatedAt: new Date("2026-01-22T11:45:00Z"),
    approvedAt: new Date("2026-01-22T13:00:00Z"),
  },

  // Pending reviews (awaiting moderation)
  {
    id: "review-samsung-galaxy-s24-ultra-mike-20260206",
    productId:
      "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    productTitle: "Super Saiyan Vegeta Final Flash 1/4 Scale Statue",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-johnson",
    rating: 4,
    title: "Solid Upgrade",
    comment:
      "Upgraded from S22 Ultra. Camera improvements are noticeable, AI is cool. Wish it had charger.",
    images: [],
    status: "pending",
    helpfulCount: 0,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-08T09:30:00Z"),
    updatedAt: new Date("2026-02-08T09:30:00Z"),
  },
  {
    id: "review-google-pixel-8-pro-jane-20260207",
    productId:
      "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    productTitle: "Ultra Instinct Goku Premium 1/6 Scale Figure",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 4,
    title: "Great Camera and Software",
    comment:
      "Pure Android experience is refreshing. AI features are useful. Battery is decent.",
    images: [],
    status: "pending",
    helpfulCount: 0,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-08T10:15:00Z"),
    updatedAt: new Date("2026-02-08T10:15:00Z"),
  },

  // Rejected review (spam/inappropriate)
  {
    id: "review-macbook-pro-16-m3-max-mike-20260207",
    productId:
      "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    productTitle: "Monkey D. Luffy Gear 5 Sun God 1/4 Scale Scene Figure",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-johnson",
    rating: 1,
    title: "Fake Product",
    comment: "This is a scam! Check out my website for real deals. [SPAM URL]",
    images: [],
    status: "rejected",
    moderatorId: "user-admin-user-admin",
    moderatorNote: "Spam content with promotional links",
    rejectionReason: "Contains spam and inappropriate promotional content",
    helpfulCount: 0,
    reportCount: 3,
    verified: false,
    createdAt: new Date("2026-02-04T16:30:00Z"),
    updatedAt: new Date("2026-02-04T17:00:00Z"),
    rejectedAt: new Date("2026-02-04T17:00:00Z"),
  },

  // Review with multiple helpful votes
  {
    id: "review-dell-xps-15-john-20260208",
    productId:
      "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    productTitle: "Roronoa Zoro Enma Slash Diorama 1/7 Scale",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-doe",
    rating: 5,
    title: "Powerful Windows Laptop",
    comment:
      "Excellent build quality and performance. Display is stunning. Perfect for development work.",
    images: ["https://picsum.photos/seed/dell-xps/800/800"],
    status: "approved",
    helpfulCount: 42,
    reportCount: 0,
    verified: false,
    featured: true,
    createdAt: new Date("2026-02-08T20:00:00Z"),
    updatedAt: new Date("2026-02-08T20:00:00Z"),
    approvedAt: new Date("2026-02-08T21:00:00Z"),
  },

  // â”€â”€â”€ Reviews for new products â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "review-oxford-shirt-priya-20260205",
    productId: "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
    productTitle: "Attack on Titan Scout Regiment Cosplay Jacket",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya-sharma",
    rating: 5,
    title: "Bought for my husband \u2014 perfect fit!",
    comment:
      "Ordered the medium and it fits perfectly. The fabric is thick but breathable. The colour is exactly as shown in pictures. Will definitely order more colours.",
    images: ["https://picsum.photos/seed/oxford-shirt/800/800"],
    status: "approved",
    helpfulCount: 18,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-05T10:00:00Z"),
    updatedAt: new Date("2026-02-05T10:00:00Z"),
    approvedAt: new Date("2026-02-05T11:00:00Z"),
  },
  {
    id: "review-oxford-shirt-raj-20260207",
    productId: "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
    productTitle: "Attack on Titan Scout Regiment Cosplay Jacket",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=raj-patel",
    rating: 4,
    title: "Good quality, runs slightly large",
    comment:
      "Nice shirt for the price. I usually wear M but ordered M and it was a bit loose \u2014 would suggest sizing down for a fitted look.",
    images: [],
    status: "approved",
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-07T14:00:00Z"),
    updatedAt: new Date("2026-02-07T14:00:00Z"),
    approvedAt: new Date("2026-02-07T15:00:00Z"),
  },
  {
    id: "review-anarkali-meera-20260210",
    productId: "product-womens-anarkali-kurta-fashion-new-fashionboutique-1",
    productTitle: "Sailor Moon Neo Queen Serenity Cosplay Dress Set",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vikram-nair",
    rating: 5,
    title: "Absolutely stunning \u2014 worth every rupee",
    comment:
      "The embroidery is detailed and the georgette is of premium quality. I wore this to a wedding and got so many compliments. Stitching is clean and the dupatta is beautiful. Deliverd in 3 days!",
    images: [
      "https://picsum.photos/seed/anarkali-kurta/800/800",
      "https://picsum.photos/seed/anarkali-detail/800/800",
    ],
    status: "approved",
    helpfulCount: 34,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: new Date("2026-02-10T18:00:00Z"),
    updatedAt: new Date("2026-02-10T18:00:00Z"),
    approvedAt: new Date("2026-02-10T19:00:00Z"),
  },
  {
    id: "review-pressure-cooker-jane-20260115",
    productId: "product-prestige-pressure-cooker-home-new-homeessentials-1",
    productTitle: "Rem & Ram Re:Zero Nendoroid Duo Set",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane-smith",
    rating: 5,
    title: "Best pressure cooker I've owned",
    comment:
      "The clip-on system makes it so much safer than my old one. Works perfectly on my glass-top induction as well. Cooks dal in 8 minutes flat. Great value for money.",
    images: ["https://picsum.photos/seed/pressure-cooker/800/800"],
    status: "approved",
    helpfulCount: 27,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: new Date("2026-01-15T09:00:00Z"),
    updatedAt: new Date("2026-01-15T09:00:00Z"),
    approvedAt: new Date("2026-01-15T10:00:00Z"),
  },
  {
    id: "review-pressure-cooker-john-20260120",
    productId: "product-prestige-pressure-cooker-home-new-homeessentials-1",
    productTitle: "Rem & Ram Re:Zero Nendoroid Duo Set",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-doe",
    rating: 4,
    title: "Solid product, delivery was fast",
    comment:
      "Great cooker. The only reason for 4 stars is the whistle is a bit loud. Everything else \u2014 build quality, weight, handles \u2014 is excellent.",
    images: [],
    status: "approved",
    helpfulCount: 9,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-20T11:00:00Z"),
    updatedAt: new Date("2026-01-20T11:00:00Z"),
    approvedAt: new Date("2026-01-20T12:00:00Z"),
  },
  {
    id: "review-yoga-mat-priya-20260212",
    productId: "product-premium-yoga-mat-sports-new-sportszone-1",
    productTitle: "Naruto Sage Mode Toad Sage 1/7 Scale PVC Figure",
    userId: "user-priya-sharma-priya",
    userName: "Priya Sharma",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya-sharma",
    rating: 5,
    title: "The alignment lines are a game changer",
    comment:
      "I've used 4 yoga mats over the years and this is by far the best. The grip is excellent even during hot yoga. The alignment marks helped me fix my Warrior II pose. Not cheap but absolutely worth it.",
    images: [
      "https://picsum.photos/seed/yoga-fitness/800/800",
      "https://picsum.photos/seed/yoga-practice/800/800",
    ],
    status: "approved",
    helpfulCount: 45,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-12T08:00:00Z"),
    updatedAt: new Date("2026-02-12T08:00:00Z"),
    approvedAt: new Date("2026-02-12T09:00:00Z"),
  },
  {
    id: "review-yoga-mat-meera-20260214",
    productId: "product-premium-yoga-mat-sports-new-sportszone-1",
    productTitle: "Naruto Sage Mode Toad Sage 1/7 Scale PVC Figure",
    userId: "user-vikram-nair-vikram",
    userName: "Vikram Nair",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vikram-nair",
    rating: 4,
    title: "Premium quality, slightly heavy",
    comment:
      "Love the mat \u2014 grip is outstanding and it doesn't slip at all. The only con is it's heavier than other mats so carrying to class is a bit of a workout itself. But for home use it's perfect.",
    images: [],
    status: "approved",
    helpfulCount: 16,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-14T17:00:00Z"),
    updatedAt: new Date("2026-02-14T17:00:00Z"),
    approvedAt: new Date("2026-02-14T18:00:00Z"),
  },
  {
    id: "review-ipad-pro-mike-20260118",
    productId: "product-apple-ipad-pro-electronics-new-techhub-1",
    productTitle: "Bleach Ichigo Bankai Tensa Zangetsu 1/6 Scale Figure",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-johnson",
    rating: 5,
    title: "Best tablet for creative work",
    comment:
      "Paired with the Apple Pencil, this is an absolute dream for digital illustration. The ProMotion display is silky smooth. Battery lasts all day. Fast delivery and came well packaged.",
    images: ["https://picsum.photos/seed/ipad-tablet/800/800"],
    status: "approved",
    helpfulCount: 52,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-18T14:00:00Z"),
    updatedAt: new Date("2026-01-18T14:00:00Z"),
    approvedAt: new Date("2026-01-18T15:00:00Z"),
  },
  {
    id: "review-galaxy-watch6-john-20260208",
    productId: "product-samsung-galaxy-watch6-electronics-new-techhub-1",
    productTitle: "Samsung Galaxy Watch 6 Classic 47mm",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-doe",
    rating: 5,
    title: "Best Android smartwatch period",
    comment:
      "Switched from Apple Watch and couldn't be happier. The rotating bezel is genius \u2014 much easier than swiping. Health tracking is accurate, sleep analysis is detailed. Battery lasts 2 days.",
    images: ["https://picsum.photos/seed/classic-watch/800/800"],
    status: "approved",
    helpfulCount: 38,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-08T12:00:00Z"),
    updatedAt: new Date("2026-02-08T12:00:00Z"),
    approvedAt: new Date("2026-02-08T13:00:00Z"),
  },
  {
    id: "review-anker-charger-raj-20260205",
    productId: "product-anker-usbc-charger-electronics-new-techhub-1",
    productTitle: "Anker 65W USB-C GaN II Charger",
    userId: "user-raj-patel-rajpatel",
    userName: "Raj Patel",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=raj-patel",
    rating: 5,
    title: "Charges everything I own",
    comment:
      "Charges my laptop, phone, and earbuds simultaneously. The 65W output means my MacBook charges at full speed. The foldable plug is great for travel. Compact and well built.",
    images: ["https://picsum.photos/seed/usb-charger/800/800"],
    status: "approved",
    helpfulCount: 29,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-05T16:00:00Z"),
    updatedAt: new Date("2026-02-05T16:00:00Z"),
    approvedAt: new Date("2026-02-05T17:00:00Z"),
  },

  // â”€â”€ New buyer reviews (Ananya, Pooja, Ravi, Sneha) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "review-iphone15-ananya-20260228",
    productId:
      "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    productTitle: "Dragon Ball Super Saiyan Blue Goku 1/4 Scale Figure",
    userId: "user-ananya-bose-ananya",
    userName: "Ananya Bose",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ananya-bose",
    rating: 5,
    title: "Switched from Android \u2014 no regrets!",
    comment:
      "Finally made the switch and this phone is simply stunning. The titanium frame feels premium, the Action Button is super handy, and the USB-C connection is a lifesaver. The camera does incredible things in low light. Super happy with this purchase.",
    images: ["https://picsum.photos/seed/iphone15/800/800"],
    status: "approved",
    helpfulCount: 21,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-28T09:00:00Z"),
    updatedAt: new Date("2026-02-28T09:00:00Z"),
    approvedAt: new Date("2026-02-28T10:00:00Z"),
  },
  {
    id: "review-kurti-pooja-20260301",
    productId:
      "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    productTitle: "Nezuko Kamado Pink Kimono Hoodie Dress",
    userId: "user-pooja-mehta-pooja",
    userName: "Pooja Mehta",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=pooja-mehta",
    rating: 5,
    title: "Gorgeous \u2014 wore it to my cousin's engagement!",
    comment:
      "Ordered this for a family function and it was the perfect choice. The print is vibrant, the fabric is soft and doesn't crease easily. Sizing was spot on. Got loads of compliments. Will order again!",
    images: [],
    status: "approved",
    helpfulCount: 19,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-03-01T11:00:00Z"),
    updatedAt: new Date("2026-03-01T11:00:00Z"),
    approvedAt: new Date("2026-03-01T12:00:00Z"),
  },
  {
    id: "review-macbook-ravi-20260302",
    productId:
      "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    productTitle: "Monkey D. Luffy Gear 5 Sun God 1/4 Scale Scene Figure",
    userId: "user-ravi-kumar-ravi",
    userName: "Ravi Kumar",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi-kumar",
    rating: 5,
    title: "Monster performance for developers",
    comment:
      "I run Docker, multiple JetBrains IDEs, and local LLM models simultaneously \u2014 this machine handles it all without breaking a sweat. The fan barely spins under normal load. Battery life is insane for a 16-inch. Best developer laptop I've ever owned.",
    images: ["https://picsum.photos/seed/macbook-laptop/800/800"],
    status: "approved",
    helpfulCount: 14,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-03-02T14:00:00Z"),
    updatedAt: new Date("2026-03-02T14:00:00Z"),
    approvedAt: new Date("2026-03-02T15:00:00Z"),
  },
  {
    id: "review-cookware-sneha-20260303",
    productId:
      "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    productTitle: "My Neighbour Totoro Nendoroid No.1234 Deluxe Set",
    userId: "user-sneha-gupta-sneha",
    userName: "Sneha Gupta",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sneha-gupta",
    rating: 4,
    title: "Great everyday cookware set",
    comment:
      "Really happy with this set \u2014 the non-stick coating is genuinely good and the pans heat very evenly. I deducted one star only because the handles get warm after extended cooking. For the price, this is outstanding value. Using it daily for 3 weeks and no issues.",
    images: [],
    status: "approved",
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-03-03T10:00:00Z"),
    updatedAt: new Date("2026-03-03T10:00:00Z"),
    approvedAt: new Date("2026-03-03T11:00:00Z"),
  },
];
