/**
 * Users Seed Data — Anime/Otaku Marketplace Theme
 * Sample user data for development and testing
 */

import type { UserDocument } from "@/db/schema";

export const usersSeedData: Partial<UserDocument>[] = [
  // Admin User
  {
    uid: "user-admin-user-admin",
    email: "admin@letitrip.in",
    phoneNumber: "+919876543210",
    phoneVerified: true,
    displayName: "Admin User",
    photoURL: null,
    avatarMetadata: null,
    role: "admin",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "System Administrator",
    },
    stats: {
      totalOrders: 0,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-09T00:00:00Z"),
      creationTime: new Date("2024-01-01T00:00:00Z").toISOString(),
      loginCount: 150,
    },
  },
  // Regular Users
  {
    uid: "user-john-doe-johndoe",
    email: "john@letitrip.in",
    phoneNumber: "+919876543211",
    phoneVerified: true,
    displayName: "John Doe",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-02-15T08:30:00Z"),
    updatedAt: new Date("2026-02-08T15:20:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
      bio: "Tech enthusiast",
      location: "Mumbai, India",
      website: "https://johndoe.com",
      socialLinks: {
        twitter: "https://twitter.com/johndoe",
        instagram: "https://instagram.com/johndoe",
      },
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 4,
      rating: 4.8,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-08T15:20:00Z"),
      creationTime: new Date("2024-02-15T08:30:00Z").toISOString(),
      loginCount: 45,
    },
  },
  {
    uid: "user-jane-smith-janes",
    email: "jane@letitrip.in",
    phoneNumber: "+919876543212",
    phoneVerified: true,
    displayName: "Jane Smith",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-03-10T10:00:00Z"),
    updatedAt: new Date("2026-02-07T12:30:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
      bio: "Fashion blogger",
      location: "Delhi, India",
      socialLinks: {
        instagram: "https://instagram.com/janesmith",
        facebook: "https://facebook.com/janesmith",
      },
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 6,
      rating: 4.9,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-07T12:30:00Z"),
      creationTime: new Date("2024-03-20T14:00:00Z").toISOString(),
      loginCount: 78,
    },
  },
  {
    uid: "user-mike-johnson-mikejohn",
    email: "mike@letitrip.in",
    phoneNumber: "+919876543213",
    phoneVerified: false,
    displayName: "Mike Johnson",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-04-20T14:15:00Z"),
    updatedAt: new Date("2026-02-05T09:45:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: false,
      bio: "Sports enthusiast",
      location: "Bangalore, India",
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 5,
      rating: 4.5,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-05T09:45:00Z"),
      creationTime: new Date("2024-05-10T10:00:00Z").toISOString(),
      loginCount: 22,
    },
  },
  // Seller Users
  {
    uid: "user-techhub-electronics-electron",
    email: "techhub@letitrip.in",
    phoneNumber: "+919876543214",
    phoneVerified: true,
    displayName: "FigureVault JP",
    photoURL:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=400&fit=crop",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeSlug: "store-techhub-electronics",
    storeStatus: "approved",
    createdAt: new Date("2024-01-15T00:00:00Z"),
    updatedAt: new Date("2026-02-09T08:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: true,
      showPhone: true,
      showOrders: false,
      showWishlist: false,
      bio: "Japan-based premium scale figures dealer — Bandai Spirits, MegaHouse, Kotobukiya and more.",
      location: "Mumbai, India",
      website: "https://figurevaultjp.example.com",
      socialLinks: {
        facebook: "https://facebook.com/figurevaultjp",
        instagram: "https://instagram.com/figurevaultjp",
      },
      storeName: "FigureVault JP",
      storeDescription:
        "Your premier source for authentic anime scale figures, limited editions, and rare collectibles direct from Japan.",
      storeCategory: "electronics",
      storeLogoURL:
        "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=400&fit=crop",
      storeBannerURL:
        "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1600&h=400&fit=crop",
      storeReturnPolicy:
        "7-day hassle-free returns on all items. Figures must be in original sealed packaging for a full refund.",
      storeShippingPolicy:
        "Free shipping on orders above ₹999. Standard delivery in 3-5 business days. Express delivery available.",
    },
    stats: {
      totalOrders: 7,
      auctionsWon: 0,
      itemsSold: 7,
      reviewsCount: 10,
      rating: 4.7,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-09T08:00:00Z"),
      creationTime: new Date("2024-06-01T00:00:00Z").toISOString(),
      loginCount: 210,
    },
  },
  {
    uid: "user-fashion-boutique-fashionb",
    email: "fashion@letitrip.in",
    phoneNumber: "+919876543215",
    phoneVerified: true,
    displayName: "AnimeCraft Apparel",
    photoURL:
      "https://images.unsplash.com/photo-1612810806695-30f7a8258391?w=400&h=400&fit=crop",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeSlug: "store-fashion-boutique",
    storeStatus: "approved",
    createdAt: new Date("2024-02-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T18:30:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: true,
      showPhone: true,
      showOrders: false,
      showWishlist: false,
      bio: "Handcrafted cosplay outfits and anime apparel — Demon Slayer, Sailor Moon, Genshin Impact and more.",
      location: "Delhi, India",
      website: "https://animecraftapparel.example.com",
      socialLinks: {
        instagram: "https://instagram.com/animecraftapparel",
        facebook: "https://facebook.com/animecraftapparel",
      },
      storeName: "AnimeCraft Apparel",
      storeDescription:
        "Crafted cosplay costumes, anime hoodies, graphic tees, and accessories for every otaku.",
      storeCategory: "fashion",
      storeLogoURL:
        "https://images.unsplash.com/photo-1612810806695-30f7a8258391?w=400&h=400&fit=crop",
      storeBannerURL:
        "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1600&h=400&fit=crop",
      storeReturnPolicy:
        "14-day returns on unworn items with original tags attached. Exchange available within 30 days.",
      storeShippingPolicy:
        "Free shipping on all orders above ₹599. Express delivery in 1-2 business days available at checkout.",
    },
    stats: {
      totalOrders: 5,
      auctionsWon: 0,
      itemsSold: 2,
      reviewsCount: 3,
      rating: 4.8,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-08T18:30:00Z"),
      creationTime: new Date("2024-02-01T00:00:00Z").toISOString(),
      loginCount: 195,
    },
  },
  {
    uid: "user-home-essentials-homeesse",
    email: "home@letitrip.in",
    phoneNumber: "+919876543216",
    phoneVerified: true,
    displayName: "OtakuShelf Co",
    photoURL:
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&h=400&fit=crop",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeSlug: "store-home-essentials",
    storeStatus: "approved",
    createdAt: new Date("2024-03-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T16:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: true,
      showPhone: true,
      showOrders: false,
      showWishlist: false,
      bio: "Nendoroid sets, Gunpla kits, and collectible display pieces for the serious anime collector.",
      location: "Pune, India",
      website: "https://otakushelfco.example.com",
      socialLinks: {
        instagram: "https://instagram.com/otakushelfco",
        facebook: "https://facebook.com/otakushelfco",
      },
      storeName: "OtakuShelf Co",
      storeDescription:
        "Nendoroids, Gunpla model kits, dioramas, and shelf-worthy collectibles for anime enthusiasts.",
      storeCategory: "home",
      storeLogoURL:
        "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&h=400&fit=crop",
      storeBannerURL:
        "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1600&h=400&fit=crop",
      storeReturnPolicy:
        "10-day returns accepted on all products. Damaged or defective items replaced at no extra cost.",
      storeShippingPolicy:
        "Free shipping on orders above ₹1499. Fragile items packed securely. Delivery in 3-7 business days.",
    },
    stats: {
      totalOrders: 3,
      auctionsWon: 0,
      itemsSold: 2,
      reviewsCount: 2,
      rating: 4.6,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-08T16:00:00Z"),
      creationTime: new Date("2024-10-01T00:00:00Z").toISOString(),
      loginCount: 142,
    },
  },

  // ─── Moderator ─────────────────────────────────────────────────────────────
  {
    uid: "user-moderator-mod-user",
    email: "moderator@letitrip.in",
    phoneNumber: "+919876543220",
    phoneVerified: true,
    displayName: "Riya Sharma",
    photoURL: null,
    avatarMetadata: null,
    role: "moderator",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-03-01T00:00:00Z"),
    updatedAt: new Date("2026-01-01T00:00:00Z"),
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Content Moderator at LetItRip",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 0, reviewsCount: 0 },
    metadata: {
      lastSignInTime: new Date("2026-02-18T09:00:00Z"),
      creationTime: new Date("2024-03-01T00:00:00Z").toISOString(),
      loginCount: 320,
    },
  },

  // ─── Additional Regular Buyers ─────────────────────────────────────────────
  {
    uid: "user-priya-sharma-priya",
    email: "priya@letitrip.in",
    phoneNumber: "+919876543260",
    phoneVerified: true,
    displayName: "Priya Sharma",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-03-15T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "Shopaholic | Fashion lover",
      location: "Hyderabad, India",
    },
    stats: {
      totalOrders: 9,
      auctionsWon: 1,
      itemsSold: 0,
      reviewsCount: 6,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-19T08:00:00Z"),
      creationTime: new Date("2025-03-15T00:00:00Z").toISOString(),
      loginCount: 74,
    },
  },
  {
    uid: "user-raj-patel-rajpatel",
    email: "raj@letitrip.in",
    phoneNumber: "+919876543270",
    phoneVerified: true,
    displayName: "Raj Patel",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-05-20T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 3,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-12T20:00:00Z"),
      creationTime: new Date("2025-05-20T00:00:00Z").toISOString(),
      loginCount: 29,
    },
  },
  {
    uid: "user-vikram-nair-vikram",
    email: "vikram@letitrip.in",
    phoneNumber: "+919876543280",
    phoneVerified: false,
    displayName: "Vikram Nair",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-08-01T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Beauty & wellness enthusiast",
      location: "Kochi, India",
    },
    stats: {
      totalOrders: 6,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 4,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-15T17:00:00Z"),
      creationTime: new Date("2025-08-01T00:00:00Z").toISOString(),
      loginCount: 41,
    },
  },

  // ── Unverified User — registered but email not yet confirmed ──────────────
  // Tests: email verification flow, /api/auth/verify-email, re-send verification,
  //        locked pages that require emailVerified: true, header badge UI
  {
    uid: "user-unverified-new-user",
    email: "newuser@letitrip.in",
    phoneNumber: null,
    phoneVerified: false,
    displayName: "New User",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: false, // ← critical: email NOT verified
    disabled: false,
    createdAt: new Date("2026-02-28T20:00:00Z"),
    updatedAt: new Date("2026-02-28T20:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
    },
    stats: {
      totalOrders: 0,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-28T20:00:00Z"),
      creationTime: new Date("2026-02-28T20:00:00Z").toISOString(),
      loginCount: 1,
    },
  },

  // ── Phone-Only User — signed up via phone OTP, no email ───────────────────
  // Tests: phone auth flow, profile completion prompt (missing email),
  //        checkout flow without email address
  {
    uid: "user-phone-only-phoneuser",
    email: null, // ← no email address
    phoneNumber: "+919988776655",
    phoneVerified: true,
    displayName: "Phone User",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: false,
    disabled: false,
    createdAt: new Date("2026-02-20T10:00:00Z"),
    updatedAt: new Date("2026-02-20T10:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
    },
    stats: {
      totalOrders: 0,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-20T10:00:00Z"),
      creationTime: new Date("2026-02-20T10:00:00Z").toISOString(),
      loginCount: 3,
    },
  },

  // ── Pending Seller — applied via BecomeSellerView, awaiting admin approval ──
  // Tests: admin review queue (GET /api/admin/stores?storeStatus=pending),
  //        BecomeSellerView success state, seller application flow
  {
    uid: "user-pending-seller-pendingsl",
    email: "pending.seller@letitrip.in",
    phoneNumber: "+919876543282",
    phoneVerified: true,
    displayName: "Pending Seller",
    photoURL: null,
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeStatus: "pending",
    createdAt: new Date("2026-03-10T14:00:00Z"),
    updatedAt: new Date("2026-03-11T09:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Aspiring seller of handmade crafts",
      location: "Jaipur, India",
    },
    stats: {
      totalOrders: 2,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2026-03-11T09:00:00Z"),
      creationTime: new Date("2025-09-01T00:00:00Z").toISOString(),
      loginCount: 12,
    },
  },

  // ── Rejected Seller — application was rejected by admin ───────────────────
  // Tests: admin rejection flow (PATCH /api/admin/stores/[uid] action:"reject"),
  //        GET /api/admin/stores?storeStatus=rejected filter
  {
    uid: "user-rejected-seller-rejectsl",
    email: "rejected.seller@letitrip.in",
    phoneNumber: "+919876543281",
    phoneVerified: false,
    displayName: "Rejected Seller",
    photoURL: null,
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeStatus: "rejected",
    createdAt: new Date("2026-02-01T10:00:00Z"),
    updatedAt: new Date("2026-02-15T16:00:00Z"),
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
    },
    stats: {
      totalOrders: 0,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-15T16:00:00Z"),
      creationTime: new Date("2026-02-01T10:00:00Z").toISOString(),
      loginCount: 5,
    },
  },

  // ─── New Buyers (added to reach 10 total regular users) ───────────────────

  // Buyer 6: Ananya Bose — vintage fashion collector
  {
    uid: "user-ananya-bose-ananya",
    email: "ananya@letitrip.in",
    phoneNumber: "+919876543231",
    phoneVerified: true,
    displayName: "Ananya Bose",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-06-10T09:00:00Z"),
    updatedAt: new Date("2026-03-05T11:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "Vintage fashion collector and auction enthusiast.",
      location: "Kolkata, West Bengal",
    },
    stats: {
      totalOrders: 7,
      auctionsWon: 2,
      itemsSold: 0,
      reviewsCount: 4,
      rating: 4.7,
    },
    ripcoinBalance: 18000,
    engagedRipcoins: 6000,
    metadata: {
      lastSignInTime: new Date("2026-03-05T11:00:00Z"),
      creationTime: new Date("2025-06-10T09:00:00Z").toISOString(),
      loginCount: 55,
    },
  },

  // Buyer 7 already covered by Vikram (uid: user-vikram-nair-vikram above)

  // Buyer 8: Pooja Mehta — home décor buyer
  {
    uid: "user-pooja-mehta-pooja",
    email: "pooja@letitrip.in",
    phoneNumber: "+919876543233",
    phoneVerified: true,
    displayName: "Pooja Mehta",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-08-15T00:00:00Z"),
    updatedAt: new Date("2026-03-02T10:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
      bio: "Home décor enthusiast | Minimalist kitchen.",
      location: "Ahmedabad, Gujarat",
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 3,
    },
    ripcoinBalance: 4000,
    engagedRipcoins: 0,
    metadata: {
      lastSignInTime: new Date("2026-03-02T10:00:00Z"),
      creationTime: new Date("2025-08-15T00:00:00Z").toISOString(),
      loginCount: 24,
    },
  },

  // Buyer 9: Ravi Kumar — fitness & sports buyer
  {
    uid: "user-ravi-kumar-ravi",
    email: "ravi@letitrip.in",
    phoneNumber: "+919876543234",
    phoneVerified: false,
    displayName: "Ravi Kumar",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-09-01T00:00:00Z"),
    updatedAt: new Date("2026-03-03T07:30:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: false,
      bio: "Marathon runner | Cycling & gym.",
      location: "Jaipur, Rajasthan",
    },
    stats: {
      totalOrders: 3,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 2,
    },
    ripcoinBalance: 3000,
    engagedRipcoins: 1500,
    metadata: {
      lastSignInTime: new Date("2026-03-03T07:30:00Z"),
      creationTime: new Date("2025-09-01T00:00:00Z").toISOString(),
      loginCount: 18,
    },
  },

  // Buyer 10: Sneha Gupta — electronics buyer
  {
    uid: "user-sneha-gupta-sneha",
    email: "sneha@letitrip.in",
    phoneNumber: "+919876543235",
    phoneVerified: true,
    displayName: "Sneha Gupta",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2025-10-01T00:00:00Z"),
    updatedAt: new Date("2026-03-05T14:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
      bio: "Software engineer | Gadget geek.",
      location: "Pune, Maharashtra",
    },
    stats: {
      totalOrders: 2,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 1,
    },
    ripcoinBalance: 6000,
    engagedRipcoins: 0,
    metadata: {
      lastSignInTime: new Date("2026-03-05T14:00:00Z"),
      creationTime: new Date("2025-10-01T00:00:00Z").toISOString(),
      loginCount: 15,
    },
  },
];
