export {
  GlobalEventManager,
  globalEventManager,
  throttle,
  debounce,
  addGlobalScrollHandler,
  addGlobalResizeHandler,
  addGlobalClickHandler,
  addGlobalKeyHandler,
  removeGlobalHandler,
  isMobileDevice,
  hasTouchSupport,
  getViewportDimensions,
  isInViewport,
  smoothScrollTo,
  preventBodyScroll,
} from "@mohasinac/utils";
