/**
 * API Route Constants
 *
 * Centralized API endpoint strings for all client-side fetch calls.
 * Prevents scattering of raw "/api/..." strings across components.
 */

export const API_ROUTES = {
  AUTH: {
    LOGOUT: "/api/auth/logout",
  },
  NEWSLETTER: {
    SUBSCRIBE: "/api/newsletter/subscribe",
  },
  DEMO: {
    SEED: "/api/demo/seed",
  },
  ADS: {
    BY_SLOT: (slotId: string) => `/api/ads?slot=${encodeURIComponent(slotId)}`,
  },
  AUCTIONS: {
    BUY_NOW: (id: string) => `/api/auctions/${id}/buy-now`,
  },
  BRANDS: {
    LIST: "/api/brands",
    BY_ID: (id: string) => `/api/brands/${id}`,
  },
  EVENTS: {
    LIST: "/api/events",
    BY_ID: (id: string) => `/api/events/${id}`,
    ENTRIES: (id: string) => `/api/events/${id}/entries`,
    LEADERBOARD: (id: string, limit?: number) =>
      `/api/events/${id}/leaderboard${limit !== undefined ? `?limit=${limit}` : ""}`,
    // SB9-E spin assignment (user-authenticated)
    SPIN: (id: string) => `/api/events/${id}/spin`,
  },
  ADMIN: {
    USERS: "/api/admin/users",
    USER_BY_ID: (uid: string) => `/api/admin/users/${uid}`,
    STORES: "/api/admin/stores",
    STORE_BY_ID: (uid: string) => `/api/admin/stores/${uid}`,
    BRANDS: "/api/admin/brands",
    BRAND_BY_ID: (id: string) => `/api/admin/brands/${id}`,
    ORDERS: "/api/admin/orders",
    ORDER_BY_ID: (id: string) => `/api/admin/orders/${id}`,
    ORDER_REFUND: (id: string) => `/api/admin/orders/${id}/refund`,
    PRODUCTS: "/api/admin/products",
    // SB-UNI-4 2026-05-13 — admin CRUD for categoryType:"bundle" rows.
    BUNDLES: "/api/admin/bundles",
    BUNDLE_BY_ID: (id: string) => `/api/admin/bundles/${id}`,
    BUNDLE_REBUILD: (id: string) => `/api/admin/bundles/${id}/rebuild`,
    PRODUCT_BY_ID: (id: string) => `/api/admin/products/${id}`,
    CATEGORIES: "/api/admin/categories",
    CATEGORY_BY_ID: (id: string) => `/api/admin/categories/${id}`,
    BLOG: "/api/admin/blog",
    BLOG_BY_ID: (id: string) => `/api/admin/blog/${id}`,
    FAQS: "/api/admin/faqs",
    FAQ_BY_ID: (id: string) => `/api/admin/faqs/${id}`,
    REVIEWS: "/api/admin/reviews",
    REVIEW_BY_ID: (id: string) => `/api/admin/reviews/${id}`,
    BIDS: "/api/admin/bids",
    BID_BY_ID: (id: string) => `/api/admin/bids/${id}`,
    COUPONS: "/api/admin/coupons",
    COUPON_BY_ID: (id: string) => `/api/admin/coupons/${id}`,
    CAROUSEL: "/api/admin/carousel",
    CAROUSEL_BY_ID: (id: string) => `/api/admin/carousel/${id}`,
    SECTIONS: "/api/admin/sections",
    SECTION_BY_ID: (id: string) => `/api/admin/sections/${id}`,
    ADS: "/api/admin/ads",
    AD_BY_ID: (id: string) => `/api/admin/ads/${id}`,
    EVENTS: "/api/admin/events",
    EVENT_BY_ID: (id: string) => `/api/admin/events/${id}`,
    // SB9-D — admin manual raffle trigger
    EVENT_TRIGGER_RAFFLE: (id: string) => `/api/admin/events/${id}/trigger-raffle`,
    NEWSLETTER: "/api/admin/newsletter",
    NEWSLETTER_BY_ID: (id: string) => `/api/admin/newsletter/${id}`,
    CONTACT_SUBMISSIONS: "/api/admin/contact-submissions",
    CONTACT_SUBMISSION_BY_ID: (id: string) => `/api/admin/contact-submissions/${id}`,
    PAYOUTS: "/api/admin/payouts",
    PAYOUT_BY_ID: (id: string) => `/api/admin/payouts/${id}`,
    ANALYTICS: "/api/admin/analytics",
    DASHBOARD: "/api/admin/dashboard",
    SITE_SETTINGS: "/api/admin/site-settings",
    SUBLISTING_CATEGORIES: "/api/admin/sublisting-categories",
    SUBLISTING_CATEGORY_BY_ID: (id: string) => `/api/admin/sublisting-categories/${id}`,
    ADDRESSES: "/api/admin/addresses",
    ADDRESS_BY_ID: (id: string) => `/api/admin/addresses/${id}`,
    // S-STORE Tier — admin moderation + reports + item requests + RBAC
    MODERATION_QUEUE: "/api/admin/moderation",
    MODERATION_BY_ID: (id: string) => `/api/admin/moderation/${id}`,
    REPORTS: "/api/admin/reports",
    REPORT_BY_ID: (id: string) => `/api/admin/reports/${id}`,
    ITEM_REQUESTS: "/api/admin/item-requests",
    ITEM_REQUEST_BY_ID: (id: string) => `/api/admin/item-requests/${id}`,
    ADMIN_ANALYTICS_CARDS: "/api/admin/analytics/cards",
    ADMIN_ANALYTICS_CARD_BY_ID: (id: string) => `/api/admin/analytics/cards/${id}`,
    ADMIN_ANALYTICS_ALERTS: "/api/admin/analytics/alerts",
    ADMIN_ANALYTICS_ALERT_BY_ID: (id: string) => `/api/admin/analytics/alerts/${id}`,
    ROLES: "/api/admin/roles",
    ROLE_BY_ID: (id: string) => `/api/admin/roles/${id}`,
    ADMIN_NOTIFICATIONS: "/api/admin/admin-notifications",
  },
  SUBLISTING_CATEGORIES: {
    BY_SLUG: (slug: string) => `/api/sublisting-categories/${slug}`,
    LISTINGS: (slug: string) => `/api/sublisting-categories/${slug}/listings`,
  },
  STORE: {
    PRODUCTS: "/api/store/products",
    ORDERS: "/api/store/orders",
    ORDER_BY_ID: (id: string) => `/api/store/orders/${id}`,
    COUPONS: "/api/store/coupons",
    COUPON_BY_ID: (id: string) => `/api/store/coupons/${id}`,
    STOREFRONT: "/api/store/storefront",
    SHIPPING: "/api/store/shipping",
    PAYOUT_SETTINGS: "/api/store/payout-settings",
    ANALYTICS: "/api/store/analytics",
    WHATSAPP_SETTINGS: "/api/store/whatsapp-settings",
    WHATSAPP_CATALOG_SYNC: "/api/store/whatsapp-settings/catalog-sync",
    REVIEWS: "/api/store/reviews",
    REVIEW_REPLY: (id: string) => `/api/store/reviews/${id}/reply`,
    PAYOUTS: "/api/store/payouts",
    PAYOUTS_REQUEST: "/api/store/payouts/request",
    ADDRESSES: "/api/store/addresses",
    ADDRESS_BY_ID: (id: string) => `/api/store/addresses/${id}`,
    BIDS: "/api/store/bids",
    SUBLISTING_CATEGORIES: "/api/store/sublisting-categories",
    SUBLISTING_CATEGORY_BY_ID: (id: string) => `/api/store/sublisting-categories/${id}`,
    PRODUCT_GROUP: (id: string) => `/api/store/products/${id}/group`,
    PRODUCT_GROUP_CHILDREN: (id: string) => `/api/store/products/${id}/group/children`,
    PRODUCT_GROUP_CHILD: (id: string, childId: string) => `/api/store/products/${id}/group/children/${childId}`,
    // SB-UNI-N — digital-code pool management (Z1)
    PRODUCT_CODES: (id: string) => `/api/store/products/${id}/codes`,
    PRODUCTS_BULK_LOCATION: "/api/store/products/bulk-location",
    ORDERS_BULK_LOCATION: "/api/store/orders/bulk-location",
    TEMPLATES: "/api/store/templates",
    TEMPLATE_BY_ID: (id: string) => `/api/store/templates/${id}`,
    PROFILE: "/api/store/profile",
    SLUG_CHECK: (slug: string) => `/api/store/slug/check?slug=${encodeURIComponent(slug)}`,
    // S-STORE Tier — extension endpoints
    PAYOUT_METHODS: "/api/store/payout-methods",
    PAYOUT_METHOD_BY_ID: (id: string) => `/api/store/payout-methods/${id}`,
    SHIPPING_CONFIGS: "/api/store/shipping-configs",
    SHIPPING_CONFIG_BY_ID: (id: string) => `/api/store/shipping-configs/${id}`,
    ANALYTICS_CARDS: "/api/store/analytics/cards",
    ANALYTICS_CARD_BY_ID: (id: string) => `/api/store/analytics/cards/${id}`,
    ANALYTICS_ALERTS: "/api/store/analytics/alerts",
    ANALYTICS_ALERT_BY_ID: (id: string) => `/api/store/analytics/alerts/${id}`,
    STORE_CATEGORIES: "/api/store/categories",
    STORE_CATEGORY_BY_ID: (id: string) => `/api/store/categories/${id}`,
    LISTING_TEMPLATES: "/api/store/listing-templates",
    LISTING_TEMPLATE_BY_ID: (id: string) => `/api/store/listing-templates/${id}`,
    GROUPED_LISTINGS: "/api/store/grouped-listings",
    GROUPED_LISTING_BY_ID: (id: string) => `/api/store/grouped-listings/${id}`,
    GOOGLE_REVIEWS: "/api/store/google-reviews",
    GOOGLE_REVIEWS_SYNC: "/api/store/google-reviews/sync",
  },
  PRODUCTS: {
    GROUP: (groupId: string) => `/api/products/group/${groupId}`,
  },
  SCAMS: {
    REPORTS: "/api/scams/reports",
  },
  // SB1-K — bundles + prize draws (additive; route handlers land in later SB sessions)
  BUNDLES: {
    LIST: "/api/bundles",
    BY_ID: (id: string) => `/api/bundles/${id}`,
  },
  PRIZE_DRAWS: {
    LIST: "/api/prize-draws",
    BY_ID: (id: string) => `/api/prize-draws/${id}`,
    REVEAL: (id: string) => `/api/prize-draws/${id}/reveal`,
  },
  ORDERS: {
    // SB-UNI-N — reveal a digital code for a confirmed order
    CODE: (id: string) => `/api/orders/${id}/code`,
  },
  USER: {
    PROFILE: "/api/user/profile",
    ADDRESSES: "/api/user/addresses",
    ADDRESS_BY_ID: (id: string) => `/api/user/addresses/${id}`,
    ORDERS: "/api/user/orders",
    ORDER_BY_ID: (id: string) => `/api/user/orders/${id}`,
    WISHLIST: "/api/user/wishlist",
    WISHLIST_ITEM: (productId: string) => `/api/user/wishlist/${productId}`,
    NOTIFICATIONS: "/api/user/notifications",
    NOTIFICATION_BY_ID: (id: string) => `/api/user/notifications/${id}`,
    NOTIFICATIONS_READ_ALL: "/api/user/notifications/read-all",
    NOTIFICATION_PREFERENCES: "/api/user/notification-preferences",
    CHANGE_PASSWORD: "/api/user/change-password",
    OFFERS: "/api/user/offers",
    EVENTS: "/api/user/events",
  },
} as const;
