/**
 * UI Labels — Admin (Part 2 of 4)
 *
 * Split from ui.ts to avoid Turbopack chunk-generation failure
 * (EcmascriptModuleContent::new_merged error in Next.js 16 Turbopack when
 * a single file contains a large deeply-nested `as const` object).
 *
 * Do NOT import directly — use `UI_LABELS` from `@/constants`.
 */

export const _UI_LABELS_ADMIN = {
  // Admin content management
  ADMIN: {
    // View mode labels
    TABLE_VIEW: "Table",
    GRID_VIEW: "Grid",
    LIST_VIEW: "List",

    DASHBOARD: {
      TITLE: "Dashboard Overview",
      SUBTITLE: "System statistics and quick actions",
      QUICK_ACTIONS: "Quick Actions",
      RECENT_ACTIVITY: "Recent Activity",
      STATS: "Statistics",
      MANAGE_USERS: "Manage Users",
      REVIEW_DISABLED: "Review Disabled Accounts",
      MANAGE_CONTENT: "Manage Content",
      NEW_USERS: "New Users",
      SYSTEM_STATUS: "System Status",
      ALL_SYSTEMS_OPERATIONAL: "All systems operational",
      NEW_USERS_REGISTERED: (count: number) =>
        `${count} new ${count === 1 ? "user" : "users"} registered in the last 30 days`,
    },
    STATS: {
      TOTAL_USERS: "Total Users",
      ACTIVE_USERS: "Active Users",
      NEW_USERS: "New Users",
      DISABLED_USERS: "Disabled Accounts",
      TOTAL_PRODUCTS: "Total Products",
      TOTAL_ORDERS: "Total Orders",
      // Seller stats
      TOTAL_LISTINGS: "Total Listings",
      ACTIVE_LISTINGS: "Active Listings",
      ACTIVE_AUCTIONS: "Active Auctions",
      DRAFT_PRODUCTS: "Drafts",
    },
    USERS: {
      TITLE: "Users",
      SUBTITLE: "Manage user accounts and permissions",
      DETAIL: "User Details",
      ALL: "All Users",
      ACTIVE: "Active",
      BANNED: "Banned",
      ADMINS: "Admins",
      SEARCH_PLACEHOLDER: "Search by name or email...",
      BAN_USER: "Ban User",
      UNBAN_USER: "Unban User",
      DELETE_USER: "Delete User",
      CHANGE_ROLE: "Change Role",
      NO_USERS_FOUND: "No users found",
      TOTAL_USERS: "Total Users",
      ACTIVE_USERS: "Active Users",
      BANNED_USERS: "Banned Users",
      ADMIN_USERS: "Admin Users",
      ROLE_UPDATE_FAILED: "Failed to update user role",
      BAN_FAILED: "Failed to update user ban status",
      DELETE_FAILED: "Failed to delete user",
      CONFIRM_ROLE_CHANGE: "Change role to",
      CONFIRM_BAN: "Are you sure you want to ban this user?",
      CONFIRM_UNBAN: "Are you sure you want to unban this user?",
      CONFIRM_DELETE:
        "PERMANENTLY DELETE this user? This action cannot be undone.",
      TYPE_DELETE_CONFIRM: 'Type "DELETE" to confirm:',
    },
    SITE: {
      TITLE: "Site Settings",
      SUBTITLE: "Configure global site settings, branding, and appearance",
      GENERAL: "General Settings",
      SEO: "SEO Settings",
      SECURITY: "Security Settings",
      SAVE_SETTINGS: "Save Settings",
      SAVE_ALL_CHANGES: "Save All Changes",
      SETTINGS_SAVED: "Settings saved successfully",
      SETTINGS_FAILED: "Failed to save settings",
      BASIC_INFO: "Basic Information",
      SITE_NAME: "Site Name",
      MOTTO: "Motto / Tagline",
      CONTACT_INFO: "Contact Information",
      SUPPORT_EMAIL: "Support Email",
      SUPPORT_PHONE: "Support Phone",
      ADDRESS: "Address",
      SOCIAL_LINKS: "Social Media Links",
      FACEBOOK: "Facebook",
      TWITTER: "Twitter",
      INSTAGRAM: "Instagram",
      LINKEDIN: "LinkedIn",
      CREDENTIALS_TITLE: "Provider Credentials",
      CREDENTIALS_SUBTITLE:
        "API keys and secrets are encrypted with AES-256-GCM before storage. Leave a field blank to keep the existing value. Keys are never shown in plain text.",
      RAZORPAY_SECTION: "Razorpay",
      RAZORPAY_KEY_ID: "Razorpay Key ID",
      RAZORPAY_KEY_SECRET: "Razorpay Key Secret",
      RAZORPAY_WEBHOOK_SECRET: "Razorpay Webhook Secret",
      RESEND_SECTION: "Resend (Email)",
      RESEND_API_KEY: "Resend API Key",
      WHATSAPP_SECTION: "WhatsApp Business API",
      WHATSAPP_API_KEY: "WhatsApp API Key",
      WHATSAPP_NUMBER: "WhatsApp Contact Number",
      CREDENTIAL_PLACEHOLDER: (masked: string) =>
        masked ? `Current: ${masked} — leave blank to keep` : "Paste new value",
      CREDENTIAL_SET: "Saved ✔",
      CREDENTIAL_NOT_SET: "Not configured",
    },
    CAROUSEL: {
      TITLE: "Carousel Management",
      SUBTITLE: "Manage homepage carousel slides (max 5 active)",
      ADD_SLIDE: "Add Slide",
      CREATE_SLIDE: "Create Carousel Slide",
      EDIT_SLIDE: "Edit Carousel Slide",
      DELETE_SLIDE: "Delete Carousel Slide",
      REORDER_SLIDES: "Reorder Slides",
      NO_SLIDES: "No slides found",
      SAVE_FAILED: "Failed to save slide",
      DELETE_FAILED: "Failed to delete slide",
    },
    CATEGORIES: {
      TITLE: "Categories",
      SUBTITLE: "Manage product categories hierarchy",
      ADD_CATEGORY: "Add Category",
      CREATE_CATEGORY: "Create Category",
      EDIT_CATEGORY: "Edit Category",
      DELETE_CATEGORY: "Delete Category",
      NO_CATEGORIES: "No categories found",
      SAVE_FAILED: "Failed to save category",
      DELETE_FAILED: "Failed to delete category",
      CANNOT_DELETE_WITH_CHILDREN:
        "Cannot delete category with subcategories. Delete children first.",
      CANNOT_DELETE_WITH_PRODUCTS:
        "Cannot delete category with products/auctions. Move them first.",
      PARENT_CATEGORY: "Parent Category",
      NONE_ROOT: "None (Root Category)",
      SHOW_ON_HOMEPAGE: "Show on Homepage",
      ENABLED: "Enabled",
      IS_BRAND: "Brand Category",
      TREE_VIEW: "Tree",
      TABLE_VIEW: "Table",
      COL_SLUG: "Slug",
      COL_PRODUCTS: "Products",
    },
    FAQS: {
      TITLE: "FAQs",
      SUBTITLE: "Manage frequently asked questions",
      ADD_FAQ: "Add FAQ",
      CREATE_FAQ: "Create FAQ",
      EDIT_FAQ: "Edit FAQ",
      DELETE_FAQ: "Delete FAQ",
      NO_FAQS: "No FAQs found",
      SAVE_FAILED: "Failed to save FAQ",
      DELETE_FAILED: "Failed to delete FAQ",
      CATEGORY: "Category",
      QUESTION: "Question",
      ANSWER: "Answer",
      PRIORITY: "Priority",
      PRIORITY_HELP: "Higher priority appears first",
      FEATURED: "Featured",
      FEATURED_LABEL: "Featured (show on homepage)",
      TAGS: "Tags (comma-separated)",
      TAGS_PLACEHOLDER: "e.g. payment, refund, shipping",
      ORDER_HELP: "Display order within same priority",
      SHOW_VARIABLES: "Show Variables",
      HIDE_VARIABLES: "Hide Variables",
      INSERT_VARIABLE_HELP: "Click to insert variable into answer:",
      SEARCH_PLACEHOLDER: "Search FAQs...",
      COL_VIEWS: "Views",
      COL_HELPFUL: "Helpful",
    },
    SECTIONS: {
      TITLE: "Homepage Sections",
      SUBTITLE: "Manage homepage sections and their order",
      ADD_SECTION: "Add Section",
      CREATE_SECTION: "Create Section",
      EDIT_SECTION: "Edit Section",
      DELETE_SECTION: "Delete Section",
      REORDER_SECTIONS: "Reorder Sections",
      NO_SECTIONS: "No sections found",
      SAVE_FAILED: "Failed to save section",
      DELETE_FAILED: "Failed to delete section",
      SECTION_TYPE: "Section Type",
      SECTION_ORDER: "Display Order",
      CONFIGURATION: "Configuration (JSON)",
    },
    REVIEWS: {
      TITLE: "Reviews",
      SUBTITLE: "Moderate product reviews",
      VIEW: "View Reviews",
      REVIEW_DETAILS: "Review Details",
      BACK_TO_LIST: "Back to List",
      APPROVE: "Approve",
      REJECT: "Reject",
      DELETE: "Delete",
      APPROVE_ALL: "Approve All Pending",
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      NO_REVIEWS: "No reviews found",
      REJECTION_REASON: "Rejection Reason",
      APPROVE_FAILED: "Failed to approve review",
      REJECT_FAILED: "Failed to reject review",
      DELETE_FAILED: "Failed to delete review",
      NO_PENDING: "No pending reviews to approve",
      VERIFIED: "Verified",
      VERIFIED_PURCHASE: "Verified Purchase",
      HELPFUL_VOTES: "Helpful Votes",
      PRODUCT: "Product",
      USER: "User",
      COMMENT: "Comment",
      RATING: "Rating",
      CREATED: "Created",
      ALL_RATINGS: "All Ratings",
      SEARCH_PLACEHOLDER: "Search products, users...",
      COL_HELPFUL: "Helpful",
    },
    PRODUCTS: {
      TITLE: "Products",
      SUBTITLE: "Manage all product listings",
      CREATE_PRODUCT: "Create Product",
      EDIT_PRODUCT: "Edit Product",
      DELETE_PRODUCT: "Delete Product",
      NO_PRODUCTS: "No products found",
      SAVE_FAILED: "Failed to save product",
      DELETE_FAILED: "Failed to delete product",
      TITLE_LABEL: "Title",
      DESCRIPTION_LABEL: "Description",
      CATEGORY_LABEL: "Category",
      SUBCATEGORY_LABEL: "Subcategory",
      BRAND_LABEL: "Brand",
      PRICE_LABEL: "Price (₹)",
      STOCK_LABEL: "Stock Quantity",
      STATUS_LABEL: "Status",
      SEARCH_PLACEHOLDER: "Search products...",
      FILTER_ALL: "All Statuses",
      SELLER_LABEL: "Seller",
      FEATURED_LABEL: "Featured",
      TAGS_LABEL: "Tags (comma-separated)",
      TAGS_PLACEHOLDER: "e.g. electronics, gadgets, sale",
      SHIPPING_LABEL: "Shipping Info",
      RETURN_POLICY_LABEL: "Return Policy",
      IS_AUCTION_LABEL: "Is Auction",
      AUCTION_END_DATE_LABEL: "Auction End Date",
      STARTING_BID_LABEL: "Starting Bid (₹)",
      IS_PROMOTED_LABEL: "Is Promoted",
      MAIN_IMAGE_LABEL: "Main Image URL",
      CONFIRM_DELETE:
        "Are you sure you want to delete this product? This cannot be undone.",
      PICKUP_ADDRESS: "Pickup Address",
    },
    ORDERS: {
      TITLE: "Orders",
      SUBTITLE: "Manage all orders",
      VIEW: "View Orders",
      DETAILS: "Order Details",
      APPROVE: "Approve Order",
      REJECT: "Reject Order",
      ICON: "🛒",
      UPDATE_STATUS: "Update Status",
      FILTER_ALL: "All Orders",
      TRACKING_NUMBER: "Tracking Number",
      NOTES: "Admin Notes",
      UPDATE_ORDER: "Update Order",
      CANCELLATION_REASON: "Cancellation Reason",
    },
    BIDS: {
      TITLE: "Auctions & Bids",
      SUBTITLE: "Monitor all auction bids across the platform",
      ICON: "🏆",
      FILTER_ALL: "All Bids",
      FILTER_ACTIVE: "Active",
      FILTER_WON: "Won",
      FILTER_OUTBID: "Outbid",
      FILTER_CANCELLED: "Cancelled",
      BIDDER: "Bidder",
      PRODUCT: "Product",
      BID_AMOUNT: "Bid Amount",
      BID_DATE: "Bid Date",
      STATUS: "Status",
      WINNING: "Winning",
      VIEW_PRODUCT: "View Product",
      EMPTY: "No bids found",
      EMPTY_SUBTITLE: "No auction bids match your current filters.",
      TOTAL_BIDS: "Total Bids",
      ACTIVE_BIDS: "Active Bids",
      WON_BIDS: "Won Bids",
      TOTAL_VALUE: "Total Bid Value",
    },
    BLOG: {
      TITLE: "Blog Posts",
      SUBTITLE: "Manage blog content and articles",
      ICON: "📝",
      CREATE: "New Post",
      EDIT: "Edit Post",
      DELETE: "Delete Post",
      PUBLISH: "Publish",
      UNPUBLISH: "Unpublish to Draft",
      ARCHIVE: "Archive",
      EMPTY: "No blog posts found",
      EMPTY_SUBTITLE: "Create your first blog post to get started.",
      FILTER_ALL: "All Posts",
      FILTER_DRAFT: "Drafts",
      FILTER_PUBLISHED: "Published",
      FILTER_ARCHIVED: "Archived",
      FORM_TITLE: "Title",
      FORM_SLUG: "Slug",
      FORM_EXCERPT: "Excerpt",
      FORM_CONTENT: "Content",
      FORM_COVER: "Cover Image URL",
      FORM_CATEGORY: "Category",
      FORM_TAGS: "Tags (comma-separated)",
      FORM_STATUS: "Status",
      FORM_FEATURED: "Featured Post",
      FORM_READ_TIME: "Read Time (minutes)",
      TOTAL_POSTS: "Total Posts",
      PUBLISHED_POSTS: "Published",
      DRAFT_POSTS: "Drafts",
      FEATURED_POSTS: "Featured",
      VIEWS: "Views",
      READ_TIME: "min read",
      AUTHOR: "Author",
      PUBLISHED_ON: "Published on",
      TAGS: "Tags",
      RELATED: "Related Articles",
    },
    COUPONS: {
      TITLE: "Coupons",
      SUBTITLE: "Manage discount coupons",
      ICON: "🏷️",
      CREATE: "Create Coupon",
      EDIT: "Edit Coupon",
      DELETE: "Delete Coupon",
      DEACTIVATE: "Deactivate",
      REACTIVATE: "Reactivate",
      NO_COUPONS: "No coupons found",
      DISCOUNT_FREE_SHIPPING: "Free shipping",
      DISCOUNT_BXGY: "BXGY",
      USAGE_HEADER: "Usage",
      USAGE_SUFFIX: " uses",
      STATUS_HEADER: "Status",
      STATUS_EXPIRED: "Expired",
      STATUS_ACTIVE: "Active",
      STATUS_INACTIVE: "Inactive",
      DISCOUNT_HEADER: "Discount",
      CODE_LABEL: "Coupon Code",
      NAME_LABEL: "Name",
      DESCRIPTION_LABEL: "Description",
      TYPE_LABEL: "Coupon Type",
      DISCOUNT_LABEL: "Discount Value",
      MAX_DISCOUNT_LABEL: "Max Discount (optional)",
      MIN_PURCHASE_LABEL: "Min Purchase Amount (optional)",
      TOTAL_LIMIT_LABEL: "Total Usage Limit (optional)",
      PER_USER_LIMIT_LABEL: "Per-User Limit (optional)",
      START_DATE_LABEL: "Start Date",
      END_DATE_LABEL: "End Date (optional)",
      IS_ACTIVE_LABEL: "Active",
      FIRST_TIME_ONLY_LABEL: "First-Time Users Only",
      STATS: "Usage Stats",
      SEARCH_PLACEHOLDER: "Search by code or name...",
    },
    PAYOUTS: {
      TITLE: "Payouts",
      SUBTITLE: "Review and process seller payout requests",
      ICON: "💳",
      FILTER_ALL: "All Payouts",
      FILTER_PENDING: "Pending",
      FILTER_PROCESSING: "Processing",
      FILTER_COMPLETED: "Completed",
      FILTER_FAILED: "Failed",
      SELLER: "Seller",
      AMOUNT: "Net Amount",
      GROSS_AMOUNT: "Gross Amount",
      PLATFORM_FEE: "Platform Fee",
      METHOD: "Payment Method",
      STATUS: "Status",
      REQUESTED: "Requested",
      PROCESSED: "Processed",
      ORDERS_COUNT: "Orders",
      ADMIN_NOTE: "Admin Note (optional)",
      UPDATE_STATUS: "Update Payout Status",
      UPDATE_PAYOUT: "Update Payout",
      EMPTY: "No payout requests",
      EMPTY_SUBTITLE: "Seller payout requests will appear here.",
      TOTAL_PENDING: "Total Pending",
      TOTAL_PAID_MONTH: "Paid This Month",
      FAILURE_COUNT: "Failed This Month",
      STATUS_PENDING: "Pending",
      STATUS_PROCESSING: "Processing",
      STATUS_COMPLETED: "Completed",
      STATUS_FAILED: "Failed",
      PAYMENT_METHOD_BANK: "Bank Transfer",
      PAYMENT_METHOD_UPI: "UPI",
      BANK_DETAILS: "Bank Details",
      UPI_ID: "UPI ID",
      ACCOUNT_MASKED: "Account",
      IFSC: "IFSC",
    },
    SESSIONS: {
      TITLE: "Sessions",
      SUBTITLE: "Manage user sessions",
      CONFIRM_REVOKE: "Revoke Session",
      CONFIRM_REVOKE_MESSAGE:
        "Are you sure you want to revoke this session? The user will be logged out.",
      CONFIRM_REVOKE_ALL: "Revoke All Sessions",
      CONFIRM_REVOKE_ALL_MESSAGE:
        "Are you sure you want to revoke all sessions? All users will be logged out.",
      COL_USER: "User",
      COL_DEVICE: "Device",
      COL_LOCATION: "Location",
      COL_LAST_ACTIVE: "Last Active",
    },
    NEWSLETTER: {
      TITLE: "Newsletter Subscribers",
      SUBTITLE: "Manage email newsletter subscriptions",
      ICON: "📧",
      TOTAL_SUBSCRIBERS: "Total Subscribers",
      ACTIVE_SUBSCRIBERS: "Active Subscribers",
      UNSUBSCRIBED: "Unsubscribed",
      SOURCE_BREAKDOWN: "Source Breakdown",
      FILTER_ALL: "All Subscribers",
      FILTER_ACTIVE: "Active",
      FILTER_UNSUBSCRIBED: "Unsubscribed",
      UNSUBSCRIBE_ACTION: "Unsubscribe",
      RESUBSCRIBE_ACTION: "Resubscribe",
      DELETE_ACTION: "Delete",
      CONFIRM_UNSUBSCRIBE: "Mark this subscriber as unsubscribed?",
      CONFIRM_DELETE:
        "Permanently delete this subscriber record? This cannot be undone.",
      EMPTY: "No subscribers found",
      EMPTY_SUBTITLE: "Newsletter subscribers will appear here.",
      COLUMN_EMAIL: "Email",
      COLUMN_STATUS: "Status",
      COLUMN_SOURCE: "Source",
      COLUMN_SUBSCRIBED: "Subscribed",
      COLUMN_UNSUBSCRIBED_AT: "Unsubscribed",
      COLUMN_ACTIONS: "Actions",
      SEARCH_PLACEHOLDER: "Search by email...",
    },
    EVENTS: {
      TITLE: "Events",
      SUBTITLE: "Manage sales, offers, polls, surveys, and feedback campaigns",
      NEW: "New Event",
      EDIT: "Edit Event",
      DELETE: "Delete Event",
      ENTRIES: "Entries",
      REVIEW_ENTRY: "Review Entry",
      APPROVE: "Approve",
      FLAG: "Flag",
      LEADERBOARD: "Leaderboard",
      ADD_FIELD: "Add field",
      PREVIEW_FORM: "Preview Form",
      END_EVENT: "End Event",
      ACTIVATE: "Activate",
      PAUSE: "Pause",
      NO_EVENTS: "No events found",
      CONFIRM_DELETE:
        "Permanently delete this event? This will also remove all entries.",
    },
    CONTENT: {
      TITLE: "Content Management",
      SUBTITLE: "Manage products, orders, and reviews",
      PRODUCTS: {
        TITLE: "Products",
        SUBTITLE: "Manage all product listings",
        VIEW: "View Products",
        CREATE: "Create Product",
        EDIT: "Edit Product",
        DELETE: "Delete Product",
        ICON: "📦",
      },
      ORDERS: {
        TITLE: "Orders",
        SUBTITLE: "Manage all orders",
        VIEW: "View Orders",
        DETAILS: "Order Details",
        APPROVE: "Approve Order",
        REJECT: "Reject Order",
        ICON: "🛒",
        UPDATE_STATUS: "Update Status",
        FILTER_ALL: "All Orders",
        TRACKING_NUMBER: "Tracking Number",
        NOTES: "Admin Notes",
        UPDATE_ORDER: "Update Order",
        CANCELLATION_REASON: "Cancellation Reason",
      },
      REVIEWS: {
        TITLE: "Reviews",
        SUBTITLE: "Moderate user reviews",
        VIEW: "View Reviews",
        APPROVE: "Approve Review",
        REJECT: "Reject Review",
        DELETE: "Delete Review",
        ICON: "⭐",
      },
      COMING_SOON: {
        TITLE: "Content Management Coming Soon",
        MESSAGE:
          "Advanced content management features are currently under development",
        ICON: "🚧",
      },
    },
    MEDIA: {
      TITLE: "Media Operations",
      SUBTITLE: "Manage image cropping and video trimming",
      CROP_IMAGE: "Crop Image",
      TRIM_VIDEO: "Trim Video",
      SOURCE_URL: "Source URL",
      SOURCE_URL_PLACEHOLDER: "https://example.com/image.jpg",
      OUTPUT_FORMAT: "Output Format",
      QUALITY: "Quality",
      QUALITY_HIGH: "High (90)",
      QUALITY_MEDIUM: "Medium (75)",
      QUALITY_LOW: "Low (60)",
      CROP_PARAMETERS: "Crop Parameters",
      X_POSITION: "X Position",
      Y_POSITION: "Y Position",
      WIDTH: "Width",
      HEIGHT: "Height",
      TRIM_PARAMETERS: "Trim Parameters",
      START_TIME: "Start Time (seconds)",
      END_TIME: "End Time (seconds)",
      VIDEO_QUALITY: "Video Quality",
      QUALITY_LOW_LABEL: "Low (500k/64k)",
      QUALITY_MEDIUM_LABEL: "Medium (1000k/128k)",
      QUALITY_HIGH_LABEL: "High (2500k/192k)",
      RECENT_OPERATIONS: "Recent Operations",
      NO_OPERATIONS: "No media operations yet",
      OPERATION_TYPE: "Operation Type",
      OPERATION_STATUS: "Status",
      PROCESSING: "Processing",
      COMPLETED: "Completed",
      FAILED: "Failed",
      DOWNLOAD_RESULT: "Download Result",
      COPY_URL: "Copy URL",
      URL_COPIED: "URL copied to clipboard",
      COL_FORMAT: "Format",
      COL_CREATED: "Created",
    },
  },
} as const;
