/**
 * UI Constants
 *
 * Centralized UI strings and labels used throughout the application
 */

export const UI_LABELS = {
  // Loading states
  LOADING: {
    DEFAULT: "Loading...",
    USERS: "Loading users...",
    DATA: "Loading data...",
    PAGE: "Loading page...",
    CONTENT: "Loading content...",
    UPLOADING: "Uploading...",
    SAVING: "Saving...",
    SENDING: "Sending...",
    CHANGING: "Changing...",
  },

  // Empty states
  EMPTY: {
    NO_DATA: "No data available",
    NO_USERS: "No users found",
    NO_RESULTS: "No results found",
    NO_ITEMS: "No items to display",
    NO_EMAIL: "No email address",
    NO_PHONE: "No phone number",
    NO_ADDRESSES: "No saved addresses",
    NOT_SET: "Not set",
  },

  // Error pages
  ERROR_PAGES: {
    NOT_FOUND: {
      TITLE: "404 - Page Not Found",
      DESCRIPTION:
        "The page you're looking for doesn't exist or has been moved.",
    },
    UNAUTHORIZED: {
      TITLE: "401 - Unauthorized",
      DESCRIPTION: "You don't have permission to access this page.",
    },
    FORBIDDEN: {
      TITLE: "403 - Forbidden",
      DESCRIPTION: "Access to this resource is forbidden.",
    },
    SERVER_ERROR: {
      TITLE: "500 - Server Error",
      DESCRIPTION: "Something went wrong on our end. Please try again later.",
    },
    GENERIC_ERROR: {
      TITLE: "Oops! Something Went Wrong",
      DESCRIPTION: "An unexpected error occurred. Please try again.",
    },
    CRITICAL_ERROR: {
      TITLE: "Critical Error",
      DESCRIPTION:
        "A critical error occurred. Please try refreshing the page or contact support if the problem persists.",
    },
  },

  // Table labels
  TABLE: {
    ACTIONS: "Actions",
    NAME: "Name",
    STATUS: "Status",
    NO_DATA_TITLE: "No Data",
    NO_DATA_DESCRIPTION: "No data available",
    SHOWING: "Showing",
    OF: "of",
    ENTRIES: "entries",
  },

  // Actions
  ACTIONS: {
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    CREATE: "Create",
    UPDATE: "Update",
    SUBMIT: "Submit",
    CONFIRM: "Confirm",
    CLOSE: "Close",
    BACK: "Back",
    NEXT: "Next",
    PREVIOUS: "Previous",
    SEARCH: "Search",
    FILTER: "Filter",
    CLEAR: "Clear",
    APPLY: "Apply",
    RESET: "Reset",
    REFRESH: "Refresh",
    RETRY: "Retry",
    UPLOAD: "Upload",
    DOWNLOAD: "Download",
    EXPORT: "Export",
    IMPORT: "Import",
    YES: "Yes",
    NO: "No",
    LOGIN: "Login",
    LOGOUT: "Logout",
    GO_HOME: "Go Home",
    GO_HOME_NOW: "Go Home Now",
    CHANGE_PASSWORD: "Change Password",
    RESEND_VERIFICATION: "Resend Verification Email",
    EDIT_PROFILE: "Edit Profile",
    VIEW_DETAILS: "View Details",
    MANAGE: "Manage",
    VIEW: "View",
    VIEW_ALL: "View All",
    SUBSCRIBE: "Subscribe",
    UPDATE_PASSWORD: "Update Password",
    DISCARD: "Discard",
  },

  // Form labels
  FORM: {
    EMAIL: "Email Address",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm Password",
    CURRENT_PASSWORD: "Current Password",
    NEW_PASSWORD: "New Password",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    DISPLAY_NAME: "Display Name",
    PHONE: "Phone Number",
    ADDRESS: "Address",
    CITY: "City",
    STATE: "State",
    ZIP_CODE: "ZIP Code",
    COUNTRY: "Country",
    EMAIL_VERIFICATION: "Email Verification",
    PHONE_VERIFICATION: "Phone Verification",
  },

  // Status labels
  STATUS: {
    ALL: "All",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    DRAFT: "Draft",
    PUBLISHED: "Published",
    EMAIL_VERIFIED: "Email Verified ✓",
    EMAIL_NOT_VERIFIED: "Email Not Verified",
    PHONE_VERIFIED: "Phone Verified ✓",
    PHONE_NOT_VERIFIED: "Phone Not Verified",
    VERIFIED: "✓ Verified",
    SUBSCRIBED: "Subscribed!",
  },

  // Role labels
  ROLES: {
    USER: "User",
    SELLER: "Seller",
    MODERATOR: "Moderator",
    ADMIN: "Admin",
  },

  // Confirmation messages
  CONFIRM: {
    DELETE: "Are you sure you want to delete this?",
    CANCEL: "Are you sure you want to cancel?",
    DISCARD: "Are you sure you want to discard changes?",
    LOGOUT: "Are you sure you want to log out?",
    UNSAVED_CHANGES:
      "You have unsaved changes. Are you sure you want to leave this page?",
  },

  // Navigation labels
  NAV: {
    HOME: "Home",
    PRODUCTS: "Products",
    AUCTIONS: "Auctions",
    SELLERS: "Sellers",
    CATEGORIES: "Categories",
    PROMOTIONS: "Promotions",
    PROFILE: "Profile",
    ORDERS: "Orders",
    WISHLIST: "Wishlist",
    ADDRESSES: "Addresses",
    SETTINGS: "Settings",
    SEARCH: "Search",
    CONTACT_US: "Contact Us",
    HELP_CENTER: "Help Center",
    ACCOUNT: "Account",
    SUPPORT: "Support",
    DARK_MODE: "Dark Mode",
    SITE_SETTINGS: "Site Settings",
    CAROUSEL: "Carousel",
    SECTIONS: "Sections",
    FAQS: "FAQs",
    REVIEWS: "Reviews",
    MEDIA: "Media",
    LOGIN: "Login",
    REGISTER: "Register",
    LOGOUT: "Logout",
    DASHBOARD: "Dashboard",
    ADMIN_DASHBOARD: "Admin Dashboard",
    SELLER_DASHBOARD: "Seller Dashboard",
    MY_PROFILE: "My Profile",
    MY_ORDERS: "My Orders",
    USERS: "Users",
  },

  // Profile section
  PROFILE: {
    EDIT_PROFILE: "Edit Profile",
    VIEW_PROFILE: "View Profile",
    MY_PROFILE: "My Profile",
    PROFILE_SETTINGS: "Profile Settings",
    PROFILE_INFORMATION: "Profile Information",
    ACCOUNT_INFORMATION: "Account Information",
    SAVED_ADDRESSES: "Saved Addresses",
    SECURITY_SETTINGS: "Security Settings",
    USER_ID: "User ID",
    DISPLAY_NAME: "Display Name",
    ROLE: "Role",
    ACCOUNT_ROLE: "Account Role",
    TOTAL_ORDERS: "Total Orders",
  },

  // Wishlist section
  WISHLIST: {
    TITLE: "My Wishlist",
    DESCRIPTION: "Save items you love to your wishlist",
    EMPTY: "Your wishlist is empty",
    ADD_TO_WISHLIST: "Add to Wishlist",
    REMOVE_FROM_WISHLIST: "Remove from Wishlist",
    ITEMS_COUNT: "Wishlist Items",
  },

  // Messages
  MESSAGES: {
    EMAIL_VERIFICATION_REQUIRED:
      "Please verify your email address to access all features. Check your inbox for a verification link.",
    PHONE_VERIFICATION_REQUIRED:
      "Verify your phone number to enable additional security features.",
    UNSAVED_CHANGES_WARNING:
      "You have unsaved changes. Are you sure you want to leave?",
    EMAIL_VERIFIED_SUCCESS:
      "Your email address has been successfully verified.",
    PHONE_VERIFIED_SUCCESS: "Your phone number has been successfully verified.",
  },

  // Auth messages and labels
  AUTH: {
    // Login page
    LOGIN: {
      TITLE: "Sign in to your account",
      CREATE_ACCOUNT_LINK: "create a new account",
      REMEMBER_ME: "Remember me",
      FORGOT_PASSWORD_LINK: "Forgot password?",
      SIGNING_IN: "Signing in...",
      SIGN_IN: "Sign in",
      OR_CONTINUE_WITH: "Or continue with",
      GOOGLE: "Google",
      APPLE: "Apple",
    },

    // Register page
    REGISTER: {
      TITLE: "Create your account",
      SIGN_IN_LINK: "sign in to your account",
      DISPLAY_NAME_LABEL: "Display Name (Optional)",
      DISPLAY_NAME_PLACEHOLDER: "John Doe",
      CONFIRM_PASSWORD: "Confirm Password",
      ACCEPT_TERMS: "I agree to the",
      TERMS_OF_SERVICE: "Terms of Service",
      PRIVACY_POLICY: "Privacy Policy",
      AND: "and",
      OR: "Or",
      CREATING_ACCOUNT: "Creating account...",
      CREATE_ACCOUNT: "Create account",
      PASSWORDS_NO_MATCH: "Passwords do not match",
      MUST_ACCEPT_TERMS: "You must accept the terms and conditions",
      GOOGLE_REGISTER_FAILED: "Google registration failed",
      APPLE_REGISTER_FAILED: "Apple registration failed",
    },

    // Forgot Password page
    FORGOT_PASSWORD: {
      TITLE: "Reset your password",
      PAGE_TITLE: "Forgot Your Password?",
      SUBTITLE:
        "Enter your email address and we'll send you a link to reset your password.",
      SEND_RESET_LINK: "Send Reset Link",
      SEND_RESET_EMAIL: "Send Reset Link",
      SENDING: "Sending...",
      CHECK_EMAIL: "Check Your Email",
      RESET_LINK_SENT:
        "We've sent a password reset link to your email address. Please check your inbox and spam folder.",
      RESET_LINK_SENT_TO:
        "If an account exists with {email}, you will receive a password reset link shortly.",
      LINK_EXPIRES: "The link will expire in 1 hour for security reasons.",
      REMEMBER_PASSWORD: "Remember your password?",
      SIGN_IN_LINK: "Sign in",
      RETURN_TO_LOGIN: "Return to Login",
      SEND_ANOTHER_EMAIL: "Send Another Email",
      BACK_TO: "Back to",
      FAILED_SEND_EMAIL: "Failed to send reset email",
    },

    // Reset Password page
    RESET_PASSWORD: {
      TITLE: "Create new password",
      PAGE_TITLE: "Reset Your Password",
      SUBTITLE: "Choose a strong password for your account",
      SUBTITLE_SHORT: "Enter your new password below",
      NEW_PASSWORD: "New Password",
      CONFIRM_NEW_PASSWORD: "Confirm New Password",
      CONFIRM_NEW_PASSWORD_PLACEHOLDER: "Confirm new password",
      RESET_PASSWORD: "Reset Password",
      RESETTING: "Resetting...",
      SUCCESS: "Password Reset Successful!",
      SUCCESS_MESSAGE:
        "Your password has been successfully reset. You can now log in with your new password.",
      CONTINUE_TO_LOGIN: "Continue to Login",
      GO_TO_LOGIN: "Go to Login",
      INVALID_TOKEN: "Invalid or expired reset link",
      INVALID_OR_MISSING_TOKEN: "Invalid or missing reset token",
      PASSWORDS_NO_MATCH: "Passwords do not match",
    },

    // Verify Email page
    VERIFY_EMAIL: {
      VERIFYING: "Verifying your email...",
      VERIFYING_TITLE: "Verifying Your Email",
      VERIFYING_MESSAGE: "Please wait while we verify your email address...",
      SUCCESS: "Email Verified!",
      FAILED: "Verification Failed",
      CONTINUE_TO_DASHBOARD: "Continue to Dashboard",
      GO_TO_PROFILE: "Go to Profile",
      GO_TO_HOME: "Go to Home",
      SUCCESS_MESSAGE:
        "Your email has been successfully verified. You can now access all features of your account.",
      ALREADY_VERIFIED: "Email already verified",
      NOT_YET_VERIFIED: "Email not yet verified. Please check your email.",
      PLEASE_SIGN_IN: "Please sign in to verify your email.",
      CHECK_FAILED: "Verification check failed",
      NO_TOKEN: "No verification token provided",
      INVALID_TOKEN_MESSAGE:
        "The verification link may have expired or is invalid. Please request a new verification email.",
      RESEND_LINK: "Resend verification link",
    },

    // Shared auth strings
    SHARED: {
      EMAIL_ADDRESS: "Email Address",
      PASSWORD: "Password",
      EMAIL_PLACEHOLDER: "your@email.com",
      PASSWORD_PLACEHOLDER: "••••••••",
    },

    // System messages
    PHONE_LOGIN_NOT_IMPLEMENTED: "Phone login not yet implemented",
    PHONE_REGISTER_NOT_IMPLEMENTED: "Phone registration not yet implemented",
    EMAIL_OR_PHONE_REQUIRED: "Email or phone number required",
    DEFAULT_DISPLAY_NAME: "User",
    DEFAULT_ROLE: "user",
    ID_TOKEN_REQUIRED: "ID token required",
    SESSION_CREATE_FAILED: "Failed to create session",
    SESSION_CLEAR_FAILED: "Failed to clear session",
    RATE_LIMIT_EXCEEDED: "Too many requests. Please try again later.",
    AUTHENTICATION_REQUIRED: "Authentication required",
    ACCOUNT_DISABLED: "Account disabled",
    EMAIL_VERIFICATION_REQUIRED_SHORT: "Email verification required",
    INSUFFICIENT_PERMISSIONS: "Insufficient permissions",
    ACCESS_DENIED: "Access Denied",
    REDIRECTING_IN: "Redirecting to home page in",
    SECONDS: "seconds...",
  },

  // Settings page
  SETTINGS: {
    TITLE: "Account Settings",
    UNSAVED_BANNER: "You have unsaved changes",
    UNSAVED_DETAIL: "Save your changes before leaving, or they will be lost.",
    SAVE_CHANGES: "Save Changes",
    SAVING: "Saving...",
  },

  // Avatar upload
  AVATAR: {
    TITLE: "Adjust Image",
    INSTRUCTION: "Drag to reposition • Use slider to zoom",
    ZOOM: "Zoom",
    POSITION: "Position",
    RESET: "Reset to center",
    SAVE_CHANGES: "Save Changes",
    CHOOSE_IMAGE: "Choose Image",
    CHANGE_PHOTO: "Change Photo",
    REMOVE_PHOTO: "Remove Photo",
    SAVE_AVATAR: "Save Avatar",
    CANCEL_CHANGE: "Cancel",
    UPLOADING: "Uploading...",
    SAVING: "Saving...",
    READY_TO_SAVE: "Click Save Avatar to apply your new profile picture.",
    RECOMMENDED_SIZE: "Upload a profile picture. Recommended size: 400x400px",
    SUPPORTED_FORMATS: "Supported formats: JPEG, PNG, WebP, GIF (max 5MB)",
    ZOOM_WARNING_TITLE: "Image quality warning",
    ZOOM_WARNING_MESSAGE:
      "Zooming out too much may result in a small, pixelated image. Consider uploading a larger image or keeping zoom at 100% or higher.",
    ALT_TEXT: "Profile avatar",
    ALT_PREVIEW: "Preview",
    ZOOM_IN: "Zoom in",
    ZOOM_OUT: "Zoom out",
    FALLBACK_USER: "User",
    DEFAULT_INITIAL: "U",
  },

  // Admin content management
  ADMIN: {
    DASHBOARD: {
      TITLE: "Dashboard Overview",
      SUBTITLE: "System statistics and quick actions",
      QUICK_ACTIONS: "Quick Actions",
      RECENT_ACTIVITY: "Recent Activity",
      STATS: "Statistics",
      MANAGE_USERS: "Manage Users",
      REVIEW_DISABLED: "Review Disabled Accounts",
      MANAGE_CONTENT: "Manage Content",
      NEW_USERS: "New Users",
      SYSTEM_STATUS: "System Status",
      ALL_SYSTEMS_OPERATIONAL: "All systems operational",
      NEW_USERS_REGISTERED: (count: number) =>
        `${count} new ${count === 1 ? "user" : "users"} registered in the last 30 days`,
    },
    USERS: {
      TITLE: "Users",
      SUBTITLE: "Manage user accounts and permissions",
      DETAIL: "User Details",
      ALL: "All Users",
      ACTIVE: "Active",
      BANNED: "Banned",
      ADMINS: "Admins",
      SEARCH_PLACEHOLDER: "Search by name or email...",
      BAN_USER: "Ban User",
      UNBAN_USER: "Unban User",
      DELETE_USER: "Delete User",
      CHANGE_ROLE: "Change Role",
      NO_USERS_FOUND: "No users found",
      TOTAL_USERS: "Total Users",
      ACTIVE_USERS: "Active Users",
      BANNED_USERS: "Banned Users",
      ADMIN_USERS: "Admin Users",
      ROLE_UPDATE_FAILED: "Failed to update user role",
      BAN_FAILED: "Failed to update user ban status",
      DELETE_FAILED: "Failed to delete user",
      CONFIRM_ROLE_CHANGE: "Change role to",
      CONFIRM_BAN: "Are you sure you want to ban this user?",
      CONFIRM_UNBAN: "Are you sure you want to unban this user?",
      CONFIRM_DELETE:
        "PERMANENTLY DELETE this user? This action cannot be undone.",
      TYPE_DELETE_CONFIRM: 'Type "DELETE" to confirm:',
    },
    SITE: {
      TITLE: "Site Settings",
      SUBTITLE: "Configure global site settings, branding, and appearance",
      GENERAL: "General Settings",
      SEO: "SEO Settings",
      SECURITY: "Security Settings",
      SAVE_SETTINGS: "Save Settings",
      SAVE_ALL_CHANGES: "Save All Changes",
      SETTINGS_SAVED: "Settings saved successfully",
      SETTINGS_FAILED: "Failed to save settings",
      BASIC_INFO: "Basic Information",
      SITE_NAME: "Site Name",
      MOTTO: "Motto / Tagline",
      CONTACT_INFO: "Contact Information",
      SUPPORT_EMAIL: "Support Email",
      SUPPORT_PHONE: "Support Phone",
      ADDRESS: "Address",
      SOCIAL_LINKS: "Social Media Links",
      FACEBOOK: "Facebook",
      TWITTER: "Twitter",
      INSTAGRAM: "Instagram",
      LINKEDIN: "LinkedIn",
    },
    CAROUSEL: {
      TITLE: "Carousel Management",
      SUBTITLE: "Manage homepage carousel slides (max 5 active)",
      ADD_SLIDE: "Add Slide",
      CREATE_SLIDE: "Create Carousel Slide",
      EDIT_SLIDE: "Edit Carousel Slide",
      DELETE_SLIDE: "Delete Carousel Slide",
      REORDER_SLIDES: "Reorder Slides",
      NO_SLIDES: "No slides found",
      SAVE_FAILED: "Failed to save slide",
      DELETE_FAILED: "Failed to delete slide",
    },
    CATEGORIES: {
      TITLE: "Categories",
      SUBTITLE: "Manage product categories hierarchy",
      ADD_CATEGORY: "Add Category",
      CREATE_CATEGORY: "Create Category",
      EDIT_CATEGORY: "Edit Category",
      DELETE_CATEGORY: "Delete Category",
      NO_CATEGORIES: "No categories found",
      SAVE_FAILED: "Failed to save category",
      DELETE_FAILED: "Failed to delete category",
      CANNOT_DELETE_WITH_CHILDREN:
        "Cannot delete category with subcategories. Delete children first.",
      CANNOT_DELETE_WITH_PRODUCTS:
        "Cannot delete category with products/auctions. Move them first.",
      PARENT_CATEGORY: "Parent Category",
      NONE_ROOT: "None (Root Category)",
      SHOW_ON_HOMEPAGE: "Show on Homepage",
      ENABLED: "Enabled",
      TREE_VIEW: "Tree",
      TABLE_VIEW: "Table",
    },
    FAQS: {
      TITLE: "FAQs",
      SUBTITLE: "Manage frequently asked questions",
      ADD_FAQ: "Add FAQ",
      CREATE_FAQ: "Create FAQ",
      EDIT_FAQ: "Edit FAQ",
      DELETE_FAQ: "Delete FAQ",
      NO_FAQS: "No FAQs found",
      SAVE_FAILED: "Failed to save FAQ",
      DELETE_FAILED: "Failed to delete FAQ",
      CATEGORY: "Category",
      QUESTION: "Question",
      ANSWER: "Answer",
      PRIORITY: "Priority",
      PRIORITY_HELP: "Higher priority appears first",
      FEATURED: "Featured",
      FEATURED_LABEL: "Featured (show on homepage)",
      TAGS: "Tags (comma-separated)",
      TAGS_PLACEHOLDER: "e.g. payment, refund, shipping",
      ORDER_HELP: "Display order within same priority",
      SHOW_VARIABLES: "Show Variables",
      HIDE_VARIABLES: "Hide Variables",
      INSERT_VARIABLE_HELP: "Click to insert variable into answer:",
    },
    SECTIONS: {
      TITLE: "Homepage Sections",
      SUBTITLE: "Manage homepage sections and their order",
      ADD_SECTION: "Add Section",
      CREATE_SECTION: "Create Section",
      EDIT_SECTION: "Edit Section",
      DELETE_SECTION: "Delete Section",
      REORDER_SECTIONS: "Reorder Sections",
      NO_SECTIONS: "No sections found",
      SAVE_FAILED: "Failed to save section",
      DELETE_FAILED: "Failed to delete section",
      SECTION_TYPE: "Section Type",
      SECTION_ORDER: "Display Order",
      CONFIGURATION: "Configuration (JSON)",
    },
    REVIEWS: {
      TITLE: "Reviews",
      SUBTITLE: "Moderate product reviews",
      VIEW: "View Reviews",
      REVIEW_DETAILS: "Review Details",
      BACK_TO_LIST: "Back to List",
      APPROVE: "Approve",
      REJECT: "Reject",
      DELETE: "Delete",
      APPROVE_ALL: "Approve All Pending",
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      NO_REVIEWS: "No reviews found",
      REJECTION_REASON: "Rejection Reason",
      APPROVE_FAILED: "Failed to approve review",
      REJECT_FAILED: "Failed to reject review",
      DELETE_FAILED: "Failed to delete review",
      NO_PENDING: "No pending reviews to approve",
      VERIFIED: "Verified",
      VERIFIED_PURCHASE: "Verified Purchase",
      HELPFUL_VOTES: "Helpful Votes",
      PRODUCT: "Product",
      USER: "User",
      COMMENT: "Comment",
      RATING: "Rating",
      CREATED: "Created",
      ALL_RATINGS: "All Ratings",
      SEARCH_PLACEHOLDER: "Search products, users...",
    },
    SESSIONS: {
      TITLE: "Sessions",
      SUBTITLE: "Manage user sessions",
      CONFIRM_REVOKE: "Revoke Session",
      CONFIRM_REVOKE_MESSAGE:
        "Are you sure you want to revoke this session? The user will be logged out.",
      CONFIRM_REVOKE_ALL: "Revoke All Sessions",
      CONFIRM_REVOKE_ALL_MESSAGE:
        "Are you sure you want to revoke all sessions? All users will be logged out.",
    },
    CONTENT: {
      TITLE: "Content Management",
      SUBTITLE: "Manage products, orders, and reviews",
      PRODUCTS: {
        TITLE: "Products",
        SUBTITLE: "Manage all product listings",
        VIEW: "View Products",
        CREATE: "Create Product",
        EDIT: "Edit Product",
        DELETE: "Delete Product",
        ICON: "📦",
      },
      ORDERS: {
        TITLE: "Orders",
        SUBTITLE: "Manage all orders",
        VIEW: "View Orders",
        DETAILS: "Order Details",
        APPROVE: "Approve Order",
        REJECT: "Reject Order",
        ICON: "🛒",
      },
      REVIEWS: {
        TITLE: "Reviews",
        SUBTITLE: "Moderate user reviews",
        VIEW: "View Reviews",
        APPROVE: "Approve Review",
        REJECT: "Reject Review",
        DELETE: "Delete Review",
        ICON: "⭐",
      },
      COMING_SOON: {
        TITLE: "Content Management Coming Soon",
        MESSAGE:
          "Advanced content management features are currently under development",
        ICON: "🚧",
      },
    },
    MEDIA: {
      TITLE: "Media Operations",
      SUBTITLE: "Manage image cropping and video trimming",
      CROP_IMAGE: "Crop Image",
      TRIM_VIDEO: "Trim Video",
      SOURCE_URL: "Source URL",
      SOURCE_URL_PLACEHOLDER: "https://example.com/image.jpg",
      OUTPUT_FORMAT: "Output Format",
      QUALITY: "Quality",
      QUALITY_HIGH: "High (90)",
      QUALITY_MEDIUM: "Medium (75)",
      QUALITY_LOW: "Low (60)",
      CROP_PARAMETERS: "Crop Parameters",
      X_POSITION: "X Position",
      Y_POSITION: "Y Position",
      WIDTH: "Width",
      HEIGHT: "Height",
      TRIM_PARAMETERS: "Trim Parameters",
      START_TIME: "Start Time (seconds)",
      END_TIME: "End Time (seconds)",
      VIDEO_QUALITY: "Video Quality",
      QUALITY_LOW_LABEL: "Low (500k/64k)",
      QUALITY_MEDIUM_LABEL: "Medium (1000k/128k)",
      QUALITY_HIGH_LABEL: "High (2500k/192k)",
      RECENT_OPERATIONS: "Recent Operations",
      NO_OPERATIONS: "No media operations yet",
      OPERATION_TYPE: "Operation Type",
      OPERATION_STATUS: "Status",
      PROCESSING: "Processing",
      COMPLETED: "Completed",
      FAILED: "Failed",
      DOWNLOAD_RESULT: "Download Result",
      COPY_URL: "Copy URL",
      URL_COPIED: "URL copied to clipboard",
    },
  },

  // User section labels
  USER: {
    PROFILE: {
      TITLE: "My Profile",
      EDIT: "Edit Profile",
      VIEW: "View Profile",
      INFORMATION: "Profile Information",
      ACCOUNT_INFO: "Account Information",
      SECURITY: "Security Settings",
    },
    SETTINGS: {
      TITLE: "Settings",
      SUBTITLE: "Manage your account preferences",
      GENERAL: "General",
      SECURITY: "Security",
      NOTIFICATIONS: "Notifications",
      PRIVACY: "Privacy",
    },
    ORDERS: {
      TITLE: "My Orders",
      SUBTITLE: "View and manage your orders",
      EMPTY: "No orders yet",
      EMPTY_SUBTITLE: "Start shopping to see your orders here",
      VIEW_ORDER: "View Order",
      ORDER_DETAILS: "Order Details",
      ORDER_NUMBER: "Order Number",
      ORDER_DATE: "Order Date",
      ORDER_STATUS: "Order Status",
      ORDER_TOTAL: "Order Total",
      BACK_TO_ORDERS: "Back to Orders",
      ORDER_NOT_FOUND: "Order not found",
      ORDER_NOT_FOUND_MESSAGE:
        "The order you're looking for doesn't exist or has been removed.",
      VIEW_ALL_ORDERS: "View All Orders",
      BROWSE_PRODUCTS: "Browse Products",
      ORDER_ITEMS: "Order Items",
      ORDER_SUMMARY: "Order Summary",
      SUBTOTAL: "Subtotal",
      SHIPPING: "Shipping",
      TAX: "Tax",
      TOTAL: "Total",
      SHIPPING_ADDRESS: "Shipping Address",
      PAYMENT_INFO: "Payment Information",
      PAYMENT_METHOD: "Payment Method",
      PAYMENT_STATUS: "Payment Status",
      PAID: "Paid",
      TRACK_ORDER: "Track Order",
      QUANTITY: "Quantity",
      EACH: "each",
      PLACED_ON: "Placed on",
    },
    WISHLIST: {
      TITLE: "My Wishlist",
      SUBTITLE: "Items you've saved for later",
      EMPTY: "Your wishlist is empty",
      EMPTY_SUBTITLE: "Save items you love to your wishlist",
      ADD_TO_CART: "Add to Cart",
      REMOVE: "Remove from Wishlist",
      ITEMS: "Wishlist Items",
    },
    ADDRESSES: {
      TITLE: "My Addresses",
      SUBTITLE: "Manage your delivery addresses",
      ADD: "Add New Address",
      ADD_FIRST: "Add Your First Address",
      EDIT: "Edit Address",
      DELETE: "Delete Address",
      DELETE_CONFIRM_TITLE: "Delete Address?",
      DELETE_CONFIRM_MESSAGE:
        "Are you sure you want to delete this address? This action cannot be undone.",
      DELETE_CONFIRM:
        "Are you sure you want to delete this address? This action cannot be undone.",
      EMPTY: "No saved addresses",
      EMPTY_SUBTITLE: "Add an address to use for shipping",
      DEFAULT: "Default Address",
      SET_DEFAULT: "Set as Default",
      SHIPPING_ADDRESS: "Shipping Address",
      BILLING_ADDRESS: "Billing Address",
    },
  },

  // Modal labels
  MODALS: {
    CONFIRM_DELETE: "Delete Confirmation",
    CONFIRM_ACTION: "Confirm Action",
    ARE_YOU_SURE: "Are you sure?",
    CANNOT_UNDO: "This action cannot be undone.",
  },

  // Homepage section labels
  HOMEPAGE: {
    HERO: {
      TITLE: "Welcome to LetItRip",
      SUBTITLE: "Discover amazing products and deals",
      CTA: "Shop Now",
      LEARN_MORE: "Learn More",
    },
    TRUST_INDICATORS: {
      TITLE: "Why Shop With Us?",
      SECURE: "Secure Payments",
      SHIPPING: "Fast Shipping",
      RETURNS: "Easy Returns",
      SUPPORT: "24/7 Support",
    },
    FEATURES: {
      TITLE: "Why Shop With Us?",
      SUBTITLE:
        "Your satisfaction is our priority. We provide a seamless shopping experience with unmatched features",
      QUALITY: "Premium Quality",
      PRICE: "Best Prices",
      SERVICE: "Excellent Service",
      WARRANTY: "Warranty Included",
    },
    NEWSLETTER: {
      TITLE: "Stay Updated",
      SUBTITLE: "Subscribe to our newsletter for exclusive deals",
      PLACEHOLDER: "Enter your email",
      BUTTON: "Subscribe",
      SUCCESS: "Successfully subscribed!",
      ERROR: "Subscription failed. Please try again.",
      PRIVACY_NOTE:
        "We respect your privacy. Unsubscribe at any time. Read our",
    },
    REVIEWS: {
      TITLE: "What Our Customers Say",
      SUBTITLE: "Read reviews from satisfied customers",
      VIEW_ALL: "View All Reviews",
      NO_REVIEWS: "No reviews yet",
    },
    AUCTIONS: {
      TITLE: "Live Auctions",
      SUBTITLE: "Bid on exclusive items",
      VIEW_ALL: "View All Auctions",
      NO_AUCTIONS: "No active auctions",
      ENDS_IN: "Ends in",
      CURRENT_BID: "Current Bid",
      PLACE_BID: "Place Bid",
    },
    CATEGORIES: {
      TITLE: "Shop by Category",
      SUBTITLE: "Browse our extensive collection",
      VIEW_ALL: "View All Categories",
    },
    FEATURED_PRODUCTS: {
      TITLE: "Featured Products",
      SUBTITLE: "Handpicked items just for you",
      VIEW_ALL: "View All Products",
    },
    BLOG: {
      TITLE: "From Our Blog",
      SUBTITLE: "Tips, stories, and insights from the community",
    },
  },

  // Footer section labels
  FOOTER: {
    QUICK_LINKS: "Quick Links",
    ABOUT_US: "About Us",
    CONTACT: "Contact",
    BLOG: "Blog",
    PRIVACY_POLICY: "Privacy Policy",
    TERMS_OF_SERVICE: "Terms of Service",
    HELP_CENTER: "Help Center",
    FAQS: "FAQs",
    SHIPPING_INFO: "Shipping Information",
    RETURNS: "Returns & Exchanges",
    SOCIAL_MEDIA: "Follow Us",
    CONNECT: "Connect",
    NEWSLETTER: "Newsletter",
    SUBSCRIBE: "Subscribe",
    COPYRIGHT: "© {year} {brand}. All rights reserved.",
    COMPANY: "Company",
    SUPPORT: "Support",
    LEGAL: "Legal",
  },

  // FAQ section
  FAQ: {
    TITLE: "Frequently Asked Questions",
    SUBTITLE:
      "Find answers to common questions about our platform, products, shipping, and more.",
    WAS_THIS_HELPFUL: "Was this helpful?",
    HELPFUL: "Helpful",
    NOT_HELPFUL: "Not Helpful",
    RELATED_QUESTIONS: "Related Questions",
    VIEW_ALL: "View All FAQs",
    SEARCH_PLACEHOLDER: "Search FAQs...",
    QUESTION_SINGULAR: "question",
    QUESTION_PLURAL: "questions",
    IN_CATEGORY: "in",
  },
} as const;

export const UI_PLACEHOLDERS = {
  EMAIL: "Enter your email address",
  PASSWORD: "Enter your password",
  CURRENT_PASSWORD: "Enter current password",
  NEW_PASSWORD: "Enter new password",
  CONFIRM_PASSWORD: "Confirm your password",
  SEARCH: "Search...",
  PHONE: "Enter phone number",
  NAME: "Enter your name",
  FIRST_NAME: "Enter first name",
  LAST_NAME: "Enter last name",
  DISPLAY_NAME: "Enter display name",
  MESSAGE: "Enter your message",
  DESCRIPTION: "Enter description",
  TITLE: "Enter title",
  ADDRESS: "Enter address",
  CITY: "Enter city",
  STATE: "Enter state/province",
  ZIP_CODE: "Enter ZIP/postal code",
  COUNTRY: "Select country",
  QUESTION: "Enter your question",
  ANSWER: "Enter the answer",
  CODE: "Enter code",
  PRICE: "Enter price",
  QUANTITY: "Enter quantity",
} as const;

export const UI_HELP_TEXT = {
  PASSWORD_REQUIREMENTS:
    "Must be at least 8 characters with uppercase, lowercase, and number",
  PHONE_FORMAT: "Format: +[country code][number]",
  PHONE_10_DIGIT: "Enter 10-digit mobile number",
  EMAIL_VERIFICATION: "Please verify your email to access all features",
  AVATAR_UPLOAD: "Upload a profile picture. Recommended size: 400x400px",
  AVATAR_FORMATS: "Supported formats: JPEG, PNG, WebP, GIF (max 5MB)",
} as const;
