/**
 * UI Constants
 *
 * Centralized UI strings and labels used throughout the application
 */

export const UI_LABELS = {
  // Loading states
  LOADING: {
    DEFAULT: "Loading...",
    USERS: "Loading users...",
    DATA: "Loading data...",
    PAGE: "Loading page...",
    CONTENT: "Loading content...",
    UPLOADING: "Uploading...",
    SAVING: "Saving...",
    SENDING: "Sending...",
    CHANGING: "Changing...",
    FAILED: "Failed to load data.",
  },

  // Empty states
  EMPTY: {
    NO_DATA: "No data available",
    NO_USERS: "No users found",
    NO_RESULTS: "No results found",
    NO_ITEMS: "No items to display",
    NO_EMAIL: "No email address",
    NO_PHONE: "No phone number",
    NO_ADDRESSES: "No saved addresses",
    NOT_SET: "Not set",
  },

  // Error pages
  ERROR_PAGES: {
    NOT_FOUND: {
      TITLE: "404 - Page Not Found",
      DESCRIPTION:
        "The page you're looking for doesn't exist or has been moved.",
    },
    UNAUTHORIZED: {
      TITLE: "401 - Unauthorized",
      DESCRIPTION: "You don't have permission to access this page.",
    },
    FORBIDDEN: {
      TITLE: "403 - Forbidden",
      DESCRIPTION: "Access to this resource is forbidden.",
    },
    SERVER_ERROR: {
      TITLE: "500 - Server Error",
      DESCRIPTION: "Something went wrong on our end. Please try again later.",
    },
    GENERIC_ERROR: {
      TITLE: "Oops! Something Went Wrong",
      DESCRIPTION: "An unexpected error occurred. Please try again.",
    },
    CRITICAL_ERROR: {
      TITLE: "Critical Error",
      DESCRIPTION:
        "A critical error occurred. Please try refreshing the page or contact support if the problem persists.",
    },
  },

  // Table labels
  TABLE: {
    ACTIONS: "Actions",
    NAME: "Name",
    STATUS: "Status",
    NO_DATA_TITLE: "No Data",
    NO_DATA_DESCRIPTION: "No data available",
    SHOWING: "Showing",
    OF: "of",
    ENTRIES: "entries",
  },

  // Actions
  ACTIONS: {
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    CREATE: "Create",
    UPDATE: "Update",
    SUBMIT: "Submit",
    CONFIRM: "Confirm",
    CLOSE: "Close",
    BACK: "Back",
    NEXT: "Next",
    PREVIOUS: "Previous",
    SEARCH: "Search",
    FILTER: "Filter",
    CLEAR: "Clear",
    APPLY: "Apply",
    RESET: "Reset",
    REFRESH: "Refresh",
    RETRY: "Retry",
    UPLOAD: "Upload",
    DOWNLOAD: "Download",
    EXPORT: "Export",
    IMPORT: "Import",
    YES: "Yes",
    NO: "No",
    LOGIN: "Login",
    LOGOUT: "Logout",
    GO_HOME: "Go Home",
    GO_HOME_NOW: "Go Home Now",
    CHANGE_PASSWORD: "Change Password",
    RESEND_VERIFICATION: "Resend Verification Email",
    EDIT_PROFILE: "Edit Profile",
    VIEW_DETAILS: "View Details",
    MANAGE: "Manage",
    VIEW: "View",
    VIEW_ALL: "View All",
    SUBSCRIBE: "Subscribe",
    UPDATE_PASSWORD: "Update Password",
    DISCARD: "Discard",
    COPY_LINK: "Copy Link",
    LINK_COPIED: "Link copied to clipboard!",
  },

  // Form labels
  FORM: {
    EMAIL: "Email Address",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm Password",
    CURRENT_PASSWORD: "Current Password",
    NEW_PASSWORD: "New Password",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    DISPLAY_NAME: "Display Name",
    PHONE: "Phone Number",
    ADDRESS: "Address",
    CITY: "City",
    STATE: "State",
    ZIP_CODE: "ZIP Code",
    COUNTRY: "Country",
    EMAIL_VERIFICATION: "Email Verification",
    PHONE_VERIFICATION: "Phone Verification",
  },

  // Status labels
  STATUS: {
    ALL: "All",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    DRAFT: "Draft",
    PUBLISHED: "Published",
    EMAIL_VERIFIED: "Email Verified ✓",
    EMAIL_NOT_VERIFIED: "Email Not Verified",
    PHONE_VERIFIED: "Phone Verified ✓",
    PHONE_NOT_VERIFIED: "Phone Not Verified",
    VERIFIED: "✓ Verified",
    SUBSCRIBED: "Subscribed!",
  },

  // Role labels
  ROLES: {
    USER: "User",
    SELLER: "Seller",
    MODERATOR: "Moderator",
    ADMIN: "Admin",
  },

  // Confirmation messages
  CONFIRM: {
    DELETE: "Are you sure you want to delete this?",
    CANCEL: "Are you sure you want to cancel?",
    DISCARD: "Are you sure you want to discard changes?",
    LOGOUT: "Are you sure you want to log out?",
    UNSAVED_CHANGES:
      "You have unsaved changes. Are you sure you want to leave this page?",
  },

  // Navigation labels
  NAV: {
    HOME: "Home",
    PRODUCTS: "Products",
    AUCTIONS: "Auctions",
    SELLERS: "Sellers",
    CATEGORIES: "Categories",
    PROMOTIONS: "Promotions",
    PROFILE: "Profile",
    ORDERS: "Orders",
    WISHLIST: "Wishlist",
    ADDRESSES: "Addresses",
    SETTINGS: "Settings",
    SEARCH: "Search",
    CONTACT_US: "Contact Us",
    HELP_CENTER: "Help Center",
    ACCOUNT: "Account",
    SUPPORT: "Support",
    DARK_MODE: "Dark Mode",
    SITE_SETTINGS: "Site Settings",
    CAROUSEL: "Carousel",
    SECTIONS: "Sections",
    FAQS: "FAQs",
    REVIEWS: "Reviews",
    MEDIA: "Media",
    LOGIN: "Login",
    REGISTER: "Register",
    LOGOUT: "Logout",
    DASHBOARD: "Dashboard",
    ADMIN_DASHBOARD: "Admin Dashboard",
    SELLER_DASHBOARD: "Seller Dashboard",
    MY_PROFILE: "My Profile",
    MY_ORDERS: "My Orders",
    USERS: "Users",
    PRODUCTS_ADMIN: "Products",
    MY_PRODUCTS: "My Products",
    MY_SALES: "My Sales",
    MY_AUCTIONS: "My Auctions",
    BIDS_ADMIN: "Bids",
    BLOG_ADMIN: "Blog",
  },

  // Profile section
  PROFILE: {
    EDIT_PROFILE: "Edit Profile",
    VIEW_PROFILE: "View Profile",
    MY_PROFILE: "My Profile",
    PROFILE_SETTINGS: "Profile Settings",
    PROFILE_INFORMATION: "Profile Information",
    ACCOUNT_INFORMATION: "Account Information",
    SAVED_ADDRESSES: "Saved Addresses",
    SECURITY_SETTINGS: "Security Settings",
    USER_ID: "User ID",
    DISPLAY_NAME: "Display Name",
    ROLE: "Role",
    ACCOUNT_ROLE: "Account Role",
    TOTAL_ORDERS: "Total Orders",
  },

  // Wishlist section
  WISHLIST: {
    TITLE: "My Wishlist",
    DESCRIPTION: "Save items you love to your wishlist",
    EMPTY: "Your wishlist is empty",
    ADD_TO_WISHLIST: "Add to Wishlist",
    REMOVE_FROM_WISHLIST: "Remove from Wishlist",
    ITEMS_COUNT: "Wishlist Items",
  },

  // Messages
  MESSAGES: {
    EMAIL_VERIFICATION_REQUIRED:
      "Please verify your email address to access all features. Check your inbox for a verification link.",
    PHONE_VERIFICATION_REQUIRED:
      "Verify your phone number to enable additional security features.",
    UNSAVED_CHANGES_WARNING:
      "You have unsaved changes. Are you sure you want to leave?",
    EMAIL_VERIFIED_SUCCESS:
      "Your email address has been successfully verified.",
    PHONE_VERIFIED_SUCCESS: "Your phone number has been successfully verified.",
  },

  // Auth messages and labels
  AUTH: {
    // Login page
    LOGIN: {
      TITLE: "Sign in to your account",
      CREATE_ACCOUNT_LINK: "create a new account",
      REMEMBER_ME: "Remember me",
      FORGOT_PASSWORD_LINK: "Forgot password?",
      SIGNING_IN: "Signing in...",
      SIGN_IN: "Sign in",
      OR_CONTINUE_WITH: "Or continue with",
      GOOGLE: "Google",
      APPLE: "Apple",
    },

    // Register page
    REGISTER: {
      TITLE: "Create your account",
      SIGN_IN_LINK: "sign in to your account",
      DISPLAY_NAME_LABEL: "Display Name (Optional)",
      DISPLAY_NAME_PLACEHOLDER: "John Doe",
      CONFIRM_PASSWORD: "Confirm Password",
      ACCEPT_TERMS: "I agree to the",
      TERMS_OF_SERVICE: "Terms of Service",
      PRIVACY_POLICY: "Privacy Policy",
      AND: "and",
      OR: "Or",
      CREATING_ACCOUNT: "Creating account...",
      CREATE_ACCOUNT: "Create account",
      PASSWORDS_NO_MATCH: "Passwords do not match",
      MUST_ACCEPT_TERMS: "You must accept the terms and conditions",
      GOOGLE_REGISTER_FAILED: "Google registration failed",
      APPLE_REGISTER_FAILED: "Apple registration failed",
    },

    // Forgot Password page
    FORGOT_PASSWORD: {
      TITLE: "Reset your password",
      PAGE_TITLE: "Forgot Your Password?",
      SUBTITLE:
        "Enter your email address and we'll send you a link to reset your password.",
      SEND_RESET_LINK: "Send Reset Link",
      SEND_RESET_EMAIL: "Send Reset Link",
      SENDING: "Sending...",
      CHECK_EMAIL: "Check Your Email",
      RESET_LINK_SENT:
        "We've sent a password reset link to your email address. Please check your inbox and spam folder.",
      RESET_LINK_SENT_TO:
        "If an account exists with {email}, you will receive a password reset link shortly.",
      LINK_EXPIRES: "The link will expire in 1 hour for security reasons.",
      REMEMBER_PASSWORD: "Remember your password?",
      SIGN_IN_LINK: "Sign in",
      RETURN_TO_LOGIN: "Return to Login",
      SEND_ANOTHER_EMAIL: "Send Another Email",
      BACK_TO: "Back to",
      FAILED_SEND_EMAIL: "Failed to send reset email",
    },

    // Reset Password page
    RESET_PASSWORD: {
      TITLE: "Create new password",
      PAGE_TITLE: "Reset Your Password",
      SUBTITLE: "Choose a strong password for your account",
      SUBTITLE_SHORT: "Enter your new password below",
      NEW_PASSWORD: "New Password",
      CONFIRM_NEW_PASSWORD: "Confirm New Password",
      CONFIRM_NEW_PASSWORD_PLACEHOLDER: "Confirm new password",
      RESET_PASSWORD: "Reset Password",
      RESETTING: "Resetting...",
      SUCCESS: "Password Reset Successful!",
      SUCCESS_MESSAGE:
        "Your password has been successfully reset. You can now log in with your new password.",
      CONTINUE_TO_LOGIN: "Continue to Login",
      GO_TO_LOGIN: "Go to Login",
      INVALID_TOKEN: "Invalid or expired reset link",
      INVALID_OR_MISSING_TOKEN: "Invalid or missing reset token",
      PASSWORDS_NO_MATCH: "Passwords do not match",
    },

    // Verify Email page
    VERIFY_EMAIL: {
      VERIFYING: "Verifying your email...",
      VERIFYING_TITLE: "Verifying Your Email",
      VERIFYING_MESSAGE: "Please wait while we verify your email address...",
      SUCCESS: "Email Verified!",
      FAILED: "Verification Failed",
      CONTINUE_TO_DASHBOARD: "Continue to Dashboard",
      GO_TO_PROFILE: "Go to Profile",
      GO_TO_HOME: "Go to Home",
      SUCCESS_MESSAGE:
        "Your email has been successfully verified. You can now access all features of your account.",
      ALREADY_VERIFIED: "Email already verified",
      NOT_YET_VERIFIED: "Email not yet verified. Please check your email.",
      PLEASE_SIGN_IN: "Please sign in to verify your email.",
      CHECK_FAILED: "Verification check failed",
      NO_TOKEN: "No verification token provided",
      INVALID_TOKEN_MESSAGE:
        "The verification link may have expired or is invalid. Please request a new verification email.",
      RESEND_LINK: "Resend verification link",
    },

    // Shared auth strings
    SHARED: {
      EMAIL_ADDRESS: "Email Address",
      PASSWORD: "Password",
      EMAIL_PLACEHOLDER: "your@email.com",
      PASSWORD_PLACEHOLDER: "••••••••",
    },

    // System messages
    PHONE_LOGIN_NOT_IMPLEMENTED: "Phone login not yet implemented",
    PHONE_REGISTER_NOT_IMPLEMENTED: "Phone registration not yet implemented",
    EMAIL_OR_PHONE_REQUIRED: "Email or phone number required",
    DEFAULT_DISPLAY_NAME: "User",
    DEFAULT_ROLE: "user",
    ID_TOKEN_REQUIRED: "ID token required",
    SESSION_CREATE_FAILED: "Failed to create session",
    SESSION_CLEAR_FAILED: "Failed to clear session",
    RATE_LIMIT_EXCEEDED: "Too many requests. Please try again later.",
    AUTHENTICATION_REQUIRED: "Authentication required",
    ACCOUNT_DISABLED: "Account disabled",
    EMAIL_VERIFICATION_REQUIRED_SHORT: "Email verification required",
    INSUFFICIENT_PERMISSIONS: "Insufficient permissions",
    ACCESS_DENIED: "Access Denied",
    REDIRECTING_IN: "Redirecting to home page in",
    SECONDS: "seconds...",
  },

  // Settings page
  SETTINGS: {
    TITLE: "Account Settings",
    UNSAVED_BANNER: "You have unsaved changes",
    UNSAVED_DETAIL: "Save your changes before leaving, or they will be lost.",
    SAVE_CHANGES: "Save Changes",
    SAVING: "Saving...",
  },

  // Avatar upload
  AVATAR: {
    TITLE: "Adjust Image",
    INSTRUCTION: "Drag to reposition • Use slider to zoom",
    ZOOM: "Zoom",
    POSITION: "Position",
    RESET: "Reset to center",
    SAVE_CHANGES: "Save Changes",
    CHOOSE_IMAGE: "Choose Image",
    CHANGE_PHOTO: "Change Photo",
    REMOVE_PHOTO: "Remove Photo",
    SAVE_AVATAR: "Save Avatar",
    CANCEL_CHANGE: "Cancel",
    UPLOADING: "Uploading...",
    SAVING: "Saving...",
    READY_TO_SAVE: "Click Save Avatar to apply your new profile picture.",
    RECOMMENDED_SIZE: "Upload a profile picture. Recommended size: 400x400px",
    SUPPORTED_FORMATS: "Supported formats: JPEG, PNG, WebP, GIF (max 5MB)",
    ZOOM_WARNING_TITLE: "Image quality warning",
    ZOOM_WARNING_MESSAGE:
      "Zooming out too much may result in a small, pixelated image. Consider uploading a larger image or keeping zoom at 100% or higher.",
    ALT_TEXT: "Profile avatar",
    ALT_PREVIEW: "Preview",
    ZOOM_IN: "Zoom in",
    ZOOM_OUT: "Zoom out",
    FALLBACK_USER: "User",
    DEFAULT_INITIAL: "U",
  },

  // Admin content management
  ADMIN: {
    DASHBOARD: {
      TITLE: "Dashboard Overview",
      SUBTITLE: "System statistics and quick actions",
      QUICK_ACTIONS: "Quick Actions",
      RECENT_ACTIVITY: "Recent Activity",
      STATS: "Statistics",
      MANAGE_USERS: "Manage Users",
      REVIEW_DISABLED: "Review Disabled Accounts",
      MANAGE_CONTENT: "Manage Content",
      NEW_USERS: "New Users",
      SYSTEM_STATUS: "System Status",
      ALL_SYSTEMS_OPERATIONAL: "All systems operational",
      NEW_USERS_REGISTERED: (count: number) =>
        `${count} new ${count === 1 ? "user" : "users"} registered in the last 30 days`,
    },
    USERS: {
      TITLE: "Users",
      SUBTITLE: "Manage user accounts and permissions",
      DETAIL: "User Details",
      ALL: "All Users",
      ACTIVE: "Active",
      BANNED: "Banned",
      ADMINS: "Admins",
      SEARCH_PLACEHOLDER: "Search by name or email...",
      BAN_USER: "Ban User",
      UNBAN_USER: "Unban User",
      DELETE_USER: "Delete User",
      CHANGE_ROLE: "Change Role",
      NO_USERS_FOUND: "No users found",
      TOTAL_USERS: "Total Users",
      ACTIVE_USERS: "Active Users",
      BANNED_USERS: "Banned Users",
      ADMIN_USERS: "Admin Users",
      ROLE_UPDATE_FAILED: "Failed to update user role",
      BAN_FAILED: "Failed to update user ban status",
      DELETE_FAILED: "Failed to delete user",
      CONFIRM_ROLE_CHANGE: "Change role to",
      CONFIRM_BAN: "Are you sure you want to ban this user?",
      CONFIRM_UNBAN: "Are you sure you want to unban this user?",
      CONFIRM_DELETE:
        "PERMANENTLY DELETE this user? This action cannot be undone.",
      TYPE_DELETE_CONFIRM: 'Type "DELETE" to confirm:',
    },
    SITE: {
      TITLE: "Site Settings",
      SUBTITLE: "Configure global site settings, branding, and appearance",
      GENERAL: "General Settings",
      SEO: "SEO Settings",
      SECURITY: "Security Settings",
      SAVE_SETTINGS: "Save Settings",
      SAVE_ALL_CHANGES: "Save All Changes",
      SETTINGS_SAVED: "Settings saved successfully",
      SETTINGS_FAILED: "Failed to save settings",
      BASIC_INFO: "Basic Information",
      SITE_NAME: "Site Name",
      MOTTO: "Motto / Tagline",
      CONTACT_INFO: "Contact Information",
      SUPPORT_EMAIL: "Support Email",
      SUPPORT_PHONE: "Support Phone",
      ADDRESS: "Address",
      SOCIAL_LINKS: "Social Media Links",
      FACEBOOK: "Facebook",
      TWITTER: "Twitter",
      INSTAGRAM: "Instagram",
      LINKEDIN: "LinkedIn",
    },
    CAROUSEL: {
      TITLE: "Carousel Management",
      SUBTITLE: "Manage homepage carousel slides (max 5 active)",
      ADD_SLIDE: "Add Slide",
      CREATE_SLIDE: "Create Carousel Slide",
      EDIT_SLIDE: "Edit Carousel Slide",
      DELETE_SLIDE: "Delete Carousel Slide",
      REORDER_SLIDES: "Reorder Slides",
      NO_SLIDES: "No slides found",
      SAVE_FAILED: "Failed to save slide",
      DELETE_FAILED: "Failed to delete slide",
    },
    CATEGORIES: {
      TITLE: "Categories",
      SUBTITLE: "Manage product categories hierarchy",
      ADD_CATEGORY: "Add Category",
      CREATE_CATEGORY: "Create Category",
      EDIT_CATEGORY: "Edit Category",
      DELETE_CATEGORY: "Delete Category",
      NO_CATEGORIES: "No categories found",
      SAVE_FAILED: "Failed to save category",
      DELETE_FAILED: "Failed to delete category",
      CANNOT_DELETE_WITH_CHILDREN:
        "Cannot delete category with subcategories. Delete children first.",
      CANNOT_DELETE_WITH_PRODUCTS:
        "Cannot delete category with products/auctions. Move them first.",
      PARENT_CATEGORY: "Parent Category",
      NONE_ROOT: "None (Root Category)",
      SHOW_ON_HOMEPAGE: "Show on Homepage",
      ENABLED: "Enabled",
      TREE_VIEW: "Tree",
      TABLE_VIEW: "Table",
    },
    FAQS: {
      TITLE: "FAQs",
      SUBTITLE: "Manage frequently asked questions",
      ADD_FAQ: "Add FAQ",
      CREATE_FAQ: "Create FAQ",
      EDIT_FAQ: "Edit FAQ",
      DELETE_FAQ: "Delete FAQ",
      NO_FAQS: "No FAQs found",
      SAVE_FAILED: "Failed to save FAQ",
      DELETE_FAILED: "Failed to delete FAQ",
      CATEGORY: "Category",
      QUESTION: "Question",
      ANSWER: "Answer",
      PRIORITY: "Priority",
      PRIORITY_HELP: "Higher priority appears first",
      FEATURED: "Featured",
      FEATURED_LABEL: "Featured (show on homepage)",
      TAGS: "Tags (comma-separated)",
      TAGS_PLACEHOLDER: "e.g. payment, refund, shipping",
      ORDER_HELP: "Display order within same priority",
      SHOW_VARIABLES: "Show Variables",
      HIDE_VARIABLES: "Hide Variables",
      INSERT_VARIABLE_HELP: "Click to insert variable into answer:",
    },
    SECTIONS: {
      TITLE: "Homepage Sections",
      SUBTITLE: "Manage homepage sections and their order",
      ADD_SECTION: "Add Section",
      CREATE_SECTION: "Create Section",
      EDIT_SECTION: "Edit Section",
      DELETE_SECTION: "Delete Section",
      REORDER_SECTIONS: "Reorder Sections",
      NO_SECTIONS: "No sections found",
      SAVE_FAILED: "Failed to save section",
      DELETE_FAILED: "Failed to delete section",
      SECTION_TYPE: "Section Type",
      SECTION_ORDER: "Display Order",
      CONFIGURATION: "Configuration (JSON)",
    },
    REVIEWS: {
      TITLE: "Reviews",
      SUBTITLE: "Moderate product reviews",
      VIEW: "View Reviews",
      REVIEW_DETAILS: "Review Details",
      BACK_TO_LIST: "Back to List",
      APPROVE: "Approve",
      REJECT: "Reject",
      DELETE: "Delete",
      APPROVE_ALL: "Approve All Pending",
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      NO_REVIEWS: "No reviews found",
      REJECTION_REASON: "Rejection Reason",
      APPROVE_FAILED: "Failed to approve review",
      REJECT_FAILED: "Failed to reject review",
      DELETE_FAILED: "Failed to delete review",
      NO_PENDING: "No pending reviews to approve",
      VERIFIED: "Verified",
      VERIFIED_PURCHASE: "Verified Purchase",
      HELPFUL_VOTES: "Helpful Votes",
      PRODUCT: "Product",
      USER: "User",
      COMMENT: "Comment",
      RATING: "Rating",
      CREATED: "Created",
      ALL_RATINGS: "All Ratings",
      SEARCH_PLACEHOLDER: "Search products, users...",
    },
    PRODUCTS: {
      TITLE: "Products",
      SUBTITLE: "Manage all product listings",
      CREATE_PRODUCT: "Create Product",
      EDIT_PRODUCT: "Edit Product",
      DELETE_PRODUCT: "Delete Product",
      NO_PRODUCTS: "No products found",
      SAVE_FAILED: "Failed to save product",
      DELETE_FAILED: "Failed to delete product",
      TITLE_LABEL: "Title",
      DESCRIPTION_LABEL: "Description",
      CATEGORY_LABEL: "Category",
      SUBCATEGORY_LABEL: "Subcategory",
      BRAND_LABEL: "Brand",
      PRICE_LABEL: "Price (₹)",
      STOCK_LABEL: "Stock Quantity",
      STATUS_LABEL: "Status",
      SELLER_LABEL: "Seller",
      FEATURED_LABEL: "Featured",
      TAGS_LABEL: "Tags (comma-separated)",
      TAGS_PLACEHOLDER: "e.g. electronics, gadgets, sale",
      SHIPPING_LABEL: "Shipping Info",
      RETURN_POLICY_LABEL: "Return Policy",
      IS_AUCTION_LABEL: "Is Auction",
      AUCTION_END_DATE_LABEL: "Auction End Date",
      STARTING_BID_LABEL: "Starting Bid (₹)",
      IS_PROMOTED_LABEL: "Is Promoted",
      MAIN_IMAGE_LABEL: "Main Image URL",
      CONFIRM_DELETE:
        "Are you sure you want to delete this product? This cannot be undone.",
    },
    ORDERS: {
      TITLE: "Orders",
      SUBTITLE: "Manage all orders",
      VIEW: "View Orders",
      DETAILS: "Order Details",
      APPROVE: "Approve Order",
      REJECT: "Reject Order",
      ICON: "🛒",
      UPDATE_STATUS: "Update Status",
      FILTER_ALL: "All Orders",
      TRACKING_NUMBER: "Tracking Number",
      NOTES: "Admin Notes",
      UPDATE_ORDER: "Update Order",
      CANCELLATION_REASON: "Cancellation Reason",
    },
    BIDS: {
      TITLE: "Auctions & Bids",
      SUBTITLE: "Monitor all auction bids across the platform",
      ICON: "🏆",
      FILTER_ALL: "All Bids",
      FILTER_ACTIVE: "Active",
      FILTER_WON: "Won",
      FILTER_OUTBID: "Outbid",
      FILTER_CANCELLED: "Cancelled",
      BIDDER: "Bidder",
      PRODUCT: "Product",
      BID_AMOUNT: "Bid Amount",
      BID_DATE: "Bid Date",
      STATUS: "Status",
      WINNING: "Winning",
      VIEW_PRODUCT: "View Product",
      EMPTY: "No bids found",
      EMPTY_SUBTITLE: "No auction bids match your current filters.",
      TOTAL_BIDS: "Total Bids",
      ACTIVE_BIDS: "Active Bids",
      WON_BIDS: "Won Bids",
      TOTAL_VALUE: "Total Bid Value",
    },
    BLOG: {
      TITLE: "Blog Posts",
      SUBTITLE: "Manage blog content and articles",
      ICON: "📝",
      CREATE: "New Post",
      EDIT: "Edit Post",
      DELETE: "Delete Post",
      PUBLISH: "Publish",
      UNPUBLISH: "Unpublish to Draft",
      ARCHIVE: "Archive",
      EMPTY: "No blog posts found",
      EMPTY_SUBTITLE: "Create your first blog post to get started.",
      FILTER_ALL: "All Posts",
      FILTER_DRAFT: "Drafts",
      FILTER_PUBLISHED: "Published",
      FILTER_ARCHIVED: "Archived",
      FORM_TITLE: "Title",
      FORM_SLUG: "Slug",
      FORM_EXCERPT: "Excerpt",
      FORM_CONTENT: "Content",
      FORM_COVER: "Cover Image URL",
      FORM_CATEGORY: "Category",
      FORM_TAGS: "Tags (comma-separated)",
      FORM_STATUS: "Status",
      FORM_FEATURED: "Featured Post",
      FORM_READ_TIME: "Read Time (minutes)",
      TOTAL_POSTS: "Total Posts",
      PUBLISHED_POSTS: "Published",
      DRAFT_POSTS: "Drafts",
      FEATURED_POSTS: "Featured",
      VIEWS: "Views",
      READ_TIME: "min read",
      AUTHOR: "Author",
      PUBLISHED_ON: "Published on",
      TAGS: "Tags",
      RELATED: "Related Articles",
    },
    COUPONS: {
      TITLE: "Coupons",
      SUBTITLE: "Manage discount coupons",
      ICON: "🏷️",
      CREATE: "Create Coupon",
      EDIT: "Edit Coupon",
      DELETE: "Delete Coupon",
      DEACTIVATE: "Deactivate",
      REACTIVATE: "Reactivate",
      NO_COUPONS: "No coupons found",
      CODE_LABEL: "Coupon Code",
      NAME_LABEL: "Name",
      DESCRIPTION_LABEL: "Description",
      TYPE_LABEL: "Coupon Type",
      DISCOUNT_LABEL: "Discount Value",
      MAX_DISCOUNT_LABEL: "Max Discount (optional)",
      MIN_PURCHASE_LABEL: "Min Purchase Amount (optional)",
      TOTAL_LIMIT_LABEL: "Total Usage Limit (optional)",
      PER_USER_LIMIT_LABEL: "Per-User Limit (optional)",
      START_DATE_LABEL: "Start Date",
      END_DATE_LABEL: "End Date (optional)",
      IS_ACTIVE_LABEL: "Active",
      FIRST_TIME_ONLY_LABEL: "First-Time Users Only",
      STATS: "Usage Stats",
    },
    SESSIONS: {
      TITLE: "Sessions",
      SUBTITLE: "Manage user sessions",
      CONFIRM_REVOKE: "Revoke Session",
      CONFIRM_REVOKE_MESSAGE:
        "Are you sure you want to revoke this session? The user will be logged out.",
      CONFIRM_REVOKE_ALL: "Revoke All Sessions",
      CONFIRM_REVOKE_ALL_MESSAGE:
        "Are you sure you want to revoke all sessions? All users will be logged out.",
    },
    CONTENT: {
      TITLE: "Content Management",
      SUBTITLE: "Manage products, orders, and reviews",
      PRODUCTS: {
        TITLE: "Products",
        SUBTITLE: "Manage all product listings",
        VIEW: "View Products",
        CREATE: "Create Product",
        EDIT: "Edit Product",
        DELETE: "Delete Product",
        ICON: "📦",
      },
      ORDERS: {
        TITLE: "Orders",
        SUBTITLE: "Manage all orders",
        VIEW: "View Orders",
        DETAILS: "Order Details",
        APPROVE: "Approve Order",
        REJECT: "Reject Order",
        ICON: "🛒",
        UPDATE_STATUS: "Update Status",
        FILTER_ALL: "All Orders",
        TRACKING_NUMBER: "Tracking Number",
        NOTES: "Admin Notes",
        UPDATE_ORDER: "Update Order",
        CANCELLATION_REASON: "Cancellation Reason",
      },
      REVIEWS: {
        TITLE: "Reviews",
        SUBTITLE: "Moderate user reviews",
        VIEW: "View Reviews",
        APPROVE: "Approve Review",
        REJECT: "Reject Review",
        DELETE: "Delete Review",
        ICON: "⭐",
      },
      COMING_SOON: {
        TITLE: "Content Management Coming Soon",
        MESSAGE:
          "Advanced content management features are currently under development",
        ICON: "🚧",
      },
    },
    MEDIA: {
      TITLE: "Media Operations",
      SUBTITLE: "Manage image cropping and video trimming",
      CROP_IMAGE: "Crop Image",
      TRIM_VIDEO: "Trim Video",
      SOURCE_URL: "Source URL",
      SOURCE_URL_PLACEHOLDER: "https://example.com/image.jpg",
      OUTPUT_FORMAT: "Output Format",
      QUALITY: "Quality",
      QUALITY_HIGH: "High (90)",
      QUALITY_MEDIUM: "Medium (75)",
      QUALITY_LOW: "Low (60)",
      CROP_PARAMETERS: "Crop Parameters",
      X_POSITION: "X Position",
      Y_POSITION: "Y Position",
      WIDTH: "Width",
      HEIGHT: "Height",
      TRIM_PARAMETERS: "Trim Parameters",
      START_TIME: "Start Time (seconds)",
      END_TIME: "End Time (seconds)",
      VIDEO_QUALITY: "Video Quality",
      QUALITY_LOW_LABEL: "Low (500k/64k)",
      QUALITY_MEDIUM_LABEL: "Medium (1000k/128k)",
      QUALITY_HIGH_LABEL: "High (2500k/192k)",
      RECENT_OPERATIONS: "Recent Operations",
      NO_OPERATIONS: "No media operations yet",
      OPERATION_TYPE: "Operation Type",
      OPERATION_STATUS: "Status",
      PROCESSING: "Processing",
      COMPLETED: "Completed",
      FAILED: "Failed",
      DOWNLOAD_RESULT: "Download Result",
      COPY_URL: "Copy URL",
      URL_COPIED: "URL copied to clipboard",
    },
  },

  // User section labels
  USER: {
    PROFILE: {
      TITLE: "My Profile",
      EDIT: "Edit Profile",
      VIEW: "View Profile",
      INFORMATION: "Profile Information",
      ACCOUNT_INFO: "Account Information",
      SECURITY: "Security Settings",
    },
    SETTINGS: {
      TITLE: "Settings",
      SUBTITLE: "Manage your account preferences",
      GENERAL: "General",
      SECURITY: "Security",
      NOTIFICATIONS: "Notifications",
      PRIVACY: "Privacy",
    },
    ORDERS: {
      TITLE: "My Orders",
      SUBTITLE: "View and manage your orders",
      EMPTY: "No orders yet",
      EMPTY_SUBTITLE: "Start shopping to see your orders here",
      VIEW_ORDER: "View Order",
      ORDER_DETAILS: "Order Details",
      ORDER_NUMBER: "Order Number",
      ORDER_DATE: "Order Date",
      ORDER_STATUS: "Order Status",
      ORDER_TOTAL: "Order Total",
      BACK_TO_ORDERS: "Back to Orders",
      ORDER_NOT_FOUND: "Order not found",
      ORDER_NOT_FOUND_MESSAGE:
        "The order you're looking for doesn't exist or has been removed.",
      VIEW_ALL_ORDERS: "View All Orders",
      BROWSE_PRODUCTS: "Browse Products",
      ORDER_ITEMS: "Order Items",
      ORDER_SUMMARY: "Order Summary",
      SUBTOTAL: "Subtotal",
      SHIPPING: "Shipping",
      TAX: "Tax",
      TOTAL: "Total",
      SHIPPING_ADDRESS: "Shipping Address",
      PAYMENT_INFO: "Payment Information",
      PAYMENT_METHOD: "Payment Method",
      PAYMENT_STATUS: "Payment Status",
      PAID: "Paid",
      TRACK_ORDER: "Track Order",
      QUANTITY: "Quantity",
      EACH: "each",
      PLACED_ON: "Placed on",
    },
    WISHLIST: {
      TITLE: "My Wishlist",
      SUBTITLE: "Items you've saved for later",
      EMPTY: "Your wishlist is empty",
      EMPTY_SUBTITLE: "Save items you love to your wishlist",
      ADD_TO_CART: "Add to Cart",
      REMOVE: "Remove from Wishlist",
      ITEMS: "Wishlist Items",
    },
    ADDRESSES: {
      TITLE: "My Addresses",
      SUBTITLE: "Manage your delivery addresses",
      ADD: "Add New Address",
      ADD_FIRST: "Add Your First Address",
      EDIT: "Edit Address",
      DELETE: "Delete Address",
      DELETE_CONFIRM_TITLE: "Delete Address?",
      DELETE_CONFIRM_MESSAGE:
        "Are you sure you want to delete this address? This action cannot be undone.",
      DELETE_CONFIRM:
        "Are you sure you want to delete this address? This action cannot be undone.",
      EMPTY: "No saved addresses",
      EMPTY_SUBTITLE: "Add an address to use for shipping",
      DEFAULT: "Default Address",
      SET_DEFAULT: "Set as Default",
      SHIPPING_ADDRESS: "Shipping Address",
      BILLING_ADDRESS: "Billing Address",
    },
  },

  // Modal labels
  MODALS: {
    CONFIRM_DELETE: "Delete Confirmation",
    CONFIRM_ACTION: "Confirm Action",
    ARE_YOU_SURE: "Are you sure?",
    CANNOT_UNDO: "This action cannot be undone.",
  },

  // Homepage section labels
  HOMEPAGE: {
    HERO: {
      TITLE: "Welcome to LetItRip",
      SUBTITLE: "Discover amazing products and deals",
      CTA: "Shop Now",
      LEARN_MORE: "Learn More",
    },
    TRUST_INDICATORS: {
      TITLE: "Why Shop With Us?",
      SECURE: "Secure Payments",
      SHIPPING: "Fast Shipping",
      RETURNS: "Easy Returns",
      SUPPORT: "24/7 Support",
    },
    FEATURES: {
      TITLE: "Why Shop With Us?",
      SUBTITLE:
        "Your satisfaction is our priority. We provide a seamless shopping experience with unmatched features",
      QUALITY: "Premium Quality",
      PRICE: "Best Prices",
      SERVICE: "Excellent Service",
      WARRANTY: "Warranty Included",
    },
    NEWSLETTER: {
      TITLE: "Stay Updated",
      SUBTITLE: "Subscribe to our newsletter for exclusive deals",
      PLACEHOLDER: "Enter your email",
      BUTTON: "Subscribe",
      SUCCESS: "Successfully subscribed!",
      ERROR: "Subscription failed. Please try again.",
      PRIVACY_NOTE:
        "We respect your privacy. Unsubscribe at any time. Read our",
    },
    REVIEWS: {
      TITLE: "What Our Customers Say",
      SUBTITLE: "Read reviews from satisfied customers",
      VIEW_ALL: "View All Reviews",
      NO_REVIEWS: "No reviews yet",
    },
    AUCTIONS: {
      TITLE: "Live Auctions",
      SUBTITLE: "Bid on exclusive items",
      VIEW_ALL: "View All Auctions",
      NO_AUCTIONS: "No active auctions",
      ENDS_IN: "Ends in",
      CURRENT_BID: "Current Bid",
      PLACE_BID: "Place Bid",
    },
    CATEGORIES: {
      TITLE: "Shop by Category",
      SUBTITLE: "Browse our extensive collection",
      VIEW_ALL: "View All Categories",
    },
    FEATURED_PRODUCTS: {
      TITLE: "Featured Products",
      SUBTITLE: "Handpicked items just for you",
      VIEW_ALL: "View All Products",
    },
    BLOG: {
      TITLE: "From Our Blog",
      SUBTITLE: "Tips, stories, and insights from the community",
    },
  },

  // Products listing page labels
  PRODUCTS_PAGE: {
    TITLE: "Products",
    SUBTITLE: "Discover amazing products and deals",
    NO_PRODUCTS: "No products found",
    NO_PRODUCTS_SUBTITLE: "Try adjusting your filters or search term",
    FILTERS: "Filters",
    CLEAR_FILTERS: "Clear Filters",
    SORT_BY: "Sort By",
    SHOWING: (count: number, total: number) =>
      `Showing ${count} of ${total} products`,
    SORT_OPTIONS: {
      NEWEST: "Newest First",
      OLDEST: "Oldest First",
      PRICE_LOW: "Price: Low to High",
      PRICE_HIGH: "Price: High to Low",
      NAME_AZ: "Name: A to Z",
      NAME_ZA: "Name: Z to A",
    },
    FILTER_CATEGORY: "Category",
    FILTER_ALL_CATEGORIES: "All Categories",
    FILTER_PRICE_RANGE: "Price Range",
    FILTER_MIN_PRICE: "Min Price",
    FILTER_MAX_PRICE: "Max Price",
    FILTER_STATUS: "Status",
    FILTER_ALL_STATUSES: "All Statuses",
    LOAD_MORE: "Load More",
    ADD_TO_CART: "Add to Cart",
    VIEW_DETAILS: "View Details",
    IN_STOCK: "In Stock",
    OUT_OF_STOCK: "Out of Stock",
    SOLD: "Sold",
    AUCTION: "Auction",
    FEATURED_BADGE: "Featured",
    PROMOTED_BADGE: "Promoted",
  },

  // Categories listing page labels
  CATEGORIES_PAGE: {
    TITLE: "Categories",
    SUBTITLE: "Browse all product categories",
    ALL_CATEGORIES: "All Categories",
    TOP_LEVEL: "Top-Level Categories",
    NO_CATEGORIES: "No categories found",
    NO_CATEGORIES_SUBTITLE: "Check back soon for new categories",
    PRODUCTS_COUNT: (count: number) =>
      count === 1 ? "1 product" : `${count} products`,
    VIEW_PRODUCTS: "View Products",
    SUBCATEGORIES: "Subcategories",
    SUBCATEGORIES_COUNT: (count: number) =>
      count === 1 ? "1 subcategory" : `${count} subcategories`,
    FEATURED: "Featured",
    BACK_TO_CATEGORIES: "Back to Categories",
    ALL_PRODUCTS_IN: (name: string) => `All products in ${name}`,
    NO_PRODUCTS_IN: (name: string) => `No products found in ${name}`,
  },

  // Search page labels
  SEARCH_PAGE: {
    TITLE: "Search",
    SUBTITLE: "Find products across the store",
    PLACEHOLDER: "Search for products...",
    NO_RESULTS: "No results found",
    NO_RESULTS_SUBTITLE: (q: string) =>
      `We couldn't find anything matching "${q}". Try a different search term.`,
    RESULTS_COUNT: (count: number, q: string) =>
      `${count} result${count !== 1 ? "s" : ""} for "${q}"`,
    SEARCHING: "Searching...",
    FILTERS: "Filters",
    CLEAR_FILTERS: "Clear Filters",
    PRICE_RANGE: "Price Range",
    MIN_PRICE: "Min price",
    MAX_PRICE: "Max price",
    CATEGORY_FILTER: "Category",
    ALL_CATEGORIES: "All Categories",
    EMPTY_QUERY: "Start typing to search for products",
  },

  // Auctions listing page labels
  AUCTIONS_PAGE: {
    TITLE: "Live Auctions",
    SUBTITLE: "Bid on unique items — auctions ending soon",
    NO_AUCTIONS: "No active auctions",
    NO_AUCTIONS_SUBTITLE: "Check back soon for new auction listings",
    CURRENT_BID: "Current Bid",
    STARTING_BID: "Starting Bid",
    BID_COUNT: (count: number) => `${count} bid${count !== 1 ? "s" : ""}`,
    ENDS_IN: "Ends in",
    ENDED: "Auction Ended",
    PLACE_BID: "Place Bid",
    VIEW_AUCTION: "View Auction",
    LIVE_BADGE: "LIVE",
    ENDING_SOON: "Ending Soon",
    SORT_ENDING_SOON: "Ending Soonest",
    SORT_LOWEST_BID: "Lowest Bid",
    SORT_HIGHEST_BID: "Highest Bid",
    SORT_MOST_BIDS: "Most Bids",
    RESULTS_COUNT: (count: number) =>
      `${count} active auction${count !== 1 ? "s" : ""}`,
    // Bid history labels
    BID_HISTORY_TITLE: "Bid History",
    BID_HISTORY_EMPTY: "No bids yet — be the first to bid!",
    WINNING_BID: "Winning Bid",
    // Place bid form labels
    YOUR_BID_LABEL: "Your Bid Amount",
    MINIMUM_BID: (amount: string) => `Minimum bid: ${amount}`,
    LOGIN_TO_BID: "Login to place a bid",
    AUCTION_ENDED_INFO:
      "This auction has ended and is no longer accepting bids",
    BID_PLACED: "Bid placed successfully!",
  },

  // Seller dashboard page labels
  SELLER_PAGE: {
    TITLE: "Seller Dashboard",
    SUBTITLE: "Manage your listings, orders, and earnings",
    TOTAL_PRODUCTS: "Total Products",
    ACTIVE_LISTINGS: "Active Listings",
    DRAFT_PRODUCTS: "Draft Products",
    ACTIVE_AUCTIONS: "Active Auctions",
    QUICK_ACTIONS: "Quick Actions",
    ADD_PRODUCT: "Add New Listing",
    VIEW_PRODUCTS: "View All Products",
    VIEW_SALES: "View Sales",
    VIEW_AUCTIONS: "View Auctions",
    NO_PRODUCTS: "No products yet",
    NO_PRODUCTS_SUBTITLE: "Start by adding your first listing",
    LOADING_STATS: "Loading dashboard stats...",
    WELCOME: (name: string) => `Welcome back, ${name}`,
    LISTING_STAT_LABEL: "listings",
    AUCTION_STAT_LABEL: "active auctions",
    // Products list page
    PRODUCTS_TITLE: "My Products",
    PRODUCTS_SUBTITLE: "Manage and update your store listings",
    CREATE_LISTING_TITLE: "Create New Listing",
    EDIT_LISTING_TITLE: "Edit Listing",
    DELETE_LISTING_CONFIRM:
      "Are you sure you want to delete this listing? This action cannot be undone.",
    PUBLISH_ACTION: "Publish",
    UNPUBLISH_ACTION: "Unpublish",
    SAVE_LISTING: "Save Listing",
    SAVING: "Saving...",
    // Orders page
    ORDERS_TITLE: "My Sales",
    ORDERS_SUBTITLE: "Orders placed for your products",
    ORDERS_EMPTY: "No orders yet",
    ORDERS_EMPTY_SUBTITLE:
      "When customers purchase your products, orders will appear here",
    ORDER_ID: "Order ID",
    BUYER: "Buyer",
    PRODUCT_SOLD: "Product",
    ORDER_DATE: "Order Date",
    ORDER_AMOUNT: "Amount",
    ORDER_STATUS: "Status",
  },

  // Product detail page labels
  PRODUCT_DETAIL: {
    BACK_TO_PRODUCTS: "Back to Products",
    ADD_TO_CART: "Add to Cart",
    BUY_NOW: "Buy Now",
    OUT_OF_STOCK: "Out of Stock",
    SOLD: "Sold",
    DESCRIPTION: "Description",
    SPECIFICATIONS: "Specifications",
    FEATURES: "Features",
    SHIPPING: "Shipping",
    RETURN_POLICY: "Return Policy",
    SELLER: "Seller",
    BRAND: "Brand",
    CATEGORY: "Category",
    AVAILABLE_STOCK: (qty: number) => `${qty} in stock`,
    AUCTION_ENDS: "Auction ends",
    CURRENT_BID: "Current Bid",
    STARTING_BID: "Starting Bid",
    PLACE_BID: "Place Bid",
    TOTAL_BIDS: (count: number) => `${count} bid${count !== 1 ? "s" : ""}`,
    REVIEWS_TITLE: "Customer Reviews",
    REVIEWS_NONE: "No reviews yet",
    REVIEWS_BE_FIRST: "Be the first to review this product",
    WRITE_REVIEW: "Write a Review",
    AVERAGE_RATING: "Average Rating",
    VERIFIED_PURCHASE: "Verified Purchase",
    HELPFUL: (count: number) => `${count} found this helpful`,
    RELATED_TITLE: "You might also like",
    PRODUCT_NOT_FOUND: "Product not found",
    PRODUCT_NOT_FOUND_SUBTITLE:
      "This product may have been removed or the link is incorrect",
    SHARE: "Share",
    COPY_LINK: "Copy Link",
    LINK_COPIED: "Link copied!",
  },

  // Cart page labels
  CART: {
    TITLE: "Shopping Cart",
    EMPTY: "Your cart is empty",
    EMPTY_SUBTITLE: "Browse products and add items to your cart",
    START_SHOPPING: "Start Shopping",
    ITEM_COUNT: (count: number) => `${count} item${count !== 1 ? "s" : ""}`,
    REMOVE: "Remove",
    QUANTITY: "Qty",
    PRICE: "Price",
    SUBTOTAL: "Subtotal",
    PROMO_CODE: "Promo Code",
    PROMO_PLACEHOLDER: "Enter code",
    PROMO_APPLY: "Apply",
    PROMO_APPLIED: "Promo applied!",
    PROMO_INVALID: "Invalid promo code",
    PROMO_REMOVE: "Remove",
    DISCOUNT: "Discount",
    DISCOUNT_APPLIED: (code: string) => `Coupon "${code}" applied`,
    ORDER_SUMMARY: "Order Summary",
    ITEMS_SUBTOTAL: "Items Subtotal",
    SHIPPING: "Shipping",
    SHIPPING_FREE: "Free",
    SHIPPING_CALCULATED: "Calculated at checkout",
    TAX: "Tax",
    TAX_CALCULATED: "Calculated at checkout",
    TOTAL: "Total",
    CHECKOUT: "Proceed to Checkout",
    CONTINUE_SHOPPING: "Continue Shopping",
    UPDATING: "Updating...",
    UPDATE_QUANTITY: "Update quantity",
  },

  // Checkout page labels
  CHECKOUT: {
    TITLE: "Checkout",
    STEP_ADDRESS: "Shipping Address",
    STEP_REVIEW: "Review Order",
    STEP_PAYMENT: "Payment",
    STEP_1_OF_2: "Step 1 of 2",
    STEP_2_OF_2: "Step 2 of 2",
    SELECT_ADDRESS: "Select a shipping address",
    NO_ADDRESSES: "No saved addresses",
    ADD_ADDRESS: "Add a New Address",
    DELIVERY_TO: "Deliver to",
    CHANGE_ADDRESS: "Change",
    REVIEW_TITLE: "Review Your Order",
    ORDER_ITEMS: "Order Items",
    SHIPPING_TO: "Shipping To",
    PAYMENT_METHOD: "Payment Method",
    COD: "Cash on Delivery",
    ONLINE_PAYMENT: "Online Payment",
    ONLINE_PAYMENT_HINT: "(Razorpay — coming soon)",
    PLACE_ORDER: "Place Order",
    PLACING_ORDER: "Placing Order...",
    BACK_TO_CART: "Back to Cart",
    ORDER_TOTAL: "Order Total",
    ITEMS_SUBTOTAL: "Items Subtotal",
    SHIPPING_FREE: "Free",
    TAX_INCLUDED: "Inclusive of taxes",
    CONFIRM_TITLE: "Confirm your order",
    PAYMENT_ON_DELIVERY: "You will pay on delivery",
  },
  // Content & Trust pages
  ABOUT_PAGE: {
    TITLE: "About LetItRip",
    SUBTITLE:
      "Connecting buyers, sellers, and bidders in one vibrant marketplace",
    MISSION_TITLE: "Our Mission",
    MISSION_TEXT:
      "LetItRip was built to democratise commerce — giving independent sellers a powerful platform to reach buyers, and giving buyers access to a diverse catalogue of unique products and exciting live auctions.",
    HOW_IT_WORKS_TITLE: "How It Works",
    HOW_BUYERS_TITLE: "For Buyers",
    HOW_BUYERS_TEXT:
      "Browse thousands of products, place auction bids in real time, and shop with confidence knowing every transaction is protected.",
    HOW_SELLERS_TITLE: "For Sellers",
    HOW_SELLERS_TEXT:
      "Create your seller account, list your products or auction items, and start earning. Our tools make inventory and order management simple.",
    HOW_BIDDERS_TITLE: "For Bidders",
    HOW_BIDDERS_TEXT:
      "Join live auctions, set auto-bid limits, and win unique items at prices you decide.",
    VALUES_TITLE: "Our Values",
    VALUES_TRUST: "Trust & Safety",
    VALUES_TRUST_TEXT:
      "Every seller is verified and every transaction is monitored for your protection.",
    VALUES_COMMUNITY: "Community First",
    VALUES_COMMUNITY_TEXT:
      "We nurture a fair, inclusive marketplace where every voice matters.",
    VALUES_INNOVATION: "Continuous Innovation",
    VALUES_INNOVATION_TEXT:
      "We keep improving our platform based on feedback from buyers and sellers.",
    TEAM_TITLE: "Meet the Team",
    TEAM_SUBTITLE: "The people behind LetItRip",
    MILESTONES_TITLE: "Our Journey",
    MILESTONE_FOUNDED:
      "Founded with a vision to simplify multi-seller commerce in India",
    MILESTONE_AUCTIONS:
      "Launched real-time auction engine with auto-bid support",
    MILESTONE_MOBILE: "Mobile-first redesign reaching thousands of new users",
    CTA_TITLE: "Ready to get started?",
    CTA_SELL: "Become a Seller",
    CTA_SHOP: "Start Shopping",
  },

  CONTACT_PAGE: {
    TITLE: "Contact Us",
    SUBTITLE:
      "We'd love to hear from you — reach out with any questions or feedback",
    FORM_TITLE: "Send a Message",
    FORM_NAME: "Your Name",
    FORM_EMAIL: "Email Address",
    FORM_SUBJECT: "Subject",
    FORM_MESSAGE: "Message",
    FORM_SEND: "Send Message",
    FORM_SENDING: "Sending...",
    FORM_SUCCESS: "Your message has been sent! We'll get back to you shortly.",
    FORM_ERROR: "Failed to send your message. Please try again.",
    INFO_TITLE: "Get in Touch",
    INFO_EMAIL_LABEL: "Email",
    INFO_PHONE_LABEL: "Phone",
    INFO_ADDRESS_LABEL: "Address",
    INFO_HOURS_LABEL: "Support Hours",
    INFO_HOURS_VALUE: "Monday – Friday, 9 AM – 6 PM IST",
    FAQ_LINK: "Check our FAQ page for quick answers",
  },

  HELP_PAGE: {
    TITLE: "Help Center",
    SUBTITLE: "Find quick answers to common questions",
    SEARCH_PLACEHOLDER: "Search help articles...",
    BROWSE_TITLE: "Browse Topics",
    TOPIC_ORDERS: "Orders & Shipping",
    TOPIC_PAYMENTS: "Payments & Refunds",
    TOPIC_ACCOUNT: "Account & Profile",
    TOPIC_SELLING: "Selling on LetItRip",
    TOPIC_AUCTIONS: "Auctions & Bidding",
    POPULAR_TITLE: "Popular Questions",
    CONTACT_PROMPT: "Still need help?",
    CONTACT_LINK: "Contact our support team",
    FAQS_LINK: "Browse all FAQs",
  },

  TERMS_PAGE: {
    TITLE: "Terms & Conditions",
    SUBTITLE: "Please read these terms carefully before using LetItRip",
    LAST_UPDATED: "Last updated: January 1, 2025",
    ACCEPTANCE_TITLE: "1. Acceptance of Terms",
    ACCEPTANCE_TEXT:
      "By accessing or using the LetItRip platform, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree, please do not use our services.",
    USE_TITLE: "2. Use of the Platform",
    USE_TEXT:
      "You may use LetItRip for lawful purposes only. You agree not to use the platform to post fraudulent listings, harass other users, or circumvent our payment and security systems.",
    ACCOUNTS_TITLE: "3. User Accounts",
    ACCOUNTS_TEXT:
      "You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorised use of your account.",
    SELLERS_TITLE: "4. Seller Responsibilities",
    SELLERS_TEXT:
      "Sellers are responsible for accurate product descriptions, timely shipping, and honouring return policies. LetItRip reserves the right to remove listings that violate these terms.",
    AUCTIONS_TITLE: "5. Auction Rules",
    AUCTIONS_TEXT:
      "All bids placed in auctions are binding. Winning bidders must complete the purchase. Bid manipulation or shill bidding is strictly prohibited.",
    LIABILITY_TITLE: "6. Limitation of Liability",
    LIABILITY_TEXT:
      "LetItRip is not liable for any indirect, incidental, or consequential damages arising from your use of the platform, including disputes between buyers and sellers.",
    CHANGES_TITLE: "7. Changes to Terms",
    CHANGES_TEXT:
      "We may update these terms at any time. Continued use of the platform constitutes acceptance of the updated terms.",
    CONTACT_TITLE: "Questions?",
    CONTACT_TEXT:
      "Contact us at legal@letitrip.in for any questions about these terms.",
  },

  PRIVACY_PAGE: {
    TITLE: "Privacy Policy",
    SUBTITLE: "Your privacy matters to us",
    LAST_UPDATED: "Last updated: January 1, 2025",
    INTRO_TITLE: "Introduction",
    INTRO_TEXT:
      'LetItRip ("we", "our", "us") is committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our platform.',
    COLLECT_TITLE: "1. Information We Collect",
    COLLECT_TEXT:
      "We collect information you provide directly (name, email, address, payment details) and information collected automatically (device data, usage logs, cookies) to provide and improve our services.",
    USE_TITLE: "2. How We Use Your Information",
    USE_TEXT:
      "We use your information to process orders, facilitate auctions, communicate with you, prevent fraud, and improve our platform. We do not sell your personal data to third parties.",
    SHARE_TITLE: "3. Sharing Your Information",
    SHARE_TEXT:
      "We may share your information with sellers to fulfil orders, with payment processors, and with service providers who assist our operations — all bound by confidentiality obligations.",
    SECURITY_TITLE: "4. Data Security",
    SECURITY_TEXT:
      "We implement industry-standard security measures including encryption, secure access controls, and regular security audits to protect your data.",
    RIGHTS_TITLE: "5. Your Rights",
    RIGHTS_TEXT:
      "You have the right to access, update, or delete your personal data at any time from your account settings. You may also opt out of marketing communications.",
    COOKIES_TITLE: "6. Cookies",
    COOKIES_TEXT:
      "We use cookies to maintain your session, remember preferences, and analyse site usage. You can manage cookie preferences in your browser settings.",
    CHANGES_TITLE: "7. Changes to this Policy",
    CHANGES_TEXT:
      "We may update this policy periodically. We will notify you of significant changes by email or via a notice on our platform.",
    CONTACT_TITLE: "Contact",
    CONTACT_TEXT:
      "For privacy-related queries, contact us at privacy@letitrip.in.",
  },

  SELLERS_PAGE: {
    TITLE: "Sell on LetItRip",
    SUBTITLE: "Reach thousands of buyers. Your own storefront. Zero hassle.",
    HERO_CTA: "Start Selling Today",
    HERO_SECONDARY: "Learn how it works",
    WHY_TITLE: "Why Sell on LetItRip?",
    BENEFIT_REACH: "Massive Reach",
    BENEFIT_REACH_TEXT:
      "Access thousands of active buyers searching for products just like yours.",
    BENEFIT_TOOLS: "Powerful Tools",
    BENEFIT_TOOLS_TEXT:
      "Manage inventory, track orders, run auctions, and analyse your sales — all in one dashboard.",
    BENEFIT_TRUST: "Built-in Trust",
    BENEFIT_TRUST_TEXT:
      "Buyer protection and seller verification give customers the confidence to spend.",
    BENEFIT_FEES: "Competitive Fees",
    BENEFIT_FEES_TEXT:
      "Keep more of what you earn with our transparent, low-fee structure.",
    HOW_TITLE: "How to Get Started",
    STEP_1_TITLE: "Create a Seller Account",
    STEP_1_TEXT:
      "Sign up for free and complete your seller profile in minutes.",
    STEP_2_TITLE: "List Your Products",
    STEP_2_TEXT:
      "Add products or auction items with photos, descriptions, and pricing.",
    STEP_3_TITLE: "Start Selling",
    STEP_3_TEXT:
      "Receive orders, ship products, and get paid directly to your account.",
    TESTIMONIALS_TITLE: "What Our Sellers Say",
    FAQ_TITLE: "Seller FAQs",
    FAQ_1_Q: "How much does it cost to sell?",
    FAQ_1_A:
      "Creating your seller account is free. We charge a small commission per completed sale.",
    FAQ_2_Q: "How do I get paid?",
    FAQ_2_A:
      "Payouts are processed to your registered bank account after order confirmation.",
    FAQ_3_Q: "Can I run auctions?",
    FAQ_3_A:
      "Yes! You can list any product as an auction with a starting bid and end date.",
    CTA_TITLE: "Ready to grow your business?",
    CTA_BUTTON: "Create Seller Account",
    SIGN_IN_PROMPT: "Already have an account?",
    SIGN_IN_LINK: "Sign in",
  },

  FOOTER: {
    QUICK_LINKS: "Quick Links",
    ABOUT_US: "About Us",
    CONTACT: "Contact",
    BLOG: "Blog",
    PRIVACY_POLICY: "Privacy Policy",
    TERMS_OF_SERVICE: "Terms of Service",
    HELP_CENTER: "Help Center",
    FAQS: "FAQs",
    SHIPPING_INFO: "Shipping Information",
    RETURNS: "Returns & Exchanges",
    SOCIAL_MEDIA: "Follow Us",
    CONNECT: "Connect",
    NEWSLETTER: "Newsletter",
    SUBSCRIBE: "Subscribe",
    COPYRIGHT: "© {year} {brand}. All rights reserved.",
    COMPANY: "Company",
    SUPPORT: "Support",
    LEGAL: "Legal",
  },

  // FAQ section
  FAQ: {
    TITLE: "Frequently Asked Questions",
    SUBTITLE:
      "Find answers to common questions about our platform, products, shipping, and more.",
    WAS_THIS_HELPFUL: "Was this helpful?",
    HELPFUL: "Helpful",
    NOT_HELPFUL: "Not Helpful",
    RELATED_QUESTIONS: "Related Questions",
    VIEW_ALL: "View All FAQs",
    SEARCH_PLACEHOLDER: "Search FAQs...",
    QUESTION_SINGULAR: "question",
    QUESTION_PLURAL: "questions",
    IN_CATEGORY: "in",
  },
} as const;

export const UI_PLACEHOLDERS = {
  EMAIL: "Enter your email address",
  PASSWORD: "Enter your password",
  CURRENT_PASSWORD: "Enter current password",
  NEW_PASSWORD: "Enter new password",
  CONFIRM_PASSWORD: "Confirm your password",
  SEARCH: "Search...",
  PHONE: "Enter phone number",
  NAME: "Enter your name",
  FIRST_NAME: "Enter first name",
  LAST_NAME: "Enter last name",
  DISPLAY_NAME: "Enter display name",
  MESSAGE: "Enter your message",
  DESCRIPTION: "Enter description",
  TITLE: "Enter title",
  ADDRESS: "Enter address",
  CITY: "Enter city",
  STATE: "Enter state/province",
  ZIP_CODE: "Enter ZIP/postal code",
  COUNTRY: "Select country",
  QUESTION: "Enter your question",
  ANSWER: "Enter the answer",
  CODE: "Enter code",
  PRICE: "Enter price",
  QUANTITY: "Enter quantity",
} as const;

export const UI_HELP_TEXT = {
  PASSWORD_REQUIREMENTS:
    "Must be at least 8 characters with uppercase, lowercase, and number",
  PHONE_FORMAT: "Format: +[country code][number]",
  PHONE_10_DIGIT: "Enter 10-digit mobile number",
  EMAIL_VERIFICATION: "Please verify your email to access all features",
  AVATAR_UPLOAD: "Upload a profile picture. Recommended size: 400x400px",
  AVATAR_FORMATS: "Supported formats: JPEG, PNG, WebP, GIF (max 5MB)",
} as const;
