/**
 * Utils Barrel Export
 *
 * App-specific utilities live locally. Generic helpers come from @mohasinac/appkit.
 */

// ------- Validators (delegated to appkit) -------
export {
  isValidEmail,
  isValidEmailDomain,
  normalizeEmail,
  isDisposableEmail,
  meetsPasswordRequirements,
  calculatePasswordStrength,
  isCommonPassword,
  isValidPhone,
  normalizePhone,
  formatPhone,
  extractCountryCode,
  isValidIndianMobile,
  isValidIndianPincode,
  isValidUrl,
  isValidUrlWithProtocol,
  isExternalUrl,
  sanitizeUrl,
  isRequired,
  minLength,
  maxLength,
  exactLength,
  isNumeric,
  inRange,
  matchesPattern,
  isInList,
} from "@mohasinac/appkit/validation";
export type {
  PasswordStrength,
  PasswordRequirements,
} from "@mohasinac/appkit/validation";

// ------- Formatters (delegated to appkit) -------
export {
  resolveDate,
  formatDate,
  formatDateTime,
  formatTime,
  formatRelativeTime,
  formatMonthYear,
  formatDateRange,
  isToday,
  isPast,
  isFuture,
  nowMs,
  isSameMonth,
  currentYear,
  nowISO,
  formatCustomDate,
  formatCurrency,
  formatNumber,
  formatPercentage,
  formatFileSize,
  formatCompactNumber,
  formatDecimal,
  formatOrdinal,
  parseFormattedNumber,
  capitalize,
  capitalizeWords,
  truncate,
  truncateWords,
  stripHtml,
  escapeHtml,
  slugify,
  maskString,
  randomString,
  isEmptyString,
  proseMirrorToHtml,
} from "@mohasinac/appkit/utils";

// ------- Converters (delegated to appkit) -------
export {
  stringToBoolean,
  booleanToString,
  arrayToObject,
  objectToArray,
  queryStringToObject,
  objectToQueryString,
  firestoreTimestampToDate,
  dateToISOString,
  parseCookies,
  getCookie,
  hasCookie,
  deleteCookie,
} from "@mohasinac/appkit/utils";

// ------- Event Management (delegated to appkit) -------
export {
  GlobalEventManager,
  globalEventManager,
  throttle,
  debounce,
  addGlobalScrollHandler,
  addGlobalResizeHandler,
  addGlobalClickHandler,
  addGlobalKeyHandler,
  removeGlobalHandler,
  isMobileDevice,
  hasTouchSupport,
  getViewportDimensions,
  isInViewport,
  smoothScrollTo,
  preventBodyScroll,
} from "@mohasinac/appkit/utils";

// ------- ID Generators (delegated to appkit) -------
export {
  generateCategoryId,
  generateUserId,
  generateProductId,
  generateAuctionId,
  generatePreOrderId,
  generateReviewId,
  generateOrderId,
  generateFAQId,
  generateCouponId,
  generateCarouselId,
  generateHomepageSectionId,
  generateBidId,
  generateBlogPostId,
  generatePayoutId,
  generateOfferId,
  generateUniqueId,
  idExists,
  generateBarcodeFromId,
  generateQRCodeData,
  generateProductImageFilename,
  generateProductVideoFilename,
  generateAuctionImageFilename,
  generatePreOrderImageFilename,
  generateReviewImageFilename,
  generateReviewVideoFilename,
  generateStoreLogoFilename,
  generateStoreBannerFilename,
  generateBlogImageFilename,
  generateEventImageFilename,
  generateCategoryImageFilename,
  generateUserAvatarFilename,
  generateCarouselImageFilename,
  generateCroppedImageFilename,
  generateTrimmedVideoFilename,
  generateInvoiceFilename,
  generatePayoutDocFilename,
  generateMediaFilename,
} from "@mohasinac/appkit/utils";
export type {
  GenerateCategoryIdInput,
  GenerateUserIdInput,
  GenerateProductIdInput,
  GenerateAuctionIdInput,
  GeneratePreOrderIdInput,
  GenerateReviewIdInput,
  GenerateOrderIdInput,
  GenerateFAQIdInput,
  GenerateCarouselIdInput,
  GenerateHomepageSectionIdInput,
  GenerateBidIdInput,
  GenerateBlogPostIdInput,
  GeneratePayoutIdInput,
  GenerateOfferIdInput,
  GenerateProductImageFilenameInput,
  GenerateProductVideoFilenameInput,
  GenerateAuctionImageFilenameInput,
  GeneratePreOrderImageFilenameInput,
  GenerateReviewImageFilenameInput,
  GenerateReviewVideoFilenameInput,
  GenerateBlogImageFilenameInput,
  GenerateEventImageFilenameInput,
  MediaFilenameContext,
} from "@mohasinac/appkit/utils";
// Guest Cart (localStorage storage for unauthenticated users) — delegated to appkit
export {
  type GuestCartItem,
  type GuestCartStorage,
  getGuestCartItems,
  addToGuestCart,
  removeFromGuestCart,
  updateGuestCartQuantity,
  clearGuestCart,
  getGuestCartCount,
  setGuestReturnTo,
  getGuestReturnTo,
  clearGuestReturnTo,
} from "@mohasinac/appkit/features/cart";
// Order Splitter (cart → order group segmentation) — delegated to appkit
export {
  splitCartIntoOrderGroups,
  type OrderGroup,
  type OrderType,
} from "@mohasinac/appkit/features/orders";
// Business Day (10:00 AM IST day-boundary logic) — migrated to appkit
export {
  BUSINESS_DAY_HOUR_IST,
  getBusinessDayStart,
  getBusinessDaysElapsed,
  getBusinessDaysRemaining,
  getBusinessDayEligibilityDate,
} from "@mohasinac/appkit/utils";

