/**
 * Categories Seed Data
 * Hierarchical category structure for products
 */

import type { CategoryDocument } from "@/db/schema";

export const categoriesSeedData: Partial<CategoryDocument>[] = [
  // ROOT: Electronics
  {
    id: "category-electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Latest tech and gadgets",
    rootId: "category-electronics",
    parentIds: [],
    childrenIds: [
      "category-mobiles-accessories-electronics",
      "category-laptops-computers-electronics",
      "category-audio-electronics",
      "category-cameras-photography-electronics",
    ],
    tier: 0,
    path: "electronics",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 1,
      auctionIds: ["auction-ps5-slim-gaming-console-techhub-1"],
      totalProductCount: 10,
      totalAuctionCount: 10,
      totalItemCount: 20,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 1,
    seo: {
      title: "Electronics - Latest Gadgets & Tech | LetItRip",
      description:
        "Shop the latest electronics including mobiles, laptops, audio devices, and cameras",
      keywords: ["electronics", "gadgets", "technology", "mobiles", "laptops"],
      ogImage: "https://picsum.photos/seed/tech-electronics/1200/630",
    },
    display: {
      icon: "📱",
      coverImage: "https://picsum.photos/seed/tech-electronics/800/800",
      color: "#3b82f6",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },
  // Electronics > Mobiles & Accessories
  {
    id: "category-mobiles-accessories-electronics",
    name: "Mobiles & Accessories",
    slug: "mobiles-accessories",
    description: "Smartphones and accessories",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [
      "category-smartphones-mobiles-accessories",
      "category-mobile-accessories-mobiles-accessories",
    ],
    tier: 1,
    path: "electronics/mobiles-accessories",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 3,
      totalAuctionCount: 1,
      totalItemCount: 4,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Mobiles & Accessories | LetItRip",
      description: "Browse smartphones and mobile accessories",
      keywords: ["mobiles", "smartphones", "mobile accessories"],
    },
    display: {
      icon: "📱",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },
  // Electronics > Mobiles > Smartphones
  {
    id: "category-smartphones-mobiles-accessories",
    name: "Smartphones",
    slug: "smartphones",
    description: "Latest smartphones",
    rootId: "category-electronics",
    parentIds: [
      "category-mobiles-accessories-electronics",
      "category-electronics",
    ],
    childrenIds: [],
    tier: 2,
    path: "electronics/mobiles-accessories/smartphones",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 3,
      productIds: [
        "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
        "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
        "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
      ],
      auctionCount: 1,
      auctionIds: ["auction-iphone15-sealed-bundle-techhub-1"],
      totalProductCount: 3,
      totalAuctionCount: 1,
      totalItemCount: 4,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 2,
    seo: {
      title: "Smartphones - Latest Models | LetItRip",
      description: "Shop the latest smartphones with best prices",
      keywords: ["smartphones", "iphone", "samsung", "android"],
    },
    display: {
      icon: "📱",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [
      { id: "category-electronics", name: "Electronics", tier: 0 },
      {
        id: "category-mobiles-accessories-electronics",
        name: "Mobiles & Accessories",
        tier: 1,
      },
    ],
  },
  // Electronics > Mobiles > Mobile Accessories
  {
    id: "category-mobile-accessories-mobiles-accessories",
    name: "Mobile Accessories",
    slug: "mobile-accessories",
    description: "Cases, chargers, and more",
    rootId: "category-electronics",
    parentIds: [
      "category-mobiles-accessories-electronics",
      "category-electronics",
    ],
    childrenIds: [],
    tier: 2,
    path: "electronics/mobiles-accessories/mobile-accessories",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Mobile Accessories | LetItRip",
      description: "Shop mobile cases, chargers, and accessories",
      keywords: ["mobile accessories", "phone cases", "chargers"],
    },
    display: {
      icon: "🔌",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [
      { id: "category-electronics", name: "Electronics", tier: 0 },
      {
        id: "category-mobiles-accessories-electronics",
        name: "Mobiles & Accessories",
        tier: 1,
      },
    ],
  },
  // Electronics > Laptops & Computers
  {
    id: "category-laptops-computers-electronics",
    name: "Laptops & Computers",
    slug: "laptops-computers",
    description: "Laptops and peripherals",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/laptops-computers",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 2,
      productIds: [
        "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
        "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
      ],
      auctionCount: 1,
      auctionIds: ["product-macbook-pro-m3-auction-electronics-techhub-1"],
      totalProductCount: 2,
      totalAuctionCount: 1,
      totalItemCount: 3,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 3,
    seo: {
      title: "Laptops & Computers | LetItRip",
      description: "Browse laptops and computers for work and gaming",
      keywords: ["laptops", "computers", "desktop", "gaming pc"],
    },
    display: {
      icon: "💻",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },
  // Electronics > Audio
  {
    id: "category-audio-electronics",
    name: "Audio",
    slug: "audio",
    description: "Headphones and speakers",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/audio",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
      ],
      auctionCount: 3,
      auctionIds: [
        "auction-airpods-pro2-audio-techhub-1",
        "auction-bose700-headphones-homeessentials-1",
        "auction-pioneer-hifi-system-homeessentials-1",
      ],
      totalProductCount: 1,
      totalAuctionCount: 3,
      totalItemCount: 4,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Audio Equipment | LetItRip",
      description: "Shop headphones, speakers, and audio devices",
      keywords: ["headphones", "speakers", "audio", "earbuds"],
    },
    display: {
      icon: "🎧",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },
  // Electronics > Cameras
  {
    id: "category-cameras-photography-electronics",
    name: "Cameras & Photography",
    slug: "cameras-photography",
    description: "Cameras and accessories",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/cameras-photography",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 4,
      auctionIds: [
        "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
        "product-vintage-leica-camera-auction-artisan-1",
        "auction-sony-alpha-7iv-camera-techhub-1",
        "auction-nikon-z30-mirrorless-techhub-1",
      ],
      totalProductCount: 0,
      totalAuctionCount: 4,
      totalItemCount: 4,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Cameras & Photography | LetItRip",
      description: "Browse DSLR, mirrorless, and action cameras",
      keywords: ["cameras", "dslr", "mirrorless", "photography"],
    },
    display: {
      icon: "📷",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },

  // ROOT: Fashion
  {
    id: "category-fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing",
    rootId: "category-fashion",
    parentIds: [],
    childrenIds: [
      "category-mens-fashion-fashion",
      "category-womens-fashion-fashion",
    ],
    tier: 0,
    path: "fashion",
    order: 2,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 2,
      totalAuctionCount: 6,
      totalItemCount: 8,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 4,
    seo: {
      title: "Fashion - Clothing & Accessories | LetItRip",
      description: "Shop the latest fashion trends for men and women",
      keywords: ["fashion", "clothing", "apparel", "accessories"],
    },
    display: {
      icon: "👗",
      coverImage: "https://picsum.photos/seed/womens-fashion/800/800",
      color: "#ec4899",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },
  // Fashion > Men's Fashion
  {
    id: "category-mens-fashion-fashion",
    name: "Men's Fashion",
    slug: "mens-fashion",
    description: "Clothing for men",
    rootId: "category-fashion",
    parentIds: ["category-fashion"],
    childrenIds: [],
    tier: 1,
    path: "fashion/mens-fashion",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
      ],
      auctionCount: 4,
      auctionIds: [
        "product-limited-air-jordan-sneakers-auction-artisan-1",
        "auction-swiss-titanium-watch-fashion-1",
        "auction-vintage-denim-jacket-fashion-1",
        "auction-supreme-box-logo-tee-fashion-1",
      ],
      totalProductCount: 1,
      totalAuctionCount: 4,
      totalItemCount: 5,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 5,
    seo: {
      title: "Men's Fashion | LetItRip",
      description: "Shop men's clothing and accessories",
      keywords: ["mens fashion", "mens clothing", "mens wear"],
    },
    display: {
      icon: "👔",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-fashion", name: "Fashion", tier: 0 }],
  },
  // Fashion > Women's Fashion
  {
    id: "category-womens-fashion-fashion",
    name: "Women's Fashion",
    slug: "womens-fashion",
    description: "Clothing for women",
    rootId: "category-fashion",
    parentIds: ["category-fashion"],
    childrenIds: [],
    tier: 1,
    path: "fashion/womens-fashion",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
      ],
      auctionCount: 2,
      auctionIds: [
        "auction-hermes-silk-scarf-fashion-1",
        "auction-designer-kanjeevaram-silk-fashion-1",
      ],
      totalProductCount: 1,
      totalAuctionCount: 2,
      totalItemCount: 3,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 6,
    seo: {
      title: "Women's Fashion | LetItRip",
      description: "Shop women's clothing and accessories",
      keywords: ["womens fashion", "womens clothing", "womens wear"],
    },
    display: {
      icon: "👗",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-fashion", name: "Fashion", tier: 0 }],
  },

  // ROOT: Home & Kitchen
  {
    id: "category-home-kitchen",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Home essentials",
    rootId: "category-home-kitchen",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "home-kitchen",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
      ],
      auctionCount: 2,
      auctionIds: [
        "auction-dyson-v15-vacuum-homeessentials-1",
        "auction-weber-charcoal-grill-homeessentials-1",
      ],
      totalProductCount: 1,
      totalAuctionCount: 2,
      totalItemCount: 3,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 7,
    seo: {
      title: "Home & Kitchen | LetItRip",
      description: "Shop home and kitchen essentials",
      keywords: ["home", "kitchen", "appliances", "furniture"],
    },
    display: {
      icon: "🏠",
      coverImage: "https://picsum.photos/seed/kitchen-category/800/800",
      color: "#10b981",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Sports & Outdoors
  {
    id: "category-sports-outdoors",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and gear",
    rootId: "category-sports-outdoors",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "sports-outdoors",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
      ],
      auctionCount: 2,
      auctionIds: [
        "auction-trek-domane-road-bike-homeessentials-1",
        "auction-babolat-tennis-racket-signed-homeessentials-1",
      ],
      totalProductCount: 1,
      totalAuctionCount: 2,
      totalItemCount: 3,
      lastUpdated: new Date("2026-03-06T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 8,
    seo: {
      title: "Sports & Outdoors | LetItRip",
      description: "Shop sports equipment and outdoor gear",
      keywords: ["sports", "outdoors", "fitness", "camping"],
    },
    display: {
      icon: "⚽",
      coverImage: "https://picsum.photos/seed/fitness-sports/800/800",
      color: "#f97316",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Beauty & Health
  {
    id: "category-beauty-health",
    name: "Beauty & Health",
    slug: "beauty-health",
    description: "Skincare, cosmetics, and wellness products",
    rootId: "category-beauty-health",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "beauty-health",
    order: 5,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 9,
    seo: {
      title: "Beauty & Health | LetItRip",
      description: "Shop skincare, cosmetics, and wellness products",
      keywords: ["beauty", "skincare", "cosmetics", "health", "wellness"],
    },
    display: {
      icon: "💄",
      coverImage: "https://picsum.photos/seed/beauty-cosmetics/800/800",
      color: "#ec4899",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Books & Stationery
  {
    id: "category-books-stationery",
    name: "Books & Stationery",
    slug: "books-stationery",
    description: "Books, notebooks, and office supplies",
    rootId: "category-books-stationery",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "books-stationery",
    order: 6,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 10,
    seo: {
      title: "Books & Stationery | LetItRip",
      description: "Shop books, notebooks, and office supplies",
      keywords: ["books", "stationery", "notebooks", "office supplies"],
    },
    display: {
      icon: "📚",
      coverImage: "https://picsum.photos/seed/books-reading/800/800",
      color: "#f59e0b",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Automotive
  {
    id: "category-automotive",
    name: "Automotive",
    slug: "automotive",
    description: "Car accessories, tools, and parts",
    rootId: "category-automotive",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "automotive",
    order: 7,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 11,
    seo: {
      title: "Automotive | LetItRip",
      description: "Shop car accessories, tools, and parts",
      keywords: ["automotive", "car accessories", "vehicle parts", "tools"],
    },
    display: {
      icon: "🚗",
      coverImage: "https://picsum.photos/seed/automotive-car/800/800",
      color: "#6b7280",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Jewelry & Accessories
  {
    id: "category-jewelry-accessories",
    name: "Jewelry & Accessories",
    slug: "jewelry-accessories",
    description: "Fine jewelry, watches, and fashion accessories",
    rootId: "category-jewelry-accessories",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "jewelry-accessories",
    order: 8,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 12,
    seo: {
      title: "Jewelry & Accessories | LetItRip",
      description: "Shop fine jewelry, watches, and fashion accessories",
      keywords: ["jewelry", "watches", "accessories", "rings", "necklaces"],
    },
    display: {
      icon: "💍",
      coverImage: "https://picsum.photos/seed/jewelry-fashion/800/800",
      color: "#d97706",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Toys & Baby
  {
    id: "category-toys-baby",
    name: "Toys & Baby",
    slug: "toys-baby",
    description: "Toys, games, and baby essentials",
    rootId: "category-toys-baby",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "toys-baby",
    order: 9,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 13,
    seo: {
      title: "Toys & Baby | LetItRip",
      description: "Shop toys, games, and baby essentials",
      keywords: ["toys", "baby", "kids", "games", "educational toys"],
    },
    display: {
      icon: "🧸",
      coverImage: "https://picsum.photos/seed/home-decor/800/800",
      color: "#8b5cf6",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Food & Groceries
  {
    id: "category-food-groceries",
    name: "Food & Groceries",
    slug: "food-groceries",
    description: "Fresh produce, packaged foods, and beverages",
    rootId: "category-food-groceries",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "food-groceries",
    order: 10,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 14,
    seo: {
      title: "Food & Groceries | LetItRip",
      description: "Shop fresh produce, packaged foods, and beverages",
      keywords: ["food", "groceries", "beverages", "fresh produce", "snacks"],
    },
    display: {
      icon: "🛒",
      coverImage: "https://picsum.photos/seed/food-grocery/800/800",
      color: "#059669",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },
];
