/**
 * Categories Seed Data
 * Hierarchical category structure for products
 */

import type { CategoryDocument } from "@/db/schema";

export const categoriesSeedData: Partial<CategoryDocument>[] = [
  // ROOT: Electronics
  {
    id: "category-electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Latest tech and gadgets",
    rootId: "category-electronics",
    parentIds: [],
    childrenIds: [
      "category-mobiles-accessories-electronics",
      "category-laptops-computers-electronics",
      "category-audio-electronics",
      "category-cameras-photography-electronics",
    ],
    tier: 0,
    path: "electronics",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 10,
      totalAuctionCount: 1,
      totalItemCount: 11,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 1,
    seo: {
      title: "Electronics - Latest Gadgets & Tech | LetItRip",
      description:
        "Shop the latest electronics including mobiles, laptops, audio devices, and cameras",
      keywords: ["electronics", "gadgets", "technology", "mobiles", "laptops"],
      ogImage:
        "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200&h=630&fit=crop",
    },
    display: {
      icon: "📱",
      coverImage:
        "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1600&h=900&fit=crop",
      color: "#3b82f6",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },
  // Electronics > Mobiles & Accessories
  {
    id: "category-mobiles-accessories-electronics",
    name: "Mobiles & Accessories",
    slug: "mobiles-accessories",
    description: "Smartphones and accessories",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [
      "category-smartphones-mobiles-accessories",
      "category-mobile-accessories-mobiles-accessories",
    ],
    tier: 1,
    path: "electronics/mobiles-accessories",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 3,
      totalAuctionCount: 0,
      totalItemCount: 3,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Mobiles & Accessories | LetItRip",
      description: "Browse smartphones and mobile accessories",
      keywords: ["mobiles", "smartphones", "mobile accessories"],
    },
    display: {
      icon: "📱",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },
  // Electronics > Mobiles > Smartphones
  {
    id: "category-smartphones-mobiles-accessories",
    name: "Smartphones",
    slug: "smartphones",
    description: "Latest smartphones",
    rootId: "category-electronics",
    parentIds: [
      "category-mobiles-accessories-electronics",
      "category-electronics",
    ],
    childrenIds: [],
    tier: 2,
    path: "electronics/mobiles-accessories/smartphones",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 3,
      productIds: [
        "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
        "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
        "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 3,
      totalAuctionCount: 0,
      totalItemCount: 3,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 2,
    seo: {
      title: "Smartphones - Latest Models | LetItRip",
      description: "Shop the latest smartphones with best prices",
      keywords: ["smartphones", "iphone", "samsung", "android"],
    },
    display: {
      icon: "📱",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [
      { id: "category-electronics", name: "Electronics", tier: 0 },
      {
        id: "category-mobiles-accessories-electronics",
        name: "Mobiles & Accessories",
        tier: 1,
      },
    ],
  },
  // Electronics > Mobiles > Mobile Accessories
  {
    id: "category-mobile-accessories-mobiles-accessories",
    name: "Mobile Accessories",
    slug: "mobile-accessories",
    description: "Cases, chargers, and more",
    rootId: "category-electronics",
    parentIds: [
      "category-mobiles-accessories-electronics",
      "category-electronics",
    ],
    childrenIds: [],
    tier: 2,
    path: "electronics/mobiles-accessories/mobile-accessories",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Mobile Accessories | LetItRip",
      description: "Shop mobile cases, chargers, and accessories",
      keywords: ["mobile accessories", "phone cases", "chargers"],
    },
    display: {
      icon: "🔌",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [
      { id: "category-electronics", name: "Electronics", tier: 0 },
      {
        id: "category-mobiles-accessories-electronics",
        name: "Mobiles & Accessories",
        tier: 1,
      },
    ],
  },
  // Electronics > Laptops & Computers
  {
    id: "category-laptops-computers-electronics",
    name: "Laptops & Computers",
    slug: "laptops-computers",
    description: "Laptops and peripherals",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/laptops-computers",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 2,
      productIds: [
        "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
        "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 2,
      totalAuctionCount: 0,
      totalItemCount: 2,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 3,
    seo: {
      title: "Laptops & Computers | LetItRip",
      description: "Browse laptops and computers for work and gaming",
      keywords: ["laptops", "computers", "desktop", "gaming pc"],
    },
    display: {
      icon: "💻",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },
  // Electronics > Audio
  {
    id: "category-audio-electronics",
    name: "Audio",
    slug: "audio",
    description: "Headphones and speakers",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/audio",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Audio Equipment | LetItRip",
      description: "Shop headphones, speakers, and audio devices",
      keywords: ["headphones", "speakers", "audio", "earbuds"],
    },
    display: {
      icon: "🎧",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },
  // Electronics > Cameras
  {
    id: "category-cameras-photography-electronics",
    name: "Cameras & Photography",
    slug: "cameras-photography",
    description: "Cameras and accessories",
    rootId: "category-electronics",
    parentIds: ["category-electronics"],
    childrenIds: [],
    tier: 1,
    path: "electronics/cameras-photography",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 1,
      auctionIds: [
        "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
      ],
      totalProductCount: 0,
      totalAuctionCount: 1,
      totalItemCount: 1,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: false,
    seo: {
      title: "Cameras & Photography | LetItRip",
      description: "Browse DSLR, mirrorless, and action cameras",
      keywords: ["cameras", "dslr", "mirrorless", "photography"],
    },
    display: {
      icon: "📷",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-electronics", name: "Electronics", tier: 0 }],
  },

  // ROOT: Fashion
  {
    id: "category-fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing",
    rootId: "category-fashion",
    parentIds: [],
    childrenIds: [
      "category-mens-fashion-fashion",
      "category-womens-fashion-fashion",
    ],
    tier: 0,
    path: "fashion",
    order: 2,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 2,
      totalAuctionCount: 0,
      totalItemCount: 2,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 4,
    seo: {
      title: "Fashion - Clothing & Accessories | LetItRip",
      description: "Shop the latest fashion trends for men and women",
      keywords: ["fashion", "clothing", "apparel", "accessories"],
    },
    display: {
      icon: "👗",
      coverImage:
        "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&h=900&fit=crop",
      color: "#ec4899",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },
  // Fashion > Men's Fashion
  {
    id: "category-mens-fashion-fashion",
    name: "Men's Fashion",
    slug: "mens-fashion",
    description: "Clothing for men",
    rootId: "category-fashion",
    parentIds: ["category-fashion"],
    childrenIds: [],
    tier: 1,
    path: "fashion/mens-fashion",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 5,
    seo: {
      title: "Men's Fashion | LetItRip",
      description: "Shop men's clothing and accessories",
      keywords: ["mens fashion", "mens clothing", "mens wear"],
    },
    display: {
      icon: "👔",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-fashion", name: "Fashion", tier: 0 }],
  },
  // Fashion > Women's Fashion
  {
    id: "category-womens-fashion-fashion",
    name: "Women's Fashion",
    slug: "womens-fashion",
    description: "Clothing for women",
    rootId: "category-fashion",
    parentIds: ["category-fashion"],
    childrenIds: [],
    tier: 1,
    path: "fashion/womens-fashion",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 6,
    seo: {
      title: "Women's Fashion | LetItRip",
      description: "Shop women's clothing and accessories",
      keywords: ["womens fashion", "womens clothing", "womens wear"],
    },
    display: {
      icon: "👗",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [{ id: "category-fashion", name: "Fashion", tier: 0 }],
  },

  // ROOT: Home & Kitchen
  {
    id: "category-home-kitchen",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Home essentials",
    rootId: "category-home-kitchen",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "home-kitchen",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 7,
    seo: {
      title: "Home & Kitchen | LetItRip",
      description: "Shop home and kitchen essentials",
      keywords: ["home", "kitchen", "appliances", "furniture"],
    },
    display: {
      icon: "🏠",
      coverImage:
        "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=1600&h=900&fit=crop",
      color: "#10b981",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },

  // ROOT: Sports & Outdoors
  {
    id: "category-sports-outdoors",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and gear",
    rootId: "category-sports-outdoors",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "sports-outdoors",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 1,
      productIds: [
        "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
      ],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 1,
      totalAuctionCount: 0,
      totalItemCount: 1,
      lastUpdated: new Date("2026-02-09T00:00:00Z"),
    },
    isFeatured: true,
    featuredPriority: 8,
    seo: {
      title: "Sports & Outdoors | LetItRip",
      description: "Shop sports equipment and outdoor gear",
      keywords: ["sports", "outdoors", "fitness", "camping"],
    },
    display: {
      icon: "⚽",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-user-admin",
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2026-02-09T00:00:00Z"),
    ancestors: [],
  },
];
