/**
 * Comprehensive FAQ Seed Data
 * 102 FAQs across 7 categories
 *
 * Categories:
 * - general: 20 FAQs
 * - shipping: 15 FAQs
 * - returns: 12 FAQs
 * - payment: 18 FAQs
 * - account: 10 FAQs
 * - products: 15 FAQs
 * - sellers: 12 FAQs
 *
 * Note: answer field will be converted to FAQAnswer object by seed script
 */

type SeedFAQ = {
  id?: string; // Optional for seedCollection compatibility
  question: string;
  answer: string; // Will be converted to { text: string, format: 'plain' }
  category: string;
  showOnHomepage: boolean;
  showInFooter: boolean;
  isPinned: boolean;
  order: number;
  priority: number;
  tags: string[];
  relatedFAQs: string[];
  useSiteSettings: boolean;
  variables: string[];
  stats: { views: number; helpful: number; notHelpful: number };
  seo: {
    slug: string;
    metaTitle: string;
    metaDescription: string;
  };
  isActive: boolean;
  createdBy: string;
};

export const FAQ_SEED_DATA: SeedFAQ[] = [
  // ============================================
  // GENERAL (20 FAQs)
  // ============================================
  {
    question: "What is LetItRip?",
    answer:
      "LetItRip is a multi-seller e-commerce and auction platform where you can buy products, participate in auctions, and discover great deals from verified sellers across India.",
    category: "general",
    showOnHomepage: true,
    showInFooter: true,
    isPinned: true,
    order: 1,
    priority: 10,
    tags: ["about", "platform", "introduction"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "what-is-letitrip",
      metaTitle:
        "What is LetItRip? | Multi-Seller Marketplace & Auction Platform",
      metaDescription:
        "Learn about LetItRip - your trusted multi-seller e-commerce and auction platform with verified sellers across India.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I contact customer support?",
    answer:
      "You can reach our customer support team at {{supportEmail}} or call us at {{supportPhone}}. We are available Monday to Saturday, 9 AM to 6 PM IST.",
    category: "general",
    showOnHomepage: true,
    showInFooter: true,
    isPinned: false,
    order: 2,
    priority: 9,
    tags: ["support", "contact", "help"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail", "supportPhone"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "contact-customer-support",
      metaTitle: "How to Contact Customer Support | LetItRip Help",
      metaDescription:
        "Get in touch with LetItRip customer support via email or phone. Available Mon-Sat, 9 AM to 6 PM IST.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Is there free shipping on all orders?",
    answer:
      "No, we do not offer blanket free shipping. Shipping costs depend on the seller, product, and delivery location. Some sellers may offer free shipping on specific products - check the product description for details.",
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 3,
    priority: 8,
    tags: ["shipping", "delivery", "costs"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "free-shipping-policy",
      metaTitle: "Free Shipping Policy | LetItRip Shipping Information",
      metaDescription:
        "Understand our shipping policy. Free shipping is only available when mentioned in the product description by the seller.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you offer free returns?",
    answer:
      "No, we do not have a blanket free returns policy. Return policies vary by seller and product. Check the product description for specific return terms, including any return shipping costs.",
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 4,
    priority: 8,
    tags: ["returns", "refunds", "policy"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "free-returns-policy",
      metaTitle: "Returns Policy | LetItRip Return Information",
      metaDescription:
        "Learn about our returns policy. Return terms vary by seller - check product descriptions for specific return policies.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept UPI, credit/debit cards (Visa, Mastercard, RuPay), net banking, digital wallets (Paytm, PhonePe, Google Pay), and EMI options on select purchases.",
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 7,
    tags: ["payment", "methods", "cards"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "payment-methods-accepted",
      metaTitle: "Payment Methods | LetItRip Accepted Payments",
      metaDescription:
        "We accept UPI, cards, net banking, digital wallets, and EMI. Shop securely on LetItRip with your preferred payment method.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I track my order?",
    answer:
      'Once your order is shipped, you\'ll receive a tracking number via email and SMS. You can also track your order in the "My Orders" section of your account.',
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 7,
    tags: ["tracking", "orders", "delivery"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "track-my-order",
      metaTitle: "How to Track Your Order | LetItRip Order Tracking",
      metaDescription:
        "Track your LetItRip order using the tracking number sent via email or check the My Orders section in your account.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I cancel my order?",
    answer:
      "Yes, you can cancel your order before it is shipped. Once shipped, cancellation is not possible, but you may initiate a return after delivery.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 6,
    tags: ["cancel", "orders", "refund"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "cancel-order",
      metaTitle: "How to Cancel an Order | LetItRip Cancellation Policy",
      metaDescription:
        "Learn how to cancel your LetItRip order before it ships. Cancellation available until the order is dispatched.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Are products on LetItRip authentic?",
    answer:
      "Yes, all sellers on our platform are verified, and we have strict quality control measures. Products are sourced directly from sellers and checked for authenticity.",
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 8,
    tags: ["authentic", "quality", "trust"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-authenticity",
      metaTitle: "Are Products Authentic? | LetItRip Quality Assurance",
      metaDescription:
        "Shop with confidence. All LetItRip sellers are verified and products undergo strict quality checks for authenticity.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is your refund policy?",
    answer:
      "Refunds are processed within 5-7 business days after we receive and inspect the returned product. The amount will be credited to your original payment method.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 6,
    tags: ["refund", "returns", "money back"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "refund-policy",
      metaTitle: "Refund Policy | LetItRip Money-Back Guarantee",
      metaDescription:
        "Get refunds within 5-7 business days after product inspection. Amount credited to original payment method.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you ship internationally?",
    answer:
      "Currently, we only ship within India. International shipping is not available at this time.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 5,
    tags: ["shipping", "international", "delivery"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "international-shipping",
      metaTitle: "International Shipping | LetItRip Delivery Areas",
      metaDescription:
        "LetItRip currently ships within India only. International shipping is not yet available.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I report a problem with my order?",
    answer:
      'Go to "My Orders", select the order, and click "Report Issue". You can also contact customer support at {{supportEmail}} with your order number.',
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 6,
    tags: ["issues", "support", "help"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "report-order-problem",
      metaTitle: "Report Order Issue | LetItRip Customer Support",
      metaDescription:
        "Having issues with your order? Report problems through My Orders or contact support with your order number.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What are your business hours?",
    answer:
      "Our customer support is available Monday to Saturday, 9:00 AM to 6:00 PM IST. Orders can be placed 24/7 on our website.",
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 12,
    priority: 4,
    tags: ["hours", "support", "timing"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "business-hours",
      metaTitle: "Business Hours | LetItRip Support Timing",
      metaDescription:
        "LetItRip support available Mon-Sat, 9 AM to 6 PM IST. Shop 24/7 online.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How secure is my personal information?",
    answer:
      "We use industry-standard SSL encryption and comply with Indian data protection laws. Your personal and payment information is securely stored and never shared with third parties without consent.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 13,
    priority: 7,
    tags: ["security", "privacy", "data"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "data-security",
      metaTitle: "Data Security | LetItRip Privacy & Protection",
      metaDescription:
        "Your data is protected with SSL encryption and Indian data protection compliance. Shop securely on LetItRip.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I modify my order after placing it?",
    answer:
      "Orders can be modified within 1 hour of placement by contacting customer support. After that, you may need to cancel and place a new order.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 14,
    priority: 5,
    tags: ["modify", "orders", "changes"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "modify-order",
      metaTitle: "Modify Order | LetItRip Order Changes",
      metaDescription:
        "Modify your LetItRip order within 1 hour of placement. Contact support for assistance with order changes.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you have a mobile app?",
    answer:
      "Currently, LetItRip is available as a mobile-optimized website. A dedicated mobile app is coming soon for iOS and Android.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 15,
    priority: 4,
    tags: ["app", "mobile", "download"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "mobile-app",
      metaTitle: "Mobile App | LetItRip iOS & Android",
      metaDescription:
        "LetItRip mobile app coming soon. Currently available as mobile-optimized website for iOS and Android.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Where is LetItRip located?",
    answer:
      "Our headquarters is located at {{companyAddress}}. We serve customers across India.",
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 16,
    priority: 3,
    tags: ["location", "address", "office"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["companyAddress"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "company-location",
      metaTitle: "Company Location | LetItRip Office Address",
      metaDescription:
        "Find LetItRip office location and contact details. Serving customers across India.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I subscribe to your newsletter?",
    answer:
      "Enter your email in the newsletter signup form at the bottom of our website to receive updates, deals, and exclusive offers.",
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 17,
    priority: 3,
    tags: ["newsletter", "subscription", "updates"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "newsletter-subscription",
      metaTitle: "Newsletter Subscription | LetItRip Updates & Deals",
      metaDescription:
        "Subscribe to LetItRip newsletter for exclusive deals, updates, and special offers delivered to your inbox.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I purchase gift cards?",
    answer:
      "Yes, gift cards are available in denominations of ₹500, ₹1000, ₹2000, and ₹5000. They can be purchased and sent via email to recipients.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 18,
    priority: 5,
    tags: ["gift cards", "vouchers", "gifts"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "gift-cards",
      metaTitle: "Gift Cards | LetItRip E-Gift Vouchers",
      metaDescription:
        "Buy LetItRip gift cards in various denominations. Perfect gift for any occasion, sent via email instantly.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is your privacy policy?",
    answer:
      "Our privacy policy details how we collect, use, and protect your personal information. You can read the full policy at {{websiteUrl}}/privacy-policy",
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 19,
    priority: 6,
    tags: ["privacy", "policy", "data"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["websiteUrl"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "privacy-policy-info",
      metaTitle: "Privacy Policy | LetItRip Data Protection",
      metaDescription:
        "Read LetItRip privacy policy to understand how we protect your personal information and comply with data laws.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you offer bulk discounts?",
    answer:
      "Yes, bulk purchase discounts are available for orders above 10 units. Contact our sales team at {{supportEmail}} for bulk pricing.",
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 20,
    priority: 4,
    tags: ["bulk", "discounts", "wholesale"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "bulk-discounts",
      metaTitle: "Bulk Discounts | LetItRip Wholesale Pricing",
      metaDescription:
        "Get bulk discounts on orders over 10 units. Contact LetItRip sales team for wholesale pricing and deals.",
    },
    isActive: true,
    createdBy: "system",
  },

  // ============================================
  // SHIPPING (15 FAQs)
  // ============================================
  {
    question: "How long does shipping take?",
    answer:
      "Shipping typically takes 3-7 business days depending on your location. Metro cities receive deliveries faster, while remote areas may take longer.",
    category: "shipping",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 9,
    tags: ["shipping", "delivery", "time"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "shipping-time",
      metaTitle: "Shipping Time | LetItRip Delivery Duration",
      metaDescription:
        "LetItRip shipping takes 3-7 business days. Metro cities get faster delivery, remote areas may take longer.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What are the shipping charges?",
    answer:
      "Shipping charges vary by seller, product weight, and delivery location. Exact charges are displayed at checkout before payment. Some sellers offer free shipping on specific products.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 8,
    tags: ["shipping", "charges", "cost"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "shipping-charges",
      metaTitle: "Shipping Charges | LetItRip Delivery Costs",
      metaDescription:
        "Shipping costs vary by seller and location. See exact charges at checkout. Some products have free shipping.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you offer express shipping?",
    answer:
      "Yes, express shipping is available in select cities for an additional charge. Deliveries within 1-2 business days. Check availability at checkout.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 7,
    tags: ["express", "fast shipping", "delivery"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "express-shipping",
      metaTitle: "Express Shipping | LetItRip Fast Delivery",
      metaDescription:
        "Get express shipping in 1-2 days for select cities. Additional charges apply. Check availability at checkout.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I change my delivery address after placing an order?",
    answer:
      "Yes, you can change your delivery address within 2 hours of placing the order. Contact customer support immediately at {{supportPhone}}.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 6,
    tags: ["address", "change", "delivery"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportPhone"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "change-delivery-address",
      metaTitle: "Change Delivery Address | LetItRip Order Modifications",
      metaDescription:
        "Change your delivery address within 2 hours of order placement. Contact support for immediate assistance.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What happens if I'm not home for delivery?",
    answer:
      "The delivery partner will attempt delivery 3 times. If you're unavailable, they'll leave a note. You can also schedule a redelivery or pick up from the nearest collection point.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["delivery", "missed", "redelivery"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "missed-delivery",
      metaTitle: "Missed Delivery | LetItRip Redelivery Options",
      metaDescription:
        "3 delivery attempts made. Schedule redelivery or pickup from collection point if you miss delivery.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you ship to PO boxes?",
    answer:
      "No, we do not ship to PO boxes. Please provide a physical address with landmark for successful delivery.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 5,
    tags: ["PO box", "delivery", "address"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "po-box-shipping",
      metaTitle: "PO Box Shipping | LetItRip Delivery Restrictions",
      metaDescription:
        "LetItRip does not ship to PO boxes. Provide a physical address with landmark for delivery.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Is signature required for delivery?",
    answer:
      "Yes, all deliveries require a signature for security. Someone 18+ must be present to receive and sign for the package.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 5,
    tags: ["signature", "delivery", "security"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "signature-required-delivery",
      metaTitle: "Signature Required | LetItRip Delivery Policy",
      metaDescription:
        "All LetItRip deliveries require signature from someone 18+ for security purposes.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I track my shipment in real-time?",
    answer:
      "Yes, once shipped, you'll receive a tracking link via SMS and email. The tracking page shows real-time location updates and estimated delivery time.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 7,
    tags: ["tracking", "real-time", "delivery"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "real-time-tracking",
      metaTitle: "Real-Time Tracking | LetItRip Shipment Location",
      metaDescription:
        "Track your LetItRip shipment in real-time with SMS and email tracking links. See live location updates.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What if my package is damaged during shipping?",
    answer:
      "If your package arrives damaged, take photos and refuse delivery if possible. Contact us immediately at {{supportEmail}} within 24 hours for a replacement or refund.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 6,
    tags: ["damaged", "package", "refund"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "damaged-package",
      metaTitle: "Damaged Package | LetItRip Shipping Claims",
      metaDescription:
        "Received damaged package? Report within 24 hours with photos for replacement or refund.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you ship to military APO/FPO addresses?",
    answer:
      "No, we currently do not ship to military APO/FPO addresses. We only deliver to physical addresses within India.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 3,
    tags: ["military", "APO", "FPO"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "military-address-shipping",
      metaTitle: "Military Address Shipping | LetItRip APO/FPO",
      metaDescription:
        "LetItRip does not ship to military APO/FPO addresses. Only physical addresses within India.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I schedule a specific delivery date?",
    answer:
      "Scheduled delivery is available for select pin codes. Choose your preferred date at checkout if available in your area.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 4,
    tags: ["scheduled", "delivery", "date"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "scheduled-delivery",
      metaTitle: "Scheduled Delivery | LetItRip Delivery Date Selection",
      metaDescription:
        "Schedule your delivery date at checkout for select areas. Choose convenient delivery timing.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What courier services do you use?",
    answer:
      "We partner with India Post, BlueDart, Delhivery, DTDC, and other reliable courier services based on your location and product type.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 12,
    priority: 4,
    tags: ["courier", "delivery partners", "shipping"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "courier-partners",
      metaTitle: "Courier Partners | LetItRip Delivery Services",
      metaDescription:
        "LetItRip partners with India Post, BlueDart, Delhivery, DTDC for reliable deliveries across India.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Is weekend delivery available?",
    answer:
      "Yes, we deliver on Saturdays. Sunday delivery is available in select metro cities for an additional charge.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 13,
    priority: 5,
    tags: ["weekend", "saturday", "sunday"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "weekend-delivery",
      metaTitle: "Weekend Delivery | LetItRip Saturday & Sunday Shipping",
      metaDescription:
        "Saturday delivery included. Sunday delivery available in metro cities for additional charge.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is the weight limit for shipments?",
    answer:
      "Individual packages are limited to 30kg. For heavier items, sellers may split orders into multiple shipments.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 14,
    priority: 3,
    tags: ["weight", "limit", "heavy items"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "shipping-weight-limit",
      metaTitle: "Shipping Weight Limit | LetItRip Heavy Items",
      metaDescription:
        "Individual packages limited to 30kg. Heavy items may be split into multiple shipments.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you offer cash on delivery (COD)?",
    answer:
      "Yes, COD is available for orders up to ₹50,000. A nominal COD handling fee may apply depending on the seller.",
    category: "shipping",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 15,
    priority: 7,
    tags: ["COD", "cash on delivery", "payment"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "cash-on-delivery",
      metaTitle: "Cash on Delivery | LetItRip COD Payment",
      metaDescription:
        "COD available for orders up to ₹50,000. Nominal handling fee may apply depending on seller.",
    },
    isActive: true,
    createdBy: "system",
  },

  // ============================================
  // RETURNS (12 FAQs)
  // ============================================
  {
    question: "What is your return policy?",
    answer:
      "Returns are accepted within 7-14 days of delivery depending on the product category. Items must be unused, in original packaging with tags. Return shipping costs may apply unless mentioned otherwise by the seller.",
    category: "returns",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 9,
    tags: ["returns", "policy", "refund"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "return-policy",
      metaTitle: "Return Policy | LetItRip Returns & Refunds",
      metaDescription:
        "Return within 7-14 days. Items must be unused with tags. Return shipping may apply per seller policy.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I initiate a return?",
    answer:
      'Go to "My Orders", select the product, click "Return Item", choose a reason, and submit. You\'ll receive return instructions via email within 24 hours.',
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 8,
    tags: ["return", "process", "how to"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "initiate-return",
      metaTitle: "How to Return | LetItRip Return Process",
      metaDescription:
        "Initiate returns from My Orders section. Choose reason and receive return instructions within 24 hours.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Who pays for return shipping?",
    answer:
      "Return shipping costs depend on the seller's policy and reason for return. If the product is defective or wrong item, seller covers shipping. For change of mind, customer may bear return costs.",
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 8,
    tags: ["return shipping", "cost", "charges"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "return-shipping-cost",
      metaTitle: "Return Shipping Cost | LetItRip Who Pays",
      metaDescription:
        "Return shipping costs vary by seller policy. Defective items: seller pays. Change of mind: customer may pay.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "When will I receive my refund?",
    answer:
      "Refunds are processed within 5-7 business days after the returned item is received and inspected. The amount is credited to your original payment method.",
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["refund", "timing", "processing"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "refund-processing-time",
      metaTitle: "Refund Processing Time | LetItRip Money Back",
      metaDescription:
        "Refunds processed within 5-7 days after item inspection. Credited to original payment method.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I exchange an item instead of returning it?",
    answer:
      'Yes, exchanges are available for size or color variations if the same product is in stock. Select "Exchange" option when initiating the return.',
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["exchange", "swap", "size"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-exchange",
      metaTitle: "Product Exchange | LetItRip Size & Color Swap",
      metaDescription:
        "Exchange for different size or color if in stock. Select exchange option when initiating return.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What items cannot be returned?",
    answer:
      'Non-returnable items include: personal care products, innerwear, food items, customized products, and items marked as "non-returnable" on the product page.',
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 7,
    tags: ["non-returnable", "exceptions", "policy"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "non-returnable-items",
      metaTitle: "Non-Returnable Items | LetItRip Return Exceptions",
      metaDescription:
        "Personal care, innerwear, food, customized items cannot be returned. Check product page for details.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do I need the original packaging for returns?",
    answer:
      "Yes, items must be returned in original packaging with all tags, labels, and accessories intact. Damaged packaging may result in partial refund or rejection.",
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 6,
    tags: ["packaging", "condition", "requirements"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "return-packaging-requirements",
      metaTitle: "Return Packaging | LetItRip Return Conditions",
      metaDescription:
        "Return items in original packaging with tags intact. Damaged packaging may affect refund.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What if I receive a defective product?",
    answer:
      "Contact us immediately at {{supportEmail}} with photos of the defect. We'll arrange a free return pickup and provide a full refund or replacement.",
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 8,
    tags: ["defective", "damaged", "quality"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "defective-product-return",
      metaTitle: "Defective Product | LetItRip Quality Issues",
      metaDescription:
        "Received defective item? Contact us with photos for free return pickup and full refund or replacement.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I return a gift?",
    answer:
      "Yes, gifts can be returned within the standard return period. Refunds will be issued as store credit or to the original purchaser's payment method.",
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 5,
    tags: ["gifts", "return", "refund"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "gift-return",
      metaTitle: "Gift Returns | LetItRip Gift Policy",
      metaDescription:
        "Return gifts within standard period. Refund as store credit or to original purchaser payment method.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I track my return?",
    answer:
      'Once your return is picked up, you\'ll receive a tracking number via email. Track the return status in "My Orders" section under "Returns & Refunds".',
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 5,
    tags: ["return tracking", "status", "updates"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "track-return",
      metaTitle: "Track Return | LetItRip Return Status",
      metaDescription:
        "Track your return with tracking number in email or check My Orders section for return status.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What if my return is rejected?",
    answer:
      "If your return is rejected due to policy violation or item condition, we'll notify you via email with the reason. The item will be shipped back to you at your expense.",
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 4,
    tags: ["rejected", "return", "policy"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "rejected-return",
      metaTitle: "Rejected Return | LetItRip Return Rejection Policy",
      metaDescription:
        "Returns may be rejected for policy violations. Item shipped back to you at your expense with reason.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I return sale or clearance items?",
    answer:
      'Sale and clearance items follow the same return policy unless marked as "final sale" or "non-returnable" on the product page.',
    category: "returns",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 12,
    priority: 5,
    tags: ["sale", "clearance", "final sale"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "sale-items-return",
      metaTitle: "Sale Items Return | LetItRip Clearance Policy",
      metaDescription:
        "Sale items returnable unless marked final sale or non-returnable. Check product page for details.",
    },
    isActive: true,
    createdBy: "system",
  },

  // ============================================
  // PAYMENT (18 FAQs)
  // ============================================
  {
    question: "What payment methods are accepted?",
    answer:
      "We accept UPI (Google Pay, PhonePe, Paytm), credit/debit cards (Visa, Mastercard, RuPay), net banking, digital wallets, and EMI options on select purchases.",
    category: "payment",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 9,
    tags: ["payment", "methods", "options"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "payment-methods",
      metaTitle: "Payment Methods | LetItRip Accepted Payments",
      metaDescription:
        "Pay with UPI, cards, net banking, wallets, or EMI. Multiple secure payment options available.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Is it safe to use my credit card on LetItRip?",
    answer:
      "Yes, absolutely. We use industry-standard SSL encryption and PCI DSS compliant payment gateways. Your card details are never stored on our servers.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 8,
    tags: ["security", "credit card", "safe"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "credit-card-security",
      metaTitle: "Credit Card Security | LetItRip Safe Payments",
      metaDescription:
        "Shop safely with SSL encryption and PCI DSS compliant gateways. Card details never stored.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you offer EMI options?",
    answer:
      "Yes, EMI is available on orders above ₹3,000 for 3, 6, 9, and 12 months. Select EMI at checkout and choose your preferred bank and tenure.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 7,
    tags: ["EMI", "installments", "payment"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "emi-options",
      metaTitle: "EMI Options | LetItRip Installment Payments",
      metaDescription:
        "EMI available on orders above ₹3,000. Choose 3, 6, 9, or 12 months at checkout.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is your cancellation and refund policy?",
    answer:
      "Orders can be cancelled before shipping. Refunds are processed within 5-7 business days to your original payment method after cancellation or return approval.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["cancellation", "refund", "policy"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "cancellation-refund-policy",
      metaTitle: "Cancellation & Refund | LetItRip Payment Policy",
      metaDescription:
        "Cancel before shipping. Refunds in 5-7 days to original payment method after approval.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I use multiple payment methods for one order?",
    answer:
      "No, currently only one payment method can be used per order. You can split orders and use different payment methods for each.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 5,
    tags: ["multiple payments", "split", "order"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "multiple-payment-methods",
      metaTitle: "Multiple Payments | LetItRip Payment Options",
      metaDescription:
        "One payment method per order. Split orders to use different payment methods.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Why was my payment declined?",
    answer:
      "Payments can be declined due to insufficient funds, incorrect card details, bank security blocks, or payment gateway issues. Contact your bank or try another payment method.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 6,
    tags: ["declined", "failed", "payment"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "payment-declined",
      metaTitle: "Payment Declined | LetItRip Payment Issues",
      metaDescription:
        "Payment declined? Check funds, card details, or bank blocks. Try another payment method.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Will I receive a payment receipt?",
    answer:
      'Yes, a payment confirmation and invoice are sent to your email immediately after successful payment. You can also download invoices from "My Orders".',
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 5,
    tags: ["receipt", "invoice", "confirmation"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "payment-receipt",
      metaTitle: "Payment Receipt | LetItRip Invoice Download",
      metaDescription:
        "Receive payment confirmation via email. Download invoices from My Orders section anytime.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you accept international credit cards?",
    answer:
      "Yes, we accept international Visa, Mastercard, and American Express cards. Currency conversion charges may apply by your card issuer.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 4,
    tags: ["international", "credit card", "foreign"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "international-credit-cards",
      metaTitle: "International Cards | LetItRip Foreign Payments",
      metaDescription:
        "Accept Visa, Mastercard, AmEx international cards. Currency conversion by card issuer.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I save my card for future purchases?",
    answer:
      "Yes, you can securely save your card details in your account for faster checkout. All saved cards are tokenized and encrypted per RBI guidelines.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 5,
    tags: ["save card", "tokenization", "security"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "save-card-details",
      metaTitle: "Save Card Details | LetItRip Secure Payments",
      metaDescription:
        "Securely save cards for faster checkout. Tokenized and encrypted per RBI guidelines.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What if I'm charged twice for one order?",
    answer:
      "Double charges are rare but can occur due to payment gateway delays. Contact us at {{supportEmail}} immediately. The duplicate charge is automatically refunded within 7-10 business days.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 6,
    tags: ["double charge", "refund", "error"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "double-charged",
      metaTitle: "Double Charged | LetItRip Payment Error Resolution",
      metaDescription:
        "Charged twice? Contact support. Duplicate charges automatically refunded in 7-10 days.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you accept PayPal?",
    answer:
      "Currently, we do not accept PayPal. We accept UPI, cards, net banking, and digital wallets for Indian transactions.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 3,
    tags: ["PayPal", "payment", "methods"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "paypal-payment",
      metaTitle: "PayPal Payment | LetItRip Payment Methods",
      metaDescription:
        "PayPal not accepted. Use UPI, cards, net banking, or wallets for payments.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Are there any hidden charges?",
    answer:
      "No, all charges including product price, shipping, taxes, and any additional fees are clearly displayed at checkout before payment. No hidden charges.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 12,
    priority: 6,
    tags: ["charges", "fees", "transparency"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "hidden-charges",
      metaTitle: "Hidden Charges | LetItRip Transparent Pricing",
      metaDescription:
        "No hidden charges. All fees displayed at checkout before payment. Complete transparency.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I get a tax invoice for my purchase?",
    answer:
      'Yes, GST invoice is automatically generated and sent via email after order confirmation. You can also download it from "My Orders" section.',
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 13,
    priority: 5,
    tags: ["tax", "invoice", "GST"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "tax-invoice",
      metaTitle: "Tax Invoice | LetItRip GST Invoice Download",
      metaDescription:
        "GST invoice sent via email and available in My Orders. Download anytime for tax purposes.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is your policy on chargebacks?",
    answer:
      "Chargebacks should be initiated only after contacting our support team. Unauthorized chargebacks may result in account suspension and legal action.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 14,
    priority: 4,
    tags: ["chargeback", "dispute", "policy"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "chargeback-policy",
      metaTitle: "Chargeback Policy | LetItRip Payment Disputes",
      metaDescription:
        "Contact support before initiating chargebacks. Unauthorized chargebacks may lead to suspension.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How long does it take for refunds to process?",
    answer:
      "Refunds are processed within 5-7 business days after return approval. It may take additional 3-5 days for your bank to credit the amount.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 15,
    priority: 7,
    tags: ["refund", "processing", "time"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "refund-processing-time",
      metaTitle: "Refund Processing | LetItRip Refund Timeline",
      metaDescription:
        "Refunds in 5-7 days after approval. Bank credit takes additional 3-5 days.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I pay using a gift card or voucher?",
    answer:
      'Yes, you can apply gift cards, promo codes, or vouchers at checkout. Enter the code in the "Apply Coupon" field before payment.',
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 16,
    priority: 5,
    tags: ["gift card", "voucher", "coupon"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "gift-card-payment",
      metaTitle: "Gift Card Payment | LetItRip Voucher Redemption",
      metaDescription:
        "Apply gift cards, promo codes, and vouchers at checkout. Enter code before payment.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What happens if payment fails but money is deducted?",
    answer:
      "If payment fails but amount is debited, the transaction is automatically reversed within 5-7 business days. Contact your bank if not credited within this time.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 17,
    priority: 6,
    tags: ["failed payment", "deducted", "refund"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "failed-payment-deduction",
      metaTitle: "Failed Payment Deducted | LetItRip Payment Issues",
      metaDescription:
        "Money deducted but payment failed? Auto-reversed in 5-7 days. Contact bank if delayed.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you charge any transaction fees?",
    answer:
      "No transaction fees for UPI, cards, or net banking. COD orders may have a nominal handling charge. All charges are shown at checkout.",
    category: "payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 18,
    priority: 4,
    tags: ["fees", "transaction", "charges"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "transaction-fees",
      metaTitle: "Transaction Fees | LetItRip Payment Charges",
      metaDescription:
        "No transaction fees for online payments. COD may have handling charge. All shown at checkout.",
    },
    isActive: true,
    createdBy: "system",
  },

  // ============================================
  // ACCOUNT (10 FAQs)
  // ============================================
  {
    question: "How do I create an account?",
    answer:
      'Click "Sign Up" in the top menu, enter your email and password, or sign up with Google/Apple. Verify your email to complete registration.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 8,
    tags: ["signup", "registration", "account"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "create-account",
      metaTitle: "Create Account | LetItRip Registration",
      metaDescription:
        "Sign up with email or Google/Apple. Verify email to complete LetItRip account registration.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "I forgot my password. How do I reset it?",
    answer:
      'Click "Forgot Password" on the login page, enter your email, and click "Reset Password". You\'ll receive a reset link via email within 5 minutes.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 7,
    tags: ["password", "reset", "forgot"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "reset-password",
      metaTitle: "Reset Password | LetItRip Password Recovery",
      metaDescription:
        "Forgot password? Get reset link via email in 5 minutes. Click Forgot Password on login page.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I change my email address?",
    answer:
      'Yes, go to "Account Settings" → "Security" → "Change Email". Enter your new email and verify it. Your login email will be updated.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 6,
    tags: ["email", "change", "account"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "change-email-address",
      metaTitle: "Change Email | LetItRip Account Settings",
      metaDescription:
        "Update your email in Account Settings. Verify new email to complete the change.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I update my profile information?",
    answer:
      'Go to "My Profile" → "Edit Profile". You can update your name, phone number, and profile picture. Click "Save Changes" to update.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 6,
    tags: ["profile", "update", "edit"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "update-profile",
      metaTitle: "Update Profile | LetItRip Profile Settings",
      metaDescription:
        "Edit your name, phone, and photo in My Profile. Save changes to update account information.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I have multiple delivery addresses?",
    answer:
      'Yes, you can save multiple delivery addresses in "My Addresses". Set one as default for faster checkout or select different addresses for each order.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["addresses", "delivery", "multiple"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "multiple-addresses",
      metaTitle: "Multiple Addresses | LetItRip Delivery Options",
      metaDescription:
        "Save multiple delivery addresses. Set default or choose different address per order.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I delete my account?",
    answer:
      'Go to "Account Settings" → "Delete Account". Enter your password and confirm deletion. Note: This action is permanent and cannot be undone.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 5,
    tags: ["delete", "account", "remove"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "delete-account",
      metaTitle: "Delete Account | LetItRip Account Removal",
      metaDescription:
        "Delete your account permanently from Account Settings. Action cannot be undone.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Why do I need to verify my email?",
    answer:
      "Email verification ensures account security, enables password reset, and allows us to send order updates and important notifications.",
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 5,
    tags: ["verification", "email", "security"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "email-verification",
      metaTitle: "Email Verification | LetItRip Account Security",
      metaDescription:
        "Verify email for security, password reset, and order updates. Essential for account protection.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I link my social media accounts?",
    answer:
      'Yes, you can link Google and Apple accounts in "Account Settings" → "Connected Accounts" for easier login and social features.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 4,
    tags: ["social", "Google", "Apple"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "link-social-accounts",
      metaTitle: "Link Social Accounts | LetItRip Google & Apple",
      metaDescription:
        "Connect Google and Apple accounts for easier login. Manage in Account Settings.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I manage my email preferences?",
    answer:
      'Go to "Account Settings" → "Email Preferences" to choose which emails you want to receive: order updates, promotions, newsletters, etc.',
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 4,
    tags: ["email", "preferences", "notifications"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "email-preferences",
      metaTitle: "Email Preferences | LetItRip Notification Settings",
      metaDescription:
        "Manage email notifications in Account Settings. Choose which emails you want to receive.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What if my account is hacked or compromised?",
    answer:
      "Immediately reset your password and contact {{supportEmail}}. We'll secure your account, review unauthorized activities, and help recover your account.",
    category: "account",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 7,
    tags: ["security", "hacked", "compromised"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "account-compromised",
      metaTitle: "Account Compromised | LetItRip Security Help",
      metaDescription:
        "Account hacked? Reset password and contact support immediately for account recovery.",
    },
    isActive: true,
    createdBy: "system",
  },

  // ============================================
  // PRODUCTS (15 FAQs)
  // ============================================
  {
    question: "How do I search for products?",
    answer:
      "Use the search bar at the top, enter keywords, brands, or product names. You can also filter by category, price range, ratings, and more from the left sidebar.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 7,
    tags: ["search", "find", "products"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "search-products",
      metaTitle: "Search Products | LetItRip Product Discovery",
      metaDescription:
        "Search by keywords, brands, or names. Filter by category, price, and ratings for easy discovery.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do product auctions work?",
    answer:
      "Select an auction item, place your bid above the current bid. Bidding closes at the auction end time. Highest bidder wins and receives payment instructions via email.",
    category: "products",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 8,
    tags: ["auction", "bidding", "win"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-auctions",
      metaTitle: "Product Auctions | LetItRip Bidding Guide",
      metaDescription:
        "Bid on auction items. Highest bidder at end time wins. Payment instructions sent via email.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I save products to view later?",
    answer:
      'Yes, click the heart icon on any product to add it to your Wishlist. Access your saved items anytime from "My Wishlist" in your account.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 6,
    tags: ["wishlist", "save", "favorites"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "save-products-wishlist",
      metaTitle: "Wishlist | LetItRip Save Products",
      metaDescription:
        "Save products to wishlist by clicking heart icon. Access saved items from My Wishlist.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I know if a product is in stock?",
    answer:
      'In-stock products show "Add to Cart" button. Out-of-stock items display "Out of Stock" with option to get notified when available.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 6,
    tags: ["stock", "availability", "inventory"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-stock-availability",
      metaTitle: "Product Availability | LetItRip Stock Status",
      metaDescription:
        "In-stock products show Add to Cart. Out-of-stock items offer notification option.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What do product ratings mean?",
    answer:
      "Ratings are 1-5 stars based on verified customer reviews. 5 stars = excellent, 1 star = poor. Read reviews for detailed feedback on quality, fit, and value.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 5,
    tags: ["ratings", "reviews", "stars"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-ratings",
      metaTitle: "Product Ratings | LetItRip Review System",
      metaDescription:
        "1-5 star ratings from verified buyers. Read reviews for quality, fit, and value feedback.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I write a product review?",
    answer:
      'Yes, after receiving your order, go to "My Orders", select the product, and click "Write Review". Share your experience to help other buyers.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 5,
    tags: ["reviews", "write", "feedback"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "write-product-review",
      metaTitle: "Write Review | LetItRip Product Feedback",
      metaDescription:
        "Write reviews after delivery from My Orders. Share your experience to help other buyers.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What are promoted products?",
    answer:
      "Promoted products are highlighted listings that sellers pay to advertise. They appear at the top of search results and category pages for better visibility.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 4,
    tags: ["promoted", "ads", "sponsored"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "promoted-products",
      metaTitle: "Promoted Products | LetItRip Sponsored Listings",
      metaDescription:
        "Promoted products are paid ads appearing at top of search and category pages.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I compare products?",
    answer:
      'Click "Compare" on up to 4 products in the same category. A comparison table shows features, prices, ratings, and specifications side-by-side.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 5,
    tags: ["compare", "products", "features"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "compare-products",
      metaTitle: "Compare Products | LetItRip Product Comparison",
      metaDescription:
        "Compare up to 4 products. See features, prices, ratings, and specs side-by-side.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is the warranty on products?",
    answer:
      "Warranty varies by product and seller. Check the product description for warranty terms. Some items come with manufacturer warranty, others with seller warranty.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 6,
    tags: ["warranty", "guarantee", "coverage"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-warranty",
      metaTitle: "Product Warranty | LetItRip Warranty Information",
      metaDescription:
        "Warranty terms in product description. Manufacturer or seller warranty depending on item.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I request a product not listed?",
    answer:
      "Yes, use the \"Request Product\" form in the Help section. Provide product details and we'll work with sellers to list it if there's sufficient demand.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 4,
    tags: ["request", "product", "availability"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "request-product",
      metaTitle: "Request Product | LetItRip Product Requests",
      metaDescription:
        "Request unlisted products via Help section. We work with sellers based on demand.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Are product photos accurate?",
    answer:
      "We require sellers to use actual product photos. However, slight variations in color may occur due to screen settings. Check product description for details.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 5,
    tags: ["photos", "images", "accuracy"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-photos-accuracy",
      metaTitle: "Product Photos | LetItRip Image Accuracy",
      metaDescription:
        "Sellers use actual photos. Slight color variations may occur. Check description for details.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What are the product categories?",
    answer:
      "Browse categories: Electronics, Fashion, Home & Kitchen, Beauty & Personal Care, Sports & Fitness, Books & Media, Toys & Games, and more. Each category has subcategories for easy navigation.",
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 12,
    priority: 4,
    tags: ["categories", "browse", "navigation"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-categories",
      metaTitle: "Product Categories | LetItRip Browse Shopping",
      metaDescription:
        "Shop by category: Electronics, Fashion, Home, Beauty, Sports, Books, Toys, and more.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How often do you add new products?",
    answer:
      'New products are added daily by our sellers. Check "New Arrivals" section or enable notifications for specific categories to stay updated.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 13,
    priority: 4,
    tags: ["new", "arrivals", "updates"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "new-products",
      metaTitle: "New Products | LetItRip Latest Arrivals",
      metaDescription:
        "New products added daily. Check New Arrivals or enable category notifications.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I report a product listing?",
    answer:
      'Yes, if you find inappropriate, counterfeit, or misleading listings, click "Report Product" on the product page or contact {{supportEmail}} with details.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 14,
    priority: 5,
    tags: ["report", "listing", "inappropriate"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: ["supportEmail"],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "report-product-listing",
      metaTitle: "Report Product | LetItRip Report Listings",
      metaDescription:
        "Report inappropriate or misleading listings. Click Report Product or contact support.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Do you offer product recommendations?",
    answer:
      'Yes, we provide personalized recommendations based on your browsing history, purchases, and preferences. See "Recommended for You" on the homepage.',
    category: "products",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 15,
    priority: 5,
    tags: ["recommendations", "personalized", "suggestions"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "product-recommendations",
      metaTitle: "Product Recommendations | LetItRip Personalized Shopping",
      metaDescription:
        "Get personalized product recommendations based on browsing and purchases.",
    },
    isActive: true,
    createdBy: "system",
  },

  // ============================================
  // SELLERS (12 FAQs)
  // ============================================
  {
    question: "How do I become a seller on LetItRip?",
    answer:
      'Click "Become a Seller" in the footer, complete the registration form with business details, submit required documents (PAN, GST, bank details), and wait for verification (2-3 business days).',
    category: "sellers",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 1,
    priority: 8,
    tags: ["seller", "registration", "become seller"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "become-seller",
      metaTitle: "Become a Seller | LetItRip Seller Registration",
      metaDescription:
        "Register as seller with business details and documents. Verification in 2-3 days.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What are the seller fees?",
    answer:
      "We charge a commission of 10-15% per sale depending on the product category. There are no listing fees, monthly charges, or hidden costs.",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 7,
    tags: ["fees", "commission", "charges"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "seller-fees",
      metaTitle: "Seller Fees | LetItRip Commission Structure",
      metaDescription:
        "10-15% commission per sale by category. No listing fees or monthly charges.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I list products?",
    answer:
      'Log in to Seller Dashboard, click "Add Product", fill in details (title, description, price, images, specifications), set shipping options, and publish. Your listing goes live immediately after review.',
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 7,
    tags: ["listing", "products", "add"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "list-products",
      metaTitle: "List Products | LetItRip Seller Guide",
      metaDescription:
        "Add products from Seller Dashboard. Fill details, set shipping, publish. Live after review.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "When do I receive payments?",
    answer:
      "Payments are released 7 days after delivery confirmation or 14 days after shipping, whichever is earlier. Funds are transferred to your registered bank account.",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 8,
    tags: ["payments", "payout", "seller"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "seller-payments",
      metaTitle: "Seller Payments | LetItRip Payout Schedule",
      metaDescription:
        "Payments released 7 days after delivery or 14 days after shipping. Transferred to bank.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I promote my products?",
    answer:
      'Yes, use the "Promote Product" feature in Seller Dashboard. Promoted listings appear at top of search results. Pricing starts at ₹10/day per product.',
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["promotion", "advertising", "sponsored"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "promote-products",
      metaTitle: "Promote Products | LetItRip Seller Advertising",
      metaDescription:
        "Promote products from Seller Dashboard. Top search placement starts at ₹10/day.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What documents do I need to register as a seller?",
    answer:
      "Required: PAN card, GST certificate (if applicable), bank account details, business address proof, and identity proof (Aadhaar/Passport/Driving License).",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 7,
    tags: ["documents", "registration", "verification"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "seller-documents",
      metaTitle: "Seller Documents | LetItRip Registration Requirements",
      metaDescription:
        "Required docs: PAN, GST, bank details, address proof, ID proof for seller registration.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I manage inventory?",
    answer:
      'Use Seller Dashboard → "Inventory Management" to update stock levels, set low-stock alerts, and bulk upload inventory via CSV files.',
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 6,
    tags: ["inventory", "stock", "management"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "manage-inventory",
      metaTitle: "Inventory Management | LetItRip Seller Dashboard",
      metaDescription:
        "Manage stock levels, set alerts, bulk upload via CSV in Seller Dashboard.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What is seller rating and how does it work?",
    answer:
      "Seller rating (1-5 stars) is based on customer reviews, order fulfillment speed, product quality, and customer service. High ratings improve visibility.",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 5,
    tags: ["rating", "reviews", "seller performance"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "seller-rating",
      metaTitle: "Seller Rating | LetItRip Performance Metrics",
      metaDescription:
        "1-5 star rating based on reviews, fulfillment, quality, service. High ratings boost visibility.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I offer discounts and coupons?",
    answer:
      'Yes, create discount codes in Seller Dashboard → "Promotions". Set percentage/fixed discounts, minimum order values, expiry dates, and usage limits.',
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 5,
    tags: ["discounts", "coupons", "promotions"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "seller-discounts",
      metaTitle: "Seller Discounts | LetItRip Coupon Creation",
      metaDescription:
        "Create discount codes in Promotions. Set amounts, minimums, expiry, usage limits.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "How do I handle returns and refunds?",
    answer:
      "Returns are managed in Seller Dashboard. When a return is requested, review the reason, approve/reject within 24 hours, and arrange pickup. Refunds are processed after inspection.",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 6,
    tags: ["returns", "refunds", "seller"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "seller-returns",
      metaTitle: "Seller Returns | LetItRip Return Management",
      metaDescription:
        "Manage returns in Dashboard. Review, approve/reject in 24h, arrange pickup, process refunds.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "What are the product listing guidelines?",
    answer:
      "Use clear photos, accurate descriptions, competitive pricing, correct category, and include all specifications. Prohibited: counterfeit goods, illegal items, misleading information.",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 6,
    tags: ["guidelines", "policies", "listing"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "listing-guidelines",
      metaTitle: "Listing Guidelines | LetItRip Seller Policies",
      metaDescription:
        "Use clear photos, accurate info, correct category. No counterfeits or misleading content.",
    },
    isActive: true,
    createdBy: "system",
  },
  {
    question: "Can I sell internationally?",
    answer:
      "Currently, LetItRip only supports domestic sales within India. International selling may be available in the future.",
    category: "sellers",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 12,
    priority: 4,
    tags: ["international", "selling", "export"],
    relatedFAQs: [],
    useSiteSettings: false,
    variables: [],
    stats: { views: 0, helpful: 0, notHelpful: 0 },
    seo: {
      slug: "international-selling",
      metaTitle: "International Selling | LetItRip Export Options",
      metaDescription:
        "Currently India-only sales. International selling coming soon.",
    },
    isActive: true,
    createdBy: "system",
  },
];

// Export with camelCase name for consistency with other seed data files
export const faqSeedData = FAQ_SEED_DATA;
