/**
 * Products Seed Data
 * Sample product data across various categories
 */

import type { ProductDocument } from "@/db/schema";

export const productsSeedData: Partial<ProductDocument>[] = [
  // Electronics > Smartphones
  {
    id: "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    title: "iPhone 15 Pro Max",
    description: "Latest iPhone with titanium design and A17 Pro chip.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Apple",
    price: 134900,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 25,
    mainImage:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1678652197950-372d7e96f926?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1678911820864-e5c67c5d96ed?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["smartphone", "iphone", "apple", "5g", "premium"],
    specifications: [
      { name: "Display", value: "6.7 inch" },
      { name: "Storage", value: "256", unit: "GB" },
      { name: "Camera", value: "48 MP" },
    ],
    features: ["Titanium design", "A17 Pro chip", "Face ID"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns accepted.",
    condition: "new",
    insurance: true,
    insuranceCost: 999,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-12-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },
  {
    id: "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    title: "Samsung Galaxy S24 Ultra",
    description: "Premium Android with S Pen and 200MP camera.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Samsung",
    price: 124999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage:
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1591122947157-26bad3a117d2?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["smartphone", "samsung", "android", "5g", "spen"],
    specifications: [
      { name: "Display", value: "6.8 inch" },
      { name: "Storage", value: "256", unit: "GB" },
      { name: "Camera", value: "200 MP" },
    ],
    features: ["S Pen included", "AI features", "100x Zoom"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-12-15T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },
  {
    id: "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    title: "Google Pixel 8 Pro",
    description: "Google flagship with AI features and pure Android.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Google",
    price: 84999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 20,
    mainImage:
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["smartphone", "google", "pixel", "android", "camera"],
    specifications: [
      { name: "Display", value: "6.7 inch" },
      { name: "Storage", value: "128", unit: "GB" },
      { name: "Camera", value: "50 MP" },
    ],
    features: ["Tensor G3 chip", "7 years updates", "Magic Eraser"],
    shippingInfo: "Free shipping in 3-5 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-20T00:00:00Z"),
    updatedAt: new Date("2026-02-04T00:00:00Z"),
  },

  // Electronics > Laptops
  {
    id: "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    title: 'MacBook Pro 16" M3 Max',
    description: "Professional laptop with M3 Max chip for creators.",
    category: "category-laptops-computers-electronics",
    subcategory: "Professional Laptops",
    brand: "Apple",
    price: 249900,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    mainImage:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["laptop", "macbook", "apple", "professional", "m3"],
    specifications: [
      { name: "Display", value: "16.2 inch" },
      { name: "RAM", value: "36", unit: "GB" },
      { name: "Storage", value: "1", unit: "TB" },
    ],
    features: ["M3 Max chip", "ProMotion", "22hr battery"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-15T23:59:59Z"),
    createdAt: new Date("2025-11-01T00:00:00Z"),
    updatedAt: new Date("2026-02-07T00:00:00Z"),
  },
  {
    id: "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    title: "Dell XPS 15",
    description: "Premium Windows laptop with i9 and RTX 4060.",
    category: "category-laptops-computers-electronics",
    subcategory: "Professional Laptops",
    brand: "Dell",
    price: 189999,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 15,
    mainImage:
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["laptop", "dell", "windows", "professional", "gaming"],
    specifications: [
      { name: "Display", value: "15.6 inch" },
      { name: "RAM", value: "32", unit: "GB" },
      { name: "Storage", value: "1", unit: "TB" },
    ],
    features: ["Intel i9", "RTX 4060", "Thunderbolt 4"],
    shippingInfo: "Free shipping in 4-6 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-15T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },

  // Fashion > Men's Fashion
  {
    id: "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    title: "Men's Cotton Casual Shirt",
    description: "Comfortable cotton shirt for daily wear.",
    category: "category-mens-fashion-fashion",
    subcategory: "Shirts",
    brand: "Raymond",
    price: 1499,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 100,
    mainImage:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["mens", "shirt", "casual", "cotton", "fashion"],
    specifications: [
      { name: "Material", value: "100% Cotton" },
      { name: "Fit", value: "Regular Fit" },
    ],
    features: ["Breathable", "Machine washable"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-09-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // Fashion > Women's Fashion
  {
    id: "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    title: "Women's Ethnic Kurti",
    description: "Ethnic kurti with traditional prints.",
    category: "category-womens-fashion-fashion",
    subcategory: "Ethnic Wear",
    brand: "Fabindia",
    price: 1999,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 80,
    mainImage:
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["womens", "kurti", "ethnic", "traditional", "fashion"],
    specifications: [
      { name: "Material", value: "Cotton Blend" },
      { name: "Length", value: "Knee Length" },
    ],
    features: ["Hand block print", "Easy care"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-08-20T00:00:00Z"),
    updatedAt: new Date("2026-01-28T00:00:00Z"),
  },

  // Home & Kitchen
  {
    id: "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    title: "Non-Stick Cookware Set",
    description: "7-piece non-stick cookware set with glass lids.",
    category: "category-home-kitchen",
    subcategory: "Cookware",
    brand: "Prestige",
    price: 3499,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage:
      "https://images.unsplash.com/photo-1584990347449-39b0ce4aa1f9?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1584990347449-39b0ce4aa1f9?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["kitchen", "cookware", "nonstick", "home", "cooking"],
    specifications: [
      { name: "Material", value: "Aluminum" },
      { name: "Pieces", value: "7" },
      { name: "Induction Safe", value: "Yes" },
    ],
    features: ["PFOA free", "Easy to clean", "Glass lids"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-07-10T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },

  // Sports & Outdoors
  {
    id: "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    title: "Yoga Mat with Carrying Bag",
    description: "Premium yoga mat with non-slip surface.",
    category: "category-sports-outdoors",
    subcategory: "Fitness",
    brand: "Reebok",
    price: 1299,
    currency: "INR",
    stockQuantity: 75,
    availableQuantity: 75,
    mainImage:
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["yoga", "fitness", "sports", "exercise", "mat"],
    specifications: [
      { name: "Material", value: "TPE" },
      { name: "Thickness", value: "6", unit: "mm" },
    ],
    features: ["Non-slip", "Eco-friendly", "Carrying bag"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-06-15T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"),
  },

  // Auction Product - Vintage Camera
  {
    id: "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    title: "Vintage Canon AE-1 Film Camera",
    description: "Classic 35mm film camera from 1980s. Fully functional.",
    category: "category-cameras-photography-electronics",
    subcategory: "Vintage Cameras",
    brand: "Canon",
    price: 15000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["camera", "vintage", "film", "canon", "collector"],
    specifications: [
      { name: "Type", value: "35mm Film SLR" },
      { name: "Lens", value: "50mm f/1.8" },
      { name: "Year", value: "1983" },
    ],
    features: ["Fully functional", "Original lens", "Film tested"],
    shippingInfo: "Insured shipping in 3-5 days.",
    returnPolicy: "No returns on auctions.",
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-14T23:59:59Z"),
    startingBid: 15000,
    currentBid: 22000,
    bidCount: 8,
    reservePrice: 25000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-14T23:59:59Z"),
    createdAt: new Date("2026-01-20T00:00:00Z"),
    updatedAt: new Date("2026-02-08T18:30:00Z"),
  },

  // Out of stock product
  {
    id: "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
    title: "Sony WH-1000XM5 Headphones",
    description: "Premium noise-cancelling headphones. Out of stock.",
    category: "category-audio-electronics",
    subcategory: "Headphones",
    brand: "Sony",
    price: 29990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=1200&h=800&fit=crop",
    ],
    status: "out_of_stock",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["headphones", "sony", "noise-cancelling", "audio", "premium"],
    specifications: [
      { name: "Type", value: "Over-ear" },
      { name: "Battery", value: "30 hours" },
    ],
    features: ["ANC", "LDAC audio", "Multipoint"],
    shippingInfo: "Currently unavailable.",
    returnPolicy: "7-day returns when available.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-05-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // ─── Men's Fashion ─────────────────────────────────────────────────────────
  {
    id: "product-mens-oxford-shirt-fashion-new-fashionboutique-1",
    title: "Classic Oxford Button-Down Shirt",
    description:
      "Timeless 100% cotton Oxford shirt with a relaxed fit. Perfect for office or casual outings. Available in multiple colours.",
    category: "category-mens-fashion-fashion",
    subcategory: "Shirts",
    brand: "StyleCraft",
    price: 1299,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 75,
    mainImage:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["shirt", "mens", "oxford", "cotton", "casual", "formal"],
    specifications: [
      { name: "Material", value: "100% Cotton" },
      { name: "Fit", value: "Regular" },
      { name: "Collar", value: "Button-down" },
    ],
    features: ["Machine washable", "Wrinkle-resistant", "Breathable fabric"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day easy returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-15T23:59:59Z"),
    createdAt: new Date("2025-11-10T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
  },
  {
    id: "product-mens-slim-chinos-fashion-new-fashionboutique-1",
    title: "Slim Fit Stretch Chinos",
    description:
      "Modern slim-fit chinos with 2% elastane for all-day comfort. Pairs well with shirts and casual tees.",
    category: "category-mens-fashion-fashion",
    subcategory: "Trousers",
    brand: "StyleCraft",
    price: 1799,
    currency: "INR",
    stockQuantity: 60,
    availableQuantity: 55,
    mainImage:
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["chinos", "trousers", "slim-fit", "mens", "stretch"],
    specifications: [
      { name: "Material", value: "98% Cotton, 2% Elastane" },
      { name: "Fit", value: "Slim" },
      { name: "Rise", value: "Mid-rise" },
    ],
    features: ["Stretch fabric", "Two front pockets", "Machine washable"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day easy returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-15T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },
  {
    id: "product-mens-leather-derby-shoes-fashion-new-fashionboutique-1",
    title: "Genuine Leather Derby Shoes",
    description:
      "Hand-stitched genuine leather derby shoes with cushioned insoles. Ideal for formal occasions and office wear.",
    category: "category-mens-fashion-fashion",
    subcategory: "Footwear",
    brand: "LeatherCraft",
    price: 3499,
    currency: "INR",
    stockQuantity: 35,
    availableQuantity: 30,
    mainImage:
      "https://images.unsplash.com/photo-1614253429340-98120bd6d753?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1614253429340-98120bd6d753?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["shoes", "leather", "derby", "formal", "mens", "handcrafted"],
    specifications: [
      { name: "Material", value: "Full-grain leather" },
      { name: "Sole", value: "Rubber" },
      { name: "Closure", value: "Lace-up" },
    ],
    features: ["Hand-stitched", "Cushioned insole", "Anti-slip sole"],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "7-day returns (unused condition).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-12-01T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },

  // ─── Women's Fashion ───────────────────────────────────────────────────────
  {
    id: "product-womens-anarkali-kurta-fashion-new-fashionboutique-1",
    title: "Embroidered Anarkali Kurta Set",
    description:
      "Elegant 3-piece Anarkali set with dupatta and palazzo. Intricate thread embroidery on georgette fabric. Perfect for festivals and weddings.",
    category: "category-womens-fashion-fashion",
    subcategory: "Ethnic Wear",
    brand: "Rang & Dhang",
    price: 2899,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 38,
    mainImage:
      "https://images.unsplash.com/photo-1583391733975-f47c28ce1930?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1583391733975-f47c28ce1930?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: ["kurta", "anarkali", "ethnic", "womens", "festive", "embroidery"],
    specifications: [
      { name: "Fabric", value: "Georgette" },
      { name: "Work", value: "Thread embroidery" },
      { name: "Set includes", value: "Kurta, Palazzo, Dupatta" },
    ],
    features: ["Dry clean recommended", "Occasion wear", "3-piece set"],
    shippingInfo: "Ships in 2-4 business days.",
    returnPolicy: "7-day returns for unworn items.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-31T23:59:59Z"),
    createdAt: new Date("2025-10-20T00:00:00Z"),
    updatedAt: new Date("2026-02-14T00:00:00Z"),
  },
  {
    id: "product-womens-casual-midi-dress-fashion-new-fashionboutique-1",
    title: "Floral Print Wrap Midi Dress",
    description:
      "Breezy wrap-style midi dress in a vibrant floral print. Made from breathable viscose. Adjustable tie-waist for a flattering fit.",
    category: "category-womens-fashion-fashion",
    subcategory: "Dresses",
    brand: "Bloomer",
    price: 1649,
    currency: "INR",
    stockQuantity: 55,
    availableQuantity: 50,
    mainImage:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["dress", "midi", "floral", "wrap", "womens", "casual"],
    specifications: [
      { name: "Material", value: "Viscose" },
      { name: "Length", value: "Midi (below knee)" },
      { name: "Closure", value: "Wrap tie" },
    ],
    features: [
      "Machine washable",
      "All-season wear",
      "Inclusive sizing XS-3XL",
    ],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day easy returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-12-10T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },
  {
    id: "product-womens-structured-tote-bag-fashion-new-fashionboutique-1",
    title: "Structured Vegan Leather Tote Bag",
    description:
      "Spacious structured tote in vegan leather with laptop compartment. Magnetic snap closure and detachable pouch.",
    category: "category-womens-fashion-fashion",
    subcategory: "Bags",
    brand: "Prada (Inspired)",
    price: 1999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage:
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["bag", "tote", "vegan-leather", "womens", "office", "laptop"],
    specifications: [
      { name: "Material", value: "Vegan leather (PU)" },
      { name: "Dimensions", value: "38 × 30 × 14 cm" },
      { name: "Compartments", value: "3 (1 laptop, 2 main)" },
    ],
    features: ['Fits 15" laptop', "Detachable pouch", "Magnetic snap"],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-05T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // ─── Home & Kitchen ────────────────────────────────────────────────────────
  {
    id: "product-prestige-pressure-cooker-home-new-homeessentials-1",
    title: "Prestige Clip-on 5L Pressure Cooker",
    description:
      "5-litre hard-anodised pressure cooker with safety valve and clip-on lid locking system. Suitable for all cooktops including induction.",
    category: "category-home-kitchen",
    subcategory: "Cookware",
    brand: "Prestige",
    price: 2499,
    currency: "INR",
    stockQuantity: 45,
    availableQuantity: 42,
    mainImage:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["pressure-cooker", "kitchen", "cookware", "induction", "prestige"],
    specifications: [
      { name: "Capacity", value: "5", unit: "L" },
      { name: "Material", value: "Hard-anodised aluminium" },
      { name: "Compatible", value: "Gas, Induction, Electric" },
    ],
    features: ["Safety valve", "Clip-on locking", "Induction compatible"],
    shippingInfo: "Free shipping over ₹999. Ships in 2-3 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-09-15T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
  },
  {
    id: "product-nonstick-cookware-set-home-new-homeessentials-1",
    title: "6-Piece Non-stick Cookware Set",
    description:
      "PFOA-free granite-coated non-stick set including 3 fry pans (18/22/26 cm) and 3 sauce pans with glass lids. Even heat distribution.",
    category: "category-home-kitchen",
    subcategory: "Cookware",
    brand: "GreenChef",
    price: 3799,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 23,
    mainImage:
      "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["cookware", "non-stick", "fry-pan", "kitchen", "set", "granite"],
    specifications: [
      { name: "Pieces", value: "6" },
      { name: "Coating", value: "Granite non-stick (PFOA-free)" },
      { name: "Compatible", value: "Gas, Induction" },
    ],
    features: ["PFOA-free", "Glass lids", "Even heating", "Easy clean"],
    shippingInfo: "Free shipping. Ships in 3-4 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-01T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"),
  },
  {
    id: "product-smart-air-purifier-home-new-homeessentials-1",
    title: "Mi Air Purifier 3 Pro — HEPA H13",
    description:
      "HEPA H13 true air purifier covering 484 sq ft. Removes PM2.5, allergens, bacteria. Smart control via Mi Home app.",
    category: "category-home-kitchen",
    subcategory: "Appliances",
    brand: "Xiaomi",
    price: 12999,
    currency: "INR",
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["air-purifier", "hepa", "smart", "xiaomi", "home", "appliance"],
    specifications: [
      { name: "Coverage", value: "484", unit: "sq ft" },
      { name: "Filter", value: "True HEPA H13" },
      { name: "CADR", value: "380", unit: "m³/h" },
    ],
    features: [
      "App control",
      "Auto mode",
      "Real-time AQI display",
      "Night mode",
    ],
    shippingInfo: "Free shipping. Ships in 2-4 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-20T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },
  {
    id: "product-solid-wood-coffee-table-home-new-homeessentials-1",
    title: "Sheesham Wood Rustic Coffee Table",
    description:
      "Handcrafted solid Sheesham (Indian rosewood) coffee table with lower shelf. Natural finish brings warmth to any living room.",
    category: "category-home-kitchen",
    subcategory: "Furniture",
    brand: "WoodCraft India",
    price: 8499,
    currency: "INR",
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["coffee-table", "sheesham", "wood", "furniture", "living-room"],
    specifications: [
      { name: "Wood", value: "Solid Sheesham" },
      { name: "Dimensions", value: "120 × 60 × 45 cm" },
      { name: "Finish", value: "Natural matte" },
    ],
    features: ["Handcrafted", "Lower shelf storage", "Pre-assembled"],
    shippingInfo: "Heavy item — ships in 7-10 days.",
    returnPolicy: "No returns on assembled furniture.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-07-01T00:00:00Z"),
    updatedAt: new Date("2025-12-15T00:00:00Z"),
  },

  // ─── Sports & Outdoors ─────────────────────────────────────────────────────
  {
    id: "product-premium-yoga-mat-sports-new-sportszone-1",
    title: "Liforme Original Yoga Mat",
    description:
      "Eco-friendly natural rubber yoga mat with alignment lines. 4.2mm thickness for superior joint cushioning. Non-slip grip in all conditions.",
    category: "category-sports-outdoors",
    subcategory: "Yoga & Fitness",
    brand: "Liforme",
    price: 3999,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 47,
    mainImage:
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["yoga", "mat", "fitness", "eco-friendly", "rubber", "non-slip"],
    specifications: [
      { name: "Material", value: "Natural rubber" },
      { name: "Thickness", value: "4.2", unit: "mm" },
      { name: "Dimensions", value: "185 × 68 cm" },
    ],
    features: [
      "Alignment guide lines",
      "Non-slip grip",
      "Eco-materials",
      "Carry strap included",
    ],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-01T23:59:59Z"),
    createdAt: new Date("2025-08-01T00:00:00Z"),
    updatedAt: new Date("2026-02-12T00:00:00Z"),
  },
  {
    id: "product-adjustable-dumbbell-set-sports-new-sportszone-1",
    title: "Adjustable Dumbbell Set 5-25 kg",
    description:
      "Space-saving adjustable dumbbells that replace 9 pairs. Dial selector adjusts weight in 2.5 kg increments from 5 to 25 kg. Ideal for home gym.",
    category: "category-sports-outdoors",
    subcategory: "Gym Equipment",
    brand: "PowerBlock",
    price: 14999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["dumbbell", "gym", "fitness", "adjustable", "home-gym", "weights"],
    specifications: [
      { name: "Weight range", value: "5–25", unit: "kg per dumbbell" },
      { name: "Increments", value: "2.5", unit: "kg" },
      { name: "Material", value: "Steel with rubber coating" },
    ],
    features: [
      "Replaces 9 pairs",
      "Compact storage",
      "Dial selector mechanism",
    ],
    shippingInfo: "Heavy item — free shipping. Ships in 5-7 days.",
    returnPolicy: "7-day returns (original packaging).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-09-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },
  {
    id: "product-cricket-bat-mrf-sports-new-sportszone-1",
    title: "MRF Genius Grand Edition Cricket Bat",
    description:
      "English willow Grade 1 cricket bat with cane handle and thick edges. Pre-knocked and ready to play. Endorsed by professional cricketers.",
    category: "category-sports-outdoors",
    subcategory: "Cricket",
    brand: "MRF",
    price: 6999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage:
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["cricket", "bat", "mrf", "english-willow", "sports"],
    specifications: [
      { name: "Wood", value: "English Willow Grade 1" },
      { name: "Handle", value: "Cane" },
      { name: "Weight", value: "1.1–1.2", unit: "kg" },
    ],
    features: ["Pre-knocked", "Anti-scuff sheet", "Bat grip included"],
    shippingInfo: "Ships in 2-4 business days.",
    returnPolicy: "7-day returns (unused).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-15T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },
  {
    id: "product-running-shoes-adidas-sports-new-sportszone-1",
    title: "Adidas Ultraboost 22 Running Shoes",
    description:
      "Premium running shoes with Boost midsole for responsive cushioning. Primeknit+ upper adapts to your foot. Ideal for long-distance running.",
    category: "category-sports-outdoors",
    subcategory: "Footwear",
    brand: "Adidas",
    price: 15999,
    currency: "INR",
    stockQuantity: 22,
    availableQuantity: 19,
    mainImage:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["running", "shoes", "adidas", "ultraboost", "sports"],
    specifications: [
      { name: "Upper", value: "Primeknit+" },
      { name: "Midsole", value: "Boost" },
      { name: "Drop", value: "10", unit: "mm" },
    ],
    features: [
      "Energy-return Boost foam",
      "Continental rubber outsole",
      "Torsion system",
    ],
    shippingInfo: "Ships in 2-3 business days.",
    returnPolicy: "15-day returns (unworn).",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },

  // ─── More Electronics ──────────────────────────────────────────────────────
  {
    id: "product-apple-ipad-pro-electronics-new-techhub-1",
    title: 'Apple iPad Pro 11" M2 (Wi-Fi, 256GB)',
    description:
      "The iPad Pro featuring Apple M2 chip, Liquid Retina display, and ProMotion 120Hz. Thunderbolt port and Wi-Fi 6E connectivity.",
    category: "category-laptops-computers-electronics",
    subcategory: "Tablets",
    brand: "Apple",
    price: 89900,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["ipad", "apple", "tablet", "m2", "pro"],
    specifications: [
      { name: "Chip", value: "Apple M2" },
      { name: "Display", value: "11-inch Liquid Retina" },
      { name: "Storage", value: "256", unit: "GB" },
    ],
    features: ["ProMotion 120Hz", "Thunderbolt port", "Wi-Fi 6E", "Face ID"],
    shippingInfo: "Free delivery in 1-2 business days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-12-15T00:00:00Z"),
    updatedAt: new Date("2026-02-16T00:00:00Z"),
  },
  {
    id: "product-samsung-galaxy-watch6-electronics-new-techhub-1",
    title: "Samsung Galaxy Watch 6 Classic 47mm",
    description:
      "Premium smartwatch with rotating bezel, BioActive sensor for health tracking, and 5ATM water resistance. Android & iOS compatible.",
    category: "category-mobiles-accessories-electronics",
    subcategory: "Smartwatches",
    brand: "Samsung",
    price: 34999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["smartwatch", "samsung", "galaxy-watch", "wearable", "health"],
    specifications: [
      { name: "Size", value: "47mm" },
      { name: "Display", value: 'AMOLED 1.47"' },
      { name: "Battery", value: "425", unit: "mAh" },
    ],
    features: [
      "Rotating bezel",
      "BioActive sensor",
      "Sleep tracking",
      "5ATM water resistant",
    ],
    shippingInfo: "Free shipping. Ships in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-10T00:00:00Z"),
    updatedAt: new Date("2026-02-10T00:00:00Z"),
  },
  {
    id: "product-anker-usbc-charger-electronics-new-techhub-1",
    title: "Anker 65W USB-C GaN II Charger",
    description:
      "Ultra-compact 65W GaN II charger with two USB-C and one USB-A port. Charges laptop, tablet, and phone simultaneously.",
    category: "category-mobile-accessories-mobiles-accessories",
    subcategory: "Chargers",
    brand: "Anker",
    price: 2499,
    currency: "INR",
    stockQuantity: 70,
    availableQuantity: 68,
    mainImage:
      "https://images.unsplash.com/photo-1625772452859-1c03d884f65d?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1625772452859-1c03d884f65d?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["charger", "usb-c", "ganII", "65w", "anker", "fast-charging"],
    specifications: [
      { name: "Total output", value: "65", unit: "W" },
      { name: "Ports", value: "2× USB-C + 1× USB-A" },
      { name: "Technology", value: "GaN II" },
    ],
    features: ["Foldable plug", "Safeguard tech", "Universal compatibility"],
    shippingInfo: "Ships in 1-2 business days.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-20T00:00:00Z"),
    updatedAt: new Date("2026-02-15T00:00:00Z"),
  },

  // ─── Auction Items ─────────────────────────────────────────────────────────
  {
    id: "product-macbook-pro-m3-auction-electronics-techhub-1",
    title: 'MacBook Pro 14" M3 Pro (16GB/512GB) — AUCTION',
    description:
      'Like-new MacBook Pro 14" with M3 Pro chip. Opened but unused — sealed in original box. Starting bid is 60% of retail. One-time listing.',
    category: "category-laptops-computers-electronics",
    subcategory: "Laptops",
    brand: "Apple",
    price: 169900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["macbook", "apple", "auction", "laptop", "m3", "pro"],
    specifications: [
      { name: "Chip", value: "M3 Pro" },
      { name: "RAM", value: "16", unit: "GB" },
      { name: "Storage", value: "512", unit: "GB" },
    ],
    features: [
      "Liquid Retina XDR display",
      "ProMotion 120Hz",
      "HDMI 2.1",
      "MagSafe 3",
    ],
    shippingInfo: "Ships within 24 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "refurbished",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-16T23:59:59Z"),
    startingBid: 100000,
    currentBid: 115000,
    bidCount: 7,
    buyNowPrice: 180000,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-16T23:59:59Z"),
    createdAt: new Date("2026-02-10T00:00:00Z"),
    updatedAt: new Date("2026-02-19T00:00:00Z"),
  },
  {
    id: "product-vintage-leica-camera-auction-artisan-1",
    title: "Vintage Leica M6 Film Camera — AUCTION",
    description:
      "1994 Leica M6 TTL 0.72 in excellent condition. All mechanics working. Original box, caps, strap, and manual included. A collector's treasure.",
    category: "category-cameras-photography-electronics",
    subcategory: "Film Cameras",
    brand: "Leica",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1606986628253-3c3d8c9da85c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1606986628253-3c3d8c9da85c?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["leica", "camera", "vintage", "film", "collector", "auction"],
    specifications: [
      { name: "Model", value: "Leica M6 TTL 0.72" },
      { name: "Year", value: "1994" },
      { name: "Condition", value: "9/10 — Excellent" },
    ],
    features: [
      "TTL metering",
      "0.72x viewfinder",
      "Original accessories included",
    ],
    shippingInfo: "Insured shipping within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 2000,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-10T18:00:00Z"),
    startingBid: 85000,
    currentBid: 97500,
    bidCount: 5,
    reservePrice: 100000,
    minBidIncrement: 2500,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-02-05T00:00:00Z"),
    updatedAt: new Date("2026-02-19T00:00:00Z"),
  },
  {
    id: "product-limited-air-jordan-sneakers-auction-artisan-1",
    title: "Nike Air Jordan 1 Retro High OG 'Chicago' — AUCTION",
    description:
      "Deadstock Air Jordan 1 Retro High OG in the iconic Chicago colourway. Size 10 US. Never worn, original box with tissue paper.",
    category: "category-mens-fashion-fashion",
    subcategory: "Sneakers",
    brand: "Nike",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: [
      "jordan",
      "sneakers",
      "nike",
      "limited",
      "deadstock",
      "auction",
      "chicago",
    ],
    specifications: [
      { name: "Model", value: "Air Jordan 1 Retro High OG" },
      { name: "Colourway", value: "Chicago (Red/White/Black)" },
      { name: "Size", value: "US 10 / UK 9 / EU 44" },
    ],
    features: [
      "Deadstock — never worn",
      "Original box",
      "Authentication certificate",
    ],
    shippingInfo: "Secure packaged shipping within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: true,
    insuranceCost: 750,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-11T20:00:00Z"),
    startingBid: 25000,
    currentBid: 38000,
    bidCount: 11,
    buyNowPrice: 65000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: new Date("2026-03-11T20:00:00Z"),
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-01T20:00:00Z"),
    createdAt: new Date("2026-02-08T00:00:00Z"),
    updatedAt: new Date("2026-02-19T00:00:00Z"),
  },

  // ── DRAFT: Trail Running Shoes ──────────────────────────────────────────────
  // Tests: seller create draft, admin cannot see in public listing API,
  //        seller publish flow, seller CRUD on own draft products
  {
    id: "product-trail-running-shoes-sports-draft-sportszone-1",
    title: "Trailblazer Pro Trail Running Shoes",
    description:
      "High-grip trail running shoes with waterproof Gore-Tex upper, Vibram outsole, and responsive EVA midsole. Suitable for technical terrain and long-distance trail runs.",
    category: "category-sports-outdoors",
    subcategory: "Running Shoes",
    brand: "Trailblazer",
    price: 8999,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=800&fit=crop",
    ],
    status: "draft", // ← seller is still setting up the listing
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["trail", "running", "shoes", "waterproof", "vibram", "gore-tex"],
    specifications: [
      { name: "Upper", value: "Gore-Tex Waterproof" },
      { name: "Outsole", value: "Vibram Megagrip" },
      { name: "Weight", value: "320", unit: "g" },
    ],
    features: [
      "Gore-Tex waterproof membrane",
      "Vibram® Megagrip outsole for technical terrain",
      "Responsive EVA midsole",
    ],
    shippingInfo: "Ships within 3–5 business days.",
    returnPolicy: "7-day return policy. Unused items only.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-02-28T12:00:00Z"),
    updatedAt: new Date("2026-02-28T12:00:00Z"),
  },

  // ── DISCONTINUED: Wired Earphones (old model replaced by wireless) ─────────
  // Tests: admin discontinue product action, discontinued badge in listings,
  //        search filter excludes discontinued, SEO canonical redirect
  {
    id: "product-wired-earphones-electronics-discontinued-techhub-1",
    title: "Sony MDR-EX15AP Wired In-Ear Earphones",
    description:
      "Sony MDR-EX15AP wired earphones with built-in microphone and remote. 9mm drivers, 1.2m tangle-free cable. This model has been discontinued and replaced by the newer wireless range.",
    category: "category-audio-electronics",
    subcategory: "Wired Earphones",
    brand: "Sony",
    price: 799,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1200&h=800&fit=crop",
    ],
    status: "discontinued", // ← admin marked discontinued; no new orders possible
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: [
      "sony",
      "earphones",
      "wired",
      "in-ear",
      "microphone",
      "discontinued",
    ],
    specifications: [
      { name: "Driver", value: "9mm" },
      { name: "Cable Length", value: "1.2", unit: "m" },
      { name: "Impedance", value: "16", unit: "Ω" },
    ],
    features: [
      "Built-in microphone & one-button remote",
      "Tangle-free cable",
      "Compatible with Android & iOS",
    ],
    shippingInfo: "N/A — product discontinued.",
    returnPolicy: "N/A — product discontinued.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2024-06-01T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"), // date admin set discontinued
  },

  // ── SOLD: Vintage Handcrafted Leather Journal ──────────────────────────────
  // Tests: sold status badge, add-to-cart blocked for sold items,
  //        seller sold inventory UI, "notify me" waitlist CTA
  {
    id: "product-vintage-leather-journal-sold-artisan-1",
    title: "Handcrafted Vintage Leather Journal — A5 Refillable",
    description:
      "Hand-stitched genuine buffalo leather journal. A5 format, 200 acid-free pages, refillable. Each journal is unique — slight variations in grain and color are part of the character.",
    category: "category-home-kitchen",
    subcategory: "Stationery",
    brand: "Artisan Crafts Co.",
    price: 3500,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&h=800&fit=crop",
    ],
    status: "sold", // ← single unit, sold to a buyer (non-auction)
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: [
      "leather",
      "journal",
      "handcrafted",
      "vintage",
      "stationery",
      "gift",
    ],
    specifications: [
      { name: "Material", value: "Genuine Buffalo Leather" },
      { name: "Format", value: "A5 (14.8 × 21 cm)" },
      { name: "Pages", value: "200 acid-free ruled" },
    ],
    features: [
      "Hand-stitched binding",
      "Refillable — replaceable inner paper block",
      "Includes bookmark ribbon and pen loop",
    ],
    shippingInfo: "Sold — no longer available.",
    returnPolicy: "N/A — item sold.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2026-01-20T10:00:00Z"),
    updatedAt: new Date("2026-02-15T12:00:00Z"), // date item was sold
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW AUCTION PRODUCTS — 16 added to bring total auctions to 20
  // "Closing soon" = ends March 7–9; "Live" = ends March 12–16
  // ═══════════════════════════════════════════════════════════════════════════

  // ── TechHub Auctions ───────────────────────────────────────────────────────

  // #1 — closing in 1 day (March 7)
  {
    id: "auction-ps5-slim-gaming-console-techhub-1",
    title: "PlayStation 5 Slim Disc Edition — AUCTION",
    description:
      "Brand-new sealed PlayStation 5 Slim Disc Edition. Includes controller, cables, and 3-month PlayStation Plus. Limited availability — closing soon!",
    category: "category-gaming-electronics",
    subcategory: "Consoles",
    brand: "Sony",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1200&h=800&fit=crop",
    ],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&h=450&fit=crop",
      duration: 15,
    },
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["ps5", "playstation", "gaming", "console", "sony", "auction"],
    specifications: [
      { name: "Model", value: "PS5 Slim Disc Edition" },
      { name: "Storage", value: "1", unit: "TB" },
      { name: "Condition", value: "Brand new sealed" },
    ],
    features: ["DualSense controller included", "3-month PS Plus", "4K gaming"],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-07T20:00:00Z"),
    startingBid: 45000,
    currentBid: 52000,
    bidCount: 9,
    buyNowPrice: 65000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-07T20:00:00Z"),
    createdAt: new Date("2026-02-20T00:00:00Z"),
    updatedAt: new Date("2026-03-05T10:00:00Z"),
  },

  // #2 — closing in 2 days (March 8)
  {
    id: "auction-airpods-pro2-audio-techhub-1",
    title: "Apple AirPods Pro 2nd Gen (USB-C) — AUCTION",
    description:
      "Sealed Apple AirPods Pro 2nd generation with USB-C charging case. Active Noise Cancellation, Transparency mode, Adaptive Audio.",
    category: "category-audio-electronics",
    subcategory: "Wireless Earphones",
    brand: "Apple",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["airpods", "apple", "earphones", "wireless", "anc", "auction"],
    specifications: [
      { name: "Model", value: "AirPods Pro 2 (USB-C)" },
      { name: "Connectivity", value: "Bluetooth 5.3" },
      { name: "Battery", value: "30 hr (with case)" },
    ],
    features: [
      "Active Noise Cancellation",
      "Transparency mode",
      "Adaptive Audio",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-08T20:00:00Z"),
    startingBid: 18000,
    currentBid: 21500,
    bidCount: 6,
    buyNowPrice: 29000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: new Date("2026-02-22T00:00:00Z"),
    updatedAt: new Date("2026-03-04T14:00:00Z"),
  },

  // #3 — live (March 14)
  {
    id: "auction-sony-alpha-7iv-camera-techhub-1",
    title: "Sony Alpha 7 IV Full-Frame Mirrorless Camera — AUCTION",
    description:
      "Sony A7 IV with 33MP BSI-CMOS sensor, 4K 60fps video, 10fps burst. Body only. Shutter count under 5000. Original box, charger, strap, battery.",
    category: "category-cameras-photography-electronics",
    subcategory: "Mirrorless Cameras",
    brand: "Sony",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1606986628253-3c3d8c9da85c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1606986628253-3c3d8c9da85c?w=1200&h=800&fit=crop",
    ],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1606986628253-3c3d8c9da85c?w=800&h=450&fit=crop",
      duration: 15,
    },
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: true,
    tags: ["sony", "camera", "mirrorless", "a7iv", "fullframe", "auction"],
    specifications: [
      { name: "Sensor", value: "33MP BSI-CMOS Full-Frame" },
      { name: "Video", value: "4K 60fps" },
      { name: "Shutter Count", value: "< 5000" },
    ],
    features: ["10fps burst", "5-axis IBIS", "Real-time eye tracking"],
    shippingInfo: "Insured shipping within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 2500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-14T20:00:00Z"),
    startingBid: 200000,
    currentBid: 215000,
    bidCount: 3,
    reservePrice: 230000,
    minBidIncrement: 5000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-02-25T00:00:00Z"),
    updatedAt: new Date("2026-03-04T09:00:00Z"),
  },

  // #4 — live (March 15)
  {
    id: "auction-nikon-z30-mirrorless-techhub-1",
    title: "Nikon Z30 APS-C Mirrorless Camera Body — AUCTION",
    description:
      "Nikon Z30 with 20.9MP APS-C sensor, 4K UHD video, flip-out screen. Great for vloggers and content creators. Includes original box and battery.",
    category: "category-cameras-photography-electronics",
    subcategory: "Mirrorless Cameras",
    brand: "Nikon",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1683267523707-76e1e7e80af8?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1683267523707-76e1e7e80af8?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["nikon", "z30", "mirrorless", "camera", "vlog", "auction"],
    specifications: [
      { name: "Sensor", value: "20.9MP APS-C CMOS" },
      { name: "Video", value: "4K UHD 30fps" },
      { name: "Screen", value: "Flip-out 3-inch touchscreen" },
    ],
    features: ["Flip-out screen", "Bluetooth/Wi-Fi", "S-Log footage"],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-15T20:00:00Z"),
    startingBid: 55000,
    currentBid: 57000,
    bidCount: 2,
    buyNowPrice: 75000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: new Date("2026-03-01T00:00:00Z"),
    updatedAt: new Date("2026-03-05T11:00:00Z"),
  },

  // #5 — live (March 16)
  {
    id: "auction-iphone15-sealed-bundle-techhub-1",
    title: "iPhone 15 256GB + MagSafe Charger Bundle — AUCTION",
    description:
      "Sealed iPhone 15 256GB in Black + MagSafe 15W charger. Unopened Apple sealed box. Great auction price opportunity.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Apple",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "techhub@letitrip.in",
    featured: false,
    tags: ["iphone", "apple", "smartphone", "sealed", "bundle", "auction"],
    specifications: [
      { name: "Storage", value: "256", unit: "GB" },
      { name: "Colour", value: "Black" },
      { name: "Includes", value: "MagSafe 15W Charger" },
    ],
    features: ["Dynamic Island", "48MP main camera", "USB-C"],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-16T20:00:00Z"),
    startingBid: 90000,
    currentBid: 93000,
    bidCount: 2,
    buyNowPrice: 120000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: new Date("2026-03-02T00:00:00Z"),
    updatedAt: new Date("2026-03-05T15:00:00Z"),
  },

  // ── Fashion Boutique Auctions ───────────────────────────────────────────────

  // #6 — closing in 2 days (March 8)
  {
    id: "auction-swiss-titanium-watch-fashion-1",
    title: "TAG Heuer Carrera Chronograph Titanium — AUCTION",
    description:
      "TAG Heuer Carrera Chronograph in titanium case, calibre Heuer 02 automatic movement. Full set — box and papers. Excellent condition, barely worn.",
    category: "category-mens-fashion-fashion",
    subcategory: "Luxury Watches",
    brand: "TAG Heuer",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1200&h=800&fit=crop",
    ],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&h=450&fit=crop",
      duration: 60,
    },
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: [
      "tag-heuer",
      "watch",
      "chronograph",
      "titanium",
      "luxury",
      "auction",
    ],
    specifications: [
      { name: "Case", value: "Titanium 43mm" },
      { name: "Movement", value: "Calibre Heuer 02 Automatic" },
      { name: "Condition", value: "Excellent (9.5/10)" },
    ],
    features: [
      "Box and papers included",
      "Automatic chronograph",
      "100m water resistant",
    ],
    shippingInfo:
      "Insured + tracked shipping within 24 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 3000,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-08T18:00:00Z"),
    startingBid: 150000,
    currentBid: 175000,
    bidCount: 4,
    reservePrice: 200000,
    minBidIncrement: 5000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-08T18:00:00Z"),
    createdAt: new Date("2026-02-18T00:00:00Z"),
    updatedAt: new Date("2026-03-03T16:00:00Z"),
  },

  // #7 — closing in 3 days (March 9)
  {
    id: "auction-vintage-denim-jacket-fashion-1",
    title: "Vintage Levi's 70505 Type III Denim Jacket (1978) — AUCTION",
    description:
      "Authentic 1978 Levi's 70505 Type III denim trucker jacket. Size 42 (L). Original orange stitching and tab. Minor fade on collar — genuine patina of age.",
    category: "category-mens-fashion-fashion",
    subcategory: "Jackets & Outerwear",
    brand: "Levi's",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1542060748-10c28b62716f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542060748-10c28b62716f?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: ["levis", "denim", "jacket", "vintage", "1978", "trucker", "auction"],
    specifications: [
      { name: "Model", value: "Levi's 70505 Type III" },
      { name: "Year", value: "1978" },
      { name: "Size", value: "42 (Large)" },
    ],
    features: [
      "Original orange stitching",
      "Levi's red tab intact",
      "Vintage patina",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-09T20:00:00Z"),
    startingBid: 8000,
    currentBid: 11000,
    bidCount: 7,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-02-24T00:00:00Z"),
    updatedAt: new Date("2026-03-05T09:00:00Z"),
  },

  // #8 — live (March 11)
  {
    id: "auction-supreme-box-logo-tee-fashion-1",
    title: "Supreme Box Logo Tee FW23 — AUCTION",
    description:
      "Authentic Supreme Box Logo T-shirt from Fall/Winter 2023 drop. Size Large. Worn once — perfect condition. Comes with original Supreme bag.",
    category: "category-mens-fashion-fashion",
    subcategory: "T-Shirts",
    brand: "Supreme",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: [
      "supreme",
      "box-logo",
      "tee",
      "streetwear",
      "fw23",
      "limited",
      "auction",
    ],
    specifications: [
      { name: "Season", value: "FW23" },
      { name: "Size", value: "Large" },
      { name: "Condition", value: "Worn once (10/10)" },
    ],
    features: [
      "Original Supreme bag",
      "Authentic box logo tee",
      "Limited FW23 release",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-11T18:00:00Z"),
    startingBid: 20000,
    currentBid: 27000,
    bidCount: 5,
    buyNowPrice: 45000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: new Date("2026-02-28T00:00:00Z"),
    updatedAt: new Date("2026-03-04T12:00:00Z"),
  },

  // #9 — live (March 13)
  {
    id: "auction-hermes-silk-scarf-fashion-1",
    title: "Hermès Silk Twill Scarf 'Jungle Love' (90cm) — AUCTION",
    description:
      "Authentic Hermès 90cm silk twill scarf in the iconic 'Jungle Love' print. Never worn, comes with original Hermès box and ribbon. Certificate of authenticity.",
    category: "category-womens-fashion-fashion",
    subcategory: "Scarves & Shawls",
    brand: "Hermès",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: true,
    tags: [
      "hermes",
      "scarf",
      "silk",
      "luxury",
      "jungle-love",
      "90cm",
      "auction",
    ],
    specifications: [
      { name: "Dimensions", value: "90 × 90 cm" },
      { name: "Material", value: "100% Silk Twill" },
      { name: "Print", value: "Jungle Love" },
    ],
    features: [
      "Never worn",
      "Original Hermès box & ribbon",
      "Certificate of authenticity",
    ],
    shippingInfo: "Insured shipping within 24 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "new",
    insurance: true,
    insuranceCost: 1000,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-13T18:00:00Z"),
    startingBid: 45000,
    currentBid: 48000,
    bidCount: 3,
    reservePrice: 55000,
    minBidIncrement: 1000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-03-01T00:00:00Z"),
    updatedAt: new Date("2026-03-04T11:00:00Z"),
  },

  // #10 — live (March 16)
  {
    id: "auction-designer-kanjeevaram-silk-fashion-1",
    title: "Sabyasachi Kanjeevaram Silk Saree — Bridal Edition — AUCTION",
    description:
      "Stunning Sabyasachi-inspired Kanjeevaram pure silk saree in deep magenta with gold zari work. 6.5m length. Worn once at a wedding. Original dust bag.",
    category: "category-womens-fashion-fashion",
    subcategory: "Sarees",
    brand: "Sabyasachi",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion@letitrip.in",
    featured: false,
    tags: [
      "sabyasachi",
      "kanjeevaram",
      "silk",
      "saree",
      "bridal",
      "zari",
      "auction",
    ],
    specifications: [
      { name: "Material", value: "Pure Kanjeevaram Silk" },
      { name: "Length", value: "6.5", unit: "m" },
      { name: "Colour", value: "Deep Magenta with Gold Zari" },
    ],
    features: [
      "Worn once — perfect condition",
      "Original dust bag included",
      "Dry-clean only",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-16T18:00:00Z"),
    startingBid: 25000,
    currentBid: 27000,
    bidCount: 2,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-03-03T00:00:00Z"),
    updatedAt: new Date("2026-03-05T10:00:00Z"),
  },

  // ── Home Essentials Auctions ───────────────────────────────────────────────

  // #11 — closing in 2 days (March 8)
  {
    id: "auction-bose700-headphones-homeessentials-1",
    title: "Bose 700 Wireless Noise-Cancelling Headphones — AUCTION",
    description:
      "Bose 700 in black — 11-level noise cancelling, 20-hour battery, voice assistant support. Lightly used. All accessories included.",
    category: "category-audio-electronics",
    subcategory: "Wireless Headphones",
    brand: "Bose",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&h=800&fit=crop",
    ],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=450&fit=crop",
      duration: 60,
    },
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["bose", "headphones", "wireless", "anc", "audio", "auction"],
    specifications: [
      { name: "Noise Cancelling", value: "11-level adjustable" },
      { name: "Battery", value: "20 hr playback" },
      { name: "Connectivity", value: "Bluetooth 5.0" },
    ],
    features: [
      "11-level noise cancellation",
      "Voice assistants (Alexa/Google)",
      "All accessories included",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-08T20:00:00Z"),
    startingBid: 25000,
    currentBid: 28000,
    bidCount: 5,
    buyNowPrice: 38000,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: new Date("2026-02-23T00:00:00Z"),
    updatedAt: new Date("2026-03-04T13:00:00Z"),
  },

  // #12 — closing in 3 days (March 9)
  {
    id: "auction-pioneer-hifi-system-homeessentials-1",
    title: "Pioneer A-40AE Stereo Amplifier + Q Acoustics Speakers — AUCTION",
    description:
      "Pioneer A-40AE stereo amplifier (45W/ch) paired with Q Acoustics 3020i bookshelf speakers. Stunning combination for vinyl or digital listening.",
    category: "category-audio-electronics",
    subcategory: "Hi-Fi Systems",
    brand: "Pioneer",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1593078165898-d3b96ef75f2c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1593078165898-d3b96ef75f2c?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["pioneer", "hifi", "amplifier", "speakers", "stereo", "auction"],
    specifications: [
      { name: "Power", value: "45", unit: "W per channel" },
      { name: "Speakers", value: "Q Acoustics 3020i" },
      { name: "Inputs", value: "Phono, CD, Line ×3" },
    ],
    features: [
      "Dedicated phono input for vinyl",
      "Optional A/B speaker output",
      "Compact bookshelf speakers included",
    ],
    shippingInfo: "Ships within 5-7 days (heavy item). Tracked.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 1000,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-09T18:00:00Z"),
    startingBid: 35000,
    currentBid: 41000,
    bidCount: 5,
    minBidIncrement: 1000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-02-25T00:00:00Z"),
    updatedAt: new Date("2026-03-04T10:00:00Z"),
  },

  // #13 — live (March 12)
  {
    id: "auction-trek-domane-road-bike-homeessentials-1",
    title: "Trek Domane AL 5 Road Bike (56cm, 2023) — AUCTION",
    description:
      "Trek Domane AL 5 aluminium endurance road bike, 56cm frame, Shimano 105 11-speed groupset. 2023 model. Very good condition, well-maintained.",
    category: "category-sports-outdoors",
    subcategory: "Road Bikes",
    brand: "Trek",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: true,
    tags: ["trek", "road-bike", "cycling", "domane", "shimano", "auction"],
    specifications: [
      { name: "Frame", value: "Alpha Aluminium" },
      { name: "Groupset", value: "Shimano 105 11-speed" },
      { name: "Frame Size", value: "56cm" },
    ],
    features: [
      "IsoSpeed decoupler",
      "Hydraulic disc brakes",
      "Tubeless-ready wheels",
    ],
    shippingInfo: "Local pickup preferred. Shipping arranged post-auction.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 1500,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-12T18:00:00Z"),
    startingBid: 60000,
    currentBid: 68000,
    bidCount: 4,
    reservePrice: 75000,
    minBidIncrement: 2000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: new Date("2026-03-12T18:00:00Z"),
    createdAt: new Date("2026-02-20T00:00:00Z"),
    updatedAt: new Date("2026-03-04T08:00:00Z"),
  },

  // #14 — live (March 14)
  {
    id: "auction-babolat-tennis-racket-signed-homeessentials-1",
    title: "Babolat Pure Aero Tennis Racket — Signed — AUCTION",
    description:
      "Babolat Pure Aero 300g, strung with RPM Blast 16 string. Signed by a national-level tennis player. Frame in perfect condition. Certificate of authenticity.",
    category: "category-sports-outdoors",
    subcategory: "Tennis",
    brand: "Babolat",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: [
      "babolat",
      "tennis",
      "racket",
      "signed",
      "pure-aero",
      "collectible",
      "auction",
    ],
    specifications: [
      { name: "Model", value: "Pure Aero" },
      { name: "Weight", value: "300", unit: "g" },
      { name: "String", value: "RPM Blast 16" },
    ],
    features: [
      "Signed by national player",
      "Certificate of authenticity",
      "Original Babolat bag",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: true,
    insuranceCost: 500,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-14T18:00:00Z"),
    startingBid: 55000,
    currentBid: 60000,
    bidCount: 4,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-02-28T00:00:00Z"),
    updatedAt: new Date("2026-03-04T09:30:00Z"),
  },

  // #15 — live (March 15)
  {
    id: "auction-dyson-v15-vacuum-homeessentials-1",
    title: "Dyson V15 Detect Absolute Cordless Vacuum — AUCTION",
    description:
      "Dyson V15 Detect Absolute in excellent condition. Fluffy Optics laser head included. All original attachments, wall mount charger, instruction booklet.",
    category: "category-home-kitchen",
    subcategory: "Vacuum Cleaners",
    brand: "Dyson",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["dyson", "vacuum", "cordless", "v15", "laser", "auction"],
    specifications: [
      { name: "Model", value: "V15 Detect Absolute" },
      { name: "Suction", value: "230 AW" },
      { name: "Battery", value: "60 min (Eco mode)" },
    ],
    features: [
      "Laser Fluffy Optics head",
      "LCD particle count display",
      "All attachments included",
    ],
    shippingInfo: "Ships within 48 hours of auction close.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: true,
    auctionEndDate: new Date("2026-03-15T20:00:00Z"),
    startingBid: 35000,
    currentBid: 38000,
    bidCount: 3,
    buyNowPrice: 52000,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "seller",
    isPromoted: false,
    createdAt: new Date("2026-03-01T00:00:00Z"),
    updatedAt: new Date("2026-03-05T08:00:00Z"),
  },

  // #16 — live (March 16)
  {
    id: "auction-weber-charcoal-grill-homeessentials-1",
    title: "Weber Original Kettle Premium 57cm Charcoal Grill — AUCTION",
    description:
      "Weber Original Kettle Premium 57cm in black. Used twice — practically new. Includes ash catcher, thermometer in lid, and two tool hooks.",
    category: "category-home-kitchen",
    subcategory: "Outdoor Grills",
    brand: "Weber",
    price: 0,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1555685813-6f1c38e64a54?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1555685813-6f1c38e64a54?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home@letitrip.in",
    featured: false,
    tags: ["weber", "grill", "charcoal", "bbq", "outdoor", "kettle", "auction"],
    specifications: [
      { name: "Diameter", value: "57", unit: "cm" },
      { name: "Cooking Area", value: "2376", unit: "cm²" },
      { name: "Material", value: "Porcelain-enamelled steel" },
    ],
    features: [
      "Built-in thermometer",
      "One-Touch cleaning system",
      "Hinged cooking grate",
    ],
    shippingInfo: "Local pickup preferred. Shipping arranged post-auction.",
    returnPolicy: "No returns on auction items.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: new Date("2026-03-16T18:00:00Z"),
    startingBid: 18000,
    currentBid: 18000,
    bidCount: 0,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    isPromoted: false,
    createdAt: new Date("2026-03-05T12:00:00Z"),
    updatedAt: new Date("2026-03-05T12:00:00Z"),
  },
];
