/**
 * Products Seed Data
 * Sample product data across various categories
 */

import type { ProductDocument } from "@/db/schema";

export const productsSeedData: Partial<ProductDocument>[] = [
  // Electronics > Smartphones
  {
    id: "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    title: "iPhone 15 Pro Max",
    description: "Latest iPhone with titanium design and A17 Pro chip.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Apple",
    price: 134900,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 25,
    mainImage:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1678652197950-372d7e96f926?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1678911820864-e5c67c5d96ed?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: true,
    tags: ["smartphone", "iphone", "apple", "5g", "premium"],
    specifications: [
      { name: "Display", value: "6.7 inch" },
      { name: "Storage", value: "256", unit: "GB" },
      { name: "Camera", value: "48 MP" },
    ],
    features: ["Titanium design", "A17 Pro chip", "Face ID"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns accepted.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-28T23:59:59Z"),
    createdAt: new Date("2025-12-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },
  {
    id: "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    title: "Samsung Galaxy S24 Ultra",
    description: "Premium Android with S Pen and 200MP camera.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Samsung",
    price: 124999,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage:
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1591122947157-26bad3a117d2?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: true,
    tags: ["smartphone", "samsung", "android", "5g", "spen"],
    specifications: [
      { name: "Display", value: "6.8 inch" },
      { name: "Storage", value: "256", unit: "GB" },
      { name: "Camera", value: "200 MP" },
    ],
    features: ["S Pen included", "AI features", "100x Zoom"],
    shippingInfo: "Free shipping in 2-3 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-12-15T00:00:00Z"),
    updatedAt: new Date("2026-02-08T00:00:00Z"),
  },
  {
    id: "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    title: "Google Pixel 8 Pro",
    description: "Google flagship with AI features and pure Android.",
    category: "category-smartphones-mobiles-accessories",
    subcategory: "Premium Smartphones",
    brand: "Google",
    price: 84999,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 20,
    mainImage:
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: false,
    tags: ["smartphone", "google", "pixel", "android", "camera"],
    specifications: [
      { name: "Display", value: "6.7 inch" },
      { name: "Storage", value: "128", unit: "GB" },
      { name: "Camera", value: "50 MP" },
    ],
    features: ["Tensor G3 chip", "7 years updates", "Magic Eraser"],
    shippingInfo: "Free shipping in 3-5 days.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-11-20T00:00:00Z"),
    updatedAt: new Date("2026-02-04T00:00:00Z"),
  },

  // Electronics > Laptops
  {
    id: "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    title: 'MacBook Pro 16" M3 Max',
    description: "Professional laptop with M3 Max chip for creators.",
    category: "category-laptops-computers-electronics",
    subcategory: "Professional Laptops",
    brand: "Apple",
    price: 249900,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    mainImage:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: true,
    tags: ["laptop", "macbook", "apple", "professional", "m3"],
    specifications: [
      { name: "Display", value: "16.2 inch" },
      { name: "RAM", value: "36", unit: "GB" },
      { name: "Storage", value: "1", unit: "TB" },
    ],
    features: ["M3 Max chip", "ProMotion", "22hr battery"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: new Date("2026-03-15T23:59:59Z"),
    createdAt: new Date("2025-11-01T00:00:00Z"),
    updatedAt: new Date("2026-02-07T00:00:00Z"),
  },
  {
    id: "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    title: "Dell XPS 15",
    description: "Premium Windows laptop with i9 and RTX 4060.",
    category: "category-laptops-computers-electronics",
    subcategory: "Professional Laptops",
    brand: "Dell",
    price: 189999,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 15,
    mainImage:
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: false,
    tags: ["laptop", "dell", "windows", "professional", "gaming"],
    specifications: [
      { name: "Display", value: "15.6 inch" },
      { name: "RAM", value: "32", unit: "GB" },
      { name: "Storage", value: "1", unit: "TB" },
    ],
    features: ["Intel i9", "RTX 4060", "Thunderbolt 4"],
    shippingInfo: "Free shipping in 4-6 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-10-15T00:00:00Z"),
    updatedAt: new Date("2026-02-05T00:00:00Z"),
  },

  // Fashion > Men's Fashion
  {
    id: "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    title: "Men's Cotton Casual Shirt",
    description: "Comfortable cotton shirt for daily wear.",
    category: "category-mens-fashion-fashion",
    subcategory: "Shirts",
    brand: "Raymond",
    price: 1499,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 100,
    mainImage:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion.boutique@example.com",
    featured: false,
    tags: ["mens", "shirt", "casual", "cotton", "fashion"],
    specifications: [
      { name: "Material", value: "100% Cotton" },
      { name: "Fit", value: "Regular Fit" },
    ],
    features: ["Breathable", "Machine washable"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-09-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },

  // Fashion > Women's Fashion
  {
    id: "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    title: "Women's Ethnic Kurti",
    description: "Ethnic kurti with traditional prints.",
    category: "category-womens-fashion-fashion",
    subcategory: "Ethnic Wear",
    brand: "Fabindia",
    price: 1999,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 80,
    mainImage:
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-fashion-boutique-fashionb",
    sellerName: "Fashion Boutique",
    sellerEmail: "fashion.boutique@example.com",
    featured: true,
    tags: ["womens", "kurti", "ethnic", "traditional", "fashion"],
    specifications: [
      { name: "Material", value: "Cotton Blend" },
      { name: "Length", value: "Knee Length" },
    ],
    features: ["Hand block print", "Easy care"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "15-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-08-20T00:00:00Z"),
    updatedAt: new Date("2026-01-28T00:00:00Z"),
  },

  // Home & Kitchen
  {
    id: "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    title: "Non-Stick Cookware Set",
    description: "7-piece non-stick cookware set with glass lids.",
    category: "category-home-kitchen",
    subcategory: "Cookware",
    brand: "Prestige",
    price: 3499,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage:
      "https://images.unsplash.com/photo-1584990347449-39b0ce4aa1f9?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1584990347449-39b0ce4aa1f9?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home.essentials@example.com",
    featured: false,
    tags: ["kitchen", "cookware", "nonstick", "home", "cooking"],
    specifications: [
      { name: "Material", value: "Aluminum" },
      { name: "Pieces", value: "7" },
      { name: "Induction Safe", value: "Yes" },
    ],
    features: ["PFOA free", "Easy to clean", "Glass lids"],
    shippingInfo: "Free shipping in 5-7 days.",
    returnPolicy: "10-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-07-10T00:00:00Z"),
    updatedAt: new Date("2026-01-20T00:00:00Z"),
  },

  // Sports & Outdoors
  {
    id: "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    title: "Yoga Mat with Carrying Bag",
    description: "Premium yoga mat with non-slip surface.",
    category: "category-sports-outdoors",
    subcategory: "Fitness",
    brand: "Reebok",
    price: 1299,
    currency: "INR",
    stockQuantity: 75,
    availableQuantity: 75,
    mainImage:
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-home-essentials-homeesse",
    sellerName: "Home Essentials",
    sellerEmail: "home.essentials@example.com",
    featured: false,
    tags: ["yoga", "fitness", "sports", "exercise", "mat"],
    specifications: [
      { name: "Material", value: "TPE" },
      { name: "Thickness", value: "6", unit: "mm" },
    ],
    features: ["Non-slip", "Eco-friendly", "Carrying bag"],
    shippingInfo: "Free shipping above ₹999.",
    returnPolicy: "7-day returns.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-06-15T00:00:00Z"),
    updatedAt: new Date("2026-01-15T00:00:00Z"),
  },

  // Auction Product - Vintage Camera
  {
    id: "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    title: "Vintage Canon AE-1 Film Camera",
    description: "Classic 35mm film camera from 1980s. Fully functional.",
    category: "category-cameras-photography-electronics",
    subcategory: "Vintage Cameras",
    brand: "Canon",
    price: 15000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: true,
    tags: ["camera", "vintage", "film", "canon", "collector"],
    specifications: [
      { name: "Type", value: "35mm Film SLR" },
      { name: "Lens", value: "50mm f/1.8" },
      { name: "Year", value: "1983" },
    ],
    features: ["Fully functional", "Original lens", "Film tested"],
    shippingInfo: "Insured shipping in 3-5 days.",
    returnPolicy: "No returns on auctions.",
    isAuction: true,
    auctionEndDate: new Date("2026-02-20T23:59:59Z"),
    startingBid: 15000,
    currentBid: 22000,
    bidCount: 8,
    isPromoted: true,
    promotionEndDate: new Date("2026-02-20T23:59:59Z"),
    createdAt: new Date("2026-01-20T00:00:00Z"),
    updatedAt: new Date("2026-02-08T18:30:00Z"),
  },

  // Out of stock product
  {
    id: "product-sony-wh-1000xm5-headphones-audio-new-techhub-electronics-1",
    title: "Sony WH-1000XM5 Headphones",
    description: "Premium noise-cancelling headphones. Out of stock.",
    category: "category-audio-electronics",
    subcategory: "Headphones",
    brand: "Sony",
    price: 29990,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=1200&h=800&fit=crop",
    ],
    status: "out_of_stock",
    sellerId: "user-techhub-electronics-electron",
    sellerName: "TechHub Electronics",
    sellerEmail: "electronics.store@example.com",
    featured: false,
    tags: ["headphones", "sony", "noise-cancelling", "audio", "premium"],
    specifications: [
      { name: "Type", value: "Over-ear" },
      { name: "Battery", value: "30 hours" },
    ],
    features: ["ANC", "LDAC audio", "Multipoint"],
    shippingInfo: "Currently unavailable.",
    returnPolicy: "7-day returns when available.",
    isAuction: false,
    isPromoted: false,
    createdAt: new Date("2025-05-01T00:00:00Z"),
    updatedAt: new Date("2026-02-01T00:00:00Z"),
  },
];
