/**
 * Reviews Seed Data
 * Sample product reviews with various ratings and statuses
 */

import type { ReviewDocument } from "@/db/schema";

export const reviewsSeedData: Partial<ReviewDocument>[] = [
  // Approved reviews
  {
    id: "review-iphone-15-pro-max-john-20260120",
    productId:
      "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    productTitle: "iPhone 15 Pro Max",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: undefined,
    rating: 5,
    title: "Absolutely Amazing!",
    comment:
      "Exceeded expectations. Camera and battery are outstanding. Worth it!",
    images: [],
    status: "approved",
    helpfulCount: 24,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-20T10:30:00Z"),
    updatedAt: new Date("2026-01-20T10:30:00Z"),
    approvedAt: new Date("2026-01-20T12:00:00Z"),
  },
  {
    id: "review-samsung-galaxy-s24-ultra-jane-20260125",
    productId:
      "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    productTitle: "Samsung Galaxy S24 Ultra",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: undefined,
    rating: 5,
    title: "Best Android Phone Yet",
    comment:
      "S Pen is useful, camera is stunning, AI features are helpful. Great for power users.",
    images: [],
    status: "approved",
    helpfulCount: 18,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-25T14:15:00Z"),
    updatedAt: new Date("2026-01-25T14:15:00Z"),
    approvedAt: new Date("2026-01-25T16:00:00Z"),
  },
  {
    id: "review-google-pixel-8-pro-mike-20260131",
    productId:
      "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    productTitle: "Google Pixel 8 Pro",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: undefined,
    rating: 4,
    title: "Great Camera, Pure Android",
    comment:
      "Love the camera and clean Android. Magic Eraser is fun. Battery could be better.",
    status: "approved",
    helpfulCount: 12,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-01T09:30:00Z"),
    updatedAt: new Date("2026-02-01T09:30:00Z"),
    approvedAt: new Date("2026-02-01T11:00:00Z"),
  },
  {
    id: "review-macbook-pro-16-m3-max-john-20260126",
    productId:
      "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    productTitle: 'MacBook Pro 16" M3 Max',
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: undefined,
    rating: 5,
    title: "Perfect for Professionals",
    comment:
      "Handles 4K editing smoothly. Display is gorgeous, battery life incredible. Best laptop ever.",
    status: "approved",
    helpfulCount: 31,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-07T11:00:00Z"),
    updatedAt: new Date("2026-02-07T11:00:00Z"),
    approvedAt: new Date("2026-02-07T13:00:00Z"),
  },
  {
    id: "review-dell-xps-15-jane-20260201",
    productId:
      "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    productTitle: "Dell XPS 15",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: undefined,
    rating: 4,
    title: "Powerful Windows Laptop",
    comment:
      "Excellent build and performance. RTX 4060 handles design work perfectly. Webcam could be better.",
    status: "approved",
    helpfulCount: 15,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-03T13:45:00Z"),
    updatedAt: new Date("2026-02-03T13:45:00Z"),
    approvedAt: new Date("2026-02-03T15:00:00Z"),
  },
  {
    id: "review-mens-cotton-casual-shirt-mike-20260205",
    productId:
      "product-mens-cotton-casual-shirt-mens-fashion-new-fashion-boutique-1",
    productTitle: "Men's Cotton Casual Shirt",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: undefined,
    rating: 4,
    title: "Good Quality, Comfortable Fit",
    comment: "Nice cotton shirt, breathable and true to size. Good value.",
    status: "approved",
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-30T15:20:00Z"),
    updatedAt: new Date("2026-01-30T15:20:00Z"),
    approvedAt: new Date("2026-01-30T16:30:00Z"),
  },
  {
    id: "review-womens-ethnic-kurti-jane-20260207",
    productId:
      "product-womens-ethnic-kurti-womens-fashion-new-fashion-boutique-1",
    productTitle: "Women's Ethnic Kurti",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: undefined,
    rating: 5,
    title: "Beautiful Design and Quality",
    comment:
      "Love this kurti! Beautiful print, excellent quality, perfect fit. Will buy more.",
    status: "approved",
    helpfulCount: 14,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-08T16:30:00Z"),
    updatedAt: new Date("2026-02-08T16:30:00Z"),
    approvedAt: new Date("2026-02-08T18:00:00Z"),
  },
  {
    id: "review-non-stick-cookware-set-john-20260208",
    productId:
      "product-non-stick-cookware-set-home-kitchen-new-home-essentials-1",
    productTitle: "Non-Stick Cookware Set",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: undefined,
    rating: 4,
    title: "Good Value Cookware Set",
    comment:
      "Good set for the price. Non-stick works well, heats evenly. Handles could be better.",
    status: "approved",
    helpfulCount: 9,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-05T10:15:00Z"),
    updatedAt: new Date("2026-02-05T10:15:00Z"),
    approvedAt: new Date("2026-02-05T12:00:00Z"),
  },
  {
    id: "review-yoga-mat-with-carrying-bag-jane-20260209",
    productId:
      "product-yoga-mat-with-carrying-bag-sports-outdoors-new-home-essentials-1",
    productTitle: "Yoga Mat with Carrying Bag",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: undefined,
    rating: 5,
    title: "Perfect for Daily Practice",
    comment:
      "Great mat with excellent grip and cushioning. No slip during intense sessions. Carrying bag is convenient.",
    status: "approved",
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-06T09:00:00Z"),
    updatedAt: new Date("2026-02-06T09:00:00Z"),
    approvedAt: new Date("2026-02-06T10:30:00Z"),
  },

  // Medium rating reviews
  {
    id: "review-vintage-canon-ae-1-film-camera-mike-20260203",
    productId:
      "auction-vintage-canon-ae-1-film-camera-cameras-photography-used-techhub-electronics-1",
    productTitle: "Vintage Canon AE-1 Film Camera",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: undefined,
    rating: 4,
    title: "Classic Beauty",
    comment:
      "Authentic vintage camera in excellent condition. Film photography at its finest.",
    status: "approved",
    helpfulCount: 7,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-02T14:20:00Z"),
    updatedAt: new Date("2026-02-02T14:20:00Z"),
    approvedAt: new Date("2026-02-02T16:00:00Z"),
  },
  {
    id: "review-iphone-15-pro-max-jane-20260204",
    productId:
      "product-iphone-15-pro-max-smartphones-new-techhub-electronics-1",
    productTitle: "iPhone 15 Pro Max",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: undefined,
    rating: 4,
    title: "Impressive Performance",
    comment:
      "Camera quality is outstanding. Battery life is solid. Slightly heavy but worth it.",
    status: "approved",
    helpfulCount: 5,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-01-22T11:45:00Z"),
    updatedAt: new Date("2026-01-22T11:45:00Z"),
    approvedAt: new Date("2026-01-22T13:00:00Z"),
  },

  // Pending reviews (awaiting moderation)
  {
    id: "review-samsung-galaxy-s24-ultra-mike-20260206",
    productId:
      "product-samsung-galaxy-s24-ultra-smartphones-new-techhub-electronics-1",
    productTitle: "Samsung Galaxy S24 Ultra",
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: undefined,
    rating: 4,
    title: "Solid Upgrade",
    comment:
      "Upgraded from S22 Ultra. Camera improvements are noticeable, AI is cool. Wish it had charger.",
    status: "pending",
    helpfulCount: 0,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-08T09:30:00Z"),
    updatedAt: new Date("2026-02-08T09:30:00Z"),
  },
  {
    id: "review-google-pixel-8-pro-jane-20260207",
    productId:
      "product-google-pixel-8-pro-smartphones-new-techhub-electronics-1",
    productTitle: "Google Pixel 8 Pro",
    userId: "user-jane-smith-janes",
    userName: "Jane Smith",
    userAvatar: undefined,
    rating: 4,
    title: "Great Camera and Software",
    comment:
      "Pure Android experience is refreshing. AI features are useful. Battery is decent.",
    status: "pending",
    helpfulCount: 0,
    reportCount: 0,
    verified: true,
    createdAt: new Date("2026-02-08T10:15:00Z"),
    updatedAt: new Date("2026-02-08T10:15:00Z"),
  },

  // Rejected review (spam/inappropriate)
  {
    id: "review-macbook-pro-16-m3-max-mike-20260207",
    productId:
      "product-macbook-pro-16-m3-max-laptops-computers-new-techhub-electronics-1",
    productTitle: 'MacBook Pro 16" M3 Max',
    userId: "user-mike-johnson-mikejohn",
    userName: "Mike Johnson",
    userAvatar: undefined,
    rating: 1,
    title: "Fake Product",
    comment: "This is a scam! Check out my website for real deals. [SPAM URL]",
    status: "rejected",
    moderatorId: "user-admin-user-admin",
    moderatorNote: "Spam content with promotional links",
    rejectionReason: "Contains spam and inappropriate promotional content",
    helpfulCount: 0,
    reportCount: 3,
    verified: false,
    createdAt: new Date("2026-02-04T16:30:00Z"),
    updatedAt: new Date("2026-02-04T17:00:00Z"),
    rejectedAt: new Date("2026-02-04T17:00:00Z"),
  },

  // Review with multiple helpful votes
  {
    id: "review-dell-xps-15-john-20260208",
    productId:
      "product-dell-xps-15-laptops-computers-new-techhub-electronics-1",
    productTitle: "Dell XPS 15",
    userId: "user-john-doe-johndoe",
    userName: "John Doe",
    userAvatar: undefined,
    rating: 5,
    title: "Powerful Windows Laptop",
    comment:
      "Excellent build quality and performance. Display is stunning. Perfect for development work.",
    status: "approved",
    helpfulCount: 42,
    reportCount: 0,
    verified: false,
    createdAt: new Date("2026-02-08T20:00:00Z"),
    updatedAt: new Date("2026-02-08T20:00:00Z"),
    approvedAt: new Date("2026-02-08T21:00:00Z"),
  },
];
