/**
 * Users Seed Data
 * Sample user data for development and testing
 */

import type { UserDocument } from "@/db/schema";

export const usersSeedData: Partial<UserDocument>[] = [
  // Admin User
  {
    uid: "user-admin-user-admin",
    email: "admin@letitrip.in",
    phoneNumber: "+919876543210",
    phoneVerified: true,
    displayName: "Admin User",
    photoURL: null,
    avatarMetadata: null,
    role: "admin",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "System Administrator",
    },
    stats: {
      totalOrders: 0,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-09T00:00:00Z"),
      creationTime: new Date("2024-01-01T00:00:00Z").toISOString(),
      loginCount: 150,
    },
  },
  // Regular Users
  {
    uid: "user-john-doe-johndoe",
    email: "john.doe@example.com",
    phoneNumber: "+919876543211",
    phoneVerified: true,
    displayName: "John Doe",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-02-15T08:30:00Z"),
    updatedAt: new Date("2026-02-08T15:20:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
      bio: "Tech enthusiast",
      location: "Mumbai, India",
      website: "https://johndoe.com",
      socialLinks: {
        twitter: "https://twitter.com/johndoe",
        instagram: "https://instagram.com/johndoe",
      },
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 4,
      rating: 4.8,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-08T15:20:00Z"),
      creationTime: new Date("2024-02-15T08:30:00Z").toISOString(),
      loginCount: 45,
    },
  },
  {
    uid: "user-jane-smith-janes",
    email: "jane.smith@example.com",
    phoneNumber: "+919876543212",
    phoneVerified: true,
    displayName: "Jane Smith",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-03-10T10:00:00Z"),
    updatedAt: new Date("2026-02-07T12:30:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: true,
      bio: "Fashion blogger",
      location: "Delhi, India",
      socialLinks: {
        instagram: "https://instagram.com/janesmith",
        facebook: "https://facebook.com/janesmith",
      },
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 6,
      rating: 4.9,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-07T12:30:00Z"),
      creationTime: new Date("2024-03-20T14:00:00Z").toISOString(),
      loginCount: 78,
    },
  },
  {
    uid: "user-mike-johnson-mikejohn",
    email: "mike.johnson@example.com",
    phoneNumber: "+919876543213",
    phoneVerified: false,
    displayName: "Mike Johnson",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-04-20T14:15:00Z"),
    updatedAt: new Date("2026-02-05T09:45:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: true,
      showWishlist: false,
      bio: "Sports enthusiast",
      location: "Bangalore, India",
    },
    stats: {
      totalOrders: 4,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 5,
      rating: 4.5,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-05T09:45:00Z"),
      creationTime: new Date("2024-05-10T10:00:00Z").toISOString(),
      loginCount: 22,
    },
  },
  // Seller Users
  {
    uid: "user-techhub-electronics-electron",
    email: "electronics.store@example.com",
    phoneNumber: "+919876543214",
    phoneVerified: true,
    displayName: "TechHub Electronics",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-01-15T00:00:00Z"),
    updatedAt: new Date("2026-02-09T08:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: true,
      showPhone: true,
      showOrders: false,
      showWishlist: false,
      bio: "Authorized electronics seller",
      location: "Mumbai, India",
      website: "https://techhub.example.com",
      socialLinks: {
        facebook: "https://facebook.com/techhub",
        instagram: "https://instagram.com/techhub",
      },
    },
    stats: {
      totalOrders: 7,
      auctionsWon: 0,
      itemsSold: 7,
      reviewsCount: 10,
      rating: 4.7,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-09T08:00:00Z"),
      creationTime: new Date("2024-06-01T00:00:00Z").toISOString(),
      loginCount: 210,
    },
  },
  {
    uid: "user-fashion-boutique-fashionb",
    email: "fashion.boutique@example.com",
    phoneNumber: "+919876543215",
    phoneVerified: true,
    displayName: "Fashion Boutique",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-02-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T18:30:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: true,
      showPhone: true,
      showOrders: false,
      showWishlist: false,
      bio: "Trendy fashion and accessories",
      location: "Delhi, India",
      website: "https://fashionboutique.example.com",
    },
    stats: {
      totalOrders: 5,
      auctionsWon: 0,
      itemsSold: 2,
      reviewsCount: 3,
      rating: 4.8,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-08T18:30:00Z"),
      creationTime: new Date("2024-02-01T00:00:00Z").toISOString(),
      loginCount: 195,
    },
  },
  {
    uid: "user-home-essentials-homeesse",
    email: "home.essentials@example.com",
    phoneNumber: "+919876543216",
    phoneVerified: true,
    displayName: "Home Essentials",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: new Date("2024-03-01T00:00:00Z"),
    updatedAt: new Date("2026-02-08T16:00:00Z"),
    publicProfile: {
      isPublic: true,
      showEmail: true,
      showPhone: true,
      showOrders: false,
      showWishlist: false,
      bio: "Quality home products",
      location: "Pune, India",
    },
    stats: {
      totalOrders: 3,
      auctionsWon: 0,
      itemsSold: 2,
      reviewsCount: 2,
      rating: 4.6,
    },
    metadata: {
      lastSignInTime: new Date("2026-02-08T16:00:00Z"),
      creationTime: new Date("2024-10-01T00:00:00Z").toISOString(),
      loginCount: 142,
    },
  },
  // Disabled User (for testing)
  {
    uid: "user-disabled-user-disabled",
    email: "disabled.user@example.com",
    phoneNumber: "+919876543999",
    phoneVerified: false,
    displayName: "Disabled User",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: false,
    disabled: true,
    createdAt: new Date("2024-05-01T00:00:00Z"),
    updatedAt: new Date("2024-06-01T00:00:00Z"),
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
    },
    stats: {
      totalOrders: 0,
      auctionsWon: 0,
      itemsSold: 0,
      reviewsCount: 0,
    },
    metadata: {
      lastSignInTime: new Date("2024-05-15T00:00:00Z"),
      creationTime: new Date("2024-04-01T00:00:00Z").toISOString(),
      loginCount: 3,
    },
  },
];
