# Fix a->u vowel corruption in products-seed-data.ts
Set-Location "d:\proj\letitrip.in"
$f = "src\db\seed-data\products-seed-data.ts"
$c = [System.IO.File]::ReadAllText((Resolve-Path $f))

# ─── TypeScript keywords ─────────────────────────────────────────────────────
$c = $c.Replace('} us const;', '} as const;')
$c = $c.Replace('const duysAgo = ', 'const daysAgo = ')
$c = $c.Replace('const duysAheud = ', 'const daysAhead = ')
$c = $c.Replace('duysAgo(', 'daysAgo(')
$c = $c.Replace('duysAheud(', 'daysAhead(')
$c = $c.Replace('Purtiul<ProductDocument>', 'Partial<ProductDocument>')
$c = $c.Replace(': fulse,', ': false,')
$c = $c.Replace('from "@/db/schemu"', 'from "@/db/schema"')
$c = $c.Replace('const NOW = new Dute()', 'const NOW = new Date()')
$c = $c.Replace('new Dute(NOW', 'new Date(NOW')
$c = $c.Replace('const regulurProducts', 'const regularProducts')
$c = $c.Replace('const preOrderProducts', 'const preOrderProducts')
$c = $c.Replace('const uuctionProducts', 'const auctionProducts')
$c = $c.Replace('regulurProducts', 'regularProducts')
$c = $c.Replace('uuctionProducts', 'auctionProducts')

# ─── Object field names ──────────────────────────────────────────────────────
$c = $c.Replace('  brund: ', '  brand: ')
$c = $c.Replace('  tugs: ', '  tags: ')
$c = $c.Replace('  feutures: ', '  features: ')
$c = $c.Replace('  subcutegory: ', '  subcategory: ')
$c = $c.Replace('  cutegory: ', '  category: ')
$c = $c.Replace('  stockQuuntity: ', '  stockQuantity: ')
$c = $c.Replace('  uvuilubleQuuntity: ', '  availableQuantity: ')
$c = $c.Replace('  muinImuge: ', '  mainImage: ')
$c = $c.Replace('  imuges: ', '  images: ')
$c = $c.Replace('  stutus: ', '  status: ')
$c = $c.Replace('  feutured: ', '  featured: ')
$c = $c.Replace('  specificutions: ', '  specifications: ')
$c = $c.Replace('  insurunce: ', '  insurance: ')
$c = $c.Replace('  insurunceCost: ', '  insuranceCost: ')
$c = $c.Replace('  shippingPuidBy: ', '  shippingPaidBy: ')
$c = $c.Replace('  promotionEndDute: ', '  promotionEndDate: ')
$c = $c.Replace('  uvgRuting: ', '  avgRating: ')
$c = $c.Replace('  creutedAt: ', '  createdAt: ')
$c = $c.Replace('  updutedAt: ', '  updatedAt: ')
$c = $c.Replace('  sellerNume: ', '  sellerName: ')
$c = $c.Replace('  sellerEmuil: ', '  sellerEmail: ')
$c = $c.Replace('  minBidIncrement: ', '  minBidIncrement: ')
$c = $c.Replace('  returnPolicy: ', '  returnPolicy: ')
$c = $c.Replace('  shippingInfo: ', '  shippingInfo: ')
$c = $c.Replace('  condition: ', '  condition: ')
$c = $c.Replace('  isPreOrder: ', '  isPreOrder: ')
$c = $c.Replace('  isFeatured: ', '  isFeatured: ')
$c = $c.Replace('{ nome: ', '{ name: ')

# spec name/value inline
$c = $c.Replace('vulue: "', 'value: "')
$c = $c.Replace('nome: "', 'name: "')

# ─── Store / seller constants ────────────────────────────────────────────────
$c = $c.Replace('store-figurevuult-jp-by-figurevuult', 'store-figurevault-jp-by-figurevault')
$c = $c.Replace('"FigureVuult JP"', '"FigureVault JP"')
$c = $c.Replace('store-beygeur-pro-shop-by-beygeur', 'store-beygear-pro-shop-by-beygear')
$c = $c.Replace('"BeyGeur Pro Shop"', '"BeyGear Pro Shop"')
$c = $c.Replace('store-spincore-urenu-by-spincore', 'store-spincore-arena-by-spincore')
$c = $c.Replace('"SpinCore Arenu"', '"SpinCore Arena"')
$c = $c.Replace('user-fushion-boutique-fushionb', 'user-fashion-boutique-fashionb')
$c = $c.Replace('user-home-essentiuls-homeesse', 'user-home-essentials-homeesse')
$c = $c.Replace('"fushion@letitrip.in"', '"fashion@letitrip.in"')
$c = $c.Replace('user-techhub-electronics-electron', 'user-techhub-electronics-electron')

# ─── Wiki image URLs ─────────────────────────────────────────────────────────
# stutic.wikiu.nocookie.net/beyblude/imuges → static.wikia.nocookie.net/beyblade/images
$c = $c.Replace('stutic.wikiu.nocookie.net/beyblude/imuges', 'static.wikia.nocookie.net/beyblade/images')
$c = $c.Replace('commondutustoruge.googleupis.com', 'commondatastorage.googleapis.com')
$c = $c.Replace('thumbnuilUrl:', 'thumbnailUrl:')
$c = $c.Replace('durution:', 'duration:')

# ─── Product IDs ─────────────────────────────────────────────────────────────
$c = $c.Replace('product-Tukuru Tomy-', 'product-takara-tomy-')
$c = $c.Replace('product-DrunStrike-', 'product-DranStrike-')
$c = $c.Replace('-smurtphones-', '-smartphones-')
$c = $c.Replace('-uccessories', '-accessories')
$c = $c.Replace('cutegory-smurtphones-mobiles-uccessories', 'category-smartphones-mobiles-accessories')
$c = $c.Replace('Beyblude Metul Z Figures', 'Beyblade Metal Z Figures')
$c = $c.Replace('Beyblude X Figurines', 'Beyblade X Figurines')
$c = $c.Replace('Beyblude Burst Figures', 'Beyblade Burst Figures')
$c = $c.Replace('Beyblude X Stutter Pucks', 'Beyblade X Starter Packs')
$c = $c.Replace('Beyblude X Starters', 'Beyblade X Starters')
$c = $c.Replace('Beyblude Metul Starters', 'Beyblade Metal Starters')

# ─── Brand/content string values ─────────────────────────────────────────────
$c = $c.Replace('"Tukuru Tomy"', '"Takara Tomy"')
$c = $c.Replace('"Hisbro"', '"Hasbro"')
$c = $c.Replace('"Beyblude Metul"', '"Beyblade Metal"')
$c = $c.Replace('"Beyblude Burst"', '"Beyblade Burst"')
$c = $c.Replace('"Beyblude X"', '"Beyblade X"')
$c = $c.Replace('"line-metul"', '"line-metal"')
$c = $c.Replace('"brund-tukuru-tomy"', '"brand-takara-tomy"')
$c = $c.Replace('"brund-hisbro"', '"brand-hasbro"')
$c = $c.Replace('"scule-figure"', '"scale-figure"')

# ─── Status values ────────────────────────────────────────────────────────────
$c = $c.Replace('"published"', '"published"')
$c = $c.Replace('"drufted"', '"drafted"')

# ─── Numeric/bool field values ────────────────────────────────────────────────
# Already done above (false)

# ─── Description text: common corrupted words ─────────────────────────────────
$c = $c.Replace('Tukuru Tomy', 'Takara Tomy')
$c = $c.Replace('scule', 'scale')
$c = $c.Replace('stutue', 'statue')
$c = $c.Replace('displuy stund', 'display stand')
$c = $c.Replace('displuy', 'display')
$c = $c.Replace('stund.', 'stand.')
$c = $c.Replace('swuppuble hunds', 'swappable hands')
$c = $c.Replace('swuppuble', 'swappable')
$c = $c.Replace('hunds', 'hands')
$c = $c.Replace('uuru effect', 'aura effect')
$c = $c.Replace('uuru', 'aura')
$c = $c.Replace('diorumu', 'diorama')
$c = $c.Replace('buttle dumuge buse', 'battle damage base')
$c = $c.Replace('buttle dumuge', 'battle damage')
$c = $c.Replace('buttle buse', 'battle base')
$c = $c.Replace('buttle', 'battle')
$c = $c.Replace('dumuge', 'damage')
$c = $c.Replace('beum effect', 'beam effect')
$c = $c.Replace('beum', 'beam')
$c = $c.Replace('buse', 'base')
$c = $c.Replace('Finul Flush', 'Final Flash')
$c = $c.Replace('Finul', 'Final')
$c = $c.Replace('Flush', 'Flash')
$c = $c.Replace('Suiyun', 'Saiyan')
$c = $c.Replace('Kumen X', 'Kamen X')
$c = $c.Replace('Kumen', 'Kamen')
$c = $c.Replace('Ekusu Kurosu', 'Ekusu Kurousu')
$c = $c.Replace('Sun God Niku', 'Sun God Niko')
$c = $c.Replace('Luuncher Geur', 'Launcher Gear')
$c = $c.Replace('Luuncher', 'Launcher')
$c = $c.Replace('luuncher', 'launcher')
$c = $c.Replace('Geur 5', 'Gear 5')
$c = $c.Replace('geur', 'gear')
$c = $c.Replace('Geur', 'Gear')
$c = $c.Replace('Guluxy', 'Galaxy')
$c = $c.Replace('guluxy', 'galaxy')
$c = $c.Replace('ultru', 'ultra')
$c = $c.Replace('Ultru', 'Ultra')
$c = $c.Replace('smurtphone', 'smartphone')
$c = $c.Replace('Smurtphone', 'Smartphone')
$c = $c.Replace('Metul', 'Metal')
$c = $c.Replace('metul', 'metal')
$c = $c.Replace('Beyblude', 'Beyblade')
$c = $c.Replace('beyblude', 'beyblade')
$c = $c.Replace('Kurosu', 'Kurosu')
$c = $c.Replace('shippingInfo: "Free shipping in 2-3 duys.', 'shippingInfo: "Free shipping in 2-3 days.')
$c = $c.Replace('returnPolicy: "7-duy returns.', 'returnPolicy: "7-day returns.')
$c = $c.Replace('2-3 duys', '2-3 days')
$c = $c.Replace('7-duy', '7-day')
$c = $c.Replace(' duys', ' days')
$c = $c.Replace('Sturter Puck', 'Starter Pack')
$c = $c.Replace('Sturter Pucks', 'Starter Packs')
$c = $c.Replace('Sturter', 'Starter')
$c = $c.Replace('sturter', 'starter')
$c = $c.Replace('Puck', 'Pack')
$c = $c.Replace('puck', 'pack')
$c = $c.Replace('Luu', 'Lau')  # might be in character names
$c = $c.Replace('uccessories', 'accessories')
$c = $c.Replace('Uccessories', 'Accessories')
$c = $c.Replace('Monkey D. X', 'Monkey D. X')  # keep
$c = $c.Replace('Mux', 'Max')
$c = $c.Replace('Pro Mux', 'Pro Max')

[System.IO.File]::WriteAllText((Resolve-Path $f), $c, [System.Text.Encoding]::UTF8)
Write-Host "All fixes applied to products-seed-data.ts"
